- src/cryptonote_config.h
- src/p2p/net_node.inl
This should resolve daemon startup taking too long by adding a 20 second timeout to DNS seed lookup.  If the time passes and no seeds have been retrieved from DNS then fallback defaults are used.
> DNS seed timeout

- src/cryptonote_core/blockchain_storage.cpp
- src/cryptonote_core/blockchain_storage.h
Use single call to get_transaction_hash to get both transaction hash and blob size. Do actual store of the blob size in transaction_chain_entry struct.
> TX's blob size store and add_transaction_from_block optimization/cleanup

- src/common/dns_utils.cpp
- src/cryptonote_core/checkpoints_create.cpp
- tests/unit_tests/dns_resolver.cpp
DNSSEC validation (with hardcoded key from unbound) added.
DNS unit tests for DNSSEC added; unit tests for IPv4 modified for the fact that example.com IP is not static.
DNSSEC enforced as available and valid for MoneroPulse DNS checkpoint updates.
> DNSSEC changes

- external/CMakeLists.txt
> fix #246 (cmake miniupnpc filename case mismatch)

- contrib/epee/include/console_handler.h
- contrib/epee/include/net/http_server_handlers_map2.h
- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/command_server.h
- src/daemon/daemon.cpp
- src/daemon/daemon.h
- src/daemon/executor.cpp
- src/daemon/rpc.h
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
Daemon interactive mode is now working again.
RPC mapped calls in daemon and wallet have both had connection_context
removed as an argument as that argument was not being used anywhere.
> Restore daemon interactive mode

- external/unbound/libunbound/libunbound.c
- src/common/dns_utils.cpp
Due to a bug in unbound, we were passing a string containing a null
character to ub_ctx_resolvconf and ub_ctx_hosts rather than a NULL
pointer.  On *nix this wasn't causing headache, but on Windows this was
causing unbound to not correctly load DNS settings from the OS.
Note on the bug: in a Windows-specific code branch in the function
ub_ctx_hosts(), if the hosts file specified was a NULL pointer, a call
to getenv() was stored in a local char* and later freed.  This is
incorrect, as we do not own that data, and caused the program to crash.
> Fixed DNS resolution bug in Windows

- src/daemon/rpc_command_executor.cpp
Fixes segmentation fault when using the start_mining command on the daemon in interactive cli mode (RPC was fine, still is).
> Fixes start_mining in cli interactive mode

- contrib/epee/include/net/abstract_tcp_server2.h
- src/common/dns_utils.cpp
- src/daemon/main.cpp
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
- tests/core_proxy/core_proxy.h
- tests/net_load_tests/clt.cpp
- tests/net_load_tests/srv.cpp
- tests/unit_tests/epee_boosted_tcp_server.cpp
old unbound #warning does not block compilation
unit tests build fine. Even though the RPC/P2P network type is required again
> [fix] log level change. compilation: dns, tests

- src/cryptonote_core/checkpoints_create.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
Only one thread will be doing the updating.
Two valid responses must match, and the first two that match will be
used.
> DNS Checkpoint updating-related fixes/changes

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
Add mempool output to daemon via command and RPC
Keep memory pool consistent when stuck tx removed
Test daemon output:
print_pool
print_pool_sh
Test RPC:
curl http://127.0.0.1:18081/get_transaction_pool
> Mempool updates

- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
It is best for miners (and makes sense) to sort transactions by fee per byte (or kb) used.
This PR addresses that and should sort it completely.
> Sort tx by fee per kb

- src/blockchain_converter/blockchain_export.cpp
Instantiate BlockchainDB in blockchain exporter to reflect recent updates.
This applies when blockchain_export.h defines SOURCE_DB as DB_LMDB.
> Fix incompatibility with blockchain exporter when source is LMDB

- CMakeLists.txt
- src/p2p/net_node.h
- src/p2p/net_node.inl
Fix two warnings arising (and causing compilation to fail) when compiling Monero on OSX Mavericks with clang:
* Deprecated 'register' storage class warning in boost.uuid
* Missing virtual destructor for node_server
> Fixes for compilation on clang

- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_utilities/blockchain_export.cpp
- src/blockchain_utilities/blockchain_import.cpp
- src/blockchain_utilities/bootstrap_file.cpp
Check if chunk size is zero instead of negative, fixing OS X compile error.
Rename "--block-number" option to "--block-stop".
Allow BlockchainLMDB to be opened read-only. Use by blockchain_export.
> Fix OS X compile error & other utilities updates

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
Could be useful for old non-deterministic wallets to be able to dump the account to import into MyMonero. For deterministic wallets, this will just be a hex representation of the seed, so it's bit redundant, but OTOH simplewallet isn't exactly overflowing with commands, so I don't see it as an issue.
Tested on W7-64.
Reopening this...
> Add spendkey dump to simplewallet

- src/blockchain_utilities/blockchain_import.cpp
- src/cryptonote_core/blockchain_storage.h
Add public method blockchain_storage::debug_pop_block_from_blockchain()
Ensure blockchain_import calls destructors before exit.
To test:
DATABASE=memory make release
// create blockchain.bin from blockchain.raw if needed
build/release/bin/blockchain_import --block-stop 1000
// try popping a single block
build/release/bin/blockchain_import --pop-blocks 1
> Support debugging command --pop-blocks on in-memory blockchain

- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
Working on Windows and Arch Linux.
Default (minimum) size is 1GiB, the map is resized to 150% of current when it becomes 80% full.  Set to check every 1000 blocks.
> Gradually grow mdb file size

- contrib/epee/include/storages/portable_storage.h
- src/p2p/net_node.inl
Add fix for compile error with multiple uses of peerid_type (uint64_t) variable in lambda expression.
- known GCC issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65843
epee: replace return value of nullptr for expected boolean with false.
Fixes #231.
> Fix compile for GCC 5.1.0

- src/p2p/net_node.inl
The random selection of a node shouldn't favor repeats that occur in the hardcoded and DNS seed node lists.
Remove hardcoded ":18080" address which gives parse error.
Test: bitmonerod --log-level 2
The seed node list displayed at startup shouldn't show duplicate addresses (includes port).
> Build seed node list without duplicates

- src/daemon/main.cpp
- src/simplewallet/simplewallet.cpp
simplewallet: Don't log view key and spend key
simplewallet: Update and add log options
- Replace --set_log with --log-level for consistency.
- Add --log-file for specifying log file path.
daemon: Set log file default to use data dir
> Update wallet and daemon log options and handling

- src/blockchain_db/lmdb/db_lmdb.cpp
When opening an existing database, don't set LMDB map size to be the default initial size for a new database. While it's not persisted to disk (if a larger map size was set in the past), it will cause the running instance's map size to be the current data.mdb file size. For sparse files, or those which otherwise don't have the size pre-allocated, this leads to a map size that won't allow new writes.
Check if resize is needed at startup.
Include specific database error in more error messages.
> Update database resize behavior

- contrib/epee/include/console_handler.h
Exit instead of reading "empty" commands in an infinite loop.
> console_handler: handle EOF properly

- contrib/epee/include/console_handler.h
- src/daemon/command_server.cpp
- src/daemon/command_server.h
- src/daemon/daemon.cpp
It uses the async console handler differently than simplewallet,
and wasn't running the same exit code, causing it to never actually
exit after breaking out of the console entry loop.
> fix ^D exit for bitmonerod

- src/p2p/connection_basic.cpp
Near as I can tell, if connection_basic is incrementing the sock count in the constructor it should decrement it in the destructor.
> properly decrement p2p socket count

- src/cryptonote_core/checkpoints_create.cpp
It's supposed to load all records and pick one that it finds twice.
> Fix DNS checkpoint consensus code

- src/wallet/wallet2.cpp
This ensures even massive wallets full of dust can sweep.
> wallet2: try to split dust sweep txs exponentially

- src/common/dns_utils.cpp
- tests/unit_tests/address_from_url.cpp
I've found that the dnssec_valid value was being wrongly let to true when it should be false. We must check not only `result->bogus`, but also `result->secure`, since `result->bogus` is 0 when dnssec isn't available for the given domain.
This PR also fixes one unit test where we query a non-existing top-level domain, and libunbound validates the non-existence with dnssec and sets `secure` to 1.
> Set dnssec_valid value correctly in dns_utils; fix address_from_url test

- src/mnemonics/language_base.h
Fix the following compile error in the tests on gcc 4.8.2:
```
electrum-words.cpp.o (symbol from plugin): In function `Language::utf8prefix(std::string const&, unsigned long)':
(.text+0x0): multiple definition of `Language::utf8prefix(std::string const&, unsigned long)'
CMakeFiles/unit_tests.dir/mnemonics.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
```
> mnemonics: fix duplicate symbol error

- src/cryptonote_core/tx_pool.cpp
This causes the calling thread to lock up due to an infinite loop when failing conditions in tx_memory_pool::fill_block_template(..)
> Fix loop bug when calling core::get_block_template(..)

- src/blockchain_db/berkeleydb/db_bdb.cpp
- src/blockchain_db/berkeleydb/db_bdb.h
- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/blockchain_utilities/blockchain_converter.cpp
- src/blockchain_utilities/blockchain_import.cpp
- src/blockchain_utilities/bootstrap_file.cpp
- src/blockchain_utilities/fake_core.h
This allows the importer and converter, when in batch mode, to complete without requiring a restart upon a full database.
The database is resized, if needed, at the start of each batch of blocks. It uses an estimate of the batch's expected storage size.
> Check and resize if needed at batch transaction start

- CMakeLists.txt
CMake supports this through THREADS_PREFER_PTHREAD_FLAG.
Remove inclusion of pthread library in EXTRA_LIBRARIES, as the
individual CMakeLists.txt files which need pthread already require it
with CMAKE_THREAD_LIBS_INIT.
> Use g++ flag "-pthread" instead of "-lpthread", where preferred

- src/cryptonote_core/blockchain.cpp
These are mainnet blocks, and would cause syncing on testnet to
reject all incoming blocks.
> blockchain: fix testnet syncing (to not use blocks.dat)

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
This can be useful if you want to be given a veto over the tx fee,
or if you want to see what a tx fee would be without actually sending.
> wallet: add boolean to always confirm transactions with the user

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- translations/monero.ts
boost doesn't support %zu for size_t, and the previous change
to %u could technically lose bits (though it would require splitting
a transfer into 4 billion transactions, which seems unlikely).
> simplewallet: use unsigned long long instead of size_t in message

- src/mnemonics/japanese.h
I ran some tests, and all prefixes seem to be unique for len(3)
> change unique_prefix_length=4 for japanese.h

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
It should avoid a lot of the issues sending more than half the
wallet's contents due to change.
Actual output selection is still random. Changing this would
improve the matching of transaction amounts to output sizes,
but may have non obvious effects on blockchain analysis.
Mapped to the new transfer_new command in simplewallet, and
transfer uses the existing algorithm.
To use in RPC, add "new_algorithm: true" in the transfer_split
JSON command. It is not used in the transfer command.
> wallet: new transaction construction algorithm

- tests/unit_tests/block_reward.cpp
Now we should take FINAL_SUBSIDY_PER_MINUTE into account
> Fix block_reward unit tests

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
This obsoletes the need for a lengthy blockchain rescan when
a transaction doesn't end up in the chain after being accepted
by the daemon, or any other reason why the wallet's idea of
spent and unspent outputs gets out of sync from the blockchain's.
> wallet: new rescan_spent command to update outputs' spent status

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
vector<bool> causes issues in serialization with Boost 1.56
> core_rpc_server: replace vector<bool> with vector<int> in RPC

- src/blockchain_utilities/blockchain_export.cpp
- src/blockchain_utilities/bootstrap_file.cpp
- src/blockchain_utilities/bootstrap_file.h
This option will export to the specified file path.
The default file path remains `<data-dir>/export/blockchain.raw`
> blockchain_export: Add --output-file argument

- src/blockchain_utilities/blockchain_import.cpp
This option specifies the input file path for importing.
The default remains `<data-dir>/export/blockchain.raw`
> blockchain_import: Add --input-file option

- src/p2p/net_node.inl
Each thread can use the same resolver.
> net_node: Use DNS resolver singleton

- src/cryptonote_core/blockchain.cpp
The height function apparently used to return the index of
the last block, rather than the height of the chain. This now
seems to be incorrect, judging the the code, so we remove the
now wrong comment, as well as a couple +/- 1 adjustments
which now cause the median calculation to differ from the
original blockchain_storage version.
> blockchain: fix off by 1 in timestamp median calculations

- contrib/epee/include/misc_log_ex.h
- src/simplewallet/simplewallet.cpp
Default to "simplewallet.log" in current directory when file path isn't obtained from epee.
In this situation previously, it defaulted to the file name of `.log` ("" + ".log") in the current directory.
(Thanks to @sammy007 for reporting bug.)
An earlier version yet used "" + "/" + ".log" = `/.log`, which resulted in silently not logging in most cases, due to lack of permission.
Test:
`PATH=$PATH:</path/to/simplewallet/folder> && simplewallet --wallet-file /dev/null`
This results in epee not finding the executable's file path, so simplewallet will now use a default log filename.
> simplewallet: Use default log file name when executable's file path is unknown

- external/unbound/libunbound/libunbound.c
Looks like Unbound has been fixed so that this is no longer an issue, yay!
> Revert f4ba92bcccd3e016c6b5fdced079bf17d1b3f371

- src/cryptonote_core/cryptonote_format_utils.cpp
- src/cryptonote_core/cryptonote_format_utils.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
They are also stored in the cache file, to be retrieved using
a new get_tx_key command.
> make tx keys available to the user

- src/crypto/chacha8.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
It contains private data, such as a record of transactions.
The key is derived from the view secret key.
The encryption currently is one shot, so may require a lot of
memory for large wallet caches.
> wallet: encrypt the cache file

- src/cryptonote_core/cryptonote_format_utils.cpp
- src/cryptonote_core/cryptonote_format_utils.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
To get the tx keys returned via RPC, set the "get_tx_key" or
"get_tx_keys" request field to true (defaults to false).
> wallet: only return tx keys via RPC if requested

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
To enable storing tx keys in the (now encrypted) wallet cache.
> simplewallet: add a store-tx-keys option to set

- src/cryptonote_core/blockchain.cpp
crypto::rand is now used for output selection
> blockchain: remove obsolete call to libc srand

- src/cryptonote_core/hardfork.cpp
An unsigned quantity is always >= 0
> hardfork: move an assert so it actually works

- external/unbound/CMakeLists.txt
It is now not needed anymore, as we use minievent instead
> unbound: do not try to link against libevent

- src/p2p/net_node.inl
upnpDiscover() takes a new argument for TTL.
Use the suggested default of 2.
> Update to compile with latest miniupnpc

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
It allows enabling the rescan_spent command only for trusted
daemon
> simplewallet: add a --trusted-daemon flag

- contrib/epee/include/console_handler.h
The daemon registers a custom exit command, which cause the
loop to stop. Catch this case before printing "Failed to read line"
as this is an expected case.
> console_handler: silence spurious message when exiting daemon

- src/cryptonote_config.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain_storage.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
The wallet and the daemon applied different height considerations
when selecting outputs to use. This can leak information on which
input in a ring signature is the real one.
Found and originally fixed by smooth on Aeon.
> Fix leak on real output when using a very recent output

- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
Displays current block height and target, net hash, hard fork
basic info, and connections.
Useful as a basic user friendly "what's going on here" command.
> daemon: add a status command

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_basic.h
- src/cryptonote_core/hardfork.cpp
- tests/unit_tests/hardfork.cpp
Using major version would cause older daemons to reject those
blocks as they fail to deserialize blocks with a major version
which is not 1. There is no such restriction on the minor
version, so switching allows older daemons to coexist with
newer ones till the actual fork date, when most will hopefully
have updated already.
Also, for the same reason, we consider a vote for 0 to be a
vote for 1, since older daemons set minor version to 0.
> hardfork: switch voting to block minor version

- src/daemon/command_parser_executor.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
They check whether they're running on testnet by accessing the
m_rpc_server object, which does not exist when in RPC mode.
Also, fix hard_fork_info being called with the wrong API.
> rpc: fix start_mining and status RPC crashes

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
The default default mixin is 4. It can now be changed per wallet.
> simplewallet: add a set default-mixin command

- src/blockchain_db/berkeleydb/db_bdb.cpp
It looks like some of the indices passed to the DB access functions
are already bumped by 1. Moreover, the existing code was not
throwing DB errors with 0 keys, and this is unlikely if it really
was using 0 keys. Last, this patch broke sync from scratch in at
least one case. So I'm calling it bad and reverting it.
This reverts commit bfc97401ae81bb30278a318de7f048c653bf6582.
> Revert "db_bdb: record numbers for recno databases start at 1"

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
It's a user friendly display of incoming and outgoing transfers,
listed by height, within an optional height range.
> wallet: track outgoing payments and add a show_transfers command

- src/blockchain_utilities/blockchain_import.cpp
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain_storage.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/rpc/core_rpc_server.cpp
- tests/core_proxy/core_proxy.cpp
- tests/core_proxy/core_proxy.h
- tests/core_tests/chaingen.h
The last relayed time of a transaction is maintained, and
transactions will be relayed again if they are still in the
pool after a certain amount of time, which increases with
the transaction's age. All such transactions are resent,
whether or not they originated on the local node.
> Relay transactions when they linger too long in the pool

- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
This fixes the hash rate being wrong on testnet after the switch
to 2 minute blocks
> rpc: pass current block target in rpc

- contrib/epee/include/net/http_server_handlers_map2.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
It does not expose the RPC for commands like start_mining, etc
(ie, commands a public node operator might want to be restricted)
> core_rpc_server: add a --restricted-rpc option

- src/cryptonote_core/cryptonote_basic.h
This allows them to be saved as a fixed (one byte) chunk whatever
the value. Using a varint will use two bytes as the high bit gets
set.
This is backward compatible with current usage (0-2 values).
> core: serialize block major/minor versions as bytes, not varints

- contrib/epee/include/console_handler.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
The daemon will be polled every 90 seconds for new blocks.
It is enabled by default, and can be turned on/off with
set auto-refresh 1 and set auto-refresh 0 in the wallet.
> wallet: optional automatic refresh from the daemon

- src/simplewallet/simplewallet.cpp
Green is now used for incoming transfers, and magenta for outgoing
transfers. This is consistent to the scheme used by other logging.
> simplewallet: swap colors in show_transfers

- src/common/util.cpp
- src/common/util.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
^C while in manual refresh will cancel the refresh, since that's
often an annoying thing to have to wait for. Also, a manual refresh
command will interrupt any running background refresh and take
over, rather than wait for the background refresh to be done, and
look to be hanging.
> wallet: cancellable refresh

- contrib/epee/include/console_handler.h
This prevents an exception from existing the loop without
calling the exit handler, if one is defined.
The daemon defines one, which stops the p2p layer, and will
only exit once the p2p layer is shut down. This would cause
a hang upon an exception, as the input thread would have
exited and the daemon would wait forever with no console
user input.
> console_handler: catch exception inside the input loop

- src/p2p/net_node.inl
Clear any partially loaded data, and start with a default config
> p2p: failure to load p2pstate.bin is not fatal anymore

- src/blockchain_db/berkeleydb/db_bdb.cpp
This is a precaution for older Berkeley DB versions.
- smooth reports an issue running with 4.7:
DB_ENV->log_set_config: DB_LOG_IN_MEMORY: method not permitted
after handle's open method
- this works just fine with 5.3
- we do not use DB_LOG_IN_MEMORY, but we use DB_LOG_AUTO_REMOVE
- libdb docs say some flags must be set before open, and some
may be set at any time, but never say some must be set after
open
- moving the call to log_set_config before open works with 5.3
Therefore, it seems best to move the call before open.
> db_bdb: move log_set_config call before open

- src/common/command_line.cpp
- src/common/command_line.h
- src/cryptonote_core/cryptonote_core.cpp
- src/daemon/command_line_args.h
- src/daemon/main.cpp
- src/p2p/net_node.inl
- src/rpc/core_rpc_server.cpp
This fixes coretests, which does not register daemon specific arguments,
but uses core, which uses those arguments. Also gets rid of an unwanted
dependency on daemon code from core.
> Register daemon command line arguments to core if they're used in core

- src/blockchain_db/lmdb/db_lmdb.cpp
When throwing an exception from being unable to begin an LMDB transaction, include the reason.
It's often been due to a write transaction attempted within a write transaction (batch mode), but there can be other reasons such as write transaction attempted while database was opened read only, or
environment's map needs to be resized.
> Add LMDB error string to database transaction exception message

- src/daemonizer/posix_daemonizer.inl
This prevents the intermediate thread from exiting properly, as
fork creates a child process with only one thread, so any existing
data_logger thread will not be in the child. Since this thread
sets a flag the data_logger dtor blocks on, all children threads
will hang on exit.
> posix_daemonizer: only create the main daemon object in the last child

- src/daemon/daemon.cpp
We need to stop the p2p layer, which causes the rest to shutdown
gracefully. Hitting ^C was still going through another path.
> daemon: fix crash exiting with ^C

- src/cryptonote_config.h
This was changed early in the project history with no stated justification.
> Revert connection limit to more customary 8

- src/wallet/wallet2.cpp
- src/wallet/wallet_errors.h
This should avoid most of wallet cache corruption cases
> wallet: save to a temporary file, then rename

- src/cryptonote_core/blockchain.cpp
- src/wallet/wallet2.cpp
> replace std::auto_ptr with std::unique_ptr

- src/wallet/wallet2.h
The version number passed to those data's serialize function
was always 0, not the wallet's version as I had expected.
A version number now exists for these structures so they're
versioned correctly.
> wallet: fix load/save versioning bug for recently added tx data

- src/daemon/command_line_args.h
- src/daemon/core.h
- src/daemon/daemon.cpp
- src/daemon/daemon.h
- src/daemon/main.cpp
- src/daemon/p2p.h
- src/daemon/protocol.h
- src/daemon/rpc.h
In particular, <boost/program_options.hpp> blows up daemon.cpp.obj,
making it too big to compile in debug mode on Win32. Even on a
release build it drops daemon.cpp.o on Linux from 31MB to 20MB.
This has no effect on the final linked binary size.
> Strip redundant includes

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/abstract_tcp_server2.inl
Since connections from the ::connect method are now kept in
a deque to be able to cancel them on exit, this leaks both
memory and a file descriptor. Here, we clean those up after
30 seconds, to avoid this. 30 seconds is higher then the
5 second timeout used in the async code, so this should be
safe. However, this is an assumption which would break if
that async code was to start relying on longer timeouts.
> epee: regularly cleanup connections we kept a reference to

- .gitignore
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
`getheight` will return the current block height. Since `bc_height` is available in the simplewallet command line, it seems convenient to have this available via RPC as well.
> command "getheight" added to RPC wallet commands

- src/blockchain_db/lmdb/db_lmdb.cpp
This improves blockchain reorganization time by allowing one of the more expensive DB lookups when popping a block to not have to seek through a long dup list in the "output_amounts" subdb. This is most noticeable for HDDs.
As before, the dup list is still walked if necessary (but in reverse), and the global output index still confirmed to be the one looked for. But under proper use, the result will be found at the end of the dup list, so we start there.
Removing an amount output index is always done in the context of popping a block, so the global output index being looked for should be the last one in that amount key's dup list. Even if the txs themselves aren't removed in reverse order (supposed to be according to original implementation), the specified amount output index will still …
> BlockchainLMDB: When removing, find amount output index fast by starting at end

- src/blockchain_db/blockchain_db.cpp
- src/blockchain_db/lmdb/db_lmdb.cpp
Data should be removed in the reverse order it was added. Not doing so breaks assumptions and can cause problems in other DB implementations.
This matches the order of tx removal in `blockchain_storage::purge_block_data_from_blockchain`.
> BlockchainDB: Remove txs in reverse order

- src/blockchain_db/berkeleydb/db_bdb.cpp
- src/blockchain_db/berkeleydb/db_bdb.h
- src/blockchain_db/blockchain_db.cpp
- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
This is needed for utilities like blockchain_export, which don't need to make any DB writes.
> BlockchainDB: skip fixup check if read-only database

- external/miniupnpc/CMakeLists.txt
Note: this drops support for CMake 2.x because we're using 3.x-style comment blocks. For realsies.
> fix miniupnpc cmakelist

- src/wallet/wallet2.cpp
Also add some flags to open, as epee's save_string_to_file does,
to truncate file, etc.
> wallet: don't forget to close the file after storing cache

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/tx_pool.cpp
Fixes intermittent test failures when the pool contains
unexpected transactions that were brought in from the
live pool.
> core: do not use the persistent pool state for tests

- tests/unit_tests/hardfork.cpp
open isn't actually called in those tests
> unit_tests: initialize db object in ctor, not open

- external/miniupnpc/CMakeLists.txt
Parse error. Expected a command name, got unquoted argument with text "]]"
Reason: Block comments are avaliable in cmake 3.0 not in 2.8 which is used in Ubuntu 14.04
> fix: cmake parse error on Ubuntu 14.04

- src/simplewallet/simplewallet.cpp
This adds the option --password-file to simplewallet.
It is useful for GUI wallets that would otherwise spawn simplewallet using the --password option, because with --password-file the password does not show up on the operating system's process tree/list.
> add --password-file option to simplewallet

- external/unbound/CMakeLists.txt
- external/unbound/config.h.cmake.in
memcmp lacks an appropriate test, the local version is getting used unconditionally.
sha512 lacks a test, the local version is getting used unconditionally and clashes with OpenSSL's.
> Cleanup symbol clashes, stdlib header

- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/p2p/net_node.inl
> More verbose on successful update of out_peers, slight rewording of command description

- external/db_drivers/liblmdb/mdb.c
- tests/unit_tests/hardfork.cpp
one-liners missed in 0.9.0 / 0.9.1
> Lastminute

- src/wallet/wallet2.cpp
If an exception occurs, the thread needs to be joined, or it
will be deleted while still live, and terminate the process.
> wallet: guard against exception in process_blocks

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
A boost lock is used to determine whether more than one process
wants to access the database. The boost file_lock doesn't seem
to like locking directories, so we use an arbitrary file in it.
This allows to still run two daemons if they have different
database directories (ie, LMDB/BDB, different data directories).
> core: prevent the database from being used by multiple daemons

- src/cryptonote_core/cryptonote_core.cpp
Locking just one db turns out to not have been a good idea, since
the pool and p2p state fdles have to be used anyway.
Also ensure the directory exists before tring to lock.
> core: move the db lock to the data directory

- src/wallet/wallet2.cpp
If it is, it points to reuse of a tx key, which isn't meant to happen.
If it does, a key image collision means that only one of those
outputs is spendable, so the wallet selects the larger amount,
unless that output was spent already.
This causes a discrepancy betewen reported received inputs and
payment total.
Since tx keys are 256 bits, this should never happen except if
done on purpose, or if a sender uses a bad PRNG.
> wallet: check a key image isn't already present when adding one

- src/cryptonote_core/blockchain.cpp
This differs from the original CN code, and there seems to be
no reason to include the block itself, if it was found
> blockchain: revert handle_get_objects adding block id on tx not found

- src/blockchain_db/berkeleydb/db_bdb.cpp
- src/blockchain_db/berkeleydb/db_bdb.h
- src/blockchain_db/blockchain_db.cpp
- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/blockchain_utilities/blockchain_import.cpp
- src/cryptonote_core/blockchain.cpp
Move HardFork DB update to BlockchainDB::add_block()
Ensures the database is consistent.
Also simplifes blockchain_import in that verify mode off has less to work around.
> Move HardFork DB update to BlockchainDB::add_block()

- src/crypto/slow-hash.c
Setting to no or 0 also works. If set, any other value enables it.
Useful for running with valgrind in cases where it fails at
properly implementing AES-NI.
> crypto: use software AES based on the MONERO_USE_SOFTWARE_AES env var

- tests/core_tests/chaingen.h
It doesn't like const objects from classes that do not have
a user defined ctor, apparently.
Reported by othe.
> core_tests: fix a compile problem with CLANG

- src/blockchain_utilities/blockchain_import.cpp
- src/blockchain_utilities/fake_core.h
Sample usage:
blockchain_import --database berkeley
blockchain_import --database berkeley#txn_nosync
Alternatively, the optional DB flags for both LMDB and BerkeleyDB can be replaced by a composite mode, which matches those optionally provided as part of the daemon's --db-type argument ("safe", "fast", "fastest").
blockchain_import --database berkeley#fastest
Argument after the # is interpreted as a composite mode if there's only one (no comma separated arguments).
More examples:
blockchain_import --database lmdb#fast
blockchain_import --database berkeley#fast
Multiple specific DB flags are still supported, e.g.
blockchain_import --database lmdb#nosync,nordahead
blockchain_import --database berkeley#txn_nosync
> blockchain_import: Add BerkeleyDB support

- src/blockchain_utilities/CMakeLists.txt
- src/blockchain_utilities/blockchain_converter.cpp
- src/blockchain_utilities/blockchain_import.cpp
Pass the CMake bit width setting to compile flags for blockchain_import
and blockchain_converter.
For LMDB on 32-bit, hyc has found that batch size of 100 appears to be a
good default.
> blockchain_import: Check bit width for more than just WIN32

- src/blockchain_utilities/CMakeLists.txt
> blockchain_import: Pass ARCH_WIDTH macro if 32-bit or not.

- contrib/epee/include/syncobj.h
- src/blockchain_utilities/blockchain_converter.cpp
- src/blockchain_utilities/blockchain_dump.cpp
- src/blockchain_utilities/blockchain_export.cpp
- src/blockchain_utilities/blockchain_import.cpp
- src/blockchain_utilities/cn_deserialize.cpp
- src/connectivity_tool/conn_tool.cpp
- src/daemon/daemon.cpp
- src/daemon/main.cpp
- src/miner/simpleminer.cpp
- src/simplewallet/simplewallet.cpp
- tests/core_proxy/core_proxy.cpp
- tests/core_tests/chaingen_main.cpp
- tests/functional_tests/main.cpp
- tests/net_load_tests/clt.cpp
- tests/net_load_tests/srv.cpp
- tests/performance_tests/main.cpp
- tests/unit_tests/main.cpp
This avoids the need to define that variable in every program
which uses epee.
> move g_test_dbg_lock_sleep from a global to a function level static

- src/cryptonote_core/account.cpp
- src/cryptonote_core/account.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
It is similar in use to --restore-from-view-key, but also expects
a spend private key.
Requested by luigi1112, and useful to restore MyMonero wallets.
> simplewallet: add a new --restore-from-keys option

- src/blockchain_db/lmdb/db_lmdb.cpp
If user-defined comparator is used, subdb shouldn't be opened with
MDB_INTEGERKEY.
TODO: Again, this will be added back with future schema updates.
> Make partial revert consistent

- src/blockchain_utilities/blockchain_export.cpp
- src/blockchain_utilities/bootstrap_file.h
TEST:
`blockchain_export -h`
This should show "berkeley" as an available option to `--database`.
With an existing BerkeleyDB database, run:
`blockchain_export --database berkeley`
> blockchain_export: Support BerkeleyDB

- src/simplewallet/simplewallet.cpp
Because obviously it doesn't work as other POSIX platforms.
Reported and tested by luigi1111.
> simplewallet: special ^C handling for windows

- src/simplewallet/simplewallet.cpp
It would try to join the auto refresh thread, which would
only happen after it was done, which would take a long time
when doing so on a newly created wallet.
> simplewallet: fix hang when setting auto-refresh to 0

- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
Only if we created the readtxn. Was missing cleanups from exceptions before.
> Add destructor for readtxns

- tests/CMakeLists.txt
They should not have been disabled in the first place
> tests: enable core tests again

- src/daemon/rpc_command_executor.cpp
It was only filling the input in non rpc mode
> rpc: fix print_tx in command line mode

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
It's logging the blockchain height, not the top block height
> cryptonote_protocol: clarify height wording

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
It takes a filename containing JSON data to generate a wallet.
The following fields are valid:
version: integer, should be 1
filename: string, path/filename for the newly created wallet
scan_from_height: 64 bit unsigned integer, optional
password: string, optional
viewkey: string, hex representation
spendkey: string, hex representation
seed: string, optional, list of words separated by spaces
Either seed or private keys should be given. If using private
keys, the spend key may be omitted (the wallet will not be
able to spend, but will see incoming transactions).
If scan_from_height is given, blocks below this height will not
be checked for transactions as an optimization.
> wallet: add a --generate-from-json flag

- Doxyfile
- src/blockchain_db/blockchain_db.h
- src/cryptonote_core/CMakeLists.txt
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/blockchain_storage.cpp
- src/cryptonote_core/checkpoints.cpp
- src/cryptonote_core/checkpoints_create.cpp
- src/cryptonote_core/checkpoints_create.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/difficulty.cpp
- src/cryptonote_core/difficulty.h
- src/daemon/core.h
Breaks compilation at least on OS X, which is very bad for a PR that is meant to just be documentation changes:-P
```
In file included from /Users/ric/Desktop/working/bitmonero/src/cryptonote_core/checkpoints.h:36:
/Users/ric/Desktop/working/bitmonero/contrib/epee/include/storages/portable_storage_template_helper.h:75:14: error:
moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
return std::move(json_buff);
^
/Users/ric/Desktop/working/bitmonero/contrib/epee/include/storages/portable_storage_template_helper.h:75:14: note:
remove std::move call here
return std::move(json_buff);
^~~~~~~~~~         ~
/Users/ric/Desktop/working/bitmonero/contrib/epee/include/storages/portable_storage_template_helper.h:120:14: error:
moving a local object in a return …
```
> Revert "Merge pull request #749"

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/verification_context.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet_errors.h
This allows appropriate action to be taken, like displaying
the reason to the user.
Do just that in simplewallet, which should help a lot in
determining why users fail to send.
Also make it so a tx which is accepted but not relayed is
seen as a success rather than a failure.
> Convey tx verification failure reasons to the RPC client

- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/unbound.cpp
These can be compiled out of libunbound, leading to failure
to check DNSSEC validity.
> tests: add test for needed OpenSSL algorithms in unbound

- src/cryptonote_core/cryptonote_format_utils.cpp
This can generate non decomposed outputs for very large block
rewards (or not so large ones if a miner decides to not quantize
the block rewards). Out of an abundance of caution, we refuse
to generate those. They are still accepted by the consensus code,
however.
> core: remove the block reward accumulation loop

- contrib/epee/include/misc_log_ex.h
This is equivalent to line buffering, as C++ seems to lack
a setvbuf equivalent which alows line buffering.
> epee: flush output after a message

- contrib/epee/include/misc_os_dependent.h
GetTickCount used in 52056dcfc480a126e06afaf209b1772b6aa77fb3
only has ~10-16ms resolution. Use higher rez timer to get 1ms rez.
> Fix get_tick_count() on Windows

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
As pointed out by smooth, a transaction's validity may change
over time as the blockchain changes.
> blockchain: remove the tx validation result cache

- src/cryptonote_core/cryptonote_format_utils.cpp
For unknown reasons, it was generated with a block reward
consisting of a single large dusty output.
> core: keep the acc loop for the genesis block

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/functional_tests/transactions_flow_test.cpp
This now requests the set of outputs that can be mixed first,
to avoid trying non dust but unmixable outputs, which we know
will fail.
> wallet: better output selection for transfer/transfer_new

- src/simplewallet/simplewallet.cpp
^C when in RPC mode would not save the wallet while it was still
refreshing after starting up.
Also, save the wallet out of the signal handler. We don't want
to call complex stuff in a signal handler.
> simplewallet: save fixes in RPC mode

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Wallet balance can be misreported when there are unconfirmed transactions with dust amounts generated from change.
If dust is meant to be added to fee or sent elsewhere to a specific dust address, the change amount was not updated to reflect this.
Suggested fix:
I have mainly modified transfer, transfer_selected.  After tx details have been worked out, do the following:
-ptx.fee has dust explicitly added to it if specified by the dust policy.
-change_dts.amount has dust subtracted from it if dust is added to fee or sent elsewhere 
-dust is zero if it is not added to fee and not sent elsewhere (i.e. it's still in the change)
In addition I've made the confirm prompt in simple_wallet::transfer a little bit more verbose so the user knows more about what's going on in regards to dust amounts. …
> Fix unconfirmed balance, accurately report fees

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
This sends all outputs in a wallet to a given address, alleviating
the difficulty people have had trying to send all monero but
being left with some small amount left.
> wallet: add a new sweep_all command and RPC command

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
We want to lock operations which access the blockchain in
wallet2. We also want the background refresh to happen again
when we cancel a foreground refresh. Wrap the locking setup
in a macro so it doesn't get copy/pasted/mangled, and use
a scope exit trick to ensure it's always properly restored.
> simplewallet: some background refresh threading fixes

- src/crypto/random.c
Avoids silent use of bad RNG in release builds, in case those
calls might actually fail.
Reported by smooth.
> random: call abort(3) instead of assert in must_succeed macro

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
Allows getting in, out, pending, and failed transfers, similarly
to the show_transfers command.
> wallet: add get_transfers rpc call

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
It allows a simple get_transfers (with default 0 min_height and
max_height) to return all transactions, instead of the unexpected
set of txes in block 0, which is probably none at all.
> wallet: add a filter_by_height field to get_transfers

- src/blockchain_db/berkeleydb/db_bdb.cpp
- src/common/util.cpp
- src/common/util.h
- src/cryptonote_core/blockchain.cpp
- src/daemon/command_line_args.h
- src/daemon/main.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
It sets the max number of threads to use for a parallel job.
This is different that the number of total threads, since monero
binaries typically start a lot of them.
> add a --max-concurency flag

- src/crypto/crypto.cpp
- src/crypto/crypto.h
- src/crypto/random.c
- src/crypto/random.h
And add a thread safe version to encourage proper use
> crypto: make clear generate_random_bytes is not thread safe

- src/crypto/slow-hash.c
The implementation of mul in asm breaks 'slow-hash' test when built with
GCC 6.1.1.  Disable this implementation in favor of plain C until it is
fixed.
Workaround for Issue #847.
(Submitting PR to make it easy for others to apply the patch. Not expecting this to be merged necessarily.)
> crypto: slow-hash: disable mul implemented in asm for ARM

- external/db_drivers/liblmdb/midl.h
Use the same size dirty list for both 64 and 32 bit.
> Fix Issue #855

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
It matches the daemon, and should allow people who're suspicious
of the background refresh to know they're synced.
> simplewallet: add a status command

- src/simplewallet/simplewallet.cpp
gmtime_r is not available in Windows, use gmtime_s instead. Also change shorthand codes (also not working in Windows).
> gmtime for Windows

- LICENSE
- README.md
Packages want to copy license file to `/usr/share/licenses/bitmonero/LICENSE`.
> readme: move license to separate file for packaging

- contrib/epee/include/net/abstract_tcp_server2.h
The noexcept specs were added to make GCC 6.1.1 happy (#846), but this
one was missing (because GCC did not complain about it on Linux, but
does complain on OSX).
This is an attempt to fix #871
> contrib: epee: add missing noexcept spec to class decl

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
Fee can now be multiplied by 2 or 3, if users want to give
priority to their transactions. There are only three levels
to avoid too much fingerprinting. Default is 1 (minimum fee).
The default multiplier can be set by "set fee-multiplier X".
> wallet: add a fee multiplier

- src/simplewallet/simplewallet.cpp
It should be less confusing for people who're used to the foreground
refresh from earlier versions.
> simplewallet: mention the background refresh thread when starting

- src/daemon/main.cpp
When an exception happens while reading the config file, we need
to print the error, as the logging system isn't initialized yet,
so the generic catch will not print anything.
> daemon: print exception errors when failing to parse config file

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
- src/wallet/wallet_rpc_server_error_codes.h
Signing is done using the spend key, since the view key may
be shared. This could be extended later, to let the user choose
which key (even a per tx key).
simplewallet's sign/verify API uses a file. The RPC uses a
string (simplewallet can't easily do strings since commands
receive a tokenized set of arguments).
> wallet: add command and RPC to sign/verify data

- CMakeLists.txt
This patch is a temprorary workaround until aliasing is fixed in the
code (Issue #847).
> cmake: pass -fno-strict-aliasing to fix build with GCC 6.1.1

- src/daemonizer/posix_fork.cpp
Keep the working directory (and umask) inherited from
the parent. Otherwise, it's impossible to control
the working directory of the daemon (from systemd, for
example).
Furthermoer, bitmonerod attempts to create logging directories and files
*in current working directory*. This fails due to permission denied and
generates a (caught, nonfatal) exception. Below is the strace with this
patch applied (so, no `chdir("/")`), showing successful opens at `log/`
relative path. Without this patch they fail (sorry, didn't save the
trace).
```
28911 getcwd("/.../bitmonero", 128) = 25
28911 stat64("/var/lib/bitmonero/.bitmonero", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
28911 stat64("/etc/bitmonerod.conf", {st_mode=S_IFREG|0644, st_size=244, ...}) = 0
28911 open("/etc/bitmonerod.conf", …
```
> daemonizer: posix: keep parent's working dir and umask

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
If the version is different, simplewallet will refuse to use that
daemon, unless --allow-mismatched-daemon-version is used.
> Add a daemon RPC version, and make simplewallet check it

- .travis.yml
- README.md
Here is a baseline Travis-CI configuration.
In the future, we should further develop a build matrix to suit our needs: expand build options, multiple compilers and versions, etc. but, for now, this minimal configuration can (at the very least) provide an easy way to see if PR's build successfully.
I've excluded the static build option because of #907 but we should consider adding the static build once the issue is resolved. Also, because of #906, I've included boost 1.55 as our boost-of-choice despite 1.54 building successfully.
Currently, the status badge points to [anonimal/bitmonero](https://travis-ci.org/anonimal/bitmonero) but that should be changed once @fluffypony or any repo owner signs-up for Travis-CI.
Sign-up should be simple as it's already been done for Kovri. Here are some …
> Implement Travis-CI

- CMakeLists.txt
The tests currently issue a warning
warning: -fassociative-math disabled; other options take precedence
The associative math optimization is turned on indirectly by -Ofast.
Apparently, the optimization is forced to be disabled, while compiling
test harnesses generated by Google Test framework.
Unfortunately, there is no -Wno-error=* flag to disable this warning
(see gcc --help=warnings).
An alternative to this patch is to disable the optimization explicitly
with -fno-associative-math, but that seems worse.
Another alternative is to not pass -Ofast for tests build, but we
want the tests to be built with exact same optimization flags as
the code being tested, otherwise the value of the tests is diminished.
Another alternative is to remove -Werror from the entire build, but
it's good to …
> cmake: do not pass -Werror when building tests

- src/simplewallet/simplewallet.cpp
Background refresh is confusing to users at startup.
> simplewallet: revert to foreground refresh at startup

- src/wallet/CMakeLists.txt
This fixes this error which (presumably) was introduced with #915:
```
CMake Error at cmake/MergeStaticLibs.cmake:35 (message):
Merge_static_libs can only process static libraries
Call Stack (most recent call first):
src/wallet/CMakeLists.txt:90 (merge_static_libs)
-- Configuring incomplete, errors occurred!
```
Re #915, it is not clear why libunbound was added to this in the first place,
since it wasn't here before and #915 doesn't seem to introduce any
new dependency on it.
Tested build with STATIC=OFF (with and without libunbound-dev libunbound8
installed) and STATIC=ON, on Ubuntu Trusty, Debian Jessie, and Arch
Linux. For static builds, beware of #926 and #907.
If this hack was introduced to make it build on some other system
(Windows? OS X?), then it will have to be dealt with, but …
> cmake: wallet: fix cmake error related to libunbound is not always static

- CMakeLists.txt
I don't have OSX to test, but this might fix #932. Tested on Linux with Clang.
This PR's branch is on top of PR #933, which is for a separate issue #926, but touches same lines and that issue is likely to also be a problem on OSX. The fix being PRed here is  	4b3a788.
> cmake: fix static build on osx (an attempt)

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
- src/wallet/wallet_rpc_server_error_codes.h
They are used to export a signed set of key images from a wallet
with a private spend key, so an auditor with the matching view key
may see which of those are spent, and which are not.
> wallet: new {ex,im}port_key_images commands and RPC calls

- CMakeLists.txt
- src/common/CMakeLists.txt
- src/common/stack_trace.cpp
- src/daemon/main.cpp
By default the flag is enabled whenever libunwind is found on the
system, with the exception of static build on OSX (for which we can't
install the throw hook #932 due to lack of support for --wrap in OSX
ld64 linker).
> cmake,common: flag for stack trace (should fix OSX build #932)

- .travis.yml
Knowing Travis CI, this may take a few more commits to fine-tune.
Referencing https://github.com/monero-project/bitmonero/blob/master/CMakeLists.txt#L415
> Build: add release-test and clang support to Travis CI

- src/simplewallet/password_container.cpp
- src/simplewallet/password_container.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
commit 9af9e4223b58bbb65a3519af2c2bfc273cbd23d6
Author: guzzi_jones <guzzijones12@gmail.com>
Date:   Mon Aug 1 00:00:19 2016 +0000
fixed some formatting
commit c7920e1cf88ff46eb9294101344d9a567f22e2da
Merge: 97eb28b 1da1c68
Author: guzzi_jones <guzzijones12@gmail.com>
Date:   Sun Jul 31 23:36:24 2016 +0000
fix#864 fix using boolean
commit 97eb28ba5dd49ddde8c8785f39b24d955e5de31c
Author: EC2 Default User <ec2-user@ip-172-31-47-165.us-west-2.compute.internal>
Date:   Sun Jul 24 02:08:10 2016 +0000
Fix #864 boolean value used to verify on new wallet
commit 1da1c68bd3a9a373c70482b6e6e95251096149f1
Author: guzzi_jones <guzzijones12@gmail.com>
Date:   Sun Jul 31 21:47:43 2016 +0000
fix #864 changed to boolean to prompt for verify
commit 5bee96652434762d2c91ce31a1b1c9f169446ddc
Author: …
> Fix#864 - prompt for password twice

- src/blockchain_db/lmdb/db_lmdb.cpp
This db is now dropped unconditionally, so may or may not be there
in the first place.
> db_lmdb: errors dropping hf starting height db on reset are not fatal

- CMakeLists.txt
- README.md
Personally, I would hold off on merging this until #951 and related documentation are resolved.
I have a feeling if #951 isn't resolved by the same time this is merged, there will be swarm of complaints about the build (e.g., any Debian stable users who don't know how to use apt-get, etc.).
> Build: make boost 1.58 minimum requirement. Fixes #956

- src/wallet/wallet2.cpp
It avoids rescan_spent resetting spent status, for example.
> wallet: store key images after importing them

- src/CMakeLists.txt
This fixes the log output not getting redirected to log file.
> cmake: fix typo in handling of STACK_TRACE

- README.md
CMake will fail if Boost < 1.58. I think we should either adjust the recipe to apply only for clang or keep as-is and enforce 1.58 minimum.
I was hoping for more dialogue in #964 or #956 before merging but here we are.
> Docs: re-introduce Boost 1.58 min req from 2a2b655

- src/simplewallet/simplewallet.cpp
A suspected bug in pthread/kernel, though might be that
I messed something up too...
This might rope in more platforms though.
> simplewallet: default to max-concurrency 1 on MacOS X

- src/wallet/api/wallet.cpp
- src/wallet/wallet2_api.h
- tests/libwallet_api_tests/main.cpp
this fixes following issue: first monero-core tries to open wallet with the empty password;  next, if status is not ok it assumes wallet is password protected, closes currently opened wallet and re-opens it asking password.
```wallet2::store()``` called unconditionally on close - and if wallet wasn't actually opened due wrong password - ```wallet2::store()``` corrupts the wallet so it can't be opened anymore.
> libwallet_api: do not store wallet on close if status is not ok

- README.md
It seems that the changes to the readme from #964 got lost because of conflicts. #981 fixed this for the linux section. But windows is affected too.
> README.md: Boost version for windows

- README.md
- utils/conf/bitmonerod.conf
- utils/systemd/bitmonerod.service
Including in light of #977 
This more the job for packages, but including these samples for the benefit of users who want to setup things manually, before packages arrive.
EDIT: If `contrib/` is a bad place for this, then maybe add a subdir called `conf`?
> contrib: example systemd service and config file

- .travis.yml
This will allow people to have Travis push notifications
for their repo without spamming the dev channel
> Build: move Travis IRC notification channel

- CMakeLists.txt
This gets rid of bitmonerod.exe's dependecy on libwindpthreads-1.dll in build
on Windows on x86_64 (via MSYS2 default toolchain). With this patch all DLL
dependencies are on DLLs in c:\windows\system32.
NOTE: As far as I can tell, -static implies -static-libgcc and -static-libstdc++.
Tested on Windows 7 x86_64 and Linux x86_64.
> cmake: pass -static when STATIC=ON on Windows

- CMakeLists.txt
Lets 'cmake .. && make' be sufficient to build.
> cmake: define a default build type

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
It is useful, especially when requesting a random one
> wallet_rpc_server: return payment id in make_integrated_address RPC

- CMakeLists.txt
- Makefile
- README.md
After @radfish's changes, I've rewritten the CMakeLists.txt, Makefile and README.md to add support for ARMv8 compilation.
Also added flags for workarounds of issues on the Cortex-A53 that affect 64-bit MAC operations and internal paging 
CMakeLists should also try to select the most appropriate flags for the FPU and floating-point ABI for ARMv7 devices
NB ARMv8 has the FPU and NEON SIMD 'always on' which is why -mfpu and -mfloat options cease compilation
> Add ARMv8 support to CMakeLists and Makefile - 2nd go

- README.md
- tests/CMakeLists.txt
- tests/daemon_tests/CMakeLists.txt
- tests/libwallet_api_tests/CMakeLists.txt
- tests/net_load_tests/CMakeLists.txt
- tests/unit_tests/CMakeLists.txt
The build with the system gtest broke because it was linking against -lgtest_main instead of -lgtest (or both). Additional problem was a bug  in the cmake script.
Issues #980 #983
> cmake: tests fix build with system gtest

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
The code used to cap at 5000 blocks per sync. It also treated 0 as 1.
Remove these checks; if specified as 0 do no periodic syncs at all.
Then the user is responsible for syncing in some external process.
> Remove blocks_per_sync limits

- contrib/epee/include/net/net_helper.h
Fixes the wallet being unable to connect to the daemon
when there is no NIC.
> epee: do not try network resolution if loopback worked

- CMakeLists.txt
- external/unbound/CMakeLists.txt
The split is to make this software more packageable. 'make install'
is used by the package building scripts, and should not be installing
vendored dependencies onto the system.
After that point, I might PR a minor rename of BUILD_GUI_DEPS to both repos, although that might be more trouble than it's worth.
> cmake: split BUILD_GUI_DEPS option into two

- src/CMakeLists.txt
32-bit build would fail to link with 'mdb_env_create undefined' (because
for 32-bit build, mdb_env_create_vl32 is defined instead).
This bug was introduced with the recent change to virtual object
libraries. The problem is that the COMPILE_DEFINITIONS property
was not propagated from dependee target (lmdb) to depedent
target's (blockchain_db) virtual object lib (obj_blockchain_db).
This patch makes that happen.
I chose to include INTERFACE_COMPILE_DEFINITIONS because there
should not be a need to propagate private defs, but it doesn't
make a difference in this case.
> cmake: fix def propagation, fixes 32-bit build

- src/crypto/CMakeLists.txt
- src/crypto/slow-hash.c
This was disabled earlier as part of diagnosing failing tests
on ARM, which turned out to be due to aliasing, fixed by
adding -fno-strict-aliasing. So, re-enabling it back.
Tested on armv7: tests pass (excluded coretests), import --verify 1 successfully imports 1000 blocks.
> crypto,cmake: enable ASM mul impl on ARM; add cmake opt

- tests/unit_tests/block_reward.cpp
Issue #1008 
__x86_64__ might not be perfect, but hopefully it's fine (tested gcc, didn't test clang). Don't want to do an if condition on sizeof() at runtime because the code in question (that's being disabled) generates a warning about overflow when compiled on 32-bit.
> tests: block reward: disable 64-bit-only tests on 32-bit systems

- contrib/snap/daemon.bash
- contrib/snap/log.bash
- contrib/snap/wallet.bash
- snapcraft.yaml
- src/daemon/CMakeLists.txt
- src/simplewallet/CMakeLists.txt
This adds [snap](https://snapcraft.io) packaging to the project. See the
link for more information on snaps, but basically, snap packages install on all Linux
distributions. On Ubuntu, snap confinement with apparmor and seccomp
provide an additional layer of security.
This snap sets up monerod as a systemd service, which should start
immediately on install. To access the wallet CLI, simply run `monero`
(/snap/bin/monero). I think it's a really quick & easy way to get
started with monero.
I've made some opinionated decisions in the packaging just to kick this
off, but I'm happy to iterate on this stuff.
> Add snap packaging.

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_format_utils.cpp
- src/cryptonote_core/tx_pool.h
There are some compile errors when DEBUG_CREATE_BLOCK_TEMPLATE is defind and also some when PER_BLOCK_CHECKPOINT is undefined.
> compile errors for DEBUG_CREATE_BLOCK_TEMPLATE and PER_BLOCK_CHECKPOINT

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
We keep 1, 2, 3 multipliers till the fee decrase from 0.01/kB
to 0.002/kB, where we start using 1, 20, 166 multipliers.
This ensures the higher multiplier will compensate for the
block reward penalty when pushing past 100% of the past median.
The fee-multiplier wallet setting is now rename to priority,
since it keeps its [0..3] range, but maps to different multiplier
values.
> wallet: change priority/fee to ArticMine's recommendation

- CMakeLists.txt
Those vars are always set, no point in checking. #1065 (incorporating own feedback from that PR)
> cmake: remove redundant checks around CMAKE_{AR,RANLIB}

- src/simplewallet/simplewallet.cpp
They're confusing, as people think it reports their balance.
> simplewallet: do not expose the details of tx splitting to the user

- src/cryptonote_core/miner.cpp
This saves on an exception dump when trying to write to /
after finding a block.
> miner: do not try to save config if the path isn't set

- src/wallet/wallet2.cpp
This fixes misreporting of amount/fee in rct txes, as the rct
tx construction code was lumping all dests (whether change or
not) in the same dests vector, while the pre-rct code was
keeping it separate.
> wallet: keep change dest separate from other dests

- contrib/epee/include/net/http_base.h
- contrib/epee/include/net/http_client.h
- contrib/epee/include/net/http_protocol_handler.h
- contrib/epee/include/net/http_protocol_handler.inl
- contrib/epee/include/net/http_server_impl_base.h
- src/common/command_line.cpp
- src/common/command_line.h
- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/command_server.h
- src/daemon/daemon.cpp
- src/daemon/main.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
This is intended to catch traffic coming from a web browser,
so we avoid issues with a web page sending a transfer RPC to
the wallet. Requiring a particular user agent can act as a
simple password scheme, while we wait for 0MQ and proper
authentication to be merged.
> epee: optionally restrict HTTP service to a configurable user agent

- CMakeLists.txt
With this it now builds and runs on FreeBSD 10.1 which uses clang version 3.4.1. Otherwise I get errors for 'iostream' file not found and stdc++ not found.
> Don't define stdc++ on FreeBSD

- src/blockchain_db/lmdb/db_lmdb.cpp
Message observed while synchronizing a node from scratch.
"LMDB memory map needs resized"
Proposing a change to:
"LMDB memory map needs to be resized"
> Fix minor typo in "need resize" message.

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/wallet2_api.h
- tests/libwallet_api_tests/main.cpp
- tests/libwallet_api_tests/scripts/README.md
- tests/libwallet_api_tests/scripts/create_wallets.sh
- fixed deadlock happened in "Wallet::close()" (introduced in https://github.com/monero-project/monero/commit/8a274eab3feab820f38503f98a3caecb5dded4a5, wait_for() was replaced to wait()), referred in issue: https://github.com/monero-project/monero-core/issues/25
- introduced getter and setter for "refresh interval"
- improved tests
> Fix "wallet->close()" deadlock

- src/simplewallet/simplewallet.cpp
I encountered this error when attempting to transfer a small amount that was the full account balance. I found a couple examples of this more complete and helpful error message being used when the same error is caught.
> Made error message consistent with other, more helpful, message

- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
Sometimes spelled 'responce'. 
Fixed to the standard spelling 'response'. 
This may fix some functionality - some calls had mixed spellings, particularly the creation of the ```response``` struct in ```contrib/epee/include/net/jsonrpc_structs.h ``` where it's later referred to as ```responce``` in other functions.
> Noticed two spellings of the word 'response' in the codebase

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/rlwrap/monerocommands_bitmonerod.txt
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
As per @moneromooo-monero's suggestion way back in #592
Also removed detach_threads() in `contrib/epee/include/net/abstract_tcp_server2.inl` which was only called in response to fast_exit
> Removed all code related to fast_exit

- src/cryptonote_core/blockchain.cpp
This is fine if our local chain is so small that it is entirely
contained within the last jump in the peer's short chain history.
> blockchain: do not reject chain histories matching only genesis

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
This reverts commit 78035d2b6c9922f4cd730df0766aa74f4854ccb2.
The patch doesn't work, and causes constant SYNCHRONIZED OK spam.
> Revert "Fix fake 'network synchronized, begin using' messages"

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
set confirm-missing-payment-id 0|1
Defaults to true.
> wallet: wallet option to confirm transfers with no payment id

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
I added this to be able to send transfers with unlock_time from the wallet:
`locked_transfer [<mixin_count>] <addr> <amount> <lockblocks> [<payment_id>]`
`lockblocks` is the number of blocks to lock the transaction for. I set this to max 1 million blocks now, about 4 years, figured people don't want to lock up their transactions for 100 years by accident. It only works for blocks, no time stamps, and only 1 amount and address.
It asks for confirmation before sending the transaction:
```
Transaction fee is 0.023000000000, of which 0.003000000000 is dust from change.
The unlock time is approximately 221.20 days.
Is this okay?  (Y/Yes/N/No)n
```
I'm not sure how popular unlock_time is, but I can see people want to use it as a way to lock up monero savings and not panic sell with large swings …
> wallet: Add locked_transfer - transfer with unlock_time

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
This was still using the old transaction creation algorithm,
coupled with a deterministic output selection scheme, which
made it ill suited to the job, since it'd loop indefinitely
in case the fee increased between the test tx and adding the
fee.
> wallet: better implementation of sweep_unmixable

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/wallet/wallet2.cpp
25% of the outputs are selected from the last 5 days (if possible),
in order to avoid the common case of sending recently received
outputs again. 25% and 5 days are subject to review later, since
it's just a wallet level change.
> wallet: select part of the fake outs from recent outpouts

- src/cryptonote_config.h
Currently dust threshold is 0.01, which means often you can end up paying a much higher fee than that the current 0.002 fee per kb.  I suggest bringing the dust threshold down to equal the fee per kb.
> Change default dust threshold to equal current fee per kb

- src/wallet/api/wallet.cpp
Instead, return an empty string to mark the error
NOTE: see https://github.com/monero-project/monero-core/issues/64 because it might break assumptions in the GUI code, need mbg033 to reply first.
> wallet_api: do not override invalid payment id

- src/wallet/api/wallet.cpp
- src/wallet/wallet2_api.h
The payment id from integrated addresses is also parsed
> wallet_api: add address validation functions

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Re-creating the transaction on the cold wallet was not splitting
the change, causing the transaction to be rejected by the network.
This worked on testnet since amounts do not have to be split.
> wallet: fix pre-rct cold wallet signing not splitting change

- src/crypto/skein.c
How much of an issue is it that the 256-bit skein pathway never runs (prior to this PR)?
> Changed ..._HASH_BITS to ..._HASHBITS as expected

- src/simplewallet/simplewallet.cpp
This will happen when sending to another address, after removing
the fee.
> simplewallet: remove destinations with zero amount in sign_transfer

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
This is on the potentially compromised wallet, but still guards
against stupid mistakes.
> wallet: print tx overview on submit_transfer too

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
The intended use is to export outputs from a hot wallet, which
can scan incoming transfers from the network, and import them
in the cold wallet, which can't. The cold wallet can then compute
key images for those outputs, which can then be exported with
export_key_images, etc.
> wallet: new import_outputs/export_outputs commands

- contrib/epee/include/string_tools.h
- src/wallet/wallet2.cpp
An error log message is serializing the contents of a `std::list<crypto::key_image>` object, which I doubt is intended. Added `static_assert`s to catch potentially any future unintentional calls. This trait is available as far back as Gcc 4.6 (maybe further), and Clang 3.4
> adding static_assert to pod functions in string tools

- src/simplewallet/simplewallet.cpp
- src/wallet/api/transaction_history.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
m_amount_out was sometimes getting initialized with the sum of
an transaction's outputs, and sometimes with the sum of outputs
that were not change. This caused confusion and bugs. We now
always set it to the sum of outputs. This reverts an earlier
fix for bad amounts as this used the other semantics. The wallet
data should be converted automatically in a percentage of cases
that I'm hesitant to estimate. In any case, restoring from seed
or keys or rebuilding the cache will get it right.
> wallet: fix bad amounts/fees again

- src/common/CMakeLists.txt
- src/common/thread_group.cpp
- src/common/thread_group.h
- src/ringct/rctSigs.cpp
Looking for general feedback (tests need to be written, etc., before merging)...
This was from a [discussion in a prior pull request](https://github.com/monero-project/monero/pull/1272). This does not use `asio::io_service` because it is a bit clunky to wait for all threads to complete `io::service::run()` (to guarantee that all handlers have completed), then restart the `io::service::run()` to re-use the threads - busy spin loops or condition variables would be needed which makes the implementation look similar to this. I added the thread re-use "feature" because one of the functions in `rctSigs.cpp` created two different `thread_group` objects, mainly so that the dispatched functions were guaranteed to complete before moving to the next section. Arguably, `std::future` should be used …
> adding thread_group for managing async tasks

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
This key is available to both cold and hot wallet.
Authenticated encryption will guard against interception and/or
modification of the file.
> wallet: encrypt outputs and key images files with the view key

- src/crypto/crypto.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
GIVE LUIGI TIME TO DOUBLE CHECK FIRST PLEASE
View wallets do not have the spend secret key, and are thus
unable to derive key images for incoming outputs. Moreover,
a previous patch set key images to zero as a means to mark
an output as having an unknown key image, so they could be
filled in when importing key images at a later time. That
later patch caused spurious collisions. We now use public
keys to detect duplicate outputs. Public keys obtained from
the blockchain are checked to be identical to the ones
derived locally, so can't be spoofed.
> wallet: fix output collision detection for view wallets

- src/cryptonote_config.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_protocol/cryptonote_protocol_defs.h
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/daemon/rpc_command_executor.cpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/net_node_common.h
- src/p2p/p2p_protocol_defs.h
Pretty much same as #1242, but fixed up the p2p stuff so that it works with current release nodes. In the previous version I altered the existing handshake, etc structs to send extra data, so it didn't play nice with current nodes. The new one has an extra trip/call for support flags on handshake. If you run this against current release nodes you will see a bunch of errors, but it should be fine, it's just the "get_support_flags" command failing since release nodes don't have it.
> fluffy-blocks-p2p-bit-flags

- src/rpc/core_rpc_server_commands_defs.h
I forgot to bump it previously when changing RPC, most notably
for the addition of the unlocked field in the histogram RPC.
This causes new wallets to not realize when they're talking to
an older daemon, and get confused trying to get outputs to use
as fake outs. This otherwise gratuitous bump ensures than old
daemons will be detected by wallets using this code.
> rpc: bump RPC version

- CMakeLists.txt
Also removed the duplicated setting of compilation flags and corrected the missing `STATIC_ASSERT_FLAG`
> Always compile Position Independent Code on 64-bit ARMv8 systems

- contrib/epee/include/net/levin_protocol_handler_async.h
When receiving an answer packet, the command code was passed
to the callback instead of the error code. This was hiding
the "command not found" failure from the peer, and in turn
causing the code to attempt to deserialize a non existent
reply string.
> levin: fix wrong value passed as return code to remote call

- src/wallet/CMakeLists.txt
There is no need to build monero-wallet-rpc when building monero-core.
> Don't build monero-wallet-rpc when building the GUI

- src/simplewallet/simplewallet.cpp
Title says it all. It would be nice to unit test some these portions, but they could be difficult to add with the amount of reads from `stdin` ...
> Fixed generate-from-json bug introduced in 358e068

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet2_api.h
ping @luigi1111 
Using one month (21600 blocks) as fudge. Should it be dynamic instead?
> Wallet2: calculate approximate blockchain height on offline creation

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
This also needs to make sure to pick the correct one, in the case
where cold signing caused to tx keys to be included.
> wallet: fix exporting outputs and key images with txes with two pubkeys

- src/common/CMakeLists.txt
- src/common/task_region.cpp
- src/common/task_region.h
- src/common/thread_group.cpp
- src/common/thread_group.h
- src/ringct/rctSigs.cpp
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/thread_group.cpp
The `thread_group` class that was added recently can re-use threads, but only "wait" on a single group of tasks at a time (all outstanding). This could be problematic if it were put into some "core" code somewhere; an asynchronous task could not start more tasks + wait because it would result in deadlock (the spawned task would be waiting for itself).
Eventually I settled on a fork-join implementation. The syntax is stolen heavily from `boost::thread::experimental` and `HPX` code, both of which are based on C++ proposal N4105. A semi-complex example from tests:
```c++
TEST(ThreadGroup, Nested) {
struct fib {
unsigned operator()(tools::thread_group& group, unsigned value) const {
if (value == 0 || value == 1) {
return value;
}
unsigned left = 0;
unsigned right = 0; …
```
> Added task_region - a fork/join task implementation

- tests/unit_tests/hardfork.cpp
Removed whitespace from a [now uncloseable pull request](https://github.com/monero-project/monero/pull/1370), and adds an extra check not present in a [still open pull request](https://github.com/monero-project/monero/pull/1350).
> Fixed undefined behavior in TestDB

- README.md
Can somebody please have a look at this to see if the final formatting has improved. The following sections were incorrectly formatted. For example:
sudo /etc/init.d/dphys-swapfile stop sudo nano /etc/dphys-swapfile CONF_SWAPSIZE=1024 sudo /etc/init.d/dphys-swapfile start
Should have been four separate lines of instructions...which again I can't seem to get to format correctly here.
If anyone knows the trick to getting multi-line lists in 'code format', please let me know.
> Fix formatting of RPi2 build instructions

- src/common/command_line.cpp
- src/common/command_line.h
- src/simplewallet/simplewallet.cpp
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/command_line.cpp
- translations/monero.ts
Code that parsed for "YES/y" now use a single function.  Updated translations file. Useful for `monero-wallet-rpc` - I can include these changes in that request (not yet opened)  if preferred.
> Added command_line::is_yes

- src/rpc/core_rpc_server_commands_defs.h
- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Daemon RPC version is now composed of a major and minor number,
so that incompatible changes bump the major version, while
compatible changes can still bump the minor version without
causing clients to unnecessarily complain.
> Improve daemon RPC version handling

- src/ringct/rctSigs.cpp
If purported pubkeys aren't actually valid pubkeys, exceptions
will fly. These will terminate if thrown in a worker thread.
Guard against this.
> ringct: guard against bad data exceptions in worker threads

- src/wallet/wallet2.cpp
If a rct transaction would cause no change to be generated, a zero
change output is added, and sent to a randomly generated address.
This ensures that no transaction will be sent with just one output,
which could cause the receiver to be able to determine which of the
inputs in the sent rings is the real one.
This is very rare, since it requires the sum of outputs to be equal
to the sum of outputs plus the fee, which is now a function of the
last few blocks.
> wallet: send 0 change to a random address where necessary with rct

- CMakeLists.txt
Never achieved what it set out to do, looking at the failure logs for the ARMv8 builds.
Just seems to increase compile time.
> Revert forcing -fPIC for all ARMv8 builds

- src/cryptonote_core/blockchain.cpp
The wrong iterator was being used.
Also preincrement iterators to avoid possibly invalidating them,
I'm not sure this is necessary, but let's be safe.
> blockchain: fix setting non trovial alternate chain as invalid

- src/cryptonote_core/cryptonote_format_utils.cpp
- src/cryptonote_core/cryptonote_format_utils.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
A bug in cold signing caused a spurious pubkey to be included
in transactions, so we need to ensure we use the correct one
when sending outputs from one of those.
> Fix sending outputs from a tx with more than one pubkey

- src/wallet/wallet2.cpp
It was 14 days after v4, it is now one day after it.
luigi1111's suggestion
> wallet: bring forward use of the dynamic fee

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
I think @Gingeropolous accidentally missed this bit - the message now makes sense again ;)
> Fix language of 'Your node is X blocks ahead|behind' message

- src/cryptonote_core/blockchain.cpp
After popping blocks from the old chain, the hard fork object's
notion of the current version was not in line with the new height,
causing the first blocks from the new chain to be rejected due
to a false expection of a newer version.
> blockchain: fix reorganizations past a hard fork boundary

- Doxyfile
- src/wallet/api/address_book.cpp
- src/wallet/api/address_book.h
- src/wallet/api/pending_transaction.cpp
- src/wallet/api/pending_transaction.h
- src/wallet/api/transaction_history.cpp
- src/wallet/api/transaction_history.h
- src/wallet/api/transaction_info.cpp
- src/wallet/api/transaction_info.h
- src/wallet/api/utils.cpp
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet_manager.cpp
- src/wallet/api/wallet_manager.h
- src/wallet/wallet2_api.h
- tests/libwallet_api_tests/main.cpp
- translations/monero.ts
Bitmonero namespace renamed Monero. Bitmonero alias added so that third party uses of the wallet can transition to Monero.
> Bitmonero namespace renamed Monero.

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/wallet2_api.h
Syncing daemon and refreshing wallet simultaneously is very resource intensive.
+ add asynchronous wallet close check
+ fixed fast refresh when creating wallet offline
+ pause/startRefresh() changed to public.
> Wallet API: Do not refresh while daemon is syncing

- src/wallet/api/address_book.cpp
- src/wallet/api/address_book.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet2_api.h
Fixes build warnings and may also prevent future headaches.
> AddressBook: use unsigned type for row ID's

- src/common/boost_serialization_helper.h
- src/common/util.cpp
- src/common/util.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
This does **not** make the program options for user selected username/password or disabled authentication hidden. That did not feel "right" - although it would prevent people from shooting themselves in the foot more quickly. Thoughts?
And I added code for some gross Win32 ACL code - a file containing the username/password for HTTP authentication is restricted to only readable by the owner of the process in Posix and Win32 (umask does this by default for Posix, but now we are really sure!). This should fail if the user is running `monero-wallet-rpc` in Windows from a FAT32 partition. Thoughts?
> Enabled HTTP auth support for monero-wallet-rpc

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/password_container.cpp
- src/wallet/password_container.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
[Enabling HTTP auth for `monero-wallet-rpc`](https://github.com/monero-project/monero/pull/1464/files) has one issue - [requesting confirmation for the password automatically displays a message for wallets](https://github.com/monero-project/monero/blob/master/src/wallet/password_container.cpp#L147). So that `password_container` could remain a class for storing passwords:
1. Except for watch-only wallets, all wallet password prompts now call `tools::wallet2::password_prompt` which toggles the same message for new wallets.
2. `tools::password_container` was refactored - instead of a two step construct object then call member function, a single static function was created. Therefore, there is no such thing as an `m_empty` `password_container`. This was done to eliminate confusion when …
> Refactored password prompting for wallets

- src/ringct/rctSigs.cpp
- src/wallet/wallet_rpc_server.h
- I removed the definition for `wallet_rpc_server::handle_command_line`, but forgot to remove the declaration ([see comment by @moneromooo-monero](https://github.com/monero-project/monero/pull/1387) ).
- I added some functors to replace `std::bind` by function address, then realized [C++11 lambdas did the same thing](https://github.com/moneromooo-monero/bitmonero/commit/f025198f195516da8654bece64bf7a1fb85be3cd#diff-786279ac0cfa372a81aa13b515b6c24f) with far more readability. They were [unintentionally re-added later](https://github.com/moneromooo-monero/bitmonero/commit/76958fc75abc18c928474eea91ac05fd5e0fcb41#diff-786279ac0cfa372a81aa13b515b6c24f) (probably due to a merge), and are currently unused.
> Removed unused functions

- src/wallet/wallet2.cpp
10s timeout should be enough when checking wallet connection status. 
fixes: https://github.com/monero-project/monero-core/issues/172
> Lower connection timeout in check_connection()

- src/simplewallet/simplewallet.cpp
The serialization format changed, and while there is code
to load the older serialization format, an older monerod
will not be able to load a file saved by a new monerod,
even though both share the same version. This is not good,
and we prefer a version bump.
> simplewallet: bump output file format version

- external/boost/archive/portable_binary_iarchive.hpp
- external/boost/archive/portable_binary_oarchive.hpp
@danrmiller Could you confirm the issue in PR #1462 is fixed by this?
> boost portable binary archive: account for API difference between 1.58 & 1.59

- src/common/dns_utils.cpp
- src/common/dns_utils.h
- src/daemon/command_parser_executor.cpp
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/api/wallet_manager.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- tests/unit_tests/address_from_url.cpp
Functions listed below are moved to cryptonote_basic_impl so that monerod can also use OpenAlias:
- `simple_wallet::get_address_from_str`
- `wallet2::addresses_from_url`
- `wallet2::address_from_txt_record`
Now you can easily do solo donation mining by `start_mining getmonero.org` :D
> make openalias also available for solo miner

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
@Jaqueeee I'm confused about the treatment of payment IDs in the address book. It makes sense to me to register and use integrated address in the address book since a 64bit payment ID gets encrypted in a transaction, but it doesn't make sense to me to include 256bit pID in the address book since you don't want to reuse an unencrypted pID which links the new transaction with past transactions.
> wallet cli: viewing and editing address book

- CMakeLists.txt
- contrib/otshell_utils/CMakeLists.txt
Issue: Without this patch, the following CMake warning is generated:
```
Warning:Configuration Debug
Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake --help-policy CMP0042" for policy details.  Use the cmake_policy command to set the policy and suppress this warning.
MACOSX_RPATH is not specified for the following targets:
blockchain_db  common  crypto  cryptonote_core  cryptonote_protocol  daemonizer  lmdb  mnemonics  p2p  ringct  roc  wallet
```
For more details on the CMake Policy CMP0042, see:
https://cmake.org/cmake/help/v3.0/policy/CMP0042.html
https://cmake.org/cmake/help/v3.0/prop_tgt/MACOSX_RPATH.html#prop_tgt:MACOSX_RPATH
> Silence CMake policy warning (CMP0042) on macos.

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/cryptonote_core/blockchain.cpp
- tests/unit_tests/hardfork.cpp
This is a normal occurence in many cases, and there is no need
to spam the log with those when it is.
> blockchain: allow marking "tx not found" without an exception

- cmake/FindLibunwind.cmake
Some versions of libunwind need liblzma. If liblzma is found,
we link against it unconditionally. If the installed libunwind
didn't need it, this is a nop.
> cmake: link against liblzma when found, for libunwind

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
Example:
> unspent_outputs 0.5 40
Amount: 0.500000000000, number of keys: 2
1200244 1205210 
Amount: 0.600000000000, number of keys: 4
1201126 1205210 1205210 1207392 
Amount: 0.700000000000, number of keys: 13
1189478 1195080 1196477 1201718 1202328 1203061 1204540 1205943 
1205943 1206101 1206599 1206599 1207393 
Amount: 0.800000000000, number of keys: 4
1201125 1201125 1201126 1203835 
Amount: 0.900000000000, number of keys: 2
1180268 1202328 
Amount: 1.000000000000, number of keys: 3
1195753 1201125 1202328 
Amount: 2.000000000000, number of keys: 6
1194368 1198020 1198856 1201718 1202200 1203835 
Amount: 3.000000000000, number of keys: 2
1195080 1204538 
Amount: 4.000000000000, number of keys: 5
1197245 1200879 1205210 1206101 1207392 
Amount: 5.000000000000, number of keys: 3 …
> wallet cli: print unspent outputs with histogram

- src/wallet/wallet2.cpp
If a reorg was large enough that a full 1000 block chunk
from the daemon was all known blocks, refresh would stop,
and no reorg would happen.
> wallet2: fix large reorgs failing

- src/simplewallet/simplewallet.cpp
The original code works fine even if the local_args becomes empty since the allocated memory doesn't get freed immediately, but certainly it's unnecessary and wrong and confusing.
> simplewallet: remove unnecessary local_args.erase(...) in set_variable()

- src/wallet/wallet2.cpp
Currently, calling the command `set xxx y` in a watch-only wallet makes it skip storing `watch_only` flag into the .keys file and thus makes it impossible to open it with the same password.
> wallet2 bugfix: store watch_only flag properly with rewrite()

- src/wallet/wallet2.cpp
wallet2::store() is called before wallet2:stop() in both gui and cli so there's no need to finish processing blocks and updating pool state before exit. This speeds up the shutdown process. Particularly when mempool is large.
> Wallet2: faster exit while refreshing

- CMakeLists.txt
- Makefile
- cmake/test-static-assert.cpp
- contrib/epee/include/console_handler.h
- external/db_drivers/liblmdb/CMakeLists.txt
- external/unbound/compat/getentropy_linux.c
- src/common/int-util.h
- src/crypto/CMakeLists.txt
- src/crypto/oaes_lib.c
- src/crypto/slow-hash.c
With clang and libc++, libwallet_merged and monero-wallet-cli builds and seems to works fine.
It still fails to build the daemon : something wrong about libblocks - format not recognized
I don't really understand what's being done at the first place :)
> Build wallet with Android NDK

- contrib/epee/include/net/http_auth.h
@Jaqueeee 
Replacement [for](https://github.com/monero-project/monero/pull/1512)
> Workarounds for gcc 4.8

- external/boost/archive/portable_binary_archive.hpp
- external/boost/archive/portable_binary_iarchive.hpp
- external/boost/archive/portable_binary_oarchive.hpp
See [comment](https://github.com/monero-project/monero/pull/1515#issuecomment-270786333) in PR #1515
I believe this fix doesn't have any real effect on monero with arm7 & armv8 builds, as there is no data to be serialized in Monero that is negative.
> portable serializer: use signed char for size

- src/simplewallet/simplewallet.cpp
Not 100$ sure this is the right fix, nor whether address book entries from URL should be stored as addresses or URLs (or both with a check for change on payment).
> Fix monero-wallet-cli compile

- src/cryptonote_core/blockchain.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Example:
[wallet 43TYdU]: sweep_all 44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A
No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): y
Transaction 1/1: txid=<c5f2895d281dc4849a2443cc6d27df804d433a496741539e13ebb569e50f43cc>
Input 1/4: amount=0.010000000000
Originating block heights:  81677 86003 784180 1207815 *1208310
|_____o_____________________________________________o__________________________*|
Input 2/4: amount=0.100000000000
Originating block heights:  95691 143843 146187 477755 *1208313
|______o__o_____________________o______________________________________________*|
Input 3/4: amount=0.000300000000
Originating block heights:  57255 73895 87661 1181392 *1208310 …
> wallet cli: print originating block heights of mixin keys when making transfer

- contrib/epee/include/net/http_auth.h
- contrib/epee/include/net/http_protocol_handler.h
- contrib/epee/include/net/http_server_impl_base.h
- contrib/epee/src/http_auth.cpp
- src/wallet/wallet_rpc_server.cpp
- tests/unit_tests/http_auth.cpp
This adds HTTP client "authorization" field generation to the same library that contains the HTTP server authentication. This does not add the "hooks" to the epee code to generate the authorization field. Client authentication will be necessary in the wallets if HTTP auth is added to the `monerod` RPC daemon.
Client authorization uses the exact same parsing framework that the server code uses. I apologize for the renaming spam - I did not plan _completely_ ahead of time.
This supercedes [PR 1514](https://github.com/monero-project/monero/pull/1514), which I will leave up because I expect this will have more discussion.
> Added (not yet enabled) HTTP client authentication

- src/blockchain_db/db_types.h
- src/common/command_line.cpp
- src/common/command_line.h
- src/cryptonote_core/cryptonote_core.cpp
Not needed anymore since the complete switch to LMDB.
Related to #1533.
> Show available types in db-type and remove db-auto-remove-logs

- src/wallet/CMakeLists.txt
- src/wallet/api/pending_transaction.cpp
- src/wallet/api/unsigned_transaction.cpp
- src/wallet/api/unsigned_transaction.h
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet2_api.h
also fixes https://github.com/monero-project/monero-core/issues/389
> GUI cold signing

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
on_get_info and on_get_info_json now includes the field start_time.
status command now report the daemon uptime.
Related to #1382.
> Add start_time to info commands and uptime to status command

- src/cryptonote_core/account.cpp
This fixes #1551, where a bad account creation timestamp was causing transactions to not load in the CLI.
The problem was that on some systems, uninitialized variables in the `tm` struct were causing `mktime()` to return `-1` in `account_base::create_from_keys()`. This is what was being passed to `mktime()`:
(tm) $0 = {
tm_sec = 0
tm_min = 0
tm_hour = 0
tm_mday = 15
tm_mon = 3
tm_year = 114
tm_wday = 1606389616
tm_yday = 32767
tm_isdst = 1
tm_gmtoff = 140734799777680
tm_zone = 0x00007fff5fbf9778 "\x12test.keys"
}
Initializing the struct to 0 before using fixes it. I also added a check to make sure errors from `mktime()` work predictably by setting `m_creation_timestamp` to 0 (epoch).
> initialize timestamp to 0 and check for mktime() error

- src/blockchain_db/berkeleydb/db_bdb.cpp
- src/blockchain_db/berkeleydb/db_bdb.h
- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/blockchain_utilities/fake_core.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
- tests/unit_tests/hardfork.cpp
This is to address issue #1463 
Faster throughput while avoiding corruption. I.e., makes
running with --db-sync-mode safe more tolerable.
Please test. Note that you may occasionally get "Attempt to get hash from height XXXX failed -- hash not in db" messages from other threads. As far as I can tell, this is harmless.
The original code used 1 DB txn per block, always. This code uses 1 DB txn per batch, so if e.g. 200 blocks are received in 1 batch during syncing, only 1 DB txn is used (and thus only 1 set of fsyncs instead of 200 fsyncs...)
> Use batch transactions when syncing

- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
The transactions are first prioritized by fee and in case the fees are equal by receive_time.
Related to #1557.
> Prioritize older transactions in the mempool

- src/cryptonote_core/blockchain.cpp
It can now be queried by RPC, so it needs to be set before
it is otherwise needed for consensus, even if no blocks had
to be added (ie, exit and restart quickly).
> core: ensure block size limit is set from the start

- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Fixes https://github.com/monero-project/monero/issues/1570
Reverted back to the previous default 200 sec timeout in wallet2 and added default 30 sec timeout in wallet API.
> fix timeout in check_connection

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
If we'd make a rct tx with just one input, we try to add
a second one to match the 2/2 ideal. This means more txes
use that template (and are thus using a larger anonymity
set), and it coalesces outputs "for free". We use dust
outputs in priority for this.
Further improvements could be made, like using the smallest
(or one of the smallest) amounts, but this would need some
thinking to see what is best there.
> wallet2: use at least two rct inputs if possible

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/hardfork.cpp
- src/cryptonote_core/hardfork.h
This is incompatible with block version voting
> core: check block version for alt chains too

- src/mnemonics/electrum-words.cpp
- tests/unit_tests/mnemonics.cpp
If a checksum word is present, language detection would use
just the word prefixes. However, a set of word prefixes may
be found in more than one language, and so the wrong language
may be found first, which could then fail the checksum, since
the check may be done with a different unique prefix length
from the one it was created from.
We now make a checksum test when we we detect a language from
prefixes only, to make sure we have the correct one.
> mnemonics: fix language detection with checksum word

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
This PR uses `MAKE_CORE_RPC_VERSION` introduced in PR #1578. It also defines RPC version 1.6 and should be merged after PR #1568 which defines RPC version 1.5.
Example:
./monero-wallet-cli --generate-from-view-key watchonly_wallet
Standard address: 47RH3d1JBXyhv3u3baLzGU6Z1G2F4UVMiDHZUYJEQqsVRViEpBV76t7eE11RsAFj8Z6v1wtchFWyHXEnyrG5fBSc6C2zPCH
View key: 163eda7fade793eb40ce9fd39e3b20d6c5165476861aded7c4ded1a252d9e205
Enter a password for your new wallet: 
Confirm Password: 
Generated new wallet: 47RH3d1JBXyhv3u3baLzGU6Z1G2F4UVMiDHZUYJEQqsVRViEpBV76t7eE11RsAFj8Z6v1wtchFWyHXEnyrG5fBSc6C2zPCH
Restore from specific blockchain height (optional, default 0),
or alternatively from specific date (YYYY-MM-DD): 2017-01-13
Restore height is: 1222233
Is this okay?  (Y/Yes/N/No): y
Starting refresh... …
> specify restore height by YYYY-MM-DD format

- contrib/epee/src/mlog.cpp
- external/easylogging++/easylogging++.h
This fixes a hang when logging something which causes some other
logging code to be called
> easylogging++: enforce recursive mutex

- src/p2p/net_peerlist.h
The method returned depth + 2 because:
- push_back was executed before the condition.
- \> instead of >= causing one more iteration.
> Honor depth in get_peerlist_head method

- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/net_peerlist.h
A random peer from the gray peer list is selected and a connection is made to check if the peer is alive.
If the connection and handshake are successful the peer is promoted to the white peer list, in case of failure the peer is evicted from the gray peer list.
The connection is closed after the check in either case.
Please, check for:
- Race conditions
- Possible side effects
- That the adequate log levels are being used
- Any other problems and suggestions
> Add gray peer list housekeeping system

- snapcraft.yaml
- Changed deprecated keywords
- Removed unnecessary wrappers
- Cleaned prime section
Resulting snap tested on ubuntu16, Archlinux 
Daemon autostarts ok, stores data at /var/snap/monero/x1/
wallet seems to work but no transactions made yet so be careful :warning: 
wallet files should be created outside snap folder, otherwise they will be deleted when removing the snap
> Streamline snap

- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/rpc/core_rpc_server.h
This prevents easy fingerprinting when you change IPs, and
will be a must when kovri gets used.
> p2p: always recreate a new peer id on startup

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/rpc/core_rpc_server.cpp
It was always set to false, even for orphan blocks
> rpc: fix orphan_status when getting blocks

- contrib/epee/src/mlog.cpp
It was not matching the LOG_PRINT_Lx mapping for 2/3/4
> hmlog: fix default level/category mapping

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
LMDB means we no longer need to type `exit` or `save` before quitting. Have updated the user messages to reflect this change. Have also made the green message orange to stand out from the rest of the log traffic and match the other.
> Update log messages - no need to type 'exit' to save DB

- src/p2p/net_peerlist.h
CATCH_ENTRY_L0 already returns the second value.
> Remove unreachable returns

- src/ringct/rctTypes.h
Easily fixed by moving a C++ header out of 'extern "C" {...}'.
When building with CC=clang CXX=clang++ make,
[ 21%] Building CXX object src/ringct/CMakeFiles/obj_ringct.dir/rctTypes.cpp.o
In file included from /home/tdprime/bitmonero/src/ringct/rctTypes.cpp:31:
In file included from /home/tdprime/bitmonero/src/ringct/rctTypes.h:43:
In file included from /home/tdprime/bitmonero/src/crypto/generic-ops.h:34:
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/cstring:100:3: error: conflicting types for 'memchr'
memchr(void* __s, int __c, size_t __n)
^
/usr/include/string.h:92:14: note: previous declaration is here
extern void *memchr (const void *__s, int __c, size_t __n)
^
... and 4 more similar errors
> Fix clang build failure, caused by mixing C and C++

- src/daemon/rpc_command_executor.cpp
This caused a random value to be used, and the resulting
incorrect fee when it wasn't 0.
> rpc: fix bc_dyn_stats not setting grace blocks

- src/common/dns_utils.cpp
- src/common/dns_utils.h
- src/cryptonote_core/cryptonote_basic_impl.cpp
- src/cryptonote_core/cryptonote_basic_impl.h
- src/simplewallet/simplewallet.cpp
Since cryptonote_core depends on common, dns_utils in common shouldn't use functions defined by cryptonote_core. This dependency issue was problematic only for debug build on mac. See PR #1626
> moved get_account_address_from_str_or_url from libcommon to libcryptonote_core

- src/cryptonote_core/tx_pool.cpp
This changes the priority of TXs when considering them for inclusion in a block template, prioritising TXs with the highest fee per KB. It also properly takes the transaction fees into account when considering whether to include them in the block, and prevents the overall block reward falling below the reward of an empty block.
> Fix fee priority for block fill

- src/rpc/core_rpc_server.cpp
- src/wallet/wallet2.cpp
These warnings were emitted by clang++, and they are real bugs.
src/rpc/core_rpc_server.cpp:208:58: warning: adding 'uint64_t'
(aka 'unsigned long') to a string does not append to the string
[-Wstring-plus-int]
res.status = "Error retrieving block at height " + height;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
The obvious intent is achieved by using std::to_string().
> Fix invalid + of std::string and int

- src/blockchain_db/lmdb/db_lmdb.cpp
- src/cryptonote_config.h
CRYPTONOTE_BLOCKCHAINDATA_FILENAME and CRYPTONOTE_BLOCKCHAINDATA_TEMP_FILENAME where not used anymore.
Update values of the defines and use them instead of hardcoded values.
> Update and use blockchain data files defines

- src/wallet/wallet2.cpp
If a rct transaction can be made with just one input, a second
output will be added. This output will be the smallest amount
output available. However, if this output is a non rct output
with less available fake outs than requested, the transaction
will be rejected. We now check the histogram to only consider
outputs with enough available fake outs in the first place.
> wallet2: fix corner case failing to send a second output

- external/db_drivers/liblmdb/mdb.c
Don't try to deref cursor page if txn's pagelist is empty
Note, this is only a 2-line change, the rest is indentation.
> Workaround VL32 cursor refcounting miscount

- src/cryptonote_core/cryptonote_core.cpp
- src/p2p/net_node.inl
poolstate.bin and p2pstate.bin are stored in .bitmonero/ if the default P2P port is being used.
If another port is used both files are stored in .bitmonero/PORTNUMBER/.
> Separate data per P2P port

- src/daemon/protocol.h
> Add missing include

- src/cryptonote_core/cryptonote_format_utils.cpp
Zero change is sent to a random address, which confuses the code
which determines which key to use to encrypt the payment id.
Ignore zero amounts for this purpose, so the payment id gets
encrypted with the real destination's key.
> core: fix integrated addresses breaking with auto zero change

- src/cryptonote_core/cryptonote_basic_impl.cpp
Credit goes to @tdprime
https://github.com/monero-project/monero/commit/55a8e982c0b34cd62d1ad1eb83d0683d5291f322#commitcomment-20736734
>  bugfix: infinite recursion in get_account_address_from_str_or_url

- src/wallet/api/utils.cpp
Not sure where this throws, but it does, with error: `resolve: Host not found (authoritative)`
Related to changes made in #1629? 
Causing GUI to crash when switching to a daemon address that doesn't resolve.
> Wallet API: Catch error from tools::is_local_address

- external/db_drivers/liblmdb/mdb.c
since it's variable size on Linux/glibc
> ITS#8582 keep mutex at end of struct

- external/easylogging++/easylogging++.h
`-fsanitize=thread` did the hard work of catching the race. @hyc @moneromooo-monero This is likely some of the strange issues being reported in various places on the trunk build. The trunk branch of easylogging adds the lock to `setThreadName`, but not `getThreadName`. Guess its time to send some patches that way.
> Fix race in setThreadName/getThreadName

- tests/CMakeLists.txt
In simple terms, add_subdirectory() is replaced with ExternalProject_Add().
This change is inspired by https://crascit.com/2015/07/25/cmake-gtest/
with one difference, no download, using the source we already have.
Before this change, make debug-test must be preceded by make clean.
Otherwise, a subsequent build would be polluted by cmake options made
by tests/gtest/.
Also removed the changed compiler flags.  My test build did not have
the affected warnings.
> fixes #1688 protect make debug-test from gtest 

- src/blockchain_db/blockchain_db.cpp
- src/blockchain_db/lmdb/db_lmdb.cpp
The recent change to not keep separate track of the blockchain
height caused the reported height to jump early in the lmdb
transaction (when the block data is added to the blocks table),
rather than at the end, after everything succeeded. Since the
block data is added before the transaction data, this caused
the transaction data to be saved with a height one more than
its expected value.
Fix this by saving the block data last. This should have no
side effects.
> db_lmdb: fix bad height saved in tx data

- src/wallet/CMakeLists.txt
This fixes undefined references when linking the GUI after PR #1626 was merged. Tested on Ubuntu 14.04 and MSYS2 on Windows 10.
> Fix building the GUI after libcryptonote_core was split

- src/daemon/daemon.cpp
When exiting while the miner is running, finding a block after
the p2p layer has been shutdown will cause a crash as the now
uninitialized p2p layer is asked to relay the found block to
any peers.
> daemon: fix crash on exit when mining

- src/p2p/net_node.h
This is only used to load, not save
> net_node: fix spurious warning about using uninitialized data

- src/wallet/wallet2.cpp
A relatedness check was meant to be done in the case of adding
an extra output if just one was enough. This was mistakenly
added to the "preferred output" case.
> wallet2: fix failure to send (relatedness check in wrong case)

- src/cryptonote_basic/miner.cpp
Background mining ( pr #1582 ) compile error
https://build.getmonero.org/builders/monero-static-debian-armv8/builds/640/steps/compile/logs/stdio
> fix undefined reference error when compiling with clang

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/cryptonote_core/blockchain.cpp
When scanning for outputs used in a set of incoming blocks,
we expect that some of the inputs in their transactions will
not be found in the blockchain, as they could be in previous
blocks in that set. Those outputs will be scanned there at
a later point. In this case, we add a flag to control wehther
an output not being found is expected or not.
> blockchain_db: do not throw on expected partial results getting keys

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
Only update target height if it's actually greater than the current target.
Only display "synchronized" when current height equals target.
> Fix spurious synchronization status msgs

- src/crypto/slow-hash.c
Fixed by moving declarations as advised by @hyc in #1720
> Fix compiler error about nested externs in slow_hash.c

- src/cryptonote_core/cryptonote_core.cpp
- src/p2p/net_node.inl
They're now used by core to determine the data directory to use
for the txpool directory.
This fixes an assert in the core tests, which don't use the RPC
server, which normally initializes the P2P code.
> core: add p2p bind port options from net_node

- src/common/dns_utils.cpp
load_txt_records_from_dns attempts to distribute `a = 0, b = -1` where
(b = dns_urls.size() - 1) and IntType is signed integer. This results in
an infinite recursion which leads to SIGSEGV.
> dns_utils: fix infinite recursion when distributing empty dns_urls

- src/cryptonote_core/cryptonote_core.cpp
- src/daemon/core.h
You're wondering how this fixes core tests, aren't you...
It prevents the miner (initialized by cryptonote::core) from
breaking trying to access arguments that were not added.
Since the tests don't use the miner directly, it makes more
sense to have cryptonote_core add those, since it also uses
the miner.
> Fix core_tests breaking on startup

- README.md
Note: the FreeBSD box is not technically 11 yet but @danrmiller said he would make that happen soon. Bumping now so we don't forget update the README later.
> README: add DragonFly BSD to build status + update FreeBSD version

- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
Output example:
```
White list size: 914/1000 (91.4%)
Gray list size: 1823/5000 (36.46%)
```
Have been using this for testing purposes.
> Add print_pl_stats daemon command

- src/wallet/wallet2.cpp
fixes https://github.com/monero-project/monero-core/issues/386 and #1527
> wallet2: fix wrong version status on daemon shutdown/startup

- contrib/epee/src/mlog.cpp
Reduces the following unnecessary information about log levels after every command-line action:
```
nodey@odroidc2:~$ monerod status
2017-02-25 13:53:31.307	      7fa109a000	INFO 	global	contrib/epee/src/mlog.cpp:145	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,global:INFO,verify:FATAL,stacktrace:INFO
2017-02-25 13:53:31.308	      7fa109a000	INFO 	global	contrib/epee/src/mlog.cpp:153	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,global:INFO,verify:FATAL,stacktrace:INFO
Height: 1253096/1253866 (99.9%) on mainnet, not mining, net hash 63.30 MH/s, v4, up to date, 29(out)+12(in) connections, uptime 0d 0h 26m 59s
```
> Increase the log level for the info about log levels

- contrib/epee/src/mlog.cpp
Errors in this layer depend on how peers behave, and thus errors
are expected
> mlog: default net.cn to FATAL

- src/daemon/protocol.h
Would have been nice to have clear console output on daemon shutdown and not need to check the logs or `top`, but this method didn't work.
> Revert attempt to write to console on daemon shutdown

- src/p2p/net_node.inl
- src/p2p/net_peerlist.h
```get_random_gray_peer``` should use an uniform distribution. Explained in #1684
> Make get_random_gray_peer distribution uniform

- src/wallet/wallet2.cpp
They were inserted using payment id as key, not txid
> wallet: fix insertion of pool transactions

- src/wallet/wallet2.cpp
This reverts commit d47dac9a88ddd46b88850a899311363b3261c89e.
Callers actually expect the key to be payment id, so this
needs a lot more changes (like storing payment ids in the
structure, and possibly also to other existing structures
which do the same thing).
> Revert "wallet: fix insertion of pool transactions"

- README.md
indicated 0.10.2.2 is the recommended version for running right now and for the upcoming fork
> updated reccommended Monero version in Readme

- CMakeLists.txt
Solution: updated the comments to reflect the current situation in terms of LMDB implementation and no longer recommend 'memory' for blockchain storage in production use.
> Problem: misleading information about LMDB storage

- Dockerfile
Dependency installation, clone and build are all currently part of a single RUN command. If any of these steps fail, they all have to be run again.
Worst case, `make` fails and you have to fetch all the dependencies again and clone the repo. This can be especially painful on a limited network connection.
By separating the steps as per this PR, they can each be cached and massively reduce build times upon failure.
> Dockerfile command separation

- src/wallet/wallet_args.cpp
This PR adds a config file option to the wallets.
This is immensely useful, especially for server deployments. You can simply set all your configuration in the file (such as rpc port and credentials) and then start up your wallet.
This also increases security in terms of hiding configuration values from the rest of the system (which would show up in process listings and histories if given as command line parameters).
> Adds a config file option to the wallets

- src/crypto/slow-hash.c
CryptoNight does exactly 524,288 iterations over the scratchpad as defined in CNS008, saying 500,000 could be confusing. I know its meant to give a rough idea (around 500k) to the reader but if you are reading the code, might as well know the exact number.
> Specify "524,288" iterations instead of "500,000"

- src/cryptonote_basic/cryptonote_basic_impl.cpp
- src/cryptonote_basic/cryptonote_basic_impl.h
- src/cryptonote_config.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/tx_pool.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- tests/unit_tests/fee.cpp
Minimum mixin 4 and enforced ringct is moved from v5 to v6.
v5 is now used for an increased minimum block size (from 60000
to 300000) to cater for larger typical/minimum transaction size.
The fee algorithm is also changed to decrease the base per kB
fee, and add a cheap tier for those transactions which we do
not care if they get delayed (or even included in a block).
> Add intervening v5 fork for increased min block size

- src/common/dns_utils.cpp
- src/common/dns_utils.h
- src/cryptonote_basic/cryptonote_basic_impl.cpp
- src/cryptonote_basic/cryptonote_basic_impl.h
- src/wallet/wallet_rpc_server.cpp
In this patch, the wallet RPC has no ability to confirm the resolved OpenAlias address because it doesn't have access to standard I/O. I'm not sure how/if such a mechanism can/should be implemented.
> wallet-rpc: enable OpenAlias

- src/p2p/net_node.h
- src/p2p/net_node.inl
In case the DNS seed(s) is/are down, which would otherwise
cause the fallback seeds to never be used
> p2p: always use the fallback seed IPs

- src/simplewallet/simplewallet.cpp
This would otherwise be a silent noop, which is confusing.
This can happen if the daemon is started, but not yet ready
to service all requests, and this is a safe catch all.
> simplewallet: catch case where no transactions are made

- src/daemon/rpc_command_executor.cpp
> daemon: fix missing close parenthesis in alt_chain_info output

- contrib/epee/src/mlog.cpp
We want to know which log categories are active.
This reverts commit 4f7bce6d20c72a1384289f7c35b7fe0ee796ed41.
> Revert "Increase the log level for the info about log levels"

- src/blockchain_db/lmdb/db_lmdb.cpp
Don't allow use of existing batch txn if it's from the wrong thread
> Partial fix #1876, check thread in block_txn_start()

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Asking for a full histogram from a remote node (since it's
untrusted) is pretty slow, and spams the remote node, so
we replace it by only adding a second input if we have rct
ones, which are for all intents and purposes always mixable.
> wallet2: speed up transactions using remote nodes

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
This massively speeds up the wallet updating the pool on mainnet,
where the tx backlog is more than 500 txes.
> wallet2: cache which pool txes were scanned already

- CMakeLists.txt
at least ubuntu 16.10 seams to fail with USE_LTO=true... so maybe switch it off by default like discussed in  IRC monero-dev
> set USE_LTO_DEFAULT to false

- src/cryptonote_core/tx_pool.cpp
The result is not actually used when uninitialized
> tx_pool: silence use of uninitialized warning

- src/cryptonote_core/blockchain.cpp
to silence the update warning, since v5 was done very early
on testnet
> blockchain: offset v5 addition date on testnet

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
When a single input is enough to satisfy a transfer, the code would
previously try to add a second input, to match the "canonical" makeup
of a transaction with two inputs and two outputs. This would cause
wallets to slowly merge outputs till all the monero ends up in a
single output, which causes trouble when making two transactions
one after the other, since change is locked for 10 blocks, and an
increasing portion of the remaining balance would end up locked on
each transaction.
There are two new settings (min-output-count and min-output-value)
which can control when to stop adding such unneeded second outputs.
The idea is that small "dust" outputs will still get added, but
larger ones will not.
Enable with, eg:
set min-output-count 10
set min-output-value 30
to avoid using an unneeded …
> wallet: try to save large outputs when using an unneeded second input

- src/cryptonote_core/blockchain.cpp
- src/simplewallet/simplewallet.cpp
Fixed a typo in the v5 hard fork finalize date, changed year from 2016 to 2017.
Also fixed a typo in a simplewallet help message (found by /u/moneronoob12345 on Reddit).
> Fix two typos

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
With the change from the original transfer method to the new
algorithm, payments to the same destination were merged. It
seemed like a good idea, optimizing space. However, it is a
useful tool for people who want to split large outputs into
several smaller ones (ie, service providers making frequent
payments, and who do not like a large chunk of their balance
being locked for 10 blocks after each payment).
Default to off, which is a change from the previous behavior.
> wallet: option to merge destinations

- src/cryptonote_basic/cryptonote_format_utils.cpp
Looks like it doesn't work on win64
> core: disable tx/block hash cache

- src/simplewallet/simplewallet.cpp
There's already a password confirmation in `transfer_new`. No need to make it more difficult to donate :P
> wallet cli: remove redundant password confirm in donate command

- README.md
... to v0.10.3.1 ... and minimum Monero version to v0.10.3.0 because the hardfork code is only in v0.10.3.x , not v0.10.2.1
> changed version of recommended monero version

- src/simplewallet/simplewallet.cpp
- translations/monero.ts
Allows fee argument default/unimportant/normal/elevated/priority to be used per transaction in CLI wallet's transfer command. Resolves #1913.
> Add per transaction fee to transfer command

- tests/unit_tests/blockchain_db.cpp
Eliminates the following warning when compiling the unit_tests:
`... blockchain_db.cpp:245:21: warning: 'tmpnam' is deprecated: This function is provided for compatibility reasons only. Due to security concerns inherent in the design of tmpnam(3), it is highly recommended that you use mkstemp(3) instead. [-Wdeprecated-declarations] std::string fname(tmpnam(NULL));`
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/stdio.h:277:7: note: 'tmpnam' has been explicitly marked deprecated here char *tmpnam(char *);`
> Replace deprecated tmpnam function.

- contrib/epee/src/mlog.cpp
Because some people just won't even try to read what is written
and freak out because the word FATAL is in here, despite the
context making it clear it's not an error.
> mlog: direct log category changes to file only

- src/cryptonote_basic/miner.cpp
- src/cryptonote_basic/miner.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
Only works from V5 fork onward - returns 0 before that block.
It may make sense to do it only on testnet for now but I can't find a non-invasive solution.
> Add expected total reward to RPC "getblocktemplate".

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
- src/wallet/wallet_rpc_server_error_codes.h
First draft, for review and comment only.
Open questions - should the CREATE command return the wallet seed to the client?
Should error messages from failed CREATE be returned to the client?
Should there be a command to list the wallets in the wallet_dir?
> Resolve #92 add ability to create wallets thru RPC

- src/simplewallet/simplewallet.cpp
Returning `false` in these command handlers will result in showing a message `unknown command: ` in [epee/include/console_handler.h](https://github.com/monero-project/monero/blob/9ed496bbc56be915d9a33dc0087cb22b554ade61/contrib/epee/include/console_handler.h#L322) which I think is incorrect behavior.
> wallet cli: corrected some inappropriate return-false

- src/wallet/wallet2.cpp
The daemon address was initialized too late
> wallet2: fix --generate-from-json in RPC mode

- src/wallet/wallet2.cpp
unconfirmed_payments changed from having the txid as key to
the payment id, and this was not changed to match.
> wallet2: fix removal of wrong txes from unconfirmed_payments

- src/wallet/wallet2.cpp
Two recent papers quantified the real usage bias for the
real output in a ring being the true one, and shows that
the current biasing is much too weak.
While we wait for a better solution, we increase the ratio
of recent-to-total fake outputs, as well as decrease the
time window for recent outputs, so that half the fake outs
are selected within the last day.
This is also arbitrary, of course, but serves as a stopgap
till a better selection algorithm is chosen.
> wallet2: bias fake outs more towards recent outputs

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
It sweeps all outputs below the given threshold
This is available via the existing sweep_all RPC, by setting
amount_threshold the desired amount (in atomic units)
> wallet: add sweep_below function

- README.md
- VULNERABILITY_RESPONSE_PROCESS.md
As discussed in Kovri meetings and IRC, here is a formalized VRP. This will aid us in working with researchers and HackerOne.
The point of contacts are tentative until there is a consensus on if we should use `dev@getmonero.org` as single POC.
RFC! This can be considered a WIP.
> Docs: add Vulnerability Response Process

- external/easylogging++/easylogging++.cc
This avoids error spews from easylogging++ when we try to log
something before easylogging is initialized, which can happen
when errors happen at command line parsing time
> easylogging++: default to creating categories by default

- src/mnemonics/CMakeLists.txt
- src/mnemonics/chinese_simplified.h
- src/mnemonics/dutch.h
- src/mnemonics/electrum-words.cpp
- src/mnemonics/electrum-words.h
- src/mnemonics/english_old.h
- src/mnemonics/french.h
- src/mnemonics/german.h
- src/mnemonics/italian.h
- src/mnemonics/japanese.h
- src/mnemonics/portuguese.h
- src/mnemonics/russian.h
- src/mnemonics/spanish.h
- tests/unit_tests/mnemonics.cpp
Also changed 'Old English' to 'English Old', because 'Old English' is actually a language in its own right, and someone may want to make a dictionary for it at some point in the future. I don't know who, but let's leave the chance open ;)
> Change all wallet language names into native names (and scripts)

- src/wallet/node_rpc_proxy.cpp
- src/wallet/wallet2.cpp
The bump to minimum mixin 4 was moved from v5 to v6
> wallet2: fix sweep_unmixable assuming wrong minimum mixin at v5

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
First stage of a change to ensure excessively large transactions can't be created to clog the mempool.
Stage 1: Remove ability to create transactions > 1.25x block size from wallet
Stage 2: Remove acceptance of transactions > 1.25x block size by transaction pool
Stage 3: Single more sophisticated transaction size checker based on historic median block size, fee priority, and @jollymort's calculations for bumping the median block size by fee
> Remove 1.25x size multiplier from wallet

- src/cryptonote_core/cryptonote_core.cpp
As Monero's blockchain has grown, most users take more than "several hours" for a fresh sync. This PR makes the daemon sync time message more accurate.
> Update sync time copy

- external/unbound/validator/val_secalgo.c
Replace EVP_VerifyInit with EVP_DigestInit, and EVP_VerifyUpdate
with EVP_DigestUpdate. Reported/requested by hyc, changed by mooo.
> unbound: update some EVP APIs to new names

- src/blockchain_db/CMakeLists.txt
- src/common/CMakeLists.txt
- src/crypto/CMakeLists.txt
- src/cryptonote_basic/CMakeLists.txt
- src/cryptonote_core/CMakeLists.txt
- src/daemon/CMakeLists.txt
- src/ringct/CMakeLists.txt
- src/simplewallet/CMakeLists.txt
- src/wallet/CMakeLists.txt
- tests/crypto/CMakeLists.txt
- tests/daemon_tests/CMakeLists.txt
- tests/functional_tests/CMakeLists.txt
- tests/hash/CMakeLists.txt
- tests/performance_tests/CMakeLists.txt
The openssl crypto lib that is the same name as the monero crypto lib can't be packed with an android app since they pack all of the native libraries into the same folder  only distinguished by the architecture so I changed it to cncrypto.
> crypto to cncrypto 

- src/simplewallet/simplewallet.cpp
With the recent change to wallet creation code, the code was
calling to the daemon before the wallet's daemon address was
initialized, and thus failing. This was causing all new wallets
to refresh from 0 instead of just fetching early block hashes.
> simplewallet: fix refresh height for new wallets

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
Since we're just counting txs, there's no reason to deserialize all the blobs.
Add a new get_transaction_pool_stats RPC that just returns the statistics.
Original code:
```
time ./monerod print_pool_stats
511 tx(es), 128702430 bytes total (min 13254, max 258312, avg 251863)
fees 148.600494060000 (avg 0.290803315185 per tx, 0.000001154605 per byte )
0 not relayed, 0 failing, 462 older than 10 minutes (oldest 3 hours ago)
real    0m12.368s
user    0m1.720s
sys     0m0.733s
```
New code:
```
time ./m2 print_pool_stats
513 tx(es), 128728942 bytes total (min 13254, max 258312, avg 250933)
fees 148.631392460000 (avg 0.289729809863 per tx, 0.000001154607 per byte )
0 not relayed, 0 failing, 462 older than 10 minutes (oldest 3 hours ago)
real    0m0.006s
user    0m0.003s
sys     0m0.000s
```
> Speedup print_pool_stats

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- tests/unit_tests/hardfork.cpp
Changed Blockchain::for_all_blocks() to for_blocks_range()
Operate on blockchain in-place instead of building a copy first.
Trying to use print_coinbase_tx_sum on the entire blockchain would kill my daemon on VPS with out of memory because it would try to build an in-memory copy of the entire blockchain before processing. Now the command still takes a long time to run but it actually finishes instead of killing the server.
> Don't copy blockchain for coinbase_tx_sum

- contrib/epee/include/net/abstract_tcp_server.h
- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/net/abstract_tcp_server_cp.inl
- contrib/epee/include/net/http_server_handlers_map2.h
- contrib/epee/include/net/levin_client_async.h
- contrib/epee/include/net/net_utils_base.h
- contrib/epee/include/string_tools.h
- src/cryptonote_protocol/cryptonote_protocol_defs.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/net_node_common.h
- src/p2p/net_peerlist.h
- src/p2p/net_peerlist_boost_serialization.h
- src/p2p/p2p_protocol_defs.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
All code which was using ip and port now uses a new IPv4 object,
subclass of a new network_address class. This will allow easy
addition of I2P addresses later (and also IPv6, etc).
Both old style and new style peer lists are now sent in the P2P
protocol, which is inefficient but allows peers using both
codebases to talk to each other. This will be removed in the
future. No other subclasses than IPv4 exist yet.
> abstracted nework addresses

- contrib/epee/src/CMakeLists.txt
- src/cryptonote_core/tx_pool.cpp
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server_commands_defs.h
If there's more than 1 tx in the pool, print a histogram of the age distribution of the txes, using up to 10 bins.
The pool's not very interesting at the moment:
```
print_pool_stats
40 tx(es), 10017447 bytes total (min 13255, max 257878, avg 250436)
fees 11.636061160000 (avg 0.290901529000 per tx, 0.000001161579 per byte )
0 not relayed, 0 failing, 39 older than 10 minutes (oldest 23 hours ago)
Age      Txes       Bytes
00:00:00       1       13255
02:20:16       0           0
04:40:32       0           0
07:00:48       0           0
09:21:04       0           0
11:41:20       0           0
14:01:36       0           0
16:21:52       0           0
18:42:08      32     8209052
21:02:24       7     1795140
```
> Add histogram to poolstats

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
Prevents crash if using libwallet and you don't call init() on the wallet before you do certain things such as refresh.
Sample crash trace file:
https://paste.fedoraproject.org/paste/0LYsQNJA6UEPycFY7ccJSl5M1UNdIGYhyRLivL9gydE=
> Prevent crash if performing certain actions before wallet is initialized

- src/simplewallet/simplewallet.cpp
Add fail-fast paths that reduce frustration around the misuse of
--wallet-file combined with --restore-deterministic-wallet.  Flow now
gives more descriptive errors and avoids having users type in their
whole seed before the failure condition is noticed.
Fixes #2060
> add simplewallet --generate-new-wallet arg checks

- src/wallet/api/wallet.cpp
It was unused, so harmless
Reported by erikd on IRC
> wallet_api: fix missing transaction parameter in callback

- contrib/epee/include/net/net_utils_base.h
I observed this compile error with my macOS Sierra after the merging of PR #2052 :
```
monero/contrib/epee/include/net/net_utils_base.h:131:19: error: use 'template' keyword
to treat 'as' as a dependent template name
KV_SERIALIZE(as<ipv4_network_address>());
^
template 
```
Adding the `template` keyword solves the problem.
https://stackoverflow.com/a/3786481
> net_utils_base: added missing template keyword

- contrib/epee/src/readline_buffer.cpp
It'd eat up a core constantly, due to spending its time jumping
back and forth between userland and kernel. We now wait for up
to a millisecond in kernel, which will be transparent to the user
and drop to idle most of the time.
> readline_buffer: fix busy wait

- contrib/epee/include/net/net_utils_base.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/p2p/net_node.inl
- src/p2p/net_peerlist_boost_serialization.h
- src/p2p/p2p_protocol_defs.h
- src/rpc/core_rpc_server.cpp
Since I had to add an ID to the derived classes anyway,
this can be used instead. This removes an apparently
pointless warning from CLANG too.
> Remove typeid use in the network_address

- contrib/epee/include/console_handler.h
- contrib/epee/src/readline_buffer.cpp
Color prompt now working and no reprompting on exit command.
Also incorporated #2094 for OSX compile fix.
> Add readline improvements

- src/mnemonics/electrum-words.cpp
- src/mnemonics/electrum-words.h
It'd see "empty" words due to extraneous spaces
> electrum-words: fix seed mistakenly thought to be old style

- contrib/epee/src/readline_buffer.cpp
- src/simplewallet/simplewallet.cpp
monero-wallet-cli commands which have multine output sometimes causes
issues with the readline support. This patch fixes show_transfers,
payments and incoming_transfers.
> Fix multiline wallet cli output with readline

- src/wallet/wallet_rpc_server.cpp
"on_transfer" incorrectly logs as "on_transfer_split".
> Fix on_transfer RPC incorrect logging info

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
Also very minor cleaning in log msgs and tab vs. space.
> Fix #2120: return per-tx amount in transfer_split RPC call.

- src/simplewallet/simplewallet.cpp
This ensures the chain and related structures can't change
while we're using them
> simplewallet: lock idle scope when sweeping

- contrib/epee/src/mlog.cpp
This ensures command output gets logged by default
> mlog: add msgwriter:INFO to log 0 and 1 defaults

- src/daemon/rpc_command_executor.cpp
When there are more than 50txs, the timestamp for the last
bin was printed incorrectly. Subtracting "now" was omitted by mistake
in 3fc22e7b78ab1dd409de4f3e8f5bff27be19735b
> Fix #2164 histogram output

- src/daemonizer/posix_fork.cpp
There's no /tmp on Android so running monerod --detach always fails. Allow overriding the path using TMPDIR environment variable.
> Don't hardcode /tmp

- src/cryptonote_basic/miner.cpp
They were set as uint8_t, which boost was apparently treating
as a character type, rather than a numeric type
> miner: fix background mining options parsing

- src/common/dns_utils.cpp
Plugs a noisy but benign memory leak
> Ensure DNSResolver destructor runs on exit

- Makefile
Most of the time, I find this is actually the target I want to build.
> Makefile: Add debug-static-all target

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
The PR is a result of this issue: https://github.com/monero-project/monero/issues/2080
Basically, it adds `get_alt_blocks_hashes` RPC call to get hashes of alternative blocks from the daemon. Currently, only number of alt blocks, through `get_info` RPC could be obtained. Getting actual information about these blocks was not available. 
The rpc call is already running on my development vps for testing. Basic support for viewing the details of the alternative blocks has already been added, thought this new call, to the onion explorer and can be seen here as an example: http://139.162.32.245:8081/altblocks
Any feedback appreciated of possible changes and improvements.
> Add on_get_alt_blocks_hashes RPC call

- src/daemonizer/posix_daemonizer.inl
- src/daemonizer/posix_fork.cpp
- src/daemonizer/posix_fork.h
- utils/systemd/monerod.service
The PID file will only be written if the daemon is called with the
`--detach` command line argument and a `--pidfile /some/file/path`
argument.
> daemon: Add ability to write a PID file

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
This avoids someone adding what amounts to mixin 0 rings in
practice, as there is no other good reason to allow this.
> core: forbid duplicate ring members from v6

- src/simplewallet/simplewallet.cpp
"Payment successfully sent" can be misleading if the TX isn't confirmed and drops from TX-pool.
Brought to attention by urza:
https://github.com/monero-project/monero/issues/2183
> Make successful transfer log message more informative

- src/simplewallet/simplewallet.cpp
Encrypted ones aren't shown, as they can't be decrypted with
the information we have, so those just show there is one
> simplewallet: show payment ids on sign_transfer

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
This fixes a small bug that is visible in the daemon when using the *print_cn* ("print connections") command where for all connections the send idle time was simply displayed as current time.
> cryptonote_protocol: Set send_idle_time in connection_info correctly

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
When scanning the txpool without having first updated the
blockchain, the tx would be seen as neither in the txpool
nor the chain, and removed, so it'd only reappear once the
chain is refreshed, and the tx seen in a block.
> wallet2: fix temporarily missing incoming tx when being mined

- src/cryptonote_core/cryptonote_tx_utils.cpp
They used to be sorted by amount, which was fine before rct,
but is now suboptimal, since amounts are not known anymore.
In particular, it would give a recipient knowledge of whether
change was higher or lower than the amount received.
> core: randomly shuffle outputs

- src/common/dns_utils.cpp
- src/common/dns_utils.h
- src/cryptonote_basic/cryptonote_basic_impl.cpp
- src/cryptonote_basic/cryptonote_basic_impl.h
- src/daemon/command_parser_executor.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet_rpc_server.cpp
Library code should definitely not ask for console input unless
it's clearly an input function. Delegating the user interaction
part to the caller means it can now be used by a GUI, or have a
decision algorithm better adapted to a particular caller.
> Move OpenAlias console input back from libs

- src/p2p/network_throttle.cpp
- src/p2p/network_throttle.hpp
This will keep leak traces less noisy, as those were one off
allocations that were technically leaking.
> network_throttle: remove unneeded heap allocations

- src/common/util.h
- src/p2p/net_node.inl
- src/p2p/p2p_protocol_defs.h
This avoids having to include p2p_protocol_defs.h in util.h,
as util.h is used a lot, and p2p_protocol_defs.h includes
a lot of other things that most users don't need.
> move get_proof_of_trust_hash from util.h to p2p_protocol_defs.h

- src/cryptonote_core/cryptonote_core.cpp
This uses DNS, which can take a while, so it's useful to know
this is the culprit when loading pauses
> core: add a message when loading checkpoints at init time

- src/wallet/api/wallet.cpp
Implemented callbacks did not match those defined in wallet2.h and so were never called.
> fix wallet callback signatures

- README.md
- utils/build_scripts/android32.Dockerfile
- utils/build_scripts/android64.Dockerfile
Copying [hyc's build instructions](https://forum.getmonero.org/5/support/87643/building-monero-v0-10-3-1-for-android) in a dockerfile, except for openssl b/c i failed at building boringssl :(
I have not tested the 64 bits build ! (don't have 64 bits android)
> Utils: Add dockerfile for android NDK build

- contrib/epee/include/net/levin_protocol_handler_async.h
- src/cryptonote_basic/connection_context.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_protocol/block_queue.cpp
- src/cryptonote_protocol/block_queue.h
- src/cryptonote_protocol/cryptonote_protocol_defs.h
- src/cryptonote_protocol/cryptonote_protocol_handler-base.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/net_node_common.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
- tests/core_proxy/core_proxy.cpp
- tests/core_proxy/core_proxy.h
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/ban.cpp
- tests/unit_tests/block_queue.cpp
A block queue is now placed between block download and
block processing. Blocks are now requested only from one
peer (unless starved).
Includes a new sync_info coommand.
Testers wanted!
I'm interested in people with extreme setups: very fast/slow CPU and fast/sluggish internet combinations.
Note that this commit has fork potential (though in all likelihood it'd only cause nodes to fail to sync).
I'm interested in reports about the speed difference between with and without the patch, and any reports of the sync wedging partway through.
> cryptonote_protocol_handler: sync speedup

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
Asks user for all the data required to merge secret keys from multisig wallets into one master wallet, which then gets full control of the multisig wallet. The resulting wallet will be the same as any other regular wallet.
Use: `monero-wallet-cli --generate-from-multisig-keys <new-wallet-file>`
Example:
$ ./build/debug/bin/monero-wallet-cli --generate-from-multisig-keys test2
Monero 'Wolfram Warptangent' (v0.10.3.1-4ff81728)
Logging to ./build/debug/bin/monero-wallet-cli.log
Multisig type (input as M/N with M <= N and M > 1): 2/2
Generating master wallet from 2 of 2 multisig wallet pieces
Multisig wallet address: 47RGRFeLPT51qvDWuw7SGf57JK7AziAVqYucct8z5yEDQ1XqU8zKEjidWjqPXk7PuHP3MJDN2AJATKy9PH7zaGV7MB8X6CH
Secret view key: ****
Secret spend key (1 of 2): ****
Secret spend key (2 of 2): …
> Add option to join multisig wallet pieces together

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
If the txes are bad, this'll be picked up by the block hash mismatch
since the tx merkle root is part of the block hash.
> blockchain: skip checking tx semantics in embedded block hash range

- src/p2p/net_node.h
- src/p2p/net_node.inl
This fixes nodes not being able to connect to nodes which use
recent code. While there, init peer_id too.
> net_node: fix m_in_timedsync initialization

- src/cryptonote_basic/connection_context.h
Why this was initialized properly before I have no idea, but
it is not anymore. Fix it, which fixes syncing in release mode.
> connection_context: initialize state

- src/wallet/api/wallet_manager.cpp
- src/wallet/api/wallet_manager.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet2_api.h
Current implementation requires wallet to be opened to validate a password. This patch allows verifying directly on the keys file by reusing wallet2 code. Also adds appropriate method to the WalletManager API.
> Enable verifying wallet password without having to load wallet.

- src/simplewallet/simplewallet.cpp
Previously, the wallet just asked for "Spend key" and "View key" but
now it specifies that these should be the secret versions of these
keys.
> simplewallet: Be explicit about secret keys

- src/simplewallet/simplewallet.cpp
It's annoying and pointless (especially as it's the only thing
where the user is asked twice)
> simplewallet: do not ask wallet filename twice when restoring

- src/cryptonote_config.h
With the new sync algorithm, the network overhead will be masked
as the thread adding blocks isn't interrupted by network calls
anymore. This should reduce memory usage a lot during sync.
> Change default block sync size from 200 to 20

- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
When a node is dropped, we stop considering its claimed blockchain
height as a factor in the target height calculation. This prevents
a runaway chain from being still thought to be the target even if
the nodes carrying it are dropped.
> cryptonote_protocol: keep target in sync with dropped connections

- src/p2p/net_node.h
- src/p2p/net_node.inl
This avoids failing to connect to the network in case all
known peers are unavailable (which can happen if the peer
list is small).
> p2p: fallback on seed nodes if we can't make a connection

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
They're interpreted as characters otherwise
> cryptonote_protocol_handler: log versions as unsigned ints

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- tests/core_proxy/core_proxy.h
- tests/unit_tests/ban.cpp
Add get_fork_version and add_ideal_fork_version to core so
cryptonote_protocol does not have to need the Blockchain
class directly, as it's not in its dependencies, and add
those to the fake core classes in tests too.
> tests: fix tests build

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet_rpc_server.cpp
wallet2::import_key_images checks with daemon if the imported key images are spent or not and should therefore only be used with a trusted node.
> fix possible privacy leak

- external/db_drivers/liblmdb/lmdb.h
- external/db_drivers/liblmdb/mdb.c
- external/db_drivers/liblmdb/mdb_copy.1
- external/db_drivers/liblmdb/mdb_copy.c
- external/db_drivers/liblmdb/mdb_dump.1
- external/db_drivers/liblmdb/mdb_dump.c
- external/db_drivers/liblmdb/mdb_stat.1
- external/db_drivers/liblmdb/mdb_stat.c
used to open the previous snapshot, in case the latest one
is corrupted
> ITS#8704 add MDB_PREVSNAPSHOT flag to mdb_env_open

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
Add `--mnemonic-language` command-line arg so it's possible to generate a wallet
without interacting with the CLI.
> simplewallet: mnemonic language command-line arg

- src/blockchain_db/lmdb/db_lmdb.cpp
- src/common/command_line.cpp
- src/common/command_line.h
- src/cryptonote_core/cryptonote_core.cpp
Use to load the database when the primary meta page is corrupted
Needs hyc's lmdb PR first.
> core: add --db-salvage command line flag

- src/cryptonote_basic/connection_context.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
Really unique yet consistent spelling mistake
> befor -> before

- src/daemon/rpc_command_executor.cpp
Block size will pretty much never be fully used, unless all txes
are using max fee.
> daemon: fix backlog estimating at max block size

- contrib/epee/include/console_handler.h
- contrib/epee/include/readline_buffer.h
- contrib/epee/src/readline_buffer.cpp
- src/simplewallet/simplewallet.cpp
And don't use std::mutex
Removes extraneous readline thread, avoids redundant copying/allocing buffers, etc...
> Simplify readline support

- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Copy cached wallet data when creating view only wallet.
fixes the bug mentioned in 1.2: https://github.com/monero-project/monero-core/issues/822
> Wallet API view-only improvements

- external/boost/archive/portable_binary_oarchive.hpp
- src/simplewallet/simplewallet.cpp
(assuming a fallthru, and not a break, was intended here)
> Silence stupid fallthru warning in gcc 7

- src/p2p/net_peerlist_boost_serialization.h
Fixes multiple connections to the same address
> p2p: init hashes after deserializing a network address

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
> cryptonote_protocol: remove old spans when received as old blocks

- src/blockchain_db/blockchain_db.cpp
- src/blockchain_db/blockchain_db.h
- src/common/command_line.cpp
- src/common/command_line.h
- src/cryptonote_core/cryptonote_core.cpp
- src/daemon/main.cpp
- src/debug_utilities/CMakeLists.txt
- tests/core_proxy/CMakeLists.txt
- tests/fuzz/CMakeLists.txt
Avoids common depending on blockchain_db, which can cause
link errors.
> move db specific options to BlockchainDB

- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/blockchain_utilities/blockchain_import.cpp
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
When one happens, cleanup must be called or the incoming tx
lock will stay locked
> core: guard against exceptions in handle_incoming_{block,tx}

- external/miniupnpc/miniwget.c
This PR fixes CVE-2017-8798 in miniupnpc in the `release-v0.11.0.0` branch.
Patch applied from: https://github.com/miniupnp/miniupnp/commit/f0f1f4b22d6a98536377a1bb07e7c20e4703d229
> Fix miniupnpc CVE-2017-8798

- src/common/command_line.cpp
- src/common/command_line.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- tests/core_proxy/core_proxy.h
- tests/unit_tests/ban.cpp
Defaults to off, but fluffy blocks are forced enabled on testnet
> Add a --fluffy-blocks option to relay blocks as fluffy blocks

- src/cryptonote_core/tx_pool.cpp
This might prevent some calls to terminate when the LockedTXN
dtor is called as part of stack unwinding caused by another
exception in the first place.
> tx_pool: declare LockedTXN dtor as noexcept(false)

- src/daemon/rpc_command_executor.cpp
I noticed when I was syncing a node from 10 days behind that "status" said next fork in 25 days. But really the next fork is in 13.6 days.
> Use latest height for fork date estimate

- src/p2p/net_node.h
- src/p2p/net_node.inl
When monerod starts it will try to add a UPnP port mapping but never cleans it up. This PR fixes this and now monerod deletes the port mapping on exit.
> Delete UPnP port mapping on exit

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
I propose/implemented a new command *wallet_info* for the CLI wallet. It displays the filename of the current wallet, its address, whether it is watch only, whether it runs with RPC restricted, and whether it runs on testnet.
When I juggled with several wallets for tests recently I noticed that there is currently no way to display the filename of the current wallet from within  the *monero-wallet-cli* program, and no *comment* or *label* feature either in order to recognize the currently opened wallet, only the address, and who remembers addresses of quickly generated and deleted-again test wallets, right?
First I wanted to simply output the filename as a second line with the *address* command, but moneromooo opined for a separate command. When I found  other little bits of info currently …
> monero-wallet-cli: New command 'wallet_info'

- src/cryptonote_basic/miner.cpp
The '/sys/class/power_supply/*/present' file usually does not exist for AC power supplies, so expecting it to be there prevents from detecting them.
And if a battery is not present, it will usually not appear in /sys/class/power_supply/, so checking for the 'present' file isn't useful.
Checking the 'online' file for AC power supplies and the 'status' file for batteries should suffice.
> background mining: Fix AC power supply detection on Linux

- src/serialization/json_object.cpp
See https://github.com/monero-project/monero/issues/2471
@NanoAkron @madscientist159 verify this fixes the build on your machines (I currently do not have an arm or ppc machine ready for testing ... yet).
> Fixes static_assert on arm and ppc builds

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet_manager.cpp
- src/wallet/api/wallet_manager.h
- src/wallet/wallet2_api.h
close should not store. otherwise there is no possibility to close without store.
also, the Wallet destructor calls close() which in turn stores the wallet - this takes a long time with no possibility of error detection/correction. destructors should not be persisting data.
the Wallet::close() closes and then deletes the WalletImpl on success which actually stores the wallet again (!!) wasting even more time.
In case someone is actively relying on this behaviour it would break!
I also think this change has no effect on simplewallet which stores and closes (stops) independently.
> remove store() from close()

- src/rpc/core_rpc_server.cpp
> Fix getblocktemplate RPC returning wrong reserved_offset

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/wallet/wallet2.cpp
Addresses #2338. 
Due to the structure of the blockchain DB, outgoing payments with no change outputs (i.e. those created by `sweep_all`) can't be handled properly, and their spent heights are set to the current blockchain height (so that they appear at the bottom with `show_transfers`).
Also, unconfirmed (pending) outgoing payments are not handled in this patch (may be added later if necessary).
> wallet2: correctly handle in/out payments for view-only wallet

- utils/systemd/monerod.service
monerod runs as user monero which does not have write
permissions for /var/run. Use systemd's RuntimeDirectory
feature to handle this.
> utils: systemd: dir for pidfile with permissions

- src/p2p/net_node.inl
Exclusive nodes may be used for privacy reasons, and thus we don't
want to connect to other nodes, even for checking connectivity.
See https://github.com/monero-project/monero/issues/2346
> p2p: disable gray list housekeeping when an exclusive node is given

- contrib/epee/include/misc_log_ex.h
- contrib/epee/src/mlog.cpp
- src/daemon/command_line_args.h
- src/daemon/main.cpp
- src/wallet/wallet_args.cpp
This was requested in #2321 and works with
- `monero-wallet-cli`
- `monero-wallet-rpc`
- `monerod`
> daemon, wallet: add --max-log-file-size option

- src/cryptonote_config.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_protocol/cryptonote_protocol_defs.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
It is unused, as it was apparently a future optimization,
and it leaks some information (though since pools publish
thei blocks they find, that amount seems small).
> protocol: remove hop count on block propagation

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
The last known hash was calculated incorrectly, causing
further chain hash downloads to restart from the current
chain. When the block queue has close to 10k blocks waiting,
this causes frequent downloads of 10k more hashes, but
with only the last few hashes actually being useful.
> cryptonote_protocol: fix needless chain hashes downloads

- README.md
MSYS2 dependencies: Added libsodium to the package install line, which was not installed automatically as a libzmq dependency on my system. Also added openssl to the package install line.
libsodium should get installed automatically as a dependency on systems where libzmq needs it.
> README: Add libzmq to dependencies and update MSYS2 dependencies

- CMakeLists.txt
This fixes static builds for me on Ubuntu 16.04 with libzmq3-dev and libsodium-dev dependencies installed, and MSYS2 with mingw-w64-x86_64-zeromq and mingw-w64-x86_64-libsodium dependencies installed. 
Tested only on x86_64. Needs testing on other platforms.
> daemon: fix static building with libzmq

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
It'd prevent further syncing. Recovery of empty hash chains is
automatic, but requires a running daemon
> wallet2: fix hash chain trimming when the inner chain becomes empty

- contrib/epee/include/net/net_utils_base.h
It has virtual functions and is used as a base class
> epee: give virtual dtor to network_address_base

- src/daemon/command_parser_executor.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
Text commands are unchanged, value `-1` sets the default limits, value `0` leaves the limits unchanged, fixed default limits and added RPCs `get_limit` and `set_limit`.
> rpc: add new RPCs to get and set limits

- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/net/net_utils_base.h
- contrib/epee/src/CMakeLists.txt
- contrib/epee/src/net_utils_base.cpp
- src/p2p/net_node.inl
- src/p2p/net_peerlist_boost_serialization.h
- src/p2p/p2p_protocol_defs.h
- src/rpc/core_rpc_server.cpp
- tests/unit_tests/ban.cpp
- tests/unit_tests/epee_utils.cpp
- tests/unit_tests/test_peerlist.cpp
See full commit message.
@moneromooo-monero This is not exactly what was discussed in https://github.com/monero-project/monero/pull/2332 or IRC, but is slightly closer to what you were trying to do except with a golang style type-erasure technique.
```c++
struct custom_address {
constexpr static bool equal(const custom_address&) noexcept { return false; }
constexpr static bool less(const custom_address&) noexcept { return false; }
constexpr static bool is_same_host(const custom_address&) noexcept { return false; }
constexpr static bool is_loopback() noexcept { return false; }
constexpr static bool is_local() noexcept { return false; }
static std::string str() { return {}; }
static std::string host_str() { return {}; }
constexpr static uint8_t get_type_id() noexcept { return uint8_t(-1); } …
```
> Upgrades to epee::net_utils::network_address

- tests/CMakeLists.txt
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/main.cpp
- tests/unit_tests/serialization.cpp
- tests/unit_tests/unit_tests_utils.h
This fixes test failure on builds that happen
to be built in 'build/' instead of 'build/release'.
> tests: pass data dir as arg

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_tx_utils.cpp
This turned out to have a flaw (sort order depends on output
index), and this doesn't really bring much anyway
> core: remove out sorting from v7 rules

- src/wallet/CMakeLists.txt
Needed to link monero-core Qt wallet.
> cmake: add libversion and libcheckpoints to libwallet_merged

- src/wallet/wallet2.cpp
Lack of it results in `m_refresh_from_block_height` being < 0 (18446744...) on low heights, which blocks `process_new_blockchain_entry` and never process coins on heights less than blocks_per_month.
Follow-up to #2258
> wallet2: missing underflow check on low heights

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
@moneroexamples 
This patch makes the `signed_monero_tx` file encrypted, making the tx pusher of your Onion Explorer unable to read it. For that purpose, an unencrypted raw tx in hex string is saved as `signed_monero_tx_raw` which can be directly fed to the `/sendrawtransaction` command. So you'll need to update your explorer accordingly when this patch gets merged.
> wallet: encrypt (un)signed tx, also optionally save unencrypted raw tx hexstr

- src/wallet/wallet2.h
- tests/unit_tests/hashchain.cpp
and relax the not-empty safety check to stay more intuitiuve
> tests: fix hashchain unit tests

- src/simplewallet/simplewallet.cpp
It'd be set to the current wallet default instead
> simplewallet: fix setting default-ring-size to 0

- src/wallet/wallet2.cpp
We don't want to count "partly filled" blocks in this case
> wallet2: fix backlog being off by 1

- Dockerfile
This commit adds ubuntu packages that are needed to build the Docker container.
There is an issue related to that: https://github.com/monero-project/monero/issues/2520
> Adding needed Ubuntu packages dependencies

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
This functionality is similar to the `do_not_relay` option in the wallet RPC, which I think would be useful for pushing tx anonymously to a remote node on Tor or I2P.
Like the wallet RPC, I could have made it as a per-transfer option by changing the command syntax of  `transfer` (e.g. introduce additional keyword `do_not_relay` at the end), but I thought that'd be cumbersome.
> wallet-cli: add --do-not-relay option

- src/debug_utilities/object_sizes.cpp
- src/wallet/wallet_rpc_server.cpp
If `--wallet-dir` was not given in the command line, _monero-wallet-rpc_ was crashing when trying to create one with empty name.
With `--wallet-dir` specified and pointing to existing directory, _monero-wallet-rpc_ was crashing trying to re-create the dir.
This fixes both errors. Checked on Linux only.
> wallet-dir fixes

- src/cryptonote_basic/miner.cpp
This fixes using the previous address when starting mining,
then stopping and restarting with a different address
> miner: always update block template when starting

- CMakeLists.txt
To avoid the suprize of stack tracing being enabled
but libunwind not being linked in.
> cmake: print which stack trace lib is used

- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/main.cpp
rather than a raw string without option
> unit_tests: data dir is now overridden with --data-dir

- tests/unit_tests/epee_utils.cpp
- tests/unit_tests/serialization.cpp
This fixes compiling unit_tests in MSYS2 on Windows after #2523 was merged.
> unit_tests: fix compiling on Windows

- CMakeLists.txt
- contrib/CMakeLists.txt
- src/CMakeLists.txt
Keep -Werror for src, contrib and do not pass it for tests/
Same as #2603 but with -Werror settings preserved.
I tested that this builds and that -Werror is correctly set, but I didn't test the order in the build because my package builds tests separately.
> cmake: build tests last

- src/cryptonote_core/cryptonote_core.cpp
This can happen for several reasons, but mainly if another block
was received, which took that tx off the pool.
> core: guard against a mined block not finding all txes in the pool

- src/blockchain_utilities/blockchain_export.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/wallet/wallet_rpc_server.cpp
Fix compiler warnings with Clang 6.0.0.
```
monero/src/cryptonote_protocol/block_queue.cpp:208:44: error:
suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
static const boost::uuids::uuid uuid0 = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
{                                          }
monero/src/wallet/wallet_rpc_server.cpp:1895:43: error:
lambda capture 'wal' is not used [-Werror,-Wunused-lambda-capture]
tools::signal_handler::install([&wrpc, &wal](int) {
^
monero/src/cryptonote_protocol/cryptonote_protocol_handler.inl:1616:40: error:
lambda capture 'arg' is not used [-Werror,-Wunused-lambda-capture]
m_p2p->for_each_connection([this, &arg, &fluffy_arg, &exclude_context, &fullConnections...
^ …
```
> Fix compiler warnings with Clang 6.0.0.

- src/wallet/wallet2.h
When loading an older wallet cache, they wouldn't be initialized,
leading them to have random(ish) values, and so assigned to some
random subaddress.
> wallet2: fix subaddress fields serialization

- src/cryptonote_core/blockchain.cpp
It is safe in those cases, though might return slightly out of date
information if another thread is busy modifying the blockchain,
but it avoids potentially lengthy delays just to get things like
the current blockchain height.
> blockchain: do not lock the blockchain lock for simple DB getters

- README.md
It doesn't show in plain text, but when the MD is displayed it shows the whole copyright notice on one single line and it doesn't make sense.
Solution: add line break to copyright notice and fix grammar.
> Problem: Copyright notice is very confusing

- src/blockchain_utilities/CMakeLists.txt
Binaries available to download on https://getmonero.org/downloads/ as
embedding monerod, monero-wallet-{cli,rpc} and
monero-blockchain-{ex,im}port.
This change synchronise download results with a manual build from
source
> blockchain_utilities: Add monero-blockchain-{ex,im}port binaries to default install targets

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet2_api.h
- tests/libwallet_api_tests/main.cpp
ping @kenshi84 
These small changes makes current master of GUI run. And probably also the Monerujo wallet. Will require some changes in https://github.com/monero-project/monero-core/pull/793
Also, it fixes the issue where GUI crashes when an old wallet is opened, because of subaddress index is getting out of bounds. Although, i nicer solution might be assigning old tx's to account/subindex 0 when cache is upgraded?
> subaddresses backwards compatibility 

- CMakeLists.txt
- contrib/epee/include/net/net_helper.h
- contrib/epee/src/CMakeLists.txt
Two independent patches.
epee: use boost type for SSL error code
Fixes compile error when building with OpenSSL v1.1:
```
contrib/epee/include/net/net_helper.h: In member function ‘void epee::net_utils::blocked_mode_client::shutdown_ssl()’:
contrib/epee/include/net/net_helper.h:579:106: error: ‘SSL_R_SHORT_READ’ was not declared in this scope
if (ec.category() == boost::asio::error::get_ssl_category() && ec.value() != ERR_PACK(ERR_LIB_SSL, 0, SSL_R_SHORT_READ))
^
contrib/epee/include/net/net_helper.h:579:106: note: suggested alternative: ‘SSL_F_SSL_READ’
```
See boost/asio/ssl/error.hpp.
Boost handles differences between OpenSSL versions.
cmake: epee: use var from FindOpenSSL.cmake
This fixes linking when path to openssl
is defined manually:
```
cmake …
```
> cmake, epee: fix build with openssl v1.1 and with manually specified openssl path

- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
Distinguish "not enough money" and "not enough unlocked money" in error msgs.
And minor typo fix in a variable name.
> Fix #1530 Distinguish "not enough money" and "not enough unlocked money" in RPC msgs

- src/daemon/command_parser_executor.cpp
- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
More flexible print_tx command in daemon.
Simply calling `print_tx <transaction hash>` now prints just a one-liner of which block contains the tx (or if it's in the pool).
More verbose output can be added with `+hex` and/or `+json`. These optional flags can be added in any order (as long as they are after the <transaction_hash> argument. It should be consistent to print a blank line at the end in every possible cases including arguments parsing failure.
After this update, you should call `print_tx <transaction hash> +hex +json` to get the very same result as the current `print_tx`command.
> Fix #2559: more flexible print_tx daemon command

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
This implements the new feature of descriptions for wallets as a whole. A description for a wallet can be set by the new command `set_description` in the CLI wallet. It can be queried by the likewise new command `get_description` .
The recently introduced CLI wallet command `wallet_info` now displays the description as well.
Please be aware that with this code active the structure version for wallets goes to 21, after it already went from 18 (version of latest release code) to 19 by some of moneromooo's recent changes and then to 20 with the subaddresses code. This means that Helium Hydra release code cannot process wallets "touched" by this code anymore. (There seems to be no easy way with Boost binary serialization to make such changes downward-compatible.)
To store the description a …
> Wallet: Descriptions through new commands 'set_description', 'get_description'

- src/wallet/wallet2.cpp
> wallet2 bugfix: supply missing subaddr_account arg to balance() and unlocked balance()

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- tests/unit_tests/hardfork.cpp
Protect node privacy by proper filtering in restricted-mode RPC answers
This patch allows to filter out sensitive information for queries that rely on the pool state, when running in restricted mode. This filtering is only applied to data sent back to RPC queries. Results of inline commands typed locally in the daemon are not affected.
In practice, when running with `--restricted-rpc`:
* get_transaction_pool will list relayed transactions with the fields "last relayed time" and "received time" set to * get_transaction_pool will not list unrelayed transaction, and will not list key images that are used purely for unrelayed * get_transaction_pool_hashes.bin will not list unrelayed transaction
* get_transaction_pool_stats will not count unrelayed transactions in any of the aggregated values …
> Protect node privacy by filtering out unrelayed txes from responses in restricted-mode RPC

- contrib/epee/include/net/levin_base.h
- contrib/epee/include/net/levin_client_async.h
- contrib/epee/include/net/levin_protocol_handler.h
- contrib/epee/include/net/levin_protocol_handler_async.h
- contrib/epee/tests/src/net/test_net.h
- src/p2p/net_node.inl
- tests/net_load_tests/clt.cpp
- tests/net_load_tests/net_load_tests.h
- tests/net_load_tests/srv.cpp
- tests/unit_tests/epee_levin_protocol_handler_async.cpp
The commands handler must not be destroyed before the config
object, or we'll be accessing freed memory.
An earlier attempt at using boost::shared_ptr to control object
lifetime turned out to be very invasive, though would be a
better solution in theory.
> Fix an object lifetime bug in net load tests

- src/common/util.h
In practice, this seems to cause monero-wallet-rpc to exit
when ^C quits whatever its output is piped into (such as tee),
but it saves, while it did not before.
> util: ignore SIGPIPE

- external/db_drivers/liblmdb/mdb.c
Check for PTHREAD_MUTEX_ROBUST_NP definition (this doesn't work
on Linux/glibc because they used an enum). Zero out mutex before
initing.
Needed for #2625
> ITS#8339 Solaris 10/11 robust mutex fixes

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
(I made this PR based on a request by @xeyleukfnd - he/she may want to answer any questions/comments from the community.)
This patch adds `--generate-from-spend-key <filename>` option to `monero-wallet-cli`. The functionality is practically the same as `--generate-from-keys`, with the difference being that the CLI doesn't ask for the public address and the view secret key which are both automatically derived from the spend secret key (assuming the wallet being deterministic). The main motivation is that sometimes users might want to store the spend secret key instead of the seed for some reason (maybe @xeyleukfnd can explain more). The functionality of deriving the public address and the view secret key from the spend secret key are already available in …
> wallet-cli: added --generate-from-spend-key option

- src/simplewallet/simplewallet.cpp
They are actually wrong if the wallet is setup in a different
denomination, and it's incursion of extrinsic lingo where monero
fits perfectly in the first place.
> simplewallet: remove XMR mentions

- README.md
- tests/CMakeLists.txt
- tests/core_tests/CMakeLists.txt
Other tests use unit_tests, performance_tests, etc.
This fixes getting it wrong half the time when typing.
> always use core_tests for consistency, not coretest

- tests/core_tests/block_reward.cpp
- tests/core_tests/block_validation.cpp
- tests/core_tests/chain_split_1.cpp
- tests/core_tests/chain_switch_1.cpp
- tests/core_tests/double_spend.cpp
- tests/core_tests/integer_overflow.cpp
- tests/core_tests/rct.cpp
- tests/core_tests/ring_signature_1.cpp
- tests/core_tests/tx_validation.cpp
- tests/core_tests/v2_tests.cpp
This fixes all tests being annoyingly rebuilt when one changes
> core_tests: do not include chaingen_tests_list.h in all tests

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Friendlier on memory/speed, we know in advance the max amount
of items, which are small and constant size, and there's a lot
of list walking involved.
> wallet2: use a vector, not a list, for selected_transfers

- README.md
- external/unbound/CMakeLists.txt
Issue: #2575
Build instructions for OpenBSD 6.2:
* boost (built with clang)
* cppzmq
Fixed a issue, where cmake was not able to find and link against libressl in unbound.
> Updated OpenBSD build instructions and fixed libressl linking issue

- src/simplewallet/simplewallet.cpp
Executing 'sweep_all' with no arguments segfaulted before.
> Fix 'sweep_all' command when called with no args

- src/common/updates.cpp
Those will have a ".exe" file extension, not .zip.
> updates: add a special case for "install-" build tags on windows

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/http_server_impl_base.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
This pull request adds the `rpc_connections_count` to the `/getinfo` RPC command and the `get_info` json rpc command.
This logic just surfaces the socket count stored by the server. I subtracted one from the value in the `get_connections_count` method as the socket count includes the initial listening socket.
I was able to test this locally by hitting the `get_info` json rpc call before and after starting up a monero-wallet-cli and seeing it increase. I also locally created some sockets via an interactive ruby shell and saw it go up each time I did and decrease when I closed it.
I'm still getting the hang of the net code so please let me know if I've missed something or if my approach below is unwise / ill advised.
Thanks!
Ref: #1964
> rpc get_info add rpc_connections_count

- src/wallet/wallet2.h
Used `RefreshDefault` as default rather than it's current `RefreshOptimizeCoinbase` value of the `RefreshType` enum.
> Set default refresh value to default

- contrib/epee/include/net/http_client.h
- src/blockchain_db/blockchain_db.cpp
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_utilities/blockchain_import.cpp
- src/blockchain_utilities/bootstrap_file.cpp
- src/blockchain_utilities/bootstrap_file.h
- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/daemon/rpc_command_executor.cpp
- src/p2p/connection_basic.cpp
- src/ringct/rctOps.h
- src/ringct/rctSigs.h
- src/ringct/rctTypes.h
- src/rpc/core_rpc_server.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- tests/core_proxy/core_proxy.cpp
- tests/core_tests/chaingen.cpp
- tests/unit_tests/ringct.cpp
- tests/unit_tests/serialization.cpp
It's nasty, and actually breaks on Solaris, where if.h fails to
build due to:
struct map *if_memmap;
> remove "using namespace std" from headers

- src/simplewallet/simplewallet.cpp
This ensures they don't go out of sync when adding/changing them,
and makes the code easier to deal with.
> simplewallet: factor transfer related exception handling

- contrib/epee/include/storages/portable_storage_to_bin.h
It's a CLANG only option, and causes GCC to error out
> epee: don't disable -Wtautological-constant-out-of-range-compare on GCC

- src/checkpoints/checkpoints.cpp
Makes working on testnet a lot easier (much less I/O when loading
and saving wallets, and exercises the hashchain code before any
changes are merged)
> checkpoints: add a testnet checkpoint at 1000000

- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_server.cpp
wallet-rpc was failing to link if readline is in use.
> More missed readline dependencies thru scoped_message_writer

- src/blockchain_utilities/bootstrap_file.cpp
> blockchain-utils: fix output_stream_header memory leak

- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_server.cpp
Adds a new command to the wallet rpc called `--prompt-for-password`.
Current behavior prior to the change is documented here:
> - --wallet-file specified with no password
>   - Asks for password and if valid logins in; failure invalid password message
Now it returns an error, "no password specified; use --prompt-for-password to prompt for a password" in this case.
- --wallet-file specified with no password
- `--prompt-for-password` not provided? Error message "no password specified; use --prompt-for-password to prompt for a password"
- `--prompt-for-password` provided, asks for password and if valid logins in; failure invalid password message
Ref: #2179
> Wallet: Add prompt-for-password flag

- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet2_api.h
- src/wallet/wallet_rpc_server.cpp
Sorry for my carelessness, but I realized now that it's rather confusing to have two different ways of telling the caller about the halt of the process (C++ exception vs additional error string).
> fix for tx proof: use exception instead of error_str when signature gen failed

- external/easylogging++/easylogging++.h
Issue: #2575
Add ELPP_OS_OPENBSD macros to easylogging++.h so that it will build on
OpenBSD.
> fixed easylogging compile issue on OpenBSD

- src/cryptonote_basic/miner.cpp
Implement missing miner functions on FreeBSD
cryptonote::miner::get_system_times(): Fetch the system's total and
idle time using sysctl kern.cp_time.
cryptonote::miner::get_process_time(): Use the same implementation as
Linux and OSX, the times(3) function conforms to POSIX.1 and is
available on FreeBSD.
cryptonote::miner::on_battery_power(): Try to fetch the battery status
using sysctl hw.acpi.acline. If that fails (if ACPI is not enabled on
the system), then try querying /dev/apm.
> Implement missing miner functions on FreeBSD

- src/daemon/main.cpp
- src/wallet/wallet_args.cpp
When the argument `--max-concurrency` is unspecified, previously the daemon received the default value of `0` which effectively set `max_concurrency` to `boost::thread::hardware_concurrency()`, while the wallet CLI received the default value of `1` which set `max_concurrency` to just `1`. This prevented the use of more than 2 threads for `start_mining` in the wallet CLI.
I have no idea why the defaulted values are different. Observed on OSX 10.12.6.
> daemon & simplewallet: don't set max-concurrency when unspecified

- tests/unit_tests/main.cpp
While there, also use the new is_arg_defaulted API instead of
going to poke the internal API directly.
> unit_tests: fix running without --data-dir

- src/simplewallet/simplewallet.cpp
Avoids turning it to a huge number
> simplewallet: translate ring size 0 to mixin 0 (default values)

- contrib/epee/include/net/http_protocol_handler.inl
In #2723 I added CORS headers to the RPC server. I used cURL at the time to test it and based the implementation off of the spec but doing such I didn't realize in order for browsers to properly use this they'd need a few additional headers.
Upon further review though there are two required here [Access-Control-Allow-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers) and [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers). The former is used for allowing the Authentication and X-Requested-With headers (with the latter of those often sent via ajax libraries). The latter is used to allow digest authentication via CORS as otherwise there's no way to access the contents of …
> RPC: CORS add Access-Control-Allow-Headers to OPTIONS preflight

- utils/systemd/monerod.service
The file needs some `Restart=`, there are a few possible arguments. None restart the service as reliably as `always`. With both `on-failure` and `on-abnormal` I've seen the service stuck in a failed state.
As for `PrivateTmp=true`, why not?
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateTmp=
> Add "Restart=always", "PrivateTmp=true" to monerod.service file.

- src/blockchain_db/blockchain_db.cpp
It could trip on a corrupt/crafted file if the user has disabled
input verification.
> blockchain_db: sanity check on tx/hash vector sizes

- src/simplewallet/simplewallet.cpp
NOTE: simplewallet seems to only remember the current account, not subaddress-within-account, not sure what's up with that, so simplewallet generates for the first address. Not sure whether it'd be better to have an optional argument instead,
> simplewallet: prevent (wrong) integrated adresses on accounts > 0

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Refactored the block height estimation and added a sanity check on the wallet's restoration height.
> Fixes #759 Add sanity check on restore height

- src/daemon/daemon.cpp
- src/daemon/rpc.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
This branch adds two new configuration options `--rpc-restricted-bind-port` and `--testnet-rpc-restricted-bind-port` which allow for a second port to be opened to handle RPC requests.
Let me know if this direction is unwise. I spent some time looking over the code and this was the approach that seemed most sensible to me but I'm still learning C++ so completely understand if I've done something asinine. Currently the login is the same across both but if there's value that could be split into a separate set of configuration arguments as well.
I was able to test this by using the `/getinfo` call across both and confirmed that `/get_peer_list` only works for the unrestricted. 
It's currently possible for someone to both set the core RPC port as restricted via `--restricted-rpc` and enable …
> RPC: allow binding of restricted port in addition to core port

- src/ringct/rctSigs.cpp
Those are not serialized, but are restored from the outPk masks,
so depending on what tries to validate the tx, those commitments
may or may not be filled with valid data at the time. The outPk
masks are already hashed as part of the rctSigBase field.
> ringct: do not include bulletproof commitments in signed message

- external/easylogging++/easylogging++.cc
- external/easylogging++/easylogging++.h
If execinfo.h is not available, output the stack trace warning only once, so we don't spam the build logs with it.
> easylogging: show the 'no stack trace' warning only once

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
If `--daemon-address` is set to a wrong remote node, `monero-wallet-cli` will now ask for either a new remote node or a local node without exiting right away.
Other changes:
* `set_node` command in the wallet to switch between nodes without restart
*  Notification and confirm before connecting to non-HTTPS nodes
> Ask again on faulty daemon-address argument

- src/wallet/wallet2.cpp
Test case attached - if you try use the password ```0how``` then rapidjson will treat the decrypted keys file as valid JSON, and will segfault when it hits the HasMembers call.
Thanks, base fuzzer
[testabc.keys.zip](https://github.com/monero-project/monero/files/1526347/testabc.keys.zip)
> catch wallet decrypt false positive

- contrib/epee/include/net/abstract_tcp_server2.inl
- src/cryptonote_protocol/cryptonote_protocol_handler-base.cpp
- src/p2p/connection_basic.cpp
- src/p2p/net_node.inl
- src/p2p/network_throttle-detail.cpp
- src/p2p/network_throttle-detail.hpp
- src/p2p/network_throttle.hpp
- src/rpc/core_rpc_server.cpp
A while ago I noted a strange asymmetry in Monero's rate limiting / throttle code: In "out" direction there was the following strange code when setting the limit in file `src/p2p/connection_basic.cpp`:
```
void connection_basic::set_rate_up_limit(uint64_t limit) {
// TODO remove __SCALING_FACTOR...
const double SCALING_FACTOR = 2.1; // to acheve the best performance
limit *= SCALING_FACTOR;
{
CRITICAL_REGION_LOCAL(	network_throttle_manager::m_lock_get_global_throttle_out );
network_throttle_manager::get_global_throttle_out().set_target_speed(limit);
network_throttle_manager::get_global_throttle_out().set_real_target_speed(limit / SCALING_FACTOR);
}
save_limit_to_file(limit);
}
```
And when reporting the number of bytes transferred there was a strange factor of 700 applied:
```
void …
```
> Corrections in rate limiting / throttle code, especially in 'out' direction

- src/common/password.cpp
- src/simplewallet/simplewallet.cpp
- translations/monero.ts
- translations/monero_fr.ts
- translations/monero_it.ts
1. Password capitalization normalization
2. Fewer pleases: Almost every sentence in the Note to write the seed down began with Please. The final commit removes all but one please. Note is now less awkward and more succinct.
> Minor text edits for wallet creation

- cmake/FindReadline.cmake
To fix the linking error described here https://github.com/monero-project/monero/pull/2841#issuecomment-346129030 we also need to link libcurses.
> fixed linking against libreadline on OpenBSD

- CONTRIBUTING.md
- README.md
Most headings capitalized every word. A few did not. Now all do.
> Readme.md: Heading capitalization and some cleanup

- contrib/epee/include/span.h
- src/common/memwipe.h
- src/crypto/chacha8.h
- src/crypto/crypto.h
- src/wallet/wallet2.cpp
- tests/crypto/CMakeLists.txt
Securely erase keys from memory when they go out of scope. Might have a
performance impact, which I haven't measured (perf measurements aren't
generally reliable on laptops).
I wasn't entirely happy with having to add the `scrubbed::inner()` methods, but some `static_assert`s in the serialization stuff complains that the wrapper class's dtor causes there to be padding, for reasons I don't yet understand. I considered hiding it slightly with an `operator*()`, but wasn't sure what the norms were in this project toward that. I'm happy to take advice/feedback here.
> Partially implement #74

- README.md
this finally got my debug-static-all to build. Obviously, its me, so this could use some edits or something.
> add libsodium as dependency for building in readme

- src/wallet/wallet_rpc_server.cpp
It's only suggestion.
Why i want this? Because if I save subaddress in my database and I want to check if payment was made on this address and the only way to do this through rpc is query all adresses and find this address by subindex and this is very ineffective.
Sorry, I don't c++, but it's working here.
I don't know what rpc_payment data structure, only tested like this
`
rpc_payment.payment_id   = m_wallet->get_subaddress_as_str(payment.second.m_subaddr_index);
`
> return subaddress in get_bulk_payments

- Dockerfile
- README.md
Solution for #2865 
> docker build --build-arg NPROC=1 -t monero .
> Dockerfile: add option to set build parallelism

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- `get_payments` / `get_bulk_payments`: The receiving (sub)address string is passed to the response's `address` field.
- `getaddress`: An optional array `std::vector<uint32_t> address_index` was added to request; when empty, all stored subaddresses will be returned. Otherwise, addresses of the specified indices will be returned.
> wallet-rpc: added receiving address to res of get(_bulk)_payments; selective addresses for getaddress

- src/simplewallet/simplewallet.cpp
If no subaddress index is given, consider all of them
> simplewallet: fix default unspent_outputs output with subaddresses

- Dockerfile
Binding RPC to 127.0.0.1 makes no sense. Despite the fact port 18081 is
exposed, no one will be able to connect to the daemon.
RPC should be listening at all interfaces when running inside a Docker
container.
> fix: bind RPC to all interfaces inside Docker container

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
(The idea was born in a Reddit thread: https://www.reddit.com/r/Monero/comments/7jll1b/multisig_safety_subaddresses_mental_model/dr8cprh/)
This patch introduces the idea of "tagging" accounts in order to group arbitrary subsets of accounts for easier finance management. The following new sub-commands are added to the `account` command:
account tag <tag_name_1> [<tag_name_2> ...]
account list_tags
account add_tag <tag_name>
account delete_tag <tag_name>
Example usage is below:
```
[wallet BgeJGK]: account
Account               Balance      Unlocked balance                 Label
0 9xLMUj       28.377593612305       12.533363012305       Primary account
*       1 BgeJGK        8.897020120000        8.897020120000             checking1
2 BeU2Yg        0.200000000000        0.000000000000 …
```
> Account tagging

- src/p2p/net_node.inl
This fixes a hang on exit due to race where a connection adds
itself to the server after the starting connections are closed,
but before the net server marks itself as stopped.
> p2p: stop net server before closing starting connections

- src/wallet/wallet2.cpp
Removing it nullified the min-outputs-{count,value} system,
and will not increase the number of attempted transactions
in the general case.
> wallet2: reinstate the single preferred output selection

- external/unbound/CMakeLists.txt
Fixes the unit test failure about SHA1 being unavailable,
and hopefully the monerod complaints about not being able
to verify DNSSEC.
Thanks to iDunk for the remote Windows testing.
> unbound: enable SHA1

- tests/unit_tests/memwipe.cpp
free might overwrite the memory, so we can't expect to see
the NULs we overwrote with, but at least we shouldn't see
the original data.
> unit_tests: fix memwipe test comparison

- src/simplewallet/simplewallet.cpp
- translations/monero.ts
- translations/monero_fr.ts
- translations/monero_it.ts
A bunch of CLI text should probably have the definite article "the" preceding a specific command.
> Better use of definite article

- CMakeLists.txt
- src/common/i18n.cpp
- translations/CMakeLists.txt
- translations/generate_translations_header.c
If a translation file exists in a "translations" directory located in
the same directory as the binary, it is used in priority (this can be
useful when working on translations as you don't have to recompile the
whole program all the time), and if no such file is found the embedded
translation file is used (if it exists).
> Embed the translation files in the binary

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
They are hex rather than words, because they are a lot longer
than "normal" seeds, as they have to embed a lot more information
> wallet: support for multisig seeds

- src/simplewallet/simplewallet.cpp
This ensures we can't get races
> simplewallet: lock idle scope in {im,ex}port_{key_images,outputs}

- src/simplewallet/simplewallet.cpp
Fixes #2848
```
[wallet 9xxxxx]: donate 5
Donating 5 to The Monero Project (donate.getmonero.org/44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A).
Wallet password: 
Error: failed to parse address
```
```
[wallet 9xxxxx]: donate 1
Error: donations are not enabled on the testnet
```
> simplewallet: disable donations on testnet

- src/crypto/blake256.c
This does not happen when used by the monero code
> blake256: fix wrong hash when computed in parts

- CMakeLists.txt
- translations/CMakeLists.txt
Define generate_translations_header as an external project to be able
to use the compilation toolchain for the host instead of the toolchain
for the target.
> Fix translations header generation when cross-compilating

- translations/CMakeLists.txt
On some systems, there is a /usr/bin/lrelease wrapper even if the real
lrelease program is not installed. So let's try to execute lrelease
after it has been found by find_program to see if it is really working.
> Check if lrelease is working before trying to use it

- src/simplewallet/simplewallet.cpp
Correct command usage texts for `export_multisig_info`, `import_multisig_info` and `export_raw_multisig_tx` that somebody probably forgot to adjust after those commands were renamed
> simplewallet: Correct 3 multisig command usage help texts, e.g. for 'export_multisig_info'

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
Similarly to #2916 resolve full address instead of only returning the subaddr indices.
This really makes talking via RPC easier, as the client doesn't need to hold and maintain address cache.
> Resolve addresses in get_transfers

- src/daemon/main.cpp
- src/simplewallet/simplewallet.cpp
Currently, the simplewallet doesn't report anything when the given command is unrecognizable. For example, with this command:
./monero-wallet-cli --daemon-address node.moneroworld.com 18089 --wallet-file mywallet
(note the missing `:` between the host name and the port number) the wallet will just silently quit because `18089` is an unknown command. This patch makes the wallet and the daemon report such unknown command so that the user can know what was wrong.
Thanks to bug report by @BigslimVdub in https://github.com/aeonix/aeon/issues/131.
> daemon+simplewallet: given an unknown command, show it

- src/wallet/CMakeLists.txt
- src/wallet/api/CMakeLists.txt
It means it can still be built with make -C build/debug wallet_api
but still not DoS us while debugging
> wallet_api: make this optional but not built by default

- src/wallet/wallet2.cpp
It can fail if it fails to parse extra, while still having filled
the returned data with partial contents
> wallet2: allow failing parse_tx_extra

- src/rpc/core_rpc_server_commands_defs.h
This changes response to use int64_t like the rest of the source, fixing #3051 .
> Change cryptonote::COMMAND_RPC_SET_LIMIT::response to use int64_t

- src/simplewallet/simplewallet.cpp
Change some confirmation dialog in wallet to look like other ones (add symbol ":" and space)
So, it will look like: (Y/Yes/N/No): y
Now it look: (Y/Yes/N/No)y
> fix some confirmation dialog, add missing symbols

- .gitignore
Developing Monero on JetBrain's CLion causes the creation of a `cmake-build-debug/` output folder.
This is an attempt to allow me to use `git add .` back without having to care about that folder which doesn't belong on this repository.
> Ignore cmake-build-debug folder on CLion

- src/cryptonote_protocol/cryptonote_protocol_defs.h
This is 32 bits on 32 bit platforms, but 64 bits on 64 bit platforms.
> cryptonote_protocol: fix size_t used in wire format

- src/common/util.cpp
This can causes crashes in libunbound
> util: warn if unbound was not built with threads

- contrib/epee/include/net/levin_protocol_handler_async.h
Addressing comments by @xyzzy42:
https://github.com/monero-project/monero/pull/2936#pullrequestreview-86339046
> The complexity of vector::erase is proportional to the number of elements after the erased element. They are all copied down. Thus, deleting a vector one by one is much faster, O(n) vs O(n^2), if you start from the end, using out_connections.end(), rather than from the beginning.
Not sure about the actual impact on performance, though (I'm not so familiar with this part of the codebase).
> levin_protocol_handler_async: erase from back of vector instead of front

- src/simplewallet/simplewallet.cpp
I forgot in #2487 to update the command name when the outgoing/incoming tx proofs are unified into a single command.
> simplewallet: fix typo get_tx_proof_out to get_tx_proof

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/api/wallet_manager.cpp
- src/wallet/api/wallet_manager.h
Recovering from keys or seed created a wallet on disk with no password. Any attacker watching the wallet directory could copy away such a file for future use. These creation methods were marked as deprecated and new methods implemented which accept a password parameter. Unfortunately, a password parameter could not simply be added to recoverFromKeys() as that would ambiguate the call (the last parm <spendkey_string> is optional) so the new method was called recoverWithKeys().
Tested with monerujo.
> all recover options with password

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
Note that the new `fee` field will still be shown as 0 for incoming transfers that have been scanned previously (you could do `rescan_bc` to force updating them, if you like).
Also, the light wallet mode is unsupported at the moment (since the MyMonero/OpenMonero API doesn't seem to provide the fee information).
> wallet rpc: show fees when querying incoming transfers

- src/wallet/wallet_rpc_server.cpp
For some unknown reason it was missing from the API.
> Allow retrieving spend key via RPC

- src/wallet/api/CMakeLists.txt
qt wallet has `include <wallet/api/wallet_api2.h>`
> cmake: set API header install path to what Qt wallet expects

- src/wallet/api/wallet2_api.h
`UnsignedTransaction::Priority` introduced in #1541 seems unused and redundant as the priority list is already defined in `PendingTransaction::Priority` which is used in `createTransaction()` etc.
TBH I don't understand why the priority enum was defined under `PendingTransaction` instead of being on its own, and why the priority had to be defined this way instead of simply using `uint32_t` in the first place. This was done long time ago in #915, and the API is already in use, so I guess it's not so easy to make changes to the API, though.
> Wallet API: remove unused enum Priority from UnsignedTransaction

- contrib/epee/include/memwipe.h
- contrib/epee/include/span.h
- contrib/epee/include/string_tools.h
Specializing a trait to lie about the properties of a class is probably a bad idea. Instead, the requirements for hex conversion were relaxed to `is_standard_layout`. Microsoft has a decent [writeup of the traits](https://msdn.microsoft.com/en-us/library/mt767760.aspx). Although, the writeup never mentions that `is_standard_layout` must be contiguous (i.e. no vtables).
> Remove is_pod trait

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet2_api.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
Not super confident if this is the right way to do it, but I wanted to give it a try:)
~~I tried to test it on testnet, but it was extremely difficult to get the tx pool clogged because the tx size was significantly reduced by BPs while the minimum block size is kept at 300kb.~~  **EDIT: I tested it on mainnet and confirmed it working.**
~~Also, this functionality is not yet implemented for the `sweep_*` methods where the backlog checking functionality isn't implemented (could/should be done in a separate PR).~~
**EDIT: Now `sweep_*` methods are also supported.**
> wallet: automatically use low priority if safe (no backlog & recent blocks not full)

- src/simplewallet/simplewallet.h
Missing i18n import in simplewallet.h after last merges.
Should fix monero core build (issue #3183) along with PR #3185.
> Bugfix : Missing i18n import in simplewallet

- tests/fuzz/CMakeLists.txt
This fixes the undefined references to boost::chrono when linking http-client_fuzz_test and levin_fuzz_test on Windows.
> Tests: Fix building of two fuzz tests on Windows

- src/cryptonote_basic/cryptonote_boost_serialization.h
- src/ringct/rctSigs.cpp
- src/ringct/rctTypes.h
Saves 64 bytes non prunable data per typical tx
This breaks v7 consensus, will require a testnet reorg from v6
> ringct: pseudoOuts moved to prunable in the simple bulletproof case

- contrib/epee/include/net/levin_protocol_handler_async.h
- contrib/epee/include/storages/http_abstract_invoke.h
- src/common/rpc_client.h
- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/p2p/net_node.cpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/p2p_protocol_defs.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
With this patch, the maximum number of incoming peers can be set either on the command line (with `--in-peers <n>` or in the config file. I've tested this and even after 12 hours the number of incoming connections does not go over the specified number whereas previously I would see between 10 and 50 incoming connections after 12 hours.
~~However it is also supposed to be possible to modify the number of incoming connections on the fly via an RPC call and that is not currently working. However setting the number of outgoing peer connections via an RPC call isn't working either.~~
~~Therefore I'll leave this PR as is and fix the RPC call business in an upcoming PR.~~
RPC is now working as well.
> Allow setting of max incoming connection count on command line and in config file

- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
Probably this isn't a comprehensive solution to the "bootstrapping node advertising" idea proposed in #2204, but I just wanted to try something simple anyway...
This patch adds a flag `--bootstrap-daemon-address` to `monerod`, for example:
monerod --bootstrap-daemon-address node.moneroworld.com:18089
If this parameter is specified, your local daemon connects to that remote node and simply acts as a 'pipe' while it is synchronizing with the network. When the sync is complete, it stops this piping and starts to respond to RPC requests using its own blockchain. The wallet connects to your local daemon as usual, and doesn't know that it's using the bootstrap remote daemon. This can be conceptually seen as moving the remote daemon address parameter `--daemon-address` of the wallet CLI/RPC/GUI …
> Bootstrap daemon

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Fixes #3080.
Please let me know if there is anything wrong with this approach.
> wallet-cli: Do not ask for scan_from_height if it is explicitly set to zero.

- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/wallet_rpc_server.cpp
Motivated by this post on StackExchange: https://monero.stackexchange.com/questions/7460/cant-transfer-monero-coins-strange-error-message
> wallet: suggest the use of sweep_unmixable when not_enough_outs_to_mix is thrown

- contrib/epee/include/wipeable_string.h
- contrib/epee/src/wipeable_string.cpp
- src/common/util.cpp
since the original reason for the indirect call (that memwipe
was not in contrib) is now gone
> wipeable_string: call memwipe directly

- src/cryptonote_basic/connection_context.h
This prevents spurious early peer drops
> connection_context: initialize m_last_request_time to current time

- src/cryptonote_core/blockchain.cpp
It's freed when we've synced past its end, but we might still
find an old chain somewhere
> blockchain: don't try to use hash check array after it's freed

- contrib/epee/include/net/abstract_tcp_server2.inl
This should make the kernel eventually clean up dead connections.
> Fix #602 Turn on socket keepalive

- src/cryptonote_core/tx_pool.cpp
Previously, when blob_size == tx_size_limit, the "m_too_big" property was set
and the transaction was rejected. This should not have been the case.
> txpool: Don't bale out when blob_size == tx_size_limit

- src/blockchain_utilities/blockchain_export.cpp
- src/blockchain_utilities/blockchain_import.cpp
- src/common/command_line.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/daemon/command_line_args.h
- src/daemon/core.h
- src/daemon/daemon.cpp
- src/daemon/main.cpp
- src/p2p/net_node.cpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- tests/core_proxy/core_proxy.cpp
Implements proposal in #3054, namely:
> Remove redundant monerod testnet options

- contrib/epee/src/memwipe.c
After #3187 was merged, I see the following error on Mac:
```
monero/contrib/epee/src/memwipe.c:55:13: error: use of undeclared identifier 'stderr'
fprintf(stderr, "Error: memset_s failed\n");
```
> memwipe: add missing #include <stdio.h>

- src/common/password.cpp
- src/common/password.h
- src/common/util.h
- src/simplewallet/simplewallet.cpp
This fixes an issue during entering a password and user pressing ^D or ^C. These are now honored and exit the password prompt.
Credit to @vtnerd also.
> handle ^D and ^C while password prompting

- src/crypto/random.c
> crypto: add missing include (WIN32)

- translations/monero.ts
- translations/monero_fr.ts
- translations/monero_it.ts
- translations/monero_sv.ts
Build error solved changing a couple of strings from `[<payment_id>]` to `[payment_id]`.
Refreshed using a tweaked `build-translations.sh` script
> Fix broken build + refresh language files

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
...and when only `min_height` is specified, it always returns empty set.
Side note: The RPC `get_payments*` and `get_transfers` methods filter by height range in a peculiar way. Block of `min_height` is excluded, while `max_height` is included in the results. This asks for being changed or at least documented. What do you think would be the best option here?
> Add default value to max_height, otherwise it's 0

- src/wallet/wallet2.cpp
This issue was observed when scanning the Aeon blockchain for the dev donation wallet.
> wallet2: don't throw when spent amount is inconsistent

- README.md
BYPRODUCTS option in cmake/Version.cmake requires cmake >= 3.2.0,
> README.md: bump minimum cmake version to 3.2.0

- src/p2p/net_node.inl
Restore the assignment to `m_testnet` that was added in #3196 and accidentally lost during rebase in #3170. Fix for #3283.
> After-merge fix for default p2p bind port

- src/cryptonote_core/cryptonote_core.cpp
An udpate may or may not be available now, but should be soon if not.
This will prevent too many people freaking out.
> cryptonote_core: change wording of fork warning message

- tests/unit_tests/serialization.cpp
- tests/unit_tests/unit_tests_utils.h
When one wants to test for a map `m` whether it contains a particular key-value pair or not, doing something like `ASSERT_EQ(value, m.find(key)->second)` will crash the whole test if the key isn't found in the map. Although currently there's no such instance in the test thanks to the test data being carefully prepared, this utility can be useful for avoiding the crash when writing new tests.
> unit_tests: gtest utility ASSERT_EQ_MAP for easily testing key-value map

- src/daemonizer/CMakeLists.txt
- src/daemonizer/posix_fork.cpp
- utils/systemd/monerod.service
~~The logging to /tmp/bitmonero.daemon.stdout.stderr caused segfaults if the /tmp mount was full~~ (#2851).
Now the daemon is only logging to /tmp/bitmonero.daemon.stdout.stderr in the debug builds.
> monerod: do not log to tmpdir in daemon mode

- Dockerfile
Boost does not use Sourceforge anymore. Instead, their download links
point to dl.bintray.com.
Earlier today Sourceforge was down, and later the Boost downloaded file
checksum did not match, which further reinforces the need to change
the URL.
> Updating Boost download URL in the Dockerfile

- src/cryptonote_core/cryptonote_tx_utils.cpp
It would fail to send, thinking it needs a destination address,
since the destination matches the change address in this case.
> [RELEASE] core: fix sending to the source address with a short payment id

- src/ringct/rctSigs.cpp
- src/ringct/rctSigs.h
It seems that this function isn't used anywhere!
> remove unused function keyImageV

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
The terminology of "mixins" and "ring sizes" are often confused with each other. If I recall correctly, the term "mixin" is more or less being "phased out" in favour of just refering to the ring size. After seeing somebody get confused about this on, IRC I made this change to use the desired ring size as the param for the "transfer" command for the rpc wallet in place of the mixin to avoid confusion.
> Use ring size rather than mixin as param for rpc transfer

- src/gen_multisig/gen_multisig.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Previously, a file containing the unencrypted Monero address was
created in the wallet's directory. This file is only used for testing
purposes and might pose as a privacy risk.
> wallet2: No longer create '.address.txt' files for non-testnet wallets

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- save the new keys file as FOO-watchonly.keys, not FOO.keys-watchonly
- catch any exception (eg, I/O errors) and error out
- print the new keys filename in simplewallet
> wallet: fixes and tweaks to the save_watch_only_command

- README.md
- utils/systemd/monerod.service
Add Tor config to systemd service. Mention no `--detach` when torsocks+systemd in README. Edit README text for structure. The Tails text is still inconsistent: text says TORSOCKS_ALLOW_INBOUND=1 is needed but the command doesn't include it. I didn't test on Tails, so I didn't change it.
> systemd,readme: torsocks config for service

- src/wallet/wallet2.cpp
Simple fixes. ~~I assume that line 258 should say "go" and not "grok".~~ On line 324 it doesn't sound right to say "you need at least one of x *and* y *and* z" it would sounds better to say "you need at least one of x *or* y *or* z"
> typo: fix error message typos in wallet2.cpp

- src/simplewallet/simplewallet.cpp
Speeds up refresh when you have a lot of in/out transactions
> simplewallet: do not call a RPC when displaying the prompt

- src/wallet/wallet2.cpp
This is not a possible return from the daemon, but I want this in
now so all wallets handle this when the daemon starts doing so.
> wallet2: handle no blocks returned in refresh to mean no new blocks
