src/p2p/net_node.inl
Use copied value of seed node index during thread creation, not
reference.
- fixes segfault
Use boost::thread::try_join_until() instead of an atomic flag result
variable for each thread.
Add and handle interrupt for thread timeout.
- fixes segfault where a thread exceeds requested timeout and tries to
assign results to a referenced, but now out-of-scope, variable in
the main thread.
=> Fix seed node threaded DNS lookup

src/wallet/wallet2.cpp, src/wallet/wallet2.h, src/wallet/wallet_rpc_server.cpp
by giving an empty list of payment IDs.
=> Allow get_bulk_payments to return all payments regardless of payment ID

src/crypto/slow-hash.c, src/cryptonote_core/difficulty.cpp
32-bit compatibility untested, but if it builds on ARM...well...you know.
=> Last fixes for ARM / 32-bit compatibility

src/simplewallet/simplewallet.cpp
default mix factor to three if unspecified in simplewallet interactive
=> default mix factor in simplewallet

contrib/epee/include/net/abstract_tcp_server2.h, contrib/epee/include/net/abstract_tcp_server2.inl, contrib/epee/include/net/http_server_impl_base.h, src/p2p/connection_basic.cpp, src/p2p/connection_basic.hpp, src/p2p/net_node.h
works for unit tests build, too
=> [fix] Network 1.8: unlimited the RPC connections

README.md
--HEAD is broken in formula for now, will fix soon, but it's always cool to stick to tagged releases.
=> Don't recommend --HEAD for brew users

src/cryptonote_core/tx_pool.cpp, src/cryptonote_core/tx_pool.h
This should fix build issues with respect to the per-kb transaction sorting changes (as well as correctly implement those changes).
=> Fixes changes to sort tx by fee per kb

src/common/dns_utils.cpp, src/common/dns_utils.h, src/wallet/wallet2.cpp, tests/unit_tests/address_from_url.cpp, tests/unit_tests/dns_resolver.cpp
This fixes the startup error, "Failed to connect to any of seed peers, ..."
Fix name@domain.tld for OpenAlias lookups
Add tests to DNS and wallet tools tests.
=> Fix seed peers startup error

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h, src/wallet/wallet2.cpp, src/wallet/wallet2.h, src/wallet/wallet_rpc_server.cpp, src/wallet/wallet_rpc_server.h, src/wallet/wallet_rpc_server_commands_defs.h
Sends all the dust to your own wallet. May fail (if the fee required
is more than the dust total). May end up paying most of the dust in fees.
=> wallet: add a sweep_dust command

src/common/dns_utils.cpp, src/common/dns_utils.h
OK, I admit I wanted to template this struct for fun too.
=> dns_utils: simpify smart pointer use, and use for url strings too

README.i18n, README.md, src/common/CMakeLists.txt, src/common/i18n.h, src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h, translations/monero.ts, utils/translations/build-translations.sh, utils/translations/update-translations.sh
The system is mostly the Qt system, but we don't use Qt to avoid
the dependencies.
See README.i18n for details.
=> Translatable strings for simplewallet

src/blockchain_db/lmdb/db_lmdb.cpp
This allows blockchain_import to work with batch and verify modes enabled
(the default).
=> Add batch support to BlockchainLMDB::get_output_key

src/blockchain_db/lmdb/db_lmdb.cpp
If there's no blocks in database (m_height == 0):
* Don't assign incorrect block range to check.
* Skip average block size check.
Test:
Run blockchain_converter with an existing source blockchain.bin and
a non-existent LMDB destination database.
The converter creates a BlockchainLMDB instance with zero height, due to
not being initialized with a genesis block, normally done by
Blockchain::init(). While different than the behavior of bitmonerod,
blockchain_import, and blockchain_export, the initialization hasn't been
strictly necessary.
The db batch size estimation normally uses an average block size, or a
default minimum block size, whichever is greater. In this case, as
there's no existing blocks to check for an average block size, the
default should be used.
=> Fix estimation of batch storage size when no blocks exist

src/common/dns_utils.cpp
=> dns_utils: fix wrong asserts

external/miniupnpc/igd_desc_parse.c
http://talosintel.com/reports/TALOS-2015-0035/
=> miniupnpc: quick fix for buffer overflow

src/blockchain_db/berkeleydb/db_bdb.cpp, src/blockchain_db/berkeleydb/db_bdb.h, src/blockchain_db/blockchain_db.h, src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h, src/cryptonote_core/blockchain.h, tests/unit_tests/hardfork.cpp
git history's here if needed to get any of this back
=> Remove some old/obsolete/unused code

src/blockchain_utilities/blockchain_dump.cpp, src/blockchain_utilities/blockchain_export.cpp
Replace boolean values and exceptions where appropriate
=> blockchain_utilities: properly exit on error

src/cryptonote_core/cryptonote_basic.h
This reverts commit c6bf73131aaf804cb17f24c856f826be2761a566, reversing
changes made to 8a52cf4055d247dd4b162985c931e99683992e3c.
=> Revert "Merge pull request #506"

src/p2p/net_node.h, src/p2p/net_node.inl
It will not try to connect to the monero network, nor listen
=> net_node: add a --offline argument

src/blockchain_db/lmdb/db_lmdb.cpp
Data is only guaranteed to be valid within the lifetime of a txn.
You cannot use data returned from LMDB after the txn ends.
Also, fixed a missing txn.commit BlockchainLMDB::get_tx_unlock_time()
=> Fix data refs in read-only txns

src/blockchain_db/lmdb/db_lmdb.cpp
Also wrap that code in two prefix/suffix macros so they are
easier to use and not forget. Also add consts to returned data
casts where applicable.
=> db_lmdb: always use a batch tx if possible

src/daemon/rpc_command_executor.cpp, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h
and add top block hash in get_info RPC
=> print top block hash in daemon diff command

src/cryptonote_core/hardfork.cpp
=> Remove assert from status command

external/db_drivers/liblmdb/lmdb.h, external/db_drivers/liblmdb/mdb.c
Was leaking this handle in mdb_env_close()
=> MDB_VL32/WIN32 - close file mapping handle in env_close

src/cryptonote_core/cryptonote_core.cpp, src/daemon/core.h, src/daemon/daemon.cpp
Do not print the exception message, and write the important bit
in red, since people will only read the last line otherwise.
=> Nicer looking exit when blockchain.bin is found

src/blockchain_db/berkeleydb/db_bdb.cpp, src/blockchain_db/berkeleydb/db_bdb.h, src/blockchain_db/blockchain_db.h, src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h, src/blockchain_utilities/fake_core.h
Delete the hf tables, so the next open will rescan and regenerate
=> Fix hf when import with verify off

CMakeLists.txt, README.md, contrib/epee/include/console_handler.h, src/blockchain_db/berkeleydb/db_bdb.cpp, src/common/int-util.h, src/crypto/crypto.cpp, src/crypto/oaes_lib.c, src/crypto/slow-hash.c, src/crypto/tree-hash.c, tests/performance_tests/performance_utils.h, tests/unit_tests/slow_memmem.cpp
I've added OpenBSD support for Monero and have included detailed build instructions too.
=> OpenBSD support for Monero

contrib/epee/include/net/http_client.h, src/common/varint.h, src/serialization/serialization.h
Hi,
just a small fix of a typo in a comment.
All the Best
hkopp/cryptobunny
=> fixed typo

external/db_drivers/liblmdb/mdb.c
Just check the requested page, don't worry about any other pages
=> MDB_VL32 change overflow page scan

src/wallet/wallet2.cpp
This reverts commit 58f890652e86039e98dff2d48d217c9ea9e84eca, reversing
changes made to 39d73d2a27730e6a5844c259d81a0ed9d4ee3000.
=> Revert "Merge pull request #632"

tests/core_tests/v2_tests.cpp, tests/core_tests/v2_tests.h
Forgot to add them before commit
=> Add the new test files

src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h
Larger safety margin for small batch sizes
=> Win32import

external/db_drivers/liblmdb/lmdb.h, external/db_drivers/liblmdb/mdb.c
=> Resync with mdb.master

src/blockchain_db/berkeleydb/db_bdb.cpp
Support blockchain_import --drop-hard-fork command.
Check if hard fork subdbs need reset.
These are for safety and debugging, matching behavior of BlockchainLMDB.
=> BlockchainBDB: Hard fork updates 

src/common/dns_utils.cpp
The second parameter to ub_ctx_set_fwd is not const until recently.
=> dns_utils: compatibility with older libunbound

tests/unit_tests/address_from_url.cpp
=> unit_tests: update test openalias address

src/blockchain_db/lmdb/db_lmdb.cpp
Other changes remain.
The parts reverted should be added back with schema updates.
=> Revert comparators

src/blockchain_db/lmdb/db_lmdb.cpp
=> More for df239428c0f43e2664f2be273996a734ca12c686

src/blockchain_db/lmdb/db_lmdb.cpp
We don't need it now with per-txn cursors.
=> Get rid of lmdb_cur

tests/unit_tests/hardfork.cpp
Match changed BlockchainDB function declaration.
=> unit_tests: fix hard fork unit test compilation

src/wallet/wallet_rpc_server.cpp
Add support for short/integrated/encrypted IDs to get_payments RPC
=> get_payments short ID

src/blockchain_db/lmdb/db_lmdb.cpp
=> More for bdec7cb

src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h
Fix SIGBUS from misaligned uint64_t references
=> avoid some val copies

src/wallet/CMakeLists.txt, src/wallet/wallet2.cpp, src/wallet/wallet2.h, src/wallet/wallet2_api.cpp, src/wallet/wallet2_api.h, src/wallet/wallet_errors.h, tests/CMakeLists.txt, tests/crypto/CMakeLists.txt, tests/libwallet_api_tests/CMakeLists.txt, tests/libwallet_api_tests/main.cpp
not sure if I placed tests for libwallet_api to the right place (tests/libwallet_api_tests) - please correct me if I'm wrong
=> libwallet public api (in progress)

contrib/epee/include/net/abstract_tcp_server2.inl
Also close sockets on failure, just in case
=> epee: fix potential hang on exit

tests/core_tests/chaingen.h
=> core_tests: fix compile failure with GCC 4.8.4

src/cryptonote_core/tx_pool.cpp, src/cryptonote_core/tx_pool.h
tx_pool.h doxygen documentation completed.
Many notes made on areas for improvement, be that functionality or
code clarity.
Commented code and unused code removed.
=> Transaction pool documentation (and some cleanup)

src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h
=> add blockhashing blob to getblocktemplate

src/simplewallet/simplewallet.cpp
When present, it can be used to validate the keys, as well
as deduce the spend key, if it is absent (watch wallet).
=> simplewallet: optional address in --generate-from-json

src/simplewallet/simplewallet.cpp, src/wallet/wallet2.cpp, src/wallet/wallet2.h
Don't prompt for restore-height on generate-new-wallet
=> Fix 19fe8ae3ef1aa46ae8fdd4e4d6862510390ddab7

README.md
Per this comment from @hyc on reddit:
https://www.reddit.com/r/Monero/comments/4cfcy2/how_can_i_connect_simplewallet_over_tor/d1q6vc6
Credits to @hyc for the text as well.
=> Update README with TAILS instructions

README.md
Help the user, so that they don't have to go look at the code and figure out that boost program options component is used, and then go look that up...
=> readme: notes on config file and fg/bg run mode

contrib/epee/include/string_tools.h, src/p2p/net_node.inl
=> allow peers without port

src/blockchain_db/berkeleydb/db_bdb.cpp, src/blockchain_db/berkeleydb/db_bdb.h, src/blockchain_db/blockchain_db.h, src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h, src/blockchain_utilities/blockchain_dump.cpp, src/cryptonote_core/hardfork.cpp, src/cryptonote_core/hardfork.h, tests/unit_tests/hardfork.cpp
It's not really needed, it used to be an optimization for when
that code was not using the db and needed to recalculate things
fast on startup.
=> remove hf_starting_height db

tests/hash-target.cpp
=> Tests: fix signed/unsigned comparison in hash-target

src/simplewallet/simplewallet.cpp, src/wallet/wallet2.cpp, src/wallet/wallet2.h, src/wallet/wallet_rpc_server.cpp, src/wallet/wallet_rpc_server_commands_defs.h
Shown in show_transfers simplewallet command, and get_transfers
RPC command, if req.pool is true.
=> wallet: add unconfirmed incoming txes from the txpool

src/cryptonote_core/hardfork.cpp
=> hardfork: fix off by one in rescaning fork state after restart

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h
The init section still has some room for cleanup if anyone is interested. :smile:
=> fix restore-deterministic height

external/db_drivers/liblmdb/mdb.c
Plug rpage leak in cursor_set
I can confirm that blockchain_import proceeds further than before. It's still running, so I don't know yet if it will import the whole chain successfully, will report more when it finishes.
=> More for Issue #855

.travis.yml, CMakeLists.txt
=> Build: libstdc++ for clang < 3.7 + boost 1.58 for Travis CI

src/wallet/wallet2.cpp
Reported by RaskaRuby, tested by iDunk5400.
=> wallet: fix build on Mac and Windows (missing include)

README.md
=> readme: clarify conf syntax, format deps into list, decrease logo size

src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_protocol/cryptonote_protocol_handler.inl
=> Fix fake 'network synchronized, begin using' messages

src/cryptonote_core/cryptonote_core.cpp
=> Change default db-sync-mode to fast, not fastest

src/common/command_line.cpp
Missed another place where default syncmode was set
=> More for PR#999

src/wallet/wallet2.cpp
If picking coinbase outputs, those are locked for a longer time
than other outputs, so we ask for more of those
=> wallet: fix not finding enough rct fake outputs

src/cryptonote_protocol/cryptonote_protocol_handler.inl
Fix for issue #591
sync status message in daemon is using v1 block time
=> Show correct amount of days behind/ahead while syncing

src/daemon/command_parser_executor.cpp, src/daemon/command_server.cpp
Fixes the help output for the actual usage of start_mining command
=> Fix upstream issue#1020

Dockerfile, README.md
=> Added basic docker file

README.md
Anyone know if ldns, BDB, expat are current?
=> readme: organize deps into table

.travis.yml, CMakeLists.txt, Makefile, tests/CMakeLists.txt
Make coverage completely optional.
Also, let's see if this ARGS works for excluding tests.
=> cmake: coverage option

CMakeLists.txt, external/unbound/CMakeLists.txt, src/wallet/CMakeLists.txt
Fix one more linkage issue for GUI. Build tested on mac os (el capitan), Windows (msys2/mingw-64) and Ubuntu 16.04 x64
=> gui/libwallet_merged: libunbound is one more dependency

CMakeLists.txt
=> cmake: handle dists which prefix gcc binaries wth arch triplet

src/daemon/rpc_command_executor.cpp
Removed cast since difficulty does not fit in int any more.
=> Daemon: fix hashrate display in diff command output

README.md
bitmonero --> monero
Addresses #1059
=> Fix homebrew formula for OS X

src/cryptonote_config.h, src/wallet/wallet2.cpp, src/wallet/wallet2.h
The wallet will start using that fee about two weeks after hard
fork 3, when most people will likely have updated their daemons.
=> Decrease minimum fee from 0.01/kB to 0.002/kB

src/crypto/slow-hash.c
More than twice as fast as plain C code. Note that both ARMv7 and
ARMv8 can be further improved with better use of NEON.
Also tweak ARMv7 multiplier
Someone please test ARMv7 with asm before merging this, thanks.
=> Add ARMv8-A AES support

src/daemon/main.cpp
Helps with investigating bug reports
=> daemon: log version when starting

README.md
Functionality handled by pacman
=> removed deprecated update-core

src/daemon/rpc_command_executor.cpp
=> daemon: report status at 99.9% rather than 100% when not quite synced

src/daemon/executor.cpp
Just making things a bit clearer for people reviewing the logs
=> Improving daemon startup log message

README.i18n
=> Small typo in README.i18n

src/cryptonote_core/blockchain.cpp, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/miner.cpp, src/cryptonote_core/tx_pool.cpp, src/cryptonote_protocol/cryptonote_protocol_handler.inl, src/daemon/protocol.h
Better step-wise logging for future debugging
=> Added log messages to reflect deactivation procedure

src/wallet/api/wallet.cpp, src/wallet/api/wallet.h, src/wallet/wallet2.cpp, src/wallet/wallet2.h, src/wallet/wallet2_api.h
Used in GUI for displaying daemon sync progress.
=> wallet2_ap & libwallet_api: added Wallet::daemonBlockChainTargetHeight()

src/rpc/core_rpc_server.cpp
fixes build error after https://github.com/monero-project/monero/pull/1149
=> Fix build error in core_rpc_server

README.md
With dashes in the dates and the markdown code aligned to make cows happy. :)
=> Hard fork info in the Readme

.gitignore, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/daemon/command_parser_executor.cpp, src/daemon/command_parser_executor.h, src/daemon/command_server.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server.h, src/rpc/core_rpc_server_commands_defs.h
Added a print_coinbase_tx_sum option
=> Command to to calculate the total of all coinbase transactions so far #1196

src/simplewallet/simplewallet.cpp, src/wallet/wallet2.h
Added a confirmation step when creating a new wallet, and the option to `exit` during the procedure with improved user notification.
Closing #1189 
Apologies for the two commits, still no git expert and it looks like changing the name of the branch locally didn't quite have the effect I was expecting.
=> Improve wallet naming behaviour

src/wallet/wallet2.cpp, src/wallet/wallet2.h
Have split #1212 back into two so I can address each separately
=> Always confirm transfers now defaults to ON

contrib/rlwrap/monerocommands_bitmonerod.txt, src/daemon/command_parser_executor.cpp, src/daemon/command_parser_executor.h, src/daemon/command_server.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h
Helps see what's going on now that Monero is getting used
Need https://github.com/monero-project/monero/pull/1247 first.
=> daemon: add a print_pool_stats daemon command

src/simplewallet/simplewallet.cpp
Factor locked_transfer into transfer_main, which brings various
improvements for free (multiple addresses, proper detection of
multiple payment ids, obeying the prompt settings).
Also fix a few things, such as using uint64_t instead of int
for block heights, actually checking whether getting blockchain
height succeeded, etc.
=> simplewallet: factor locked_transfer, and fix a few rough edges

src/daemon/rpc_command_executor.cpp
=> daemon: fix min/max tracking using the wrong size

CMakeLists.txt
Added line to CMakeLists.txt which might aid in debugging
=> Report Boost library version during compilation

contrib/epee/include/storages/levin_abstract_invoke2.h
Tiny change, but with more 'Unknown error 1007' appearing with fluffy blocks, this one was making my eye twitch...
=> Unkonown -> unknown

Makefile, README.md
All changed for consistency :)
And simplified description in README.md
=> Changed ARM6/7/8 to ARMv6/7/8 to be nice to peronero

README.md
Brushed off my dusty old RPi 2, fiddled for a couple of days and came up with the way to build successfully
=> Add instructions to README.md for building on the Raspberry Pi 2

src/cryptonote_core/cryptonote_format_utils.cpp, src/cryptonote_core/cryptonote_format_utils.h, src/wallet/wallet2.cpp, src/wallet/wallet2.h
As mentioned, it's about 33% faster using 25% less CPU than before on my i7 6700 SSD machine when syncing from block 800,000. More testing would be appreciated.
Someone can also fix the tests if they want. :)
=> Refresh optimization

src/wallet/api/wallet.cpp, src/wallet/api/wallet.h, src/wallet/wallet2_api.h
Based with moneromooo's PR's to avoid conflicts while testing. 
Will rebase later.
=> Wallet API: added getTxKey()

src/wallet/api/wallet.cpp
fixes https://github.com/monero-project/monero-core/issues/116
=> Wallet API: Pause refresh while creating transaction

src/common/thread_group.cpp
See https://github.com/monero-project/monero/pull/1291
=> thread_group: fix build with asserts enabled

src/wallet/wallet2.cpp
=> wallet: fix corner case of no recent outputs available

src/wallet/api/wallet.cpp, src/wallet/api/wallet.h
fixes https://github.com/monero-project/monero-core/issues/139
=> Wallet API: fix broken cache file rebuild in GUI

.gitignore, src/wallet/wallet2.cpp
Clamps user supplied restore height to daemon blockchain height.
=> monero-wallet-cli: Stop refresh when top block is reached #1190

contrib/epee/include/console_handler.h
Thanks to duckduckgo and the internet.
This might even compile.
=> epee: blind attempt to fix exit hang on windows

src/cryptonote_core/blockchain.cpp, src/cryptonote_core/blockchain.h, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server.h, src/rpc/core_rpc_server_commands_defs.h, src/wallet/wallet2.cpp
Someone apparently needs that to make a wallet but never asked.
If you read that and that's not what you wanted, the bugtracker
is at https://github.com/monero-project/monero/issues
=> rpc: add output indices to gettransactions

README.md
Very basic start, but something to be built on.
Also useful for #1354
=> Instructions for debugging LMDB crashes taken from #1360

src/cryptonote_core/cryptonote_basic_impl.cpp
https://github.com/monero-project/monero-core/issues/211
=> change 'invalid address format' loglevel

src/wallet/api/wallet_manager.cpp, src/wallet/api/wallet_manager.h, src/wallet/wallet2_api.h
Blockchain height, version, Mining hash rate...
=> wallet_api: add a few daemon related getters

src/cryptonote_core/blockchain.cpp
If the block reward to use for the fee calculation can't be
calculated (should not happen in practice), use a high bound,
so we use a fee overestimate that will be accepted by the network.
=> blockchain: use high bound block reward on error where appropriate

src/common/stack_trace.cpp, src/cryptonote_core/blockchain.cpp, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_format_utils.cpp, src/cryptonote_core/tx_pool.cpp, src/cryptonote_protocol/cryptonote_protocol_handler.h, src/p2p/net_node.inl, src/wallet/api/wallet.cpp, src/wallet/wallet2.cpp, src/wallet/wallet2.h, src/wallet/wallet_rpc_server.cpp
Just a few typos I ran into while exploring the code. It's not much but hey, it still helps credibility.
=> Fix a few minor typos

external/miniupnpc/minihttptestserver.c
=> Spelling in errors

contrib/epee/include/net/munin_connection_handler.h
=> Spelling in errors (2)

.gitignore, src/wallet/wallet2.cpp
This reverts commit fd181b03bb58a8b0628d2af8637cf6bb968fc437.
https://github.com/monero-project/monero/pull/1197 can cause an infinite loop together with #1404
=> Remove infinite loop in refresh code

src/wallet/wallet2.cpp
=> wallet2: pass by const ref where possible

src/common/thread_group.h
vtnerd (original author) confirmed this is the Right Way.
=> thread_group: fix build on older GCC

README.md
modified all min and rec versions to v0.10.1 for v4 and v5 forks
=> modded minimum and recommended monero versions

src/ringct/rctSigs.cpp
And rangeProofs are on outputs...
=> Tx verification failing is not an error

src/simplewallet/simplewallet.cpp, src/wallet/password_container.cpp, src/wallet/password_container.h
Possibly other pedantry. Pedants are people too.
=> monero-wallet-cli wording changes 'n' stuff

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h
=> wallet cli: donate command

src/ringct/rctTypes.h
A proposed fix to the following issue: https://github.com/monero-project/monero/issues/1448
=> fix MGs json

README.md, src/simplewallet/simplewallet.cpp
Closes #1447. References #1451.
=> simplewallet: hardcode Monero's donation address + add return type, add note to README

src/simplewallet/simplewallet.cpp
=> simplewallet: add pending/pool/failed in the show_transfers help

tests/unit_tests/http_auth.cpp
See [this comment](https://github.com/monero-project/monero/pull/1444#issuecomment-268114458)
=> Fixes for google test < 1.8

src/cryptonote_core/cryptonote_core.cpp
It was counting things many, many times
=> core: fix recalculation of emission/fees

src/cryptonote_core/blockchain.cpp
Also miner tx hash to log level 1 (have you ever tried to find a testnet miner tx hash?)
=> add tx hash and mixin to time stats

src/crypto/tree-hash.c
Here is a basic algo that doesn't make your eyes bleed when you look at it.
More background, and other approaches to the problem can be found here - https://en.wikipedia.org/wiki/Find_first_set
I ran the core tests and passed successfully.  I had following test failures, but I don't think they have anything to do with me
unit_tests
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] DNSResolver.DNSSECSuccess
[  FAILED  ] AddressFromURL.Failure
libwallet_api_tests
Seg fault
=> Heard you had some trouble groking logarightms some time ago :)

external/boost/archive/portable_binary_iarchive.hpp, external/boost/archive/portable_binary_oarchive.hpp
Broken by d1d6e27ab661f71d90fb6530db84d5a2b92550a8
=> Fix multiple definition clash on ARMv7 build

src/wallet/api/wallet.cpp
Fixes: https://github.com/monero-project/monero-core/issues/363
=> Wallet API: prevent missing transactions in GUI

src/wallet/api/wallet.cpp, src/wallet/api/wallet.h, src/wallet/wallet2_api.h
Make parse_uri available to GUI
=> Add parse_uri to wallet2_api

src/wallet/wallet2.cpp, src/wallet/wallet2.h
=> Cold signing: make sure short payment id isnt encrypted twice

src/simplewallet/simplewallet.cpp
#1498 
Or, you know, make it prettier.
=> add msg for donate

CMakeLists.txt
Change from negative to positive tests
=> Change logic of testing for libunwind on OSX and ARM

src/cryptonote_core/blockchain.cpp
=> fix time stats mixin

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h, src/wallet/api/transaction_history.cpp, src/wallet/api/transaction_info.cpp, src/wallet/api/transaction_info.h, src/wallet/api/wallet.cpp, src/wallet/wallet2.cpp, src/wallet/wallet2.h, src/wallet/wallet2_api.h, tests/libwallet_api_tests/main.cpp
Callbacks needed for showing pool tx's in GUI + number of confirmations.
=> Wallet2 + API: Callbacks for unconfirmed transfers

src/wallet/api/address_book.cpp
Fixes https://github.com/monero-project/monero-core/issues/392
=> Wallet API: support integrated addresses in address book.

src/daemon/command_parser_executor.cpp, src/daemon/command_parser_executor.h, src/daemon/command_server.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h
About the tip of the main chain, and the last N blocks
=> rpc: add a command to get info about the current blockchain

src/cryptonote_core/blockchain.cpp, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/cryptonote_core/tx_pool.cpp, src/cryptonote_core/tx_pool.h, src/cryptonote_protocol/cryptonote_protocol_handler.inl, src/daemon/rpc_command_executor.cpp, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h, tests/core_proxy/core_proxy.cpp, tests/core_proxy/core_proxy.h, tests/core_tests/chaingen.h, tests/unit_tests/ban.cpp
Also print its value when printing pool
=> fix do_not_relay not preventing relaying on a timer

src/cryptonote_core/blockchain.cpp, src/cryptonote_core/cryptonote_core.cpp, src/ringct/rctSigs.cpp, src/ringct/rctSigs.h
Semantics can be checked early
=> rct: split rct checks between semantics and other

src/rpc/core_rpc_server_commands_defs.h
[suggested](https://github.com/monero-project/monero/pull/1569#discussion_r96114461) by @moneromooo-monero
=> rpc: macro to define core RPC version for avoiding future mistake

src/blockchain_db/blockchain_db.cpp
Was causing blocks just before hardfork to be checked as wrong version.
=> Fix PR#1506, off by one in chain height

src/p2p/net_node.h, src/p2p/net_node.inl
=> Limit incoming connections from the same IP

src/blockchain_db/lmdb/db_lmdb.cpp
resize messages should display by default. change unknown DB version to MWARNING from MINFO.
=> Tweak some msg loglevels

src/wallet/wallet2.cpp
This would have tried to send a second output to make the tx
look like the 2/2 ideal, but it would not fail to find one
because picking an output from preferred_inputs priority list
did not remove it from the unused tranfer/dust outputs, so
it would try to send the same output twice.
While there, I also added a check to avoid sending a second
input if it's related to the first. Better 1/2 than linking
inputs, I think.
=> wallet2: fix sending a rct tx with a single output available

external/easylogging++/easylogging++.h
Thanks to @moneromooo-monero's suggestion in #1595
=> Fixed a deadlock issue with easylogger++

src/common/CMakeLists.txt
Bug and fix reported by tdprime
=> comon: fix link error on at least one platform (no clue which one)

CMakeLists.txt
I am not sure about this one, but i can't figure out how to fix it with env variable. So maybe it is the right way to do it (cmake newbie).
=> cmake set atomic for android

src/wallet/api/wallet.cpp, src/wallet/wallet2_api.h
Didn't manage to use the MDEBUG macros inside Qt without adding a bunch of boost dependencies. 
@moneromooo-monero
=> Wallet API: Easylogger wrapper for GUI

src/wallet/wallet2.cpp, src/wallet/wallet2.h
I broke this very recently and didn't notice in time
=> wallet2: fix transactions not considering rct inputs

src/cryptonote_basic/miner.cpp, src/cryptonote_basic/miner.h, src/daemon/command_parser_executor.cpp, src/daemon/command_server.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h
my extremely poor attempt at background mining, definitely not ready for prime-time.
mostly throwing it up here for feedback/proof of concept/etc.
only works for linux, only tested on ubuntu.
"start_mining [addr] [thread_count] true"
feel free to point out any and all stupidity/terribleness, thanks everyone :)
=> background mining

src/blockchain_utilities/blockchain_export.cpp, src/blockchain_utilities/blockchain_import.cpp, src/blockchain_utilities/bootstrap_file.cpp
also move a couple logs from INFO to DEBUG
=> tools: set requested log level

src/cryptonote_core/tx_pool.cpp
=> tx_pool: revert template filling changes

tests/libwallet_api_tests/CMakeLists.txt, tests/libwallet_api_tests/main.cpp, tests/net_load_tests/CMakeLists.txt, tests/net_load_tests/clt.cpp, tests/net_load_tests/srv.cpp, tests/unit_tests/CMakeLists.txt, tests/unit_tests/epee_boosted_tcp_server.cpp, tests/unit_tests/epee_levin_protocol_handler_async.cpp
@danrmiller lets watch the win32 build.
=> switch to boost::thread for mingw build

src/cryptonote_protocol/cryptonote_protocol_handler.inl
- only pause mining once we've got the lock (in practice, it'll
already be paused by another thread if we can't get the lock
at once though)
- do not call prepare_handle_incoming_blocks when we dismissed
all the blocks, it only causes cleanup_handle_incoming_blocks
to complain afterwards
=> cryptonote_protocol: tweaks to the syncing speedup

src/blockchain_db/blockchain_db.cpp, src/blockchain_db/blockchain_db.h, src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h, src/cryptonote_core/blockchain.cpp, src/cryptonote_core/blockchain.h, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/cryptonote_protocol/cryptonote_protocol_handler.inl, src/rpc/core_rpc_server.cpp, tests/core_proxy/core_proxy.h, tests/unit_tests/ban.cpp, tests/unit_tests/hardfork.cpp
This speeds up operations such as serving blocks to syncing peers
=> blockchain_db: add "raw" blobdata getters for block and transaction

src/simplewallet/simplewallet.cpp
=> Add support for smart mining through wallet.

src/common/updates.cpp, src/common/updates.h, src/cryptonote_core/cryptonote_core.cpp
The files are hashed and the hashes signed
=> updates: use HTTP, not HTTPS

src/wallet/wallet_rpc_server.cpp, src/wallet/wallet_rpc_server.h, src/wallet/wallet_rpc_server_commands_defs.h
and remove trusted_daemon fields from transfer RPCs,
it is much friendlier on users
=> wallet_rpc_server: new --trusted-daemon flag

src/daemon/command_parser_executor.cpp, src/daemon/command_parser_executor.h, src/daemon/command_server.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server.h, src/rpc/core_rpc_server_commands_defs.h
subcommands "check", "download", and "update".
update is not yet implemented.
=> daemon/rpc: updates command and RPC

src/cryptonote_protocol/cryptonote_protocol_handler-base.cpp
=> protocol: tone down a rate limit not implemented yet warning

src/blockchain_db/blockchain_db.h, src/cryptonote_basic/CMakeLists.txt, src/cryptonote_core/CMakeLists.txt, src/cryptonote_core/blockchain.h, src/cryptonote_core/hardfork.cpp, src/cryptonote_core/hardfork.h, src/daemon/rpc_command_executor.cpp, tests/unit_tests/hardfork.cpp
should fix a cross dependency betewen cryptonote_basic and
blockchain_db
=> core: move hardfork back to cryptonote_core

src/wallet/api/wallet_manager.cpp, src/wallet/api/wallet_manager.h, src/wallet/wallet2_api.h
Fixes https://github.com/monero-project/monero-core/issues/501
=> wallet api: add missing mining options

src/blockchain_utilities/blockchain_import.cpp
Incomplete ifdef cleanup in 9e82b694da120708652871b55f639d1ef306a7ec
=> Fix double-import

src/cryptonote_basic/cryptonote_format_utils.cpp
Fix two small typos as mentioned by reddit user nthterm.
=> format_utils: fix typo in assert message

src/simplewallet/simplewallet.cpp, src/wallet/wallet2.cpp, src/wallet/wallet2.h
Also tweak wallet2 password code to verify password without
saying it's a new wallet, because it's assuming things.
=> wallet: add password command

README.md
changed hard forking to hard fork and fixed date format
=> Improved wording in hard fork schedule section

src/cryptonote_protocol/cryptonote_protocol_handler.inl
=> protocol: fix wrong tx being looked up from fluffy block

README.md
As discussed with @moneromooo-monero added hint on how to configure jails in FreeBSD to get monero running.
=> Added hint to adjust jail configuration to readme for FreeBSD

src/wallet/wallet_rpc_server.cpp
Address book modification, setting tx nodes, importing key images
=> wallet_rpc_server: make a few RPCs unavailable in restricted mode

src/simplewallet/simplewallet.cpp
Those can create unsigned transactions
=> simplewallet: allow setting tx priority in watch wallets

contrib/epee/include/md5_l.inl, contrib/epee/include/net/levin_protocol_handler_async.h, contrib/epee/include/net/net_utils_base.h, contrib/epee/include/string_tools.h, contrib/epee/src/CMakeLists.txt, contrib/epee/src/string_tools.cpp, src/cryptonote_core/blockchain.h, tests/unit_tests/CMakeLists.txt, tests/unit_tests/epee_utils.cpp
Now less boost/asio in your headers.
=> Removed boost/asio.hpp include from epee/string_tools.h

src/daemon/executor.cpp, src/daemon/executor.h, src/daemonizer/posix_daemonizer.inl
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
=> create a foreground non-interactive mode

README.md
=> Updated Readme for v5/v6 hardfork

contrib/epee/src/string_tools.cpp
I hope the freebsd build goes green ...
=> Fix freebsd build

src/ringct/rctOps.cpp
Avoids scaring people when seeing some invalid txes
=> ringct: move ge_frombytes_vartime failure error to warning

src/cryptonote_basic/cryptonote_basic.h, src/cryptonote_basic/cryptonote_format_utils.cpp
Would be nice to have someone to try this, who had the previous version break :)
=> core: fix blob size cache, and reenable hash and blob size caches

external/easylogging++/easylogging++.cc
#1693 didn't survive easylogging update
Opened issue upstream https://github.com/muflihun/easyloggingpp/pull/530
Edit: Issue merged upstream
=> Easylogging: fix android build

external/easylogging++/ea_config.h
ELPP_STACKTRACE_ON_CRASH doesn't look used anymore
=> Easylogging: remove unused config def

src/cryptonote_config.h, src/p2p/net_node.h, src/p2p/net_node.inl, src/p2p/net_peerlist.h, src/p2p/net_peerlist_boost_serialization.h, src/p2p/p2p_protocol_defs.h
Based on https://eprint.iacr.org/2015/263.pdf 4. Anchor connections.
Peer list serialisation version bumped to 5.
Reviews and suggestions are welcome.
=> Add anchor connections

README.md
Just linking the reference to the README.i18n file.
=> Linking i18n internationalization file

README.md
@hyc are you going to add your instructions for the RPi 1?
=> Update README.md instructions for Boost 1.64 and a little bit of formatting

external/easylogging++/CMakeLists.txt
Required after recent updates to easylogging
=> GUI: easylogging++ install target

src/blockchain_db/blockchain_db.h, src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h, src/blockchain_utilities/blockchain_import.cpp, src/blockchain_utilities/fake_core.h, src/cryptonote_core/blockchain.cpp, src/cryptonote_core/blockchain.h, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/cryptonote_core/tx_pool.cpp, src/cryptonote_core/tx_pool.h, src/cryptonote_protocol/cryptonote_protocol_handler.inl, src/rpc/core_rpc_server.cpp, tests/core_proxy/core_proxy.h, tests/core_tests/chaingen.h, tests/unit_tests/ban.cpp, tests/unit_tests/hardfork.cpp
I'll be using that on my mainnet node for a while to see if anything breaks, but looks fine on testnet + passes tests.
=> move txpool to database

src/wallet/wallet2.cpp
=> fix get_upper_transaction rename

contrib/epee/src/CMakeLists.txt
Missed a crypto -> cncrypto rename
=> Fix PR#2039

src/crypto/slow-hash.c
Fix #1991 . For some reason it doesn't work when inlined, and newer gcc always
tried to inline it.
Obviously a longer term fix would be to find out why the inlined version doesn't work. I've spent some time poking at it but couldn't figure it out yet; this at least gets it working for now.
=> Fix asm multiply again

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h
This is trivial, but often requested, and possibly hard to do
in Windows. That makes it more user friendly.
=> simplewallet: new command to generate a random payment id

src/blockchain_db/blockchain_db.h, src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h, src/cryptonote_core/blockchain.cpp, src/cryptonote_core/blockchain.h, src/cryptonote_core/tx_pool.cpp, tests/unit_tests/hardfork.cpp
Avoids exception spam for the "nope, not found" case
=> blockchain_db: add a txpool tx getter which returns existence

src/crypto/crypto.cpp, src/crypto/crypto.h, src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h
This is a refined version of PR #1943. Its follow-up PR #1945 was taken down after a private discussion with @luigi1111.
```
[wallet 42vPNJ]: get_tx_proof 23d4a5075d7272f305036103da70526d224c083ac73c2756e80049e6aad3214f 44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A
Signature: ProofV1ihLMTQQFuaoH6GiBnu5PzZ2hhocmMZDMpHQWEXLB7HqBKNYXFbUASND7k3J3hCAgk2NocW2jxQ3Ngd4vWGCez1pFXMUc5bt7snVfiWH2ohzF1H7m1RThkuVZqRvYASMENuni
[wallet 42vPNJ]: check_tx_proof 23d4a5075d7272f305036103da70526d224c083ac73c2756e80049e6aad3214f 44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A ProofV1ihLMTQQFuaoH6GiBnu5PzZ2hhocmMZDMpHQWEXLB7HqBKNYXFbUASND7k3J3hCAgk2NocW2jxQ3Ngd4vWGCez1pFXMUc5bt7snVfiWH2ohzF1H7m1RThkuVZqRvYASMENuni …
```
=> Proof of payment by only revealing key derivation, not the actual tx secret key

README.i18n.md
Per #2069 - This adds the markdown formatting.
=> Formatting README.i18n.md as Markdown.

contrib/epee/include/net/levin_protocol_handler_async.h
Due to bad refactoring in PR #2073.
timeout_handler() doesn't work as a virtual function.
=> Fix issue #2119 SEGV

contrib/epee/src/readline_buffer.cpp
=> Add notification on stop of readline_buffer

contrib/epee/include/console_handler.h, contrib/epee/include/readline_buffer.h, contrib/epee/src/readline_buffer.cpp, src/simplewallet/simplewallet.cpp
Most notably is the addition of tab completion for command entry. Also other glitches fixed.
- Add missing unbind key
- Fix colored messages
- Add command completion
- Preserve last command input
- Fix cursor position issues
=> Add various readline related fixes and improvments

src/cryptonote_basic/miner.cpp
Fixes #2143
Includes fixes from PR #2144
=> fix on_battery_power for linux

translations/monero.ts, translations/monero_fr.ts, translations/monero_it.ts
This PR update the _monero.ts_ file and add the file _monero_it.ts_ containing the italian translation.
_monero.ts_ updated using 'lrelease'
_monero_it.ts_ checked with linguist and built with 'lupdate'
15/499 lines left untranslated
=> Italian translation + update monero.ts

cmake/FindMiniupnpc.cmake
The version of miniupnpc in external/ uses API version 16, but the
code also seems to work for API version 10. Also remove detection
of older unsupported versions.
This fix allowed the detection of version 1.9.20140610 on Debian testing. WIth the Debian libminiupnpc-dev package installed it uses that, without the package installed, it uses the in-tree version.
This should be reviewed by someone who knows CMake better than me.
=> cmake: Update detection of external miniupnpc

src/simplewallet/simplewallet.cpp, src/wallet/wallet2.cpp, src/wallet/wallet2.h, src/wallet/wallet_rpc_server.cpp, src/wallet/wallet_rpc_server_commands_defs.h
also show it in simplewallet's show_transfer
=> wallet: return unlock_time in get_transfers

src/cryptonote_core/blockchain.cpp
We want to know what happened when a block is wrongly rejected
=> blockchain: log more info when we reject an orphan

src/wallet/wallet2.cpp
As reported by jaquee, the calculation could underflow for very
low heights.
Additionally, we now use the target height too.
=> wallet2: improve refresh height determination

contrib/epee/src/mlog.cpp, src/p2p/net_node.inl
This should prevent "silent" failures to start
=> Tweak net logs so we get more info on why networking can't start

src/cryptonote_core/blockchain.cpp, src/cryptonote_core/blockchain.h, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/cryptonote_protocol/cryptonote_protocol_defs.h, src/cryptonote_protocol/cryptonote_protocol_handler.inl, tests/core_proxy/core_proxy.h, tests/unit_tests/ban.cpp
=> protocol: pass blockchain cumulative difficulty when syncing

contrib/epee/include/readline_buffer.h, contrib/epee/src/readline_buffer.cpp
Attempting to fix #2298 and #2217
=> Readline fixes

contrib/epee/include/string_tools.h, contrib/rlwrap/monerocommands_bitmonerod.txt, src/common/thread_group.cpp, src/crypto/crypto.cpp, src/cryptonote_protocol/block_queue.cpp, src/cryptonote_protocol/block_queue.h, src/cryptonote_protocol/cryptonote_protocol_handler.h, src/cryptonote_protocol/cryptonote_protocol_handler.inl, src/daemon/rpc_command_executor.cpp, src/p2p/net_node.inl, src/p2p/p2p_protocol_defs.h
It could happen if a connection went into standby mode, while
it was the one which had requested the next span, and that span
was still waiting for the data, and that peer is not on the
main chain. Other peers can then start asking for that data
again and again, but never get it as only that forked peer does.
=> cryptonote_protocol: fix sync wedge corner case

src/cryptonote_core/tx_pool.cpp
=> tx_pool: fix crash in stats

src/blockchain_db/blockchain_db.cpp, src/blockchain_db/blockchain_db.h, src/blockchain_db/db_types.h, src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_utilities/blockchain_export.cpp, src/blockchain_utilities/blockchain_import.cpp, src/blockchain_utilities/blocksdat_file.h, src/common/command_line.cpp, src/cryptonote_core/cryptonote_core.cpp, src/daemon/main.cpp, src/debug_utilities/CMakeLists.txt, tests/core_proxy/CMakeLists.txt, tests/fuzz/CMakeLists.txt, tests/unit_tests/hardfork.cpp
Hide LMDB-specific stuff behind blockchain_db.h. Nobody besides blockchain_db.cpp
should ever be including DB-specific headers any more.
=> DB cleanup

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h, src/wallet/wallet2.cpp, src/wallet/wallet2.h
including expected transaction backlog at different priorities
=> simplewallet: new "fee" command to display fee information

external/boost/archive/portable_binary_oarchive.hpp, src/simplewallet/simplewallet.cpp
=> Silence stupid fallthru warning in gcc 7

src/daemon/rpc_command_executor.cpp
=> Use latest height for fork date estimate v0.11

external/db_drivers/liblmdb/mdb.c
=> ITS#8728 fix MDB_VL32 freeing overflow page

src/cryptonote_core/blockchain.cpp, src/cryptonote_core/blockchain.h, src/rpc/core_rpc_server.cpp
Changes to the core code to make things cleaner and make using the core code for the new zmq rpc nicer.
I was asked to separate these changes into their own PR, so here we are.
=> DRY changes

CONTRIBUTING.md
As discussed in `#monero-dev`, inspired by https://github.com/monero-project/monero-site/pull/292#issuecomment-315559220.
IIRC, @moneromooo-monero may also want revisions to the existing C4.
=> Docs: add C4 and C4 addendum

src/daemon/command_server.cpp
clarification of required parameter for bc_dyn_stats
=> clarification bc_dyn_stats

src/wallet/wallet2.cpp
=> Update wallet2.cpp for misspelling

src/cryptonote_core/tx_pool.cpp
instead of just failing
This is a workaround for bad tx blobs being inserted in the
pool for unknown reasons
=> tx_pool: drop invalid txes from the pool on startup

src/cryptonote_basic/cryptonote_format_utils.cpp, src/cryptonote_basic/cryptonote_format_utils.h, src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h, src/wallet/wallet2.cpp, src/wallet/wallet2.h
This uses luigi1111's CN_Add method.
See https://xmr.llcoins.net for details.
=> wallet: add encrypted seed functionality

src/common/util.cpp, src/common/util.h, src/wallet/wallet_rpc_server.cpp, src/wallet/wallet_rpc_server.h
Partially mitigates https://github.com/monero-project/monero/issues/1768
=> Do not create file when wallet RPC user/pass is given and use file locking

README.md
Remove rlwrap info from README
=> Readline is now supported directly

src/blockchain_db/blockchain_db.h, src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h, src/blockchain_utilities/blockchain_import.cpp, src/blockchain_utilities/bootstrap_file.cpp, src/blockchain_utilities/bootstrap_file.h, src/cryptonote_core/blockchain.cpp, tests/unit_tests/hardfork.cpp
=> Use actual batch size for resize estimates

README.md
Aligned table for all you terminal knuckleheads and tried to better explain the schedule and what a user needs to do
=> README Network Consensus Protocol Upgrade Table

CMakeLists.txt
I think this should fix #2402 please test and feedback
=> Fix OpenSSL 1.1 detection for static builds

src/cryptonote_core/cryptonote_tx_utils.cpp
=> core: undo output sorting

contrib/epee/include/net/levin_protocol_handler_async.h
close might end up dropping a ref, ending up removing the
connection from m_connects, as the lock is recursive. This'd
cause an out of bounds exception and kill the idle connection
maker thread
=> epee: keep a ref to a connection we're deleting

external/db_drivers/liblmdb/mdb_load.1, external/db_drivers/liblmdb/mdb_load.c
To allow reloading of custom-sorted DBs from mdb_dump
=> Add -a append option to mdb_load

README.md
We don't have to compile boost by ourselves anymore!
=> Update Raspberry Pi build instructions

src/cryptonote_core/cryptonote_core.cpp, src/rpc/core_rpc_server.cpp
rather than in the same directory as the prebuilt versions
=> Source updates are in a source subdirectory

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h, src/wallet/wallet2.cpp, src/wallet/wallet2.h
=> simplewallet: allow to set threshold before warning about tx backlog

README.md
As requested reopened  #2464 on master branch.
=> README.md: fix portable binaries build targets

src/cryptonote_core/cryptonote_tx_utils.cpp, src/cryptonote_core/cryptonote_tx_utils.h, src/wallet/wallet2.cpp
=> construct_tx_and_get_tx_key: return sorted sources for print_ring_memebrs to work properly

src/blockchain_utilities/blockchain_import.cpp, src/blockchain_utilities/blocksdat_file.cpp, src/blockchain_utilities/blocksdat_file.h, src/cryptonote_config.h, src/cryptonote_core/blockchain.cpp, src/cryptonote_core/blockchain.h, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/cryptonote_protocol/cryptonote_protocol_handler.inl, tests/core_proxy/core_proxy.h, tests/unit_tests/ban.cpp
This shaves a lot of space off binaries
=> precomputed block hashes are now in blocks of N (currently 256)

README.md
AUR request finally completed.
=> readme: update Arch/AUR pkg name; post-rebranding

src/simplewallet/simplewallet.cpp
Also mention those options in the start_mining help line
=> simplewallet: allow 1/yes/y as well as true for start_mining options

README.md, src/common/dns_utils.cpp, src/common/dns_utils.h, tests/unit_tests/dns_resolver.cpp
=> dns_utils: allow an optional DNS server IP in DNS_PUBLIC

CMakeLists.txt, contrib/epee/include/net/http_client.h, contrib/epee/include/net/net_helper.h, contrib/epee/include/storages/http_abstract_invoke.h, contrib/epee/include/storages/portable_storage_val_converters.h, contrib/epee/include/string_tools.h, src/cryptonote_basic/cryptonote_format_utils.cpp, src/cryptonote_basic/cryptonote_format_utils.h, src/rpc/core_rpc_server_commands_defs.h, src/wallet/api/transaction_history.cpp, src/wallet/api/wallet.cpp, src/wallet/api/wallet.h, src/wallet/wallet2.cpp, src/wallet/wallet2.h, src/wallet/wallet2_api.h
Adds support for MyMonero and OpenMonero to Wallet2 and Wallet API. 
- added SSL support to epee http_client, required by mymonero
- Implemented all mymonero/openmonero api endpoints
- Tested successfully with monero GUI on Mac, iPhone and Android. Will PR the corresponding updates to GUI repo soon^tm. 
Todo: Simplewallet support
Happy midsummer!
=> Lightwallets (openMonero/myMonero)

README.md
The package has recently been accepted in the repository, voidlinux/void-packages@637c8a1cd5d0bd9eda5489b5b7f5561accf04a77 .
=> README: Add package installation instructions for Void Linux

src/daemon/command_parser_executor.cpp
And any other exception, just to be safe
=> daemon: catch out of range exceptions too when calling stoll

src/daemon/command_parser_executor.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h
Makes debugging tx verification easier
=> daemon: use @N syntax to output_histogram for specific amounts

contrib/epee/include/misc_log_ex.h, contrib/epee/include/net/abstract_tcp_server2.inl, contrib/epee/src/mlog.cpp, src/blockchain_db/lmdb/db_lmdb.cpp
Level 1 logs map to INFO, so setting log level to 1 should
show these. Demote some stuff to DEBUG to avoid spam, though.
=> frob level 1 logs a bit for consistency

src/cryptonote_protocol/cryptonote_protocol_handler.inl
This is safer, as we don't risk break expectations (eg, requesting
block hashes and then receiving a late set of blocks). Dropping a
connection means another will be attempted in a fresh state.
Also bump the kick timeout to 5 minutes, to ensure we only kick
really idle peers.
=> protocol: kick idle peers by dropping them

tests/unit_tests/sha256.cpp
=> unit_tests: fix build on windows

src/cryptonote_core/cryptonote_tx_utils.cpp, src/cryptonote_core/cryptonote_tx_utils.h, tests/core_tests/block_validation.cpp, tests/core_tests/chaingen.cpp, tests/core_tests/double_spend.inl, tests/core_tests/integer_overflow.cpp, tests/core_tests/transaction_tests.cpp, tests/core_tests/v2_tests.cpp, tests/performance_tests/ge_frombytes_vartime.h, tests/performance_tests/is_out_to_acc.h
=> tests: fixes for performance_tests and core_tests after subaddress patch

src/rpc/message.cpp
JSON-RPC 1.0/2.0 indicates that the field name is "result" and not "response". The entire object returned is referred to as the "response object" which was probably the source of the confusion.
@tewinget did I get all cases? Are there any tests to update for this? This will break anyone using this on the master branch.
=> Fix JSON-RPC response object over ZMQ

tests/README.md, tests/unit_tests/crypto.cpp
Wrote some basic documentation for running and writing Monero tests.
Included a Keccak unit test as an example for writing tests.
=> Test documentation & Keccak unit test

src/rpc/core_rpc_server.h
It's pretty slow and I/O intensive
=> rpc: make get_coinbase_tx_sum a restricted RPC

tests/unit_tests/CMakeLists.txt, tests/unit_tests/subaddress.cpp
Unit test that provides the test harness, and a basic initialization of a subaddress account.
=> Subaddress unit tests

src/common/command_line.cpp, src/common/command_line.h, src/simplewallet/simplewallet.cpp
=> simplewallet: reject invalid argument for boolean parameter

src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h
As per asked on Reddit: https://redd.it/7928r0
=> rpc: added miner_tx_hash to resp of getblock

src/rpc/core_rpc_server.cpp
=> rpc: add performance timers

src/common/password.cpp
=> Disguise password length in prompt

src/wallet/wallet2.h
=> wallet2 bugfix: loading old m_unconfirmed_payments

src/wallet/wallet2.cpp
I've been investigating the same issue that recently merged #2764 addressed. The bug is fixed, however I think the following solution is better.
1. it reuses already computed unlocked balance,
2. it takes indices (`index=a,b,c,...`) into account
3. it gets rid of duplicated check if `needed_money > balance`
If I'm wrong, please just drop it.
=> Correct totals computation

src/daemon/rpc_command_executor.cpp
Find it bad that you don't know if flushing is complete or if you have to wait because something hanging
=> Daemon: print msg upon success for commands that are completely silent

src/simplewallet/simplewallet.cpp
Old errors messages where still mentioning ring size 3.
Added a preprocessor constant to track min ring size and use it in relevant messages.
=> Update ring size in outdated error msgs with set_default_ring_size

src/wallet/wallet2.cpp, src/wallet/wallet_errors.h, src/wallet/wallet_rpc_server.cpp
I've added exceptions for *address index out of bounds* and *account index out of bounds* together with handling in RPC.
=> Add out-of-bound exceptions and handle them in RPC

src/cryptonote_protocol/cryptonote_protocol_defs.h, src/cryptonote_protocol/cryptonote_protocol_handler.inl, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h
It's sent as JSON, so raw binary is not appropriate
=> make connection_id a string in RPC

contrib/snap/snapcraft.yaml
=> Update snap version to 0.11.1

README.md
Added a heading in the readme that describes the release staging schedule and protocol.
=> Update README.md with info about release timelines

utils/build_scripts/android32.Dockerfile, utils/build_scripts/android64.Dockerfile
Fix for #2725 
Instructions from @danrmiller [here](https://github.com/monero-project/monero/issues/2725#issuecomment-339330412)
Requires #2841
=> Android dockerfile: add zmq dependency

src/wallet/wallet_rpc_server.cpp
This reverts commit b60f48f0e31c17638f771042887b2fffdbad15b4.
=> Revert "return subaddress in get_bulk_payments"

src/wallet/wallet2.cpp
Helpful now that tx sizes are smaller
=> wallet2: print tx size in bytes and kB

README.md
The current Readme's section on supporting Monero financially could use some polish. This PR proposes to emphasize how Monero is community led and has no source of funds outside generous donations. If people are visiting the README and they see that donating financially is the easiest/simplest thing they can do to help Monero, then it seems like they'll be more likely to donate.
=> README.md: Improve copy for supporting the project

tests/unit_tests/crypto.cpp
The author doesn't seem to be finishing/fixing this, and it
doesn't do anything.
=> tests: remove unused/unfinished keccak bits

src/wallet/wallet_rpc_server.cpp, src/wallet/wallet_rpc_server.h, src/wallet/wallet_rpc_server_commands_defs.h
Additional tx keys, amounts and fees were missing in some cases
=> wallet_rpc_server: factor transfer info return and add missing info

src/common/threadpool.cpp
If a queued job uses a waiter, then we want to run that waiter's
jobs in the current thread if all threads are busy, even if the
queue is empty, since there is no guarantee that any thread will
free up to take care of that new job, since all the threads might
be running a job which spawns such a recursive job and will block
till that recursive job is done, which it will never be since it
relies on the queue being polled by one of those blocked threads.
=> threadpool: fix deadlock in recursive waiter usage

src/blockchain_db/lmdb/db_lmdb.cpp
Reset thread-specific flags when a write txn is started.
Also remove some redundant start-readtxn code.
=> Fix stale readcursor flags

cmake/FindReadline.cmake
Add checks for termcap if needed by readline
=> Fixes #2919

src/wallet/wallet2.cpp
I encountered this strange behavior:
```
[wallet 9xLMUj]: incoming_transfers available
amount   spent    unlocked  ringct    global index                                                               tx id      addr index
0.021846280000       F    unlocked  RingCT          326479  <25cebe40f22757a9284448013564110c785432d8a6111bd76594ab01043a37ad>               0
0.024081800000       F    unlocked  RingCT          326998  <10810ca2bba18f8bf3287fea5ddb11f88f0135296f28baf07e2615505c530786>               0
0.010000000000       F    unlocked  RingCT          330773  <3ca10a03457ffa1c5a4fe1ee531b6bbbef13ca9a13a44b1acc53425a8ae0c3a6>               0
0.071060800000       F    unlocked  RingCT          331324  <99db5d8a48ba549644f37850cbf03e2353fa5248b422a0074d0cb009e0b93e3d>               0 …
```
=> sweep_below: do not prematurely exclude subaddresses set

cmake/FindReadline.cmake, contrib/epee/src/CMakeLists.txt, src/daemon/CMakeLists.txt, src/gen_multisig/CMakeLists.txt, src/simplewallet/CMakeLists.txt
Reported by @xmr-eric on IRC. This PR allows build without a readline dependancy.
=> Keep readline optional

README.md
Replaces #2671 that have been open for many months and contains many other changes
=> Add Dependencies for Fedora, take 2

translations/monero_sv.ts
=> added Swedish translation

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h, tests/unit_tests/address_from_url.cpp
Fixes #1549
Conflicts with #3029
=> Factor the monero donation address

tests/performance_tests/main.cpp, tests/performance_tests/performance_tests.h
Removes a good bit of annoyance running those
=> performance_tests: add a --filter option to select what to run

src/simplewallet/simplewallet.cpp, src/wallet/wallet2.cpp, translations/monero.ts, translations/monero_fr.ts, translations/monero_it.ts
=> Improved terminology from create to generate

src/common/util.cpp
=> Fixes #3044: OSX output folder

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h, src/wallet/wallet2.cpp, src/wallet/wallet2.h
I hope this isn't making the confirm prompt too abundant...
=> simplewallet: check file overwrite when exporting stuff

tests/unit_tests/ringct.cpp
decodeRct returns the amount, which may be zero
=> unit_tests: do not ASSERT_TRUE(decodeRct(...))

src/ringct/bulletproofs.cc
Changes from sarang, from a recommendation by an anonymous reviewer
=> bulletproofs: more robust challenge computation

src/daemon/rpc.h, src/rpc/rpc_args.cpp, src/simplewallet/simplewallet.cpp, src/wallet/api/address_book.cpp, src/wallet/api/wallet.cpp, src/wallet/wallet2.cpp, src/wallet/wallet_rpc_server.cpp, translations/monero.ts, translations/monero_fr.ts, translations/monero_it.ts
=> Fixed UI typos

src/common/int-util.h, src/crypto/chacha.c, src/crypto/oaes_lib.c, src/crypto/tree-hash.c
These changes allow building the hashing (cncrypto) lib on Windows with Visual Studio.
=> Support building cncrypto lib with msvc

translations/monero_sv.ts
=> Update translation source from create to generate

CMakeLists.txt
since there's no config.h here
=> cmake: add -DHAVE_ defines to the command line

tests/performance_tests/main.cpp
Fix for coverity issues 182551, 182543, 182535, 161883, 142959 (Uncaught exception) ~and 182572 (Array compared against 0)~
=> Fix coverity issues in performance_tests/main.cpp

src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h
Fix #3230 Don't create readtxn until after txn_safe gate check
=> Fix Issue 3230 invalid readtxn

src/cryptonote_basic/miner.cpp
=> Closes #2886: really ignore battery checking

contrib/epee/src/wipeable_string.cpp
=> wipeable_string: don't try to wipe an empty buffer

src/wallet/wallet2.cpp
Since commit b0426d4c refresh height for a newly created wallet
connected to a sync'd daemon was off by a month. Now we only use
the 1 month safety margin if we're unable to talk to a daemon.
=> [RELEASE] Fix refresh height estimation

src/ringct/rctSigs.cpp
The code removed from the loop, code does not depend on the loop.
=> rctSigs - loop invariant code removed from the loop

src/blockchain_db/lmdb/db_lmdb.cpp
=> [RELEASE] db_lmdb: fix free space reporting

src/simplewallet/simplewallet.cpp
And also use uint64_t instead of int for heights where appropriate
=> [RELEASE] simplewallet: fix print_ring_members printing wrong heights

src/cryptonote_config.h, src/cryptonote_core/cryptonote_tx_utils.cpp
This might probably break testnet because it was using the mainnet genesis tx.
=> Use `genesis_tx` parameter in `generate_genesis_block`.

Dockerfile
#3313  added libboost_locale as a requirement
=> Dockerfile: add boost locale

README.md
* Removed the db package, as it is not required
* Added the libiconv package
* Updated the boost build instructions (added locale)
* Updated cppzmq to version 4.2.3 which does not require the symlink hack anymore
=> README.md: Updated OpenBSD build instructions

src/simplewallet/simplewallet.cpp
A malicious daemon (or MITM) could attempt to add spurious errors
so the wallet tries again, sending another set of fake outs.
=> simplewallet: add a warning when getting a daemon error in transfer

README.md, cmake/Version.cmake
Fix #3463, Also removes BYPRODUCT dependency on CMake 3.2
=> Fix generating version.cpp

src/common/dns_utils.cpp, src/common/util.cpp
Common on currently used distros
=> common: make this build with unbound 1.4.20

src/cryptonote_core/tx_pool.cpp
A key image may be present more than once if all but one of the
txes spending that key image are coming from blocks. When loading
a txpool from storage, we must load the one that's not from a
block first to avoid rejection
=> tx_pool: fix loading with colliding key images

src/daemon/main.cpp
Currently, the config file is read after some other args have been read, which means that if those settings are specified in the config file, they aren't reflected in the program. Here's one particular problem reported in #3603: if one launches the daemon as
monerod --config-file /etc/test_monerod.conf
with the config file containing:
testnet=1
the daemon log gets written to the  *mainnet* log file (`~/.bitmonero/bitmonero.log`) instead of the testnet log file (`~/.bitmonero/testnet/bitmonero.log`) because the daemon log path is determined before reading the config file.
Also, I've removed the following bit
```c++
if (!config_path.has_parent_path())
{
config_path = data_dir / config_path;
}
```
which I found confusing, because the default data dir depends on the network type …
=> daemon: read config file before reading any other args

src/crypto/slow-hash.c
- https://github.com/seredat/karbowanec/issues/41
- #3694
=> slow-hash: fix memory leak for Windows /karbowanec#41

src/wallet/wallet2.cpp
This is dup of PR #3650 @moneromooo-monero
=> import_multisig_info: fix sanity check crash in detach_blockchain

src/cryptonote_protocol/cryptonote_protocol_handler.inl
=> cryptonote_protocol_handler.inl: remove span read just now that failed to pass some basic tests

src/cryptonote_core/blockchain.cpp
Might be a bit heavy handed, but conservative.
=> blockchain: invalidate misc caches when popping blocks

README.md
=> [RELEASE] Update readme to include link to announcement list

src/daemon/rpc_command_executor.cpp
=> daemon: request unpruned transactions for print_tx

tests/unit_tests/hardfork.cpp
This reverts commit 20ef37bbcac7715d5299dd77d401583420e07ced, reversing
changes made to 40070a661fd2ff503e07f4ed48dfe9fe67cfa297.
=> Revert "Merge pull request #3775"

src/cryptonote_core/blockchain.cpp
=> Pop top if block version disagrees with the ideal fork version

README.md
Added link to readme for https://lists.getmonero.org
=> Update readme to include link to announcement list

src/wallet/api/wallet.cpp, src/wallet/api/wallet2_api.h
Motivated by https://github.com/monero-project/monero-gui/pull/1358
=> Wallet API: allow log path to be non-default

src/blockchain_db/berkeleydb/db_bdb.cpp, src/blockchain_db/berkeleydb/db_bdb.h, src/blockchain_db/blockchain_db.cpp, src/blockchain_db/blockchain_db.h, src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h, src/blockchain_utilities/blockchain_usage.cpp, src/cryptonote_basic/cryptonote_format_utils.cpp, src/cryptonote_basic/cryptonote_format_utils.h, src/cryptonote_core/blockchain.cpp, src/cryptonote_core/blockchain.h, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/rpc/core_rpc_server.cpp, src/rpc/daemon_handler.cpp, tests/unit_tests/hardfork.cpp
This bumps DB version to 2, migration code will run for v1 DBs
DO NOT MERGE before the release.
=> db_lmdb: save pruned and prunable tx data separately

src/blockchain_utilities/blockchain_usage.cpp
=> blockchain_usage: don't divide by 0 when there is nothing to process

src/cryptonote_core/blockchain.h, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, tests/core_proxy/core_proxy.h, tests/unit_tests/ban.cpp
Needed by https://github.com/aeonix/aeon-rebase/pull/4
=> core: add get_earliest_ideal_height_for_version()

src/cryptonote_core/blockchain.cpp
=> blockchain: log in DEBUG when a block is found, and where

contrib/epee/include/net/http_protocol_handler.h, contrib/epee/include/net/http_protocol_handler.inl
=> wallet-rpc: added IPs to error logging in simple_http_connection_handler

README.md
Accidentally closed #3791 
Demoted the 3rd party maintained package installs to after compiling
from repository source and removed the broken Homebrew package
instructions.
=> README: add disclaimer about 3rd party packages

README.md
cloning and extra build details included.
=> adding win building details.

src/cryptonote_core/blockchain.cpp
avoids RPC thread dying, causing the wallet to timeout
=> blockchain: return error when requesting non existent output

README.md
=> Update Readme to indicate recommended version

src/simplewallet/simplewallet.cpp
As per the discussion in #3767 If this gets merged then 3767 would be closed
=> simplewallet: don't limit miner threads in wallet

src/simplewallet/simplewallet.cpp
=> simplewallet: fix string handling when donating

README.md
Update readme to include pcslite dependency
=> Update readme to include pcslite dependency

README.md
update readme to include debian one liner for deps , because who wants to select all of those individually
=> update readme to include debian one liner for deps

Dockerfile, README.md
Updated new versions of dependencies
=> Updated new versions of dependencies

tests/unit_tests/CMakeLists.txt, tests/unit_tests/device.cpp
Annoyingly, its locking semantics are borked since it does not
do any locking
=> unit_tests: add device unit tests

src/blockchain_db/blockchain_db.h, src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h, tests/unit_tests/hardfork.cpp
This should help new nodes predict how much disk space will be
needed for a full sync
=> rpc: add blockchain disk size to getinfo

src/simplewallet/simplewallet.cpp, src/wallet/node_rpc_proxy.cpp, src/wallet/node_rpc_proxy.h, src/wallet/wallet2.cpp
=> node_rpc_proxy: factor a few RPC calls using get_info

src/blockchain_db/lmdb/db_lmdb.cpp
=> db_lmdb: don't sync a read only DB

src/simplewallet/simplewallet.cpp
avoids people thinking it's somehow a generic AE system
=> simplewallet: reword "seed encryption" to "seed offset"

src/wallet/wallet2.cpp
That takes a lot of time for even not so large wallets
=> wallet2: fix O(n^2) behaviour in import_key_images

src/wallet/wallet2.cpp
=> wallet2: guard against bad outputs in import_outputs

Dockerfile
=> Update cmake version

README.i18n.md
Qt link has changed.
Also fixing proper capitalization.
=> Updating Qt download link

src/mnemonics/electrum-words.cpp
=> electrum-words: fix bytes_to_words on big endian

src/wallet/wallet2.cpp
All daemons will not support pruned blocks
=> wallet2: remove obsolete pruned/unpruned case

src/simplewallet/simplewallet.cpp
to match those used by the various transfer functions
=> simplewallet: allow named priority levels for default-priority

src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h
instead of a random ratio from 60% to 90%.
=> db_lmdb: resize blockchain database when 90% filled

CMakeLists.txt
=> CMakeLists.txt: add -mmitigate-rop to security flags if found

tests/fuzz/fuzzer.cpp
=> fuzz_tests: use __AFL_INIT when available

src/blockchain_utilities/blockchain_blackball.cpp, src/simplewallet/simplewallet.cpp, src/wallet/ringdb.cpp, src/wallet/ringdb.h, src/wallet/wallet2.cpp, src/wallet/wallet2.h, tests/unit_tests/ringdb.cpp
Will need rebasing on top of a couple other PRs which are going to be merged shortly.
=> Blackballing improvements

src/debug_utilities/cn_deserialize.cpp
=> cn_deserialize: comment out pruned tx case

src/cryptonote_basic/cryptonote_format_utils.cpp
Another such pubkey might be valid
=> cryptonote_format_utils: do not early out on invalid tx pubkeys

Dockerfile
Updated dependencies cmake 3.12.1 and boost 1.68
=> Updated dependencies cmake 3.12.1 and boost 1.68

src/wallet/api/wallet.cpp, src/wallet/api/wallet.h, src/wallet/api/wallet2_api.h
Added call `hasMultisigPartialKeyImages` to let multisig wallet know if they need to import multisig partial key images
=> WalletAPI: 'hasMultisigPartialKeyImages' function added

tests/difficulty/difficulty.cpp
Fixes a compile error on ARM64 Debian Jessie
=> Fix missing std::runtime_error def in difficulty.cpp

src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h
Make it easier for a user to be told when to update
=> rpc: add a "is an update available" flag in get_info

README.md
with consensus rules and block heights
=> update readme fork table

src/crypto/keccak.c
=> Fixed Keccak implementation on big-endian platforms

src/wallet/wallet_rpc_server.cpp
Thanks iDunk for building patches on windows
=> wallet_rpc_server: fix build for windows

src/ringct/bulletproofs.cc
instead of merging that with other scalar multiplications
where possible for speed, since this is not actually safe
=> bulletproofs: multiply points by 8 first thing in verification

src/wallet/wallet_rpc_server.cpp
Thanks iDunk for the windows testing
=> wallet_rpc_server: fix --run-as-service on Windows

src/wallet/api/wallet.cpp, src/wallet/api/wallet.h, src/wallet/api/wallet2_api.h
amount and offset (instead of pubkey)
=> wallet2_api: blackball/unblackball now take two parameters

src/common/CMakeLists.txt, src/common/notify.cpp, src/common/spawn.cpp, src/common/spawn.h
Also renames `exec` to `spawn`
=> common: Windows 'spawn' support for tx and block notifications

src/wallet/wallet2.cpp
Avoids triggering the sanity check
=> wallet2: clear found out for every tx key

src/device/device_ledger.cpp
Increasing the timeout resolves the issues in #4512 for me on macOS.
=> device: increase ledger timeout to 2 minutes

contrib/epee/include/net/abstract_tcp_server2.inl, contrib/epee/include/net/http_protocol_handler.inl, src/daemon/daemon.cpp, src/debug_utilities/object_sizes.cpp, src/p2p/net_node.cpp, src/wallet/wallet_rpc_server.h, tests/net_load_tests/clt.cpp, tests/net_load_tests/srv.cpp
instead, delegate the work to a one off thread
and notify it from the signal handler
=> daemon: do not run complex code in a signal handler

src/p2p/net_node.inl
This reverts commit 909398efc79cb1fa92e330e9a50a316ca5858953.
It looks like it's causing trouble with tor on some setups
=> Revert "p2p: connect via the bound ip, if any"

src/common/password.cpp
Thanks to iDunk for the testing back and forth
=> password: fix secure input with echo on windows

src/blockchain_utilities/CMakeLists.txt, src/blockchain_utilities/blockchain_blackball.cpp, src/simplewallet/simplewallet.cpp, src/wallet/api/wallet.cpp, src/wallet/ringdb.cpp, src/wallet/wallet2.cpp, tests/unit_tests/ringdb.cpp
Apparently some people seem to think it's a censorship list...
=> Rename "blackball" for clarity

src/device/device_io_hid.cpp, src/device/device_io_hid.hpp, src/device/device_ledger.cpp
=> device: fixed Ledger Nano S device selection on Windows/Mac

src/cryptonote_core/blockchain.cpp
Lest we get people get scared again
=> blockchain: move two new verification errors to the verify category

src/cryptonote_core/blockchain.cpp
=> blockchain: add check test options are given for fakechain mode

src/cryptonote_core/tx_pool.cpp, src/rpc/core_rpc_server.cpp
…rsion in get_transactions RPC
Fixes problem made in #4592
=> [RELEASE] tx_pool: revert #4592 and move bin2hex conversion to on_get_transaction_pool

src/wallet/wallet2.cpp
in order to unbias selection from blocks with few txes
=> wallet2: extend fake out picks away from the gamma pick

src/p2p/net_node.inl
as per the source documentation
=> p2p: a negative result from UPNP_GetValidIGD is an error

tests/unit_tests/notify.cpp
=> unit_tests: call umask before mkstemp

src/blockchain_utilities/CMakeLists.txt, src/blockchain_utilities/blockchain_stats.cpp
Report statistics from a blockchain DB. Supersedes #2387
=> Add stats utility

src/simplewallet/simplewallet.cpp, src/wallet/wallet2.h
it doesn't display the details, which are already displayed
in show_transfer
=> simplewallet: display locked/unlocked state in show_transfers

src/wallet/wallet2.cpp
=> wallet2: use padded bulletproofs for multisig signing

src/simplewallet/simplewallet.cpp
=> simplewallet: reorganize SCOPED_WALLET_UNLOCK a bit more

CMakeLists.txt
Fixes building on PowerPC Big Endian Ubuntu 16
=> build: ubuntu 16 ppc build fixes

tests/unit_tests/notify.cpp
=> unit_tests: fix leak when the test check fails

contrib/epee/include/net/http_server_handlers_map2.h
It's useful info to have when investigating logs
=> epee: log HTTP/RPC calls at info level

README.md
its the one thing I do. I change the table.
=> readme 0.13.0.4 in the table

contrib/epee/include/mlocker.h, contrib/epee/src/mlocker.cpp, src/common/http_connection.h, src/wallet/wallet2.cpp
Coverity 189689, 189690, 189692, 189695
=> various: do not propagate exception through dtor

contrib/epee/src/mlocker.cpp
When the rlimit is too low, the logs are flooded with mlock errors. This patch will show only the first such error. munlock errors are silenced only if an mlock previously failed (because then there is nothing to unlock).
=> epee: Only show a single mlock() error, to avoid flooding the log

src/ringct/rctSigs.cpp
Ledger does some basic checks on them
=> ringct: fix dummy bulletproofs on ledger in fake mode

contrib/epee/include/net/levin_client_async.h, contrib/epee/include/net/levin_protocol_handler_async.h
Just a minor change of debug information in `contrib/epee/include/net/levin_protocol_handler_async.h`.
=> Changed RECIEVED to RECEIVED.

src/cryptonote_core/blockchain.cpp, src/cryptonote_core/blockchain.h
This ensures the io service that runs in another thread cannot
access data after it's deleted
=> blockchain: call deinit in dtor

src/simplewallet/simplewallet.cpp
=> simplewallet: donate command validate amount

contrib/epee/src/mlog.cpp, src/common/perf_timer.h
and make them not default at log level 1
=> perf_timer: make all logs Info level

src/common/spawn.cpp
https://github.com/monero-project/monero/pull/4333#issuecomment-444090072
=> notifications: ignore child process when exec

contrib/epee/include/net/buffer.h, contrib/epee/include/net/http_server_handlers_map2.h, contrib/epee/include/net/levin_base.h, contrib/epee/include/net/levin_client.h, contrib/epee/include/net/levin_client.inl, contrib/epee/include/net/levin_protocol_handler_async.h, contrib/epee/include/span.h, contrib/epee/include/storages/http_abstract_invoke.h, contrib/epee/include/storages/levin_abstract_invoke2.h, contrib/epee/include/storages/portable_storage.h, contrib/epee/include/storages/portable_storage_template_helper.h, contrib/epee/src/CMakeLists.txt, contrib/epee/src/buffer.cpp, src/cryptonote_protocol/cryptonote_protocol_handler.h, src/cryptonote_protocol/cryptonote_protocol_handler.inl, src/p2p/net_node.h, src/p2p/net_node.inl, src/p2p/net_node_common.h, tests/fuzz/levin.cpp, tests/net_load_tests/net_load_tests.h, tests/unit_tests/epee_levin_protocol_handler_async.cpp, tests/unit_tests/epee_utils.cpp
avoids pointless allocs and memcpy
=> epee: better network buffer data structure

src/wallet/wallet2.cpp
Found by Coverity (188336 in Anonimal's Coverity account).
=> Wallet: Initialize members without default ctor.

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h
Estimate restore height from given date
=> Add --restore-date param

src/rpc/core_rpc_server.cpp, src/simplewallet/simplewallet.cpp, src/wallet/wallet2.cpp, src/wallet/wallet2.h
If you find more, feel free to patch.
=> wallet: do not display daemon controlled text if untrusted

README.md, tests/README.md
=> remove trailing whitespace in README.md

src/common/i18n.cpp
If there are more valid characters, add them in, I did not find
an actual list.
=> i18n: filter LANG/LC_LANG for valid characters

tests/unit_tests/mnemonics.cpp
Tests https://github.com/monero-project/monero/pull/5063
=> Added two tests for partial word and case tolerance in mnemonics

contrib/depends/packages/sodium-darwin.mk, contrib/depends/packages/sodium.mk, contrib/depends/patches/sodium/fix-whitespace.patch
=> bump sodium to 1.0.16

src/cryptonote_core/blockchain.cpp
Also check return of that function, it can now return error
=> blockchain: fix m_long_term_block_weight_height initialization

src/blockchain_db/lmdb/db_lmdb.cpp
=> db_ldmb: fix missing mdb_dbi_close in migration

src/rpc/core_rpc_server.cpp
Fix for #4399.
Also unifies code for serializing pruned tx to binary/json into one.
(Cherry-picked from #4586)
=> [RELEASE] rpc: fix wrongly formatted JSON for pruned tx

src/wallet/wallet2.cpp
=> wallet: fix payment ID decryption for construction data with dummy v0.13

src/wallet/api/subaddress_account.cpp, src/wallet/api/wallet.cpp, src/wallet/api/wallet.h, src/wallet/api/wallet2_api.h, src/wallet/api/wallet_manager.cpp
=> Wallet api changes v0.14.0.1

src/simplewallet/simplewallet.cpp
=> simplewallet: tell the user to complain to the recipient

src/blockchain_db/lmdb/db_lmdb.cpp
=> db_lmdb: fix missing mdb_dbi_close in migration

src/ringct/bulletproofs.cc
=> bulletproofs: speed up vector_power_sum

ANONYMITY_NETWORKS.md, contrib/epee/include/net/net_utils_base.h, src/cryptonote_config.h, src/net/CMakeLists.txt, src/net/fwd.h, src/net/i2p_address.cpp, src/net/i2p_address.h, src/net/parse.cpp, src/net/parse.h, src/net/socks.cpp, src/net/socks.h, src/p2p/net_node.cpp, src/p2p/net_peerlist_boost_serialization.h, src/p2p/p2p_protocol_defs.h
Adds i2p support on top of #4988.
=> i2p: initial support

src/wallet/wallet_rpc_server.cpp, src/wallet/wallet_rpc_server_commands_defs.h
=> wallet-rpc: get transfers for all accounts and subaddresses

src/rpc/core_rpc_server.cpp
It's slow work, so let's not expose it
=> rpc: make fill_pow restricted

contrib/epee/include/net/net_ssl.h, contrib/epee/src/net_ssl.cpp
Use SSL API directly, skip boost layer
=> Fix startup errors with SSL cert generation

src/cryptonote_basic/cryptonote_format_utils.cpp
Human readable message if maximum outputs reached
=> Human readable message if maximum outputs reached

src/wallet/wallet2.cpp
As dummy payment ID is a legitimate value now (8xzero byte) the `bool get_short_payment_id()` has to be changed a bit as it returns 8x0B also as an indication of failure / absence of short payment ID. 
Because of this construction data does not get updated in `get_construction_data_with_decrypted_short_payment_id()`. As a consequence, the encrypted dummy ID stays in the construction data `extra` and payment ID is scrambled.
=> wallet: fix payment ID decryption for construction data with dummy

README.md
it occurred to me that someone discovering monero for the first time, through the code and actually reading the readme, would not have any indication of the design focuses of keeping monero decentralized, both in terms of the mining infrastructure and the low cost of node operation.  I know the topic is sort of a ... wishy washy thing, but I tried to craft some language that gets the point across in general terms.
=> update readme to include blurb on decentralization

src/wallet/wallet2.cpp, src/wallet/wallet2.h
We generate and check tx proofs and verify the amounts in those
match what the original amounts were.
Note: will probably need to be adapted to work with ledger
=> wallet2: sanity check new tx before sending
