- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
This function isn't used in the codebase.
Signed-off-by: Jean Pierre Dudey <jeandudey@hotmail.com>
> Remove the `Blockchain::get_all_known_block_ids` function.

- src/simplewallet/simplewallet.cpp
Currently the `wallet_info` command will just show `Description:  ` (just blank after) if a description has not been set. This PR will show `Description: N/A` if a description has not been set.
> simplewallet: show 'Not set' for empty wallet description

- src/simplewallet/simplewallet.cpp
Because #3175 set the default value of `m_explicit_refresh_from_block_height` to `true`, any wallet restoration operations such as `monero-wallet-cli --restore-deterministic-wallet` would never ask for the restore height even when none is provided explicitly via `--restore-height`.
> [RELEASE] simplewallet: fix restore height prompt that got disabled by #3175

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.h
Add command line option allowing to restrict the default sub-address lookahead in order to avoid hours of set-up when creating a HW based wallet.
> [RELEASE] Add cli option to set range of subaddress lookahead

- src/cryptonote_core/blockchain.cpp
They were already forbidden implicitely, but let's make that
explicit for robustness
> blockchain: forbid bulletproof types before v8

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
via user setting first, then DNS TXT record, hardcoded fallback
> wallet: make the segregation height settable

- src/mnemonics/chinese_simplified.h
- src/mnemonics/dutch.h
- src/mnemonics/electrum-words.cpp
- src/mnemonics/electrum-words.h
- src/mnemonics/english.h
- src/mnemonics/english_old.h
- src/mnemonics/esperanto.h
- src/mnemonics/french.h
- src/mnemonics/german.h
- src/mnemonics/italian.h
- src/mnemonics/japanese.h
- src/mnemonics/language_base.h
- src/mnemonics/lojban.h
- src/mnemonics/portuguese.h
- src/mnemonics/russian.h
- src/mnemonics/spanish.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
On some Windows systems, displaying language names in their own
languages freezes the display.
> simplewallet: new --use-english-language-names flag

- README.md
This is needed because we now have #2133 merged for release.
> README: add instructions for cloning / submodules

- README.md
changed wording in hard fork section because reasons. Added prospective slot of next hardfork to communicate that more are coming because it never stops.
its everywhere and all at the same time.
> change wording in hard fork description section

- README.md
- cmake/Version.cmake
Fix #3463, Also removes BYPRODUCT dependency on CMake 3.2
The requirement for CMake 3.2.0 was introduced erroneously
in commit e29282d and is no longer present
> [RELEASE] Fix generating version.cpp

- src/rpc/core_rpc_server.h
so that those nodes can still be used for sending transactions
> rpc: make get_output_distribution a non-restricted RPC

- src/device/device_default.cpp
We now force little endianness
> device: fix endianess dependence on subaddress secret key generation

- src/device/device.hpp
- src/device/device_default.cpp
- src/device/device_default.hpp
- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
- src/wallet/wallet2.cpp
**Main modification**
When additional keys was needed, the TX scan failed because the
derivation data was always recomputed with the main tx_key and not
the corresponding additional one.
Moreover this patch avoid perf decreasing when not using HW device.
**Others**
Change from std mutex to boost mutex
> [RELEASE] Fix sub-address tx scan.

- src/wallet/api/wallet.cpp
DEFAULT_MIXIN is currently set to 4 (ringsize 5,) but should be 6 (ringsize 7) for 0.12 "Lithium Luna"
credits to endogenic for pointing this out
> wallet: fix default mixin (4 -> 6)

- src/cryptonote_core/cryptonote_tx_utils.cpp
`shuffled_dsts` ended up being unused due to the confusion during the revert of output sorting.
> cryptonote_tx_util: make destinations properly shuffled

- src/device/device.hpp
- src/device/device_default.cpp
- src/device/device_default.hpp
- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
- src/wallet/wallet2.cpp
#3591 rebased on Master after merged
**Main modification**
When additional keys was needed, the TX scan failed because the
derivation data was always recomputed with the main tx_key and not
the corresponding additional one.
Moreover this patch avoid perf decreasing when not using HW device.
**Others**
Change from std mutex to boost mutex
> [RELEASE] Fix sub-address tx scan

- src/blockchain_utilities/blockchain_blackball.cpp
It doesn't like the explicit NULL dereference (which is fine, honest)
> blockchain_blackball: fix build with CLANG 5

- src/simplewallet/simplewallet.cpp
Currently, the help message is inconsistent with L5406:
fail_msg_writer() << tr("usage: sign_transfer [export]");
> simplewallet: fix help message of sign_transfer

- src/wallet/wallet2.cpp
This fixes #3505. Tested on OSX 13.12
> import_multisig_info: fix sanity check crash in detach_blockchain

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- tests/core_proxy/core_proxy.h
- tests/unit_tests/ban.cpp
This is less likely to occur in Monero since it has a much larger hash rate, but it's possible that there are nodes mining a higher version but is forked from somewhere it's known to be otherwise (i.e. at a checkpoint that's known to be v6).
The behaviour this avoids is logging a false positive indicating a potential protocol upgrade.
I speculate that without this PR, the error may trigger if a chain fork like MoneroV doesn't properly configure their network and are broadcasting to Monero daemons.
> Only log a block voting error if top version is higher and isn't ideal fork version

- .gitmodules
f21df05 was never supposed to be merged into the master branch.
fluffypony merged #3670 before #3668 was rebased and resolved.
Note: the cherry-picked commit hashes are now invalid because #3670
was merged before #3668 was rebased with the updated repo location.
> [MERGE IMMEDIATELY] Build: update miniupnp submodule

- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/syncobj.h
Regressed by boostorg/thread@fea3e33128aa. Fixes #3663.
`<boost/thread/condition_variable.hpp>` is already used by the project without checking `BOOST_VERSION`:
https://github.com/monero-project/monero/blob/6f6521ad7a9832788e07f7f7d181ba29b010e311/src/common/threadpool.h#L30-L32
https://github.com/monero-project/monero/blob/6f6521ad7a9832788e07f7f7d181ba29b010e311/src/wallet/api/wallet.h#L38-L40
> Unbreak build against Boost 1.67

- src/daemon/command_parser_executor.cpp
- src/daemon/rpc_command_executor.cpp
- src/p2p/net_node.h
- src/rpc/core_rpc_server_commands_defs.h
The interactive daemon commands `limit`, `limit_up` and `limit_down` plus the corresponding RPC calls were basically broken since my own [PR #2866] was merged last December: When I corrected a bug and streamlined code in connection with the command-line parameter `--limit-rate`  I did not recognize that the code for the interactive commands and the RPC calls behind them needs also corrections:
Any limit given interactively or over RPC was still multiplied by 1024 which is wrong since [PR #2866].
Those multiplications confusingly look like they could have something to do with going from kilobytes/second to bytes/second and therefore needed, but in fact they just were part of some "fudging" necessary because of a then still unrecognized bug. Details see my December PR.
> Fix broken interactive daemon 'limit' commands plus RPC calls

- src/common/CMakeLists.txt
Should fix #3706 -- I was able to reproduce the issue and then fix it with this commit (`make debug`).
It appears that boost::this_thread::sleep_for (present in the Boost Threads library) has references to boost::chrono::steady_clock::now() , which was causing building with shared libraries to fail.
> Add Boost Chrono library to common

- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/syncobj.h
In file included from src/cryptonote_basic/hardfork.cpp:33:
In file included from src/blockchain_db/blockchain_db.h:42:
In file included from src/cryptonote_basic/hardfork.h:31:
contrib/epee/include/syncobj.h:37:10: fatal error: 'boost/thread/v2/thread.hpp' file not found
#include <boost/thread/v2/thread.hpp>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/rpc/daemon_handler.cpp:29:
In file included from src/rpc/daemon_handler.h:36:
In file included from src/p2p/net_node.h:41:
In file included from contrib/epee/include/net/levin_server_cp2.h:32:
In file included from contrib/epee/include/net/abstract_tcp_server2.h:324:
contrib/epee/include/net/abstract_tcp_server2.inl:44:10: fatal error: 'boost/thread/v2/thread.hpp' file not found
#include <boost/thread/v2/thread.hpp> // TODO …
> epee: Drop deprecated Boost.Thread header

- src/common/CMakeLists.txt
Cherry pick of #3709 for the release branch.
> [RELEASE] Add Boost Chrono library to common

- src/daemon/command_parser_executor.cpp
- src/daemon/rpc_command_executor.cpp
- src/p2p/net_node.h
- src/rpc/core_rpc_server_commands_defs.h
As per instruction from @moneromooo-monero I re-did master PR #3705 for the v0.12 release branch:
Fix interactive daemon commands `limit`, `limit_up` and `limit_down` plus the corresponding RPC calls that were basically broken since my own PR #2866 was merged last December
> [RELEASE] Fix broken interactive daemon 'limit' commands plus RPC calls

- CMakeLists.txt
- cmake/FindPCSC.cmake
- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
Fix PCSC/WinSCard compilation under windows.
- In FindPCSC.cmake, It seems FIND_PATH doesnot correclty handle the msys mount point. So use the LETTER: variant by using MSYS2_FOLDER variable.
- Add some #warning if PCSC and/or Ledger device is disabled.
> Fix PCSC discovery under Windows/MSYS

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
This addresses issue https://github.com/monero-project/monero/issues/3717
> Use median timestamp if current time renders a block invalid

- Dockerfile
During some builds I noticed that `sha256sum` was failing because it expects two spaces between the filename and hash, _and_ this was not causing `docker build` to fail.
This PR seeks to fix those `sha256sum` checks, as well as add `set -ex` to catch this, and other, errors in the future.
> Fix Dockerfile sha256sum errors

- src/simplewallet/simplewallet.cpp
Exit immediatly if the wallet file specified with `--wallet-file` flag is not found.
> simplewallet: exit if specified wallet file doesn't exist

- src/rpc/core_rpc_server.cpp
The distribution was not converted to cumulative after a cache hit
> rpc: fix get_output_distribution cache for the cumulative case

- src/wallet/api/pending_transaction.cpp
- src/wallet/api/pending_transaction.h
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Hey guys! We are making multisig gui wallet and we'd like these changes to be in upcoming release.
Added abilities in gui wallet api to:
* create multisig wallets
* multisig key images exchange
* create, sign, commit multisig transactions
* Refactored the facility to set Wallet status to work in atomic way.
Tested transaction sending on ubuntu 17.10
API usage example: https://github.com/naughtyfox/monero-multisig-api-example/blob/master/main.cpp
> [RELEASE] multisig entries for wallet api

- src/daemon/command_parser_executor.cpp
Otherwise it looks like `Mining to a testnetaddress, make sure this is intentional!`.
> Add a space in mining to testnet/stagenet string

- src/cryptonote_core/blockchain.cpp
This data comes from untrusted peers, and validation failures
are therefore normal.
> blockchain: demote a hash-of-hashes validation warning to debug

- src/rpc/core_rpc_server.cpp
This avoids double conversion on a later cache hit
> rpc: convert distribution to cumulative after caching

- src/cryptonote_basic/hardfork.cpp
- tests/unit_tests/hardfork.cpp
I encountered the problem with `get_earliest_ideal_height_for_version()` while working on the rebase of Aeon (see https://github.com/aeonix/aeon-rebase/pull/4), where it is planned to bump the hf version from v1 to v7 at once.
Some unit tests are also added.
> Some fixes for HardFork

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
`wallet2::sign` function can't work in multisignature wallets
> `signMultisigParticipant` & `verifyWithPublicKey` functions added into wallet api

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
Multisig GUI wallet needs to know it's signer key
> WalletApi: publicMultisigSignerKey method

- tests/gtest/cmake/internal_utils.cmake
- tests/gtest/include/gtest/internal/gtest-port.h
Compile errors on Windows were reported by @iDunk5400 in https://github.com/monero-project/monero/pull/3245#issuecomment-364563419, but somehow the problem was never addressed since then.
```
In file included from C:/msys64/home/monero/tests/gtest/include/gtest/internal/gtest-internal.h:40:0,
from C:/msys64/home/monero/tests/gtest/include/gtest/gtest.h:58,
from C:/msys64/home/monero/tests/gtest/src/gtest-all.cc:39:
C:/msys64/home/monero/tests/gtest/include/gtest/internal/gtest-port.h:1782:3: error: 'AutoHandle' does not name a type; did you mean 'mutable'?
AutoHandle thread_;
^~~~~~~~~~
mutable
In file included from C:/msys64/home/monero/tests/gtest/src/gtest-all.cc:43:0:
C:/msys64/home/monero/tests/gtest/src/gtest-death-test.cc:637:3: error: 'AutoHandle' does not name a type; did you …
```
> gtest: Fix compilation on MinGW with pthread /googletest#621

- src/crypto/slow-hash.c
Added malloc() based on FORCE_USE_HEAP for arm64, x86 & x86_64 targets just like it is for arm32. (Instead of using the stack whose size is next to impossible to control on android.)
> malloc scratchpad for all supported android archs

- src/simplewallet/simplewallet.cpp
Give an error if an improper log level (not between 0 and 4) is supplied.
> simplewallet: handle improper log levels

- src/simplewallet/simplewallet.cpp
Change the wallet's 'show_transfers' command to always output the transaction date with timestamp (24 hour UTC).
> Improve 'show_transfers' date formatting

- cmake/FindReadline.cmake
Hi,
I noticed that even if GNU Readline is installed through Homebrew, the CMakefile won't pick it up. This is due to Homebrew sensibly not symlinking the readline libraries, as it can cause conflict with system libs.
This commit queries Homebrew for the GNU Readline location (exactly the same as the OpenSSL library detection) and allows the build process to successfully use it.
> Use GNU Readline if installed on OSX via Homebrew

- src/cryptonote_core/blockchain.cpp
This can happen if a peer tries to obtain the next span from other
peers if that span is needed for not downloaded yet. Also if the
peer maliciously requests a non existent block hash.
> blockchain: avoid exception if asked for a block we do not have

- src/p2p/net_node.h
- src/p2p/net_node.inl
Those were added to the seed nodes list even when they had already
been added. Moreover, the current index was not reset after they
were added, typically causing previous seeds to be used, and some
of those fallback seeds to not be tried.
> p2p: fix fallback seed node usage

- src/cryptonote_core/blockchain.cpp
This patch is included in https://github.com/monero-project/monero/pull/2887 but is valid standalone, and fixes an issue caused if/when a fork's difficulty block count exceeds the previous fork as part of a protocol change.
Monero's current count of 720 is high, so this is defensive code in the case the protocol goes lower in one version then higher in another.
> Ensure m_timestamps has the correct number for computing difficulty

- src/wallet/wallet2.cpp
My intention is to mitigate #3761 by returning "bad signature", rather than throwing an error, as the error is triggered inappropriately in the case of checking the signature against a different txid than the one used to create the signature. This causes issues for monerophp: https://github.com/monero-integrations/monerophp/issues/72 & my temp fix: https://github.com/monero-integrations/monerophp/pull/74
> check_spend_proof

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
references https://github.com/monero-project/monero/issues/2954
> simple-wallet-cli: warnings about missing key images for watchonly wallet

- src/cryptonote_core/cryptonote_core.cpp
This gets rid of an innocuous race trying to add the same tx
twice to the txpool
> core: lock incoming tx lock when checking the txpool and chain

- src/wallet/api/wallet.cpp
The CLI wallet has a `--restore-from-spend-key` option which will restore a deterministic wallet from only the private spend key. This functionality would be nice to have in the GUI wallet too. This PR will generate and use a deterministic viewkey if a private spend key is supplied but a private view key is not when restoring a wallet
> wallet api: use deterministic viewkey if one is not supplied

- CMakeLists.txt
- cmake/FindPCSC.cmake
- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
PR #3843 based on release-v0.12 => rebased on master
Fix PCSC/WinSCard compilation under windows.
- In FindPCSC.cmake, It seems FIND_PATH doesnot correclty handle the msys mount point. So use the LETTER: variant by using MSYS2_FOLDER variable.
- Add some #warning if PCSC and/or Ledger device is disabled.
> Fix PCSC compilation under windows

- external/easylogging++/easylogging++.cc
- external/easylogging++/easylogging++.h
It turns out this can be fairly heavy when logging a lot
> easylogging++: cached allowed categories

- src/cryptonote_basic/miner.cpp
- src/daemon/command_parser_executor.cpp
Return false if invalid parameters are given for `ignore_battery` or `do_background_mining` and add console message if `ignore_battery` is being used.
> command_parser_executor: better handle optional miner params

- src/daemon/main.cpp
Once readline is initialized, std::cerr's operator<< will
output a 0xff byte for unknown reasons.
> daemon: fix readline interfering with std::cerr usage

- src/blockchain_utilities/blockchain_blackball.cpp
Fixes error message on freebsd that not all return values in the lambda are of the same type
Fixes #3645 
`return type basic_string<[3 * ...]> must match previous return type const basic_string<[3 * ...]> when lambda expression has unspecified explicit return type`
> Fix for compile error on freebsd `const basic_string`

- README.md
- src/common/util.cpp
- src/simplewallet/simplewallet.cpp
Otherwise the previous daemon's trustedness would carry over.
If not specified, the local address check is performed again.
> simplewallet: add optional trusted/untrusted argument to set_daemon

- README.md
Update readme to explain and warn about building master, and encourage (via example) to build release branches.  
Also updated instance where example build instructions had 0.11.0 as the most recent release.
> readme - explain building master vs. release

- src/wallet/wallet_args.cpp
This means monero-wallet-rpc still does, but the user level program
does not.
> wallet: do not log by default if we're not asked to log to console

- src/common/util.cpp
- src/common/util.h
- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/api/wallet_manager.cpp
- src/wallet/api/wallet_manager.h
- src/wallet/wallet2.cpp
> Wallet API: add support for wallet creation from hardware device

- src/blockchain_db/blockchain_db.h
- src/cryptonote_core/tx_pool.cpp
Avoids valgrind reporting uninitialized data usage
> tx_pool: initialize bitflags padding since it gets written to storage

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Cold signing was always using Borromean range proofs, causing
a larger tx, and an incorrect fee
> wallet2: fix bulletproof cold signing

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/net/http_protocol_handler.inl
- contrib/epee/include/net/net_utils_base.h
- tests/fuzz/levin.cpp
- tests/unit_tests/epee_levin_protocol_handler_async.cpp
a connection's timeout is halved for every extra connection
from the same host.
Also keep track of when we don't need to use a connection
anymore, so we can close it and free the resource for another
connection.
> epee: adaptive connection timeout system

- src/cryptonote_basic/cryptonote_basic_impl.cpp
- src/cryptonote_config.h
- src/cryptonote_core/blockchain.cpp
- src/p2p/net_node.inl
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
The first patch which is about refactoring the use of settings in `cryptonote_config.h` was motivated by the second patch which is to allow the additional node addresses specified via flags like `--add-priority-node` to be resolved (the refactoring is used for obtaining the default P2P port).
I understand that the refactoring part may feel iffy especially because it touches `generate_genesis_block`. It can be dropped if it's deemed unnecessary and the second patch can be written without the refactoring.
> cryptonote_config refactoring + node address resolution

- src/wallet/wallet2.cpp
Otherwise rct outputs would be just displayed as 0.
> wallet2: use decoded amount when reporting repeated output key

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- tests/functional_tests/transactions_flow_test.cpp
for privacy reasons, so an untrusted node can't easily track
wallets from IP address to IP address, etc. The granularity
is 1024 blocks, which is about a day and a half.
> wallet: on first refresh, start off with a quantized height

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
This is based on how much an attacking miner stands to lose in block
rewardy by mining a private chain which double spends a payment.
This is not foolproof, since mining is based on luck, and breaks
down as the attacking miner nears 50% of the network hash rate,
and the estimation is based on a constant block reward.
> wallet: include a suggested number of confirmations based on amount

- contrib/epee/include/file_io_utils.h
- contrib/epee/include/string_tools.h
- src/common/util.cpp
- src/common/util.h
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Maybe this way of trying to lock a file is stupid, but perhaps better than nothing...
> wallet: prevent the same wallet file from being opened by multiple processes

- src/wallet/wallet2.cpp
This would cause crashes when trying to tag an account that was
just created
> wallet2: fix out of sync account tag cache

- src/wallet/wallet_rpc_server.cpp
stop_mining, all the tag RPCs, and make_uri failed to check that m_wallet existed before deref'ing it.
> Fix RPC crashes that didn't check for an open wallet

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
This should be proof against any way one might get to multiple
processing, such as generating the same derivation from the
same pubkey, etc
> wallet2: ensure outputs are processed only once

- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
This is called a lot when creating a block template, and
does not change until the blockchain changes.
This also avoids tx parsing when cached.
> tx_pool: cache check_tx_inputs results

- tests/unit_tests/ringct.cpp
Helps a bit when running with valgrind
> unit_tests: do not recreate the same base rct sig all the time

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Some outputs of factional amounts cannot pay for the additional fees due to their inclusion, so it'd be sensible to not bother with them at all.
> Allow fractional outputs to be ignored

- src/common/CMakeLists.txt
- src/daemon/CMakeLists.txt
- src/p2p/CMakeLists.txt
- src/rpc/CMakeLists.txt
- src/simplewallet/CMakeLists.txt
- src/wallet/CMakeLists.txt
- tests/unit_tests/CMakeLists.txt
For some reason, this confuses and kills ASAN on startup
as it thinks const uint8_t ipv4_network_address::ID is
defined multiple times.
> remove epee from link lines where it's redundant

- src/cryptonote_core/blockchain.cpp
when a block being added to the main chain is invalid.
This ensures the peer is banned after a number of these.
> blockchain: set the m_verivation_failed flag in a couple more places

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
This can happen when there's a very large reorg on the daemon
(ie, on testnet)
> wallet2: recover from index out of hashchain bounds error

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
This implements locked_sweep_all for the simplewallet and fixes a small bug in sweep_main
> monero-wallet-cli: added locked_sweep_all command

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Also added notes to `WalletManager::verifyWalletPassword` (which afaik seems unused
by anyone at the moment) regarding the need to unlock the keys file beforehand.
> wallet2: unlock keys file before calling verify_password (needed for Windows)

- contrib/epee/src/memwipe.c
> memwipe: don't call the workhorse for 0 bytes

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
as per "An Empirical Analysis of Linkability in the Monero
Blockchain", by Miller et al.
> wallet2: use a gamma distribution to pick fake outs

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
Before :
```
[76.204.26.194:18080 OUT]  Synced 20801/1597463
```
Now :
```
[201.153.31.87:18080 OUT]  Synced 35371/1597473 2% (1562102 blocks remaining)
```
Tested on Ubuntu 17.10 (amd64), Ubuntu 18.04 (amd64) and working for both (not very incredible, I just add some text processioning).
It was requested in #4014 
This pr is clone of #4017
> [monerod][Tested Working][Request Execution] Added blocks remaining count and percent of advancment during syncronisation

- tests/unit_tests/ringdb.cpp
Fixes failing test during Arch package build (due to attempt to write to
~/.bitmonero/...). Also, now it is consistent with other tests.
> tests: ringdb: use --data-dir arg

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Motivated by this discussion: https://www.reddit.com/r/Monero/comments/92ekxo/i_sent_monero_to_binance_from_mymonero_but_havent/
This patch allows users to import tx secret keys after restoring a wallet that was originally created using 3rd party wallet services, like MyMonero, so that tx proofs can then be generated.
> simplewallet: add set_tx_key for importing tx keys from 3rd party wallets

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
Currently, when simplewallet resotres a wallet, the refresh height setting is changed after the creation (call to `new_wallet` or `restore`), and it doesn't get saved unless the user explicitly updates the wallet settings via the `set` command.
An example:
```
~/monero$ ./monero-wallet-cli --stagenet --restore-deterministic-wallet --generate-new-wallet wallets/temp-1
This is the command line monero wallet. It needs to connect to a monero
daemon to work correctly.
WARNING: Do not reuse your Monero keys on an another fork, UNLESS this fork has key reuse mitigations built in. Doing so will harm your privacy.
Monero 'Lithium Luna' (v0.12.3.0-release)
Logging to ./monero-wallet-cli.log
Specify Electrum seed: ashtray testing metro bovine cabin using wipeout lectures vaults directed fruit …
```
> simplewallet: make sure wallet config is stored right after creation

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet_manager.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- tests/unit_tests/serialization.cpp
The `--restricted-rpc` option is currently included in the args list of `monero-wallet-cli`, but it is only used in `monero-wallet-rpc`.
> wallet2: make --restricted-rpc available for wallet RPC only

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
This avoids constant rechecking of the same things each time
a miner asks for the block template. The tx pool maintains
a cookie to allow users to detect when the pool state changed,
which means the block template needs rebuilding.
This is the same patch as https://github.com/monero-project/monero/pull/810 ported to current master, as reservations were withdrawn.
> core: cache block template where possible

- contrib/epee/src/mlog.cpp
eg, --log-file=foo.log
This would otherwise throw and crash with a stack overflow
> mlog: handle filenames without parent directories

- src/blockchain_db/berkeleydb/db_bdb.h
- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- tests/unit_tests/hardfork.cpp
It was actually incorrect, as it would not return commitment
> blockchain_db: remove unused get_output_key variant

- src/blockchain_db/blockchain_db.cpp
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
Blocks have a very wide range, whereas actual size is the relevant
quantity to consider when syncing
> core: sync database based on bytes added, not blocks added

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
Non fluffy block nodes should now be very rare
> cryptonote_protocol: don't serialize an unneeded new block message

- src/ringct/rctTypes.h
- src/rpc/daemon_handler.cpp
- src/rpc/message_data_structs.h
- src/serialization/json_object.cpp
- src/serialization/json_object.h
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/json_serialization.cpp
`GET_BLOCKS_FAST` was broken, and `pseudo_outs` in transaction wasn't being sent if bulletproof. This does aggressively change the names of some fields simultaneously, so take a look. Other motivations were more descriptive names ("prunable" instead of "p", etc), and "flattening" the variant for inputs and outputs.
> Fixed ZMQ-RPC for transactions and GET_BLOCKS_FAST

- README.md
I didn't change the minimum version in the table though, because 0.12.0 will work for this block version
> update README to change all 0.12.2 to 0.12.3

- src/simplewallet/simplewallet.cpp
Division by 365.25 does of course result in years, not months ...
> simplewallet: correct number of human-readable months

- src/simplewallet/simplewallet.cpp
Many people are using this as a "let's see what this does" command
when something doesn't work as they thought it should, and thus
destroying info that they might still need.
> simplewallet: add a warning and prompt on rescan_blockchain

- Dockerfile
- contrib/codefresh/codefresh.yml
> Added Codefresh.yml pipeline

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
Refresh command added to `monero-wallet-rpc` so we can manually invoke resync from RPC API.
> rpc-wallet: refresh command added

- README.md
I'm not so confident, but it seems like the development package is required for Debian/Ubuntu (and probably also for Fedora)? Or is it optional that can be skipped using some switch in ZeroMQ?
Addressing #3203
> README: add dependency on libpgm-dev

- src/wallet/node_rpc_proxy.cpp
- src/wallet/wallet2.cpp
xref https://github.com/ryo-currency/ryo-currency/pull/86
> Backport of Ryo fix for a wallet caching bug

- src/simplewallet/simplewallet.cpp
After I thoroughly studied C++/Boost thread sync support and its use in `simplewallet` I noticed that the `LOCK_IDLE_SCOPE` macro does not contain any outright bug, but is nevertheless needlessly complex and does things that have no effect, and I propose to simplify it from 10 lines of code down to 3.
Two threads within `simplewallet` must be in sync when accessing / changing the `wallet2` object: The main thread and the idle thread that does autorefresh. Sync is done through locks on the `m_idle_mutex` mutex: The thread that manages to put a lock on that mutex can be sure to have exclusive access to the wallet until the lock is lifted.
The main thread uses the `LOCK_IDLE_SCOPE` macro to lock and relies on the destructor of the `boost::unique_lock` object at the end of the method in …
> simplewallet: Simplify LOCK_IDLE_SCOPE macro

- README.md
- src/crypto/CMakeLists.txt
- src/crypto/crypto.h
- src/device/device_ledger.cpp
- src/ringct/rctTypes.h
- tests/performance_tests/equality.h
- tests/performance_tests/main.cpp
- tests/unit_tests/crypto.cpp
Oddly, it looks like while it's way slower than memcmp, the timings for both different and equal are pretty similar for both.
> add and use constant time 32 byte equality function

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- tests/functional_tests/transactions_flow_test.cpp
The setting for trusting the daemon or not is common to all of the CLI, the RPC and the GUI, so it seems natural to move the boolean variable to wallet2. This also makes the `--untrusted-daemon` flag available to the RPC which was missing previously.
Consequently, the boolean arg `trusted_daemon` to many functions of `wallet2` was dropped. Note, however, that this wasn't applied to `wallet2::refresh()` because the existing code contains a few instances of calling `refresh(false)`.
> wallet: store trusted-daemon flag in wallet2

- src/crypto/keccak.c
- src/crypto/keccak.h
- needed for TREZOR integration
> Incremental Keccak API

- tests/unit_tests/serialization.cpp
This actually prevents copy elision
> unit_tests: remove std::move in return statement

- src/ringct/rctTypes.h
This might avoid unnecessary copies.
Reported by stoffu
> ringct: make conversion functions return const refs

- CMakeLists.txt
Current GCC produces broken binaries with these options
> CMakeLists.txt: disable -fstack-protector* on windows

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
> wallet: Add close_wallet RPC

- src/blockchain_db/lmdb/db_lmdb.cpp
- src/common/util.cpp
- src/common/util.h
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/is_hdd.cpp
First two commits have been discussed in [#4278](https://github.com/monero-project/monero/pull/4278#issuecomment-414245928)
> is_hdd: update for linux only

- src/device/device_ledger.cpp
Transaction on testnet with V8.8 blocks seems to work.
> Add bulletproof support

- Makefile
One build directory per branch/arch.
This proposal allows to perform multiple compilation from different branch/arch in
separate directories.
Example:
build
├── GNU_Linux
│   ├── multi-compilation
│   │   └── release
│   └── NanoS-USBHID
│       └── release
└── Msys
└── NanoS-USBHID
└── release
Edit 1:
Try to handle special char as : / \ .
--data-dir in unit test not yet tested
Edit 2:
donot use param for uname. -o is not supported by MacOS.
> One build directory per branch/arch.

- contrib/epee/include/net/abstract_tcp_server2.inl
When this throws in a loop, stack trace generation can take
a significant amount of CPU
> epee: use the socket::bind variant which does not throw

- src/common/dns_utils.cpp
It should be useful from the 11th of october 2018.
The old key is still trusted for now.
https://www.icann.org/resources/pages/ksk-rollover
> dns_util: add new DNSSEC trust anchor for rollover

- src/wallet/wallet_rpc_server_commands_defs.h
This removes the unused fields `tx_key`, `fee` & `tx_blob`.
Those are not close to be added in wallet_rpc_server.cpp (which only return tx_hash on line 1262), and at least `fee` is misleading as defaulting to `0` when the `relay_tx` method is used.
> wallet_rpc_server: remove unused fields in relay_tx RPC

- src/wallet/wallet2.cpp
Motivated by a user error reported by el00ruobuob_ on IRC
> wallet2.get_reserve_proof: throw when specified amount is zero

- src/cryptonote_basic/account.cpp
- src/cryptonote_basic/account.h
- src/device/device.cpp
- src/device/device.hpp
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- Device name is a new wallet property
- Full device name is now a bit more structured so we can address particular device vendor + device path. Example: `Ledger`, `Trezor:udp`, `Trezor:udp:127.0.0.1:21324`, `Trezor:bridge:usb01`. The part before `:` identifies HW device implementation, the optional part after `:` is device path to look for.
- Device registry changed a bit so devices can be registered also in runtime - required for Trezor to break circular dependencies (Trezor is in separate cmake module as it has more dependencies which would cause circular deps)
- New --hw-device parameter added to the wallet, can name the hardware device
- Device reconnect  command added to wallet2 and simplewallet
> hw_device: support for multiple devices added [for review]

- src/gen_multisig/gen_multisig.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- tests/functional_tests/transactions_flow_test.cpp
- tests/unit_tests/multisig.cpp
Sending funds with the GUI got broken with #4131 because setting the wallet setting `m_rpc` to true in the API was done in `WalletImpl::doInit` which is called after calling `wallet2::load_keys`, meaning that the spend key got encrypted nevertheless. This patch fixes this by making sure that the `m_rpc` is properly set in the ctor of `wallet2` which is called from the ctor of `WalletImpl`.
> api/wallet: properly disable key encryption

- contrib/epee/include/hex.h
- contrib/epee/include/wipeable_string.h
- contrib/epee/src/wipeable_string.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet_rpc_server.cpp
- tests/unit_tests/wipeable_string.cpp
The main remaining uses of std::string with secret data now seems to be multisig generation and sending secrets over the network. For the latter, maybe the client could send a public key with which to encrypt the data. For multisig, I don't know.
> More use of wipeable_string

- src/mnemonics/chinese_simplified.h
- src/mnemonics/dutch.h
- src/mnemonics/english.h
- src/mnemonics/english_old.h
- src/mnemonics/esperanto.h
- src/mnemonics/french.h
- src/mnemonics/german.h
- src/mnemonics/italian.h
- src/mnemonics/japanese.h
- src/mnemonics/language_base.h
- src/mnemonics/lojban.h
- src/mnemonics/portuguese.h
- src/mnemonics/russian.h
- src/mnemonics/spanish.h
from several minutes to 10-15 seconds
> mnemonics: fix outrageous compile time with CLANG in release

- src/daemon/main.cpp
- src/rpc/rpc_args.cpp
- passing by parameter is insecure as it is shown in the process list
- using environment variable for passing the password is more secure with this respect
Thanks for considering.
> rpc: allow to pass RPC login via RPC_LOGIN env var

- src/cryptonote_core/blockchain.cpp
> blockchain: add mainnet v8 height targetting 18 october

- src/daemon/rpc_command_executor.cpp
This fixes the horrendous slowdown in bc_dyn_stats
> daemon: request no PoW hashes we don't need when asking for blocks

- src/wallet/wallet2.cpp
Calling code needs to know if the operation has been finished successfully.
This PR fixes issue https://github.com/monero-project/monero/issues/4359
> wallet2: import_multisig forward refresh exception

- src/ringct/rctTypes.h
I realized that the new BP format is being serialized incorrectly when using the updated https://github.com/moneroexamples/onion-monero-blockchain-explorer:
With this patch:
> rctTypes: fix incorrect serialization

- contrib/epee/include/span.h
- tests/unit_tests/epee_utils.cpp
- Support for classes
- Added `remove_prefix` function
- Added `to_mut_span` and `as_mut_byte_span`
@moneromooo-monero 
The light-wallet-server also these functions.
> Added features to epee::span<T> :

- src/device/device.hpp
- src/device/device_default.hpp
- src/device/device_ledger.hpp
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/api/wallet_manager.cpp
- src/wallet/api/wallet_manager.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Provides ```WalletManager::queryWalletHardware()``` in the wallet API to query if (and how) the wallet is hardware-backed. This also implicitly verifies the wallet password without the need for the hardware to be connected. (```WalletManager::verifyWalletPassword()``` does not work on hardware-backed wallets without the hardware device being connected, so in order to check if a wallet is hardware-backed, the hardware needs to be connected...) These two methods share a lot of code, but I am still at a loss of how to refactor it well. Enumeration of the Hardware Devices might also be in order, but as current code assumes Ledger or not (boolean) I did not.
This PR also provides ```key_on_device``` to the Wallet API to enable handling of open wallets appropriately.
> [WalletAPI] Allow query if Wallet is on hardware

- src/common/CMakeLists.txt
- src/common/error.cpp
- src/common/error.h
- src/common/expect.cpp
- src/common/expect.h
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/expect.cpp
This is used heavily in the [light wallet server PR](https://github.com/monero-project/monero/pull/4139). It provides a value-or-error object similar to `result<T, E>` in Rust or `expected<T, E>` / `outcome<T, E>` as seen on the boost mailing lists. The behavior in use in the light wallet library:
* `T foo() noexcept;` can never fail.
* `T foo();` only has unrecoverable errors.
* `expect<T> foo() noexcept;` only has recoverable errors.
* `expect<T> foo();` has recoverable and unrecoverable errors.
In other words, throwing an exception is for shutting down the process whereas `expect<T>` is for returning errors that can be handled. The error type is `std::error_code` which is extensible - making it possible to track the source of an error. Example with LMDB errors:
```c++
namespace
{ …
```
> expect<T> - a value-or-error implementation

- contrib/epee/src/mlog.cpp
They're controllable by potential attackers and would just spam
> mlog: do not display http errors by default

- src/wallet/node_rpc_proxy.cpp
This makes it easier to avoid bugs on the caller side if errors are
represented by non empty strings.
This fixes the refresh height setting in new wallets when no daemon
is running.
> node_rpc_proxy: return a non empty error string on connection failure

- Dockerfile
Given the issue #4396, a problem copying files during the multi-stage docker build, this PR fixes the bug.
> Fixes Dockerfile build problem #4396

- Dockerfile
- utils/build_scripts/android32.Dockerfile
Otherwise it only works with branch master (and it's currently missing `bin` dir)
> Dockerfile: use single build dir

- src/common/dns_utils.cpp
A few of them are now returning invalid replies.
> dns_utils: refresh list of usable DNSSEC servers

- src/cryptonote_core/cryptonote_tx_utils.cpp
> build: fix gcc false positive 'stringop-overflow' warning

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
Since subaddresses were added, a tx can now create more than
one payment
> wallet_rpc_server: include all transfer records for a txid

- src/blockchain_db/lmdb/db_lmdb.cpp
Should only stop the rtxn if we actually started it
Fixes Coverity 184960
> Fix rtxn usage in BlockchainLMDB::get_estimated_batch_size

- src/common/password.cpp
- src/common/util.cpp
- src/common/util.h
- src/simplewallet/simplewallet.cpp
**Issue description** : https://github.com/ryo-currency/ryo-currency/pull/102
**Monero Issue** : #4351
> simplewallet: Add Unicode input_line [Ryo backport]

- src/gen_multisig/gen_multisig.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- translations/monero.ts
Some strings were not detected by lupdate because "tr() cannot be called without
context".
> Fix some calls to the translation function

- README.md
According to #4203 I successfully built v0.13.0.2-RC2 with functional Ledger support after installing `mingw-w64-x86_64-hidapi` in MSYS2. And the deps table indicates it should not be optional so I add it in instruction.
> README: update MSYS2 dependencies for Ledger

- Makefile
- README.md
- utils/build_scripts/android64.Dockerfile
This patch adds a new Dockerfile to build for Android 64-bit and modify the README to add details and fix output directory where to fetch the binaries from.
This should fix issue https://github.com/monero-project/monero/issues/4478
> Utils: Add Dockerfile for android 64-bit build

- src/wallet/wallet2.cpp
This code was deciding which bulletproof configuration to use
based on ptx which weren't created yet.
> wallet2: fix cold signing using non padded bulletproofs

- src/wallet/wallet2.cpp
Same as #4574 but this is to master
> [Wallet API] query_device() defaults to SOFTWARE

- Dockerfile
The Docker image is failing to build, as the submodules are not being
explicitly initialized and updated.
Fixes: https://github.com/monero-project/monero/issues/4582
Signed-off-by: Tyler Baker <tyler@foundries.io>
> Dockerfile: init and update submodules

- src/wallet/api/wallet.cpp
It was creating a new wallet without a password first (this should
be fixed), then not changing the password correctly
> wallet2_api: fix generating new wallet in the GUI

- src/common/spawn.cpp
- src/common/util.cpp
- src/common/util.h
No need to give whatever we're calling access to what we use
> spawn: close all file descriptors before execve

- contrib/epee/src/mlog.cpp
For best results use `set TERM=xterm` in Command prompt before running a Monero binary. Or use `setx TERM xterm` to make the change permanent in environment variables of your %USERNAME%.
Only works on newer versions of Windows 10.
> ANSI colors in Windows 10

- src/cryptonote_core/tx_pool.cpp
- src/rpc/core_rpc_server.cpp
…rsion in get_transactions RPC
Fixes problem made in #4592
I believe this renaming is justified because the distinction between raw blobs and hex strings can be very confusing.
> tx_pool: revert #4592 and move bin2hex conversion to on_get_transaction_pool

- src/rpc/core_rpc_server.cpp
0 is placeholder for whole chain, so we should compare chain
height changes rather than chain-height-or-zero. Even this isn't
totally foolproof if a blocks are popped and the same number
added again, but it is much better as it prevents the data from
slowly going out of sync.
> rpc: fix output distribution caching ignoring chain changes

- contrib/epee/include/console_handler.h
It's a common confusion point for users which run monerod
without stdin and with --detach
> console_handler: add a global log when exiting via EOF

- contrib/epee/src/mlog.cpp
For best results use `set TERM=xterm` in Command prompt before running a Monero binary. Or use `setx TERM xterm` to make the change permanent in environment variables of your %USERNAME%.
Only works on newer versions of Windows 10.
> ANSI colors in Windows 10 (v0.13)

- src/cryptonote_basic/cryptonote_basic.h
- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_basic/cryptonote_format_utils.h
- src/cryptonote_core/cryptonote_tx_utils.cpp
- tests/unit_tests/test_tx_utils.cpp
This removes some small amount of fingerprinting entropy.
There is no consensus rule to require this since this field
is technically free form, and a transaction is free to have
custom data in it.
> cryptonote: sort tx_extra fields

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
The warning threshold is set to allow a false positive every
ten days on average.
> cryptonote_core: warn when the block rate deviates from expectations

- translations/monero_ja.ts
Translate all contexts but simple_wallet for Japanese, translate 23% of simple_wallet for Japanese. Depending on how things are determined in monero-dev channel (e.g. suggested that 0.13 branch only be bug fix commits post 0.13 release), I will push the remaining translations to the relevant branch.
> Translate all contexts but simple_wallet for Japanese, translate 23% of simple_wallet for Japanese

- contrib/depends/packages/libiconv.mk
- contrib/depends/packages/sodium.mk
- contrib/depends/patches/libiconv/fix-whitespace.patch
- contrib/depends/patches/sodium/fix-whitespace.patch
- contrib/gitian/README.md
- contrib/gitian/gitian-build.py
- contrib/gitian/gitian-linux.yml
- contrib/gitian/gitian-osx.yml
- contrib/gitian/gitian-win.yml
- contrib/gitian/symbol-check.py
This adds a gitian build script and gitian descriptor to achieve reproducible builds in monero. 
Currently the build script in gitian-build.py still clones bitcoin's repository used to exchange, compare and store signatures. These two repos should be created on monero, namely gitian.sigs and ~monero-detached-sigs~. Edit: since no apple or windows certs are required, monero-detached-sigs is not needed. 
It also just builds Linux binaries at the moment. Gitian descriptors for OSX and windows still need to be created. 
To test this out, create a remote copy of this branch on your fork, tag a version to it in the format 'vN.N.N' and prepare the host as depicted in the README included in this pull request. Then setup and run a detached signature build.
Please post reported checksums below, so …
> Add gitian build script

- src/common/util.cpp
This PR contains 2 patches for the Windows daemon:
- Add detection of OS versions newer than Windows 7 when calling **--os-version** argument
- Fix terminal colors on newer versions of Windows 10 - see issue https://github.com/monero-project/monero/issues/1934
This was tested working on Windows 10 build 14393.
> Windows: improve version detection

- src/simplewallet/simplewallet.cpp
Affects any platform that uses fork/clone to implement threads.
The bug occurs due to the signal handler being set before we start background refresh thread, so signal handling will be inherited by the background refresh thread as well.
SIGINT handler will be executed in arbitrary thread's context.
Deadlock occurs if a user hits CTRL+C twice.
Locks:
1. Global mutex in SIGINT handler
https://github.com/monero-project/monero/blob/master/src/common/util.h#L213
2. Condition variable mutex 
https://github.com/monero-project/monero/blob/master/src/simplewallet/simplewallet.cpp#L7000
https://github.com/monero-project/monero/blob/master/src/simplewallet/simplewallet.cpp#L7057
> simplewallet: fixed deadlock if a user hits CTRL+C twice

- contrib/epee/include/readline_buffer.h
- contrib/epee/src/readline_buffer.cpp
It happens when readline displays a prompt just before switching
to a shorter one
> readline_buffer: fix "cursor in prompt" bug

- src/rpc/core_rpc_server.cpp
Fix for #4399.
Also unifies code for serializing pruned tx to binary/json into one.
Example query:
$ curl -H 'Content-Type: application/json' -X POST http://127.0.0.1:18081/get_transactions -d '{"txs_hashes":["eaf5e7be5d346aadb4855bcf701d3758c8f298a4d7dfbf74ab73de2242381003"],"decode_as_json":true,"prune":true}'
Invalid JSON string returned by the current master (note the missing curly brackets at the front and the back):
"as_hex": "02000102000787d127c2fc54f9de7bf2cc289ff82fffc509fbf922c675477a4493922aa6fbafb4ca404511a54f89e5c486e4466dbcd10ca751f0bd02000280f421bb61df58295fcd9b54ef90f73e0eb17bec935fb0e26878925685cdca01000264f3083552ce5dca50c8f4337a22d9b6348fea5028831909ae71f8422a9d527021010acac7df0cdf5b9961be7b5ecef7efa949c209e40f933dbf32fc531cd4c7ecea018090dfc04ad6d480da4434e8ab5f685454991 …
> rpc: fix wrongly formatted JSON for pruned tx

- Makefile
- README.md
Depends can now be compiled with `make depends target=$triple`, where
$triple is one of the supported build targets.
Adapt the Makefile for this change, remove not needed windows deps from
depends setup description.
> Add building with depends to the Makefile

- src/daemon/rpc_command_executor.cpp
Fixes #4576
The output does have a pretty long address. We can do two things;
* Show only part of the mining address.
* Create a dedicated command with mining information.
> daemon: Show mining address

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
Changeset: `rescan_bc` command implemented in WalletAPI as `Wallet::rescanBlockchain()` and `Wallet::rescanBlockchainAsync()` methods.
Rationale: This functionality was required by mobile wallet team.
Notes: `WalletListener::refreshed()` callback is called only after `Wallet::rescanBlockchain()` is finished (It could be requested in background thread even while earlier `Wallet::refreshAsync()` is going on). This is implemented as a cycle in `doRefresh()` until `m_refreshShouldRescan==false`
> WalletAPI: rescanBlockchain, rescanBlockchainAsync

- src/simplewallet/simplewallet.cpp
- translations/monero.ts
- translations/monero_fr.ts
- translations/monero_it.ts
- translations/monero_sv.ts
Describe the output format.
If Monero is interested in this patch, I can update more CLI wallet help messages in a similar way. Only submitting one now to make the review and potential discussion easier. Once I learn if there are any changes necessary, I can submit more messages in one MR.
> Simplewallet: update help text for show_transfers.

- src/common/perf_timer.cpp
- src/common/perf_timer.h
Makes it easier to enable what we need
> perf_timer: separate log categories based on caller categories

- README.i18n.md
Just noticed this inconsistency. Not sure when the repo was renamed from monero-core to monero-gui.
As a side note, I think some improvements to terminology consistency(Monero GUI/Monero Core GUI/Monero Core) could help with general understanding in the community. Unsure if a sort of wiki for this already exists or not.
> Updating Monero GUI repo link in README.i18n.md

- src/cryptonote_core/cryptonote_core.cpp
Because it's proving hard to get it without the reformatting.
> cryptonote_core: fix build error gcc 5.4.0 'sign-compare'

- src/mnemonics/electrum-words.cpp
To support 13-word (and any other size for the future) mnemonics by avoiding out of bounds memory access in callers like bytes_to_words, etc.
> Updated electrum-words/create_checksum_index to support variable word list length

- src/wallet/wallet2.cpp
Looks like it gets reverted anyway
> wallet2/create_transactions_2: removed extraneous shuffle before sort of unused_*_indices_per_subaddr

- src/rpc/CMakeLists.txt
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/rpc/daemon_handler.cpp
- src/rpc/daemon_handler.h
- src/rpc/daemon_messages.cpp
- src/rpc/daemon_messages.h
- src/rpc/message_data_structs.h
- src/rpc/rpc_handler.cpp
- src/rpc/rpc_handler.h
- src/serialization/json_object.cpp
- src/serialization/json_object.h
- src/wallet/wallet2.cpp
The OSS light-server-wallet will make use of these changes. Please look at the fee estimate one, it differs from the HTTP-JSON-RPC one slightly - it returns `base_fee`, `size_scale`, `fee_mask`, and `hard_fork_version`. The size scale isn't strictly needed, but its somewhat nice to avoid having the clients check version to determine whether the base rate is per-byte or per-kibibyte. If useful, I will update the HTTP-JSON-RPC call eventually.
The output distribution for calls for ZMQ-JSON-RPC and HTTP-JSON-RPC both use the same caching mechanism (including the recent update by @moneromooo-monero ).
> Update ZMQ fee estimate and add ZMQ output distribution

- src/cryptonote_core/tx_pool.cpp
Seem to be using receive time to subtract the weight, but prune doesn't get called often in reality and lesser so now with Bulletproofs.
> Fix prune using receive time as tx_weight

- src/rpc/CMakeLists.txt
@fluffypony, build of 7e2483e yields the following error
```
Undefined symbols for architecture x86_64:
"cryptonote::core::get_output_distribution(unsigned long long, unsigned long long, unsigned long long, unsigned long long&, std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> >&, unsigned long long&) const", referenced from:
cryptonote::rpc::RpcHandler::get_output_distribution(cryptonote::core&, unsigned long long, unsigned long long, unsigned long long, bool) in rpc_handler.cpp.o
```
This PR fixes the compilation error.
> rpc: fix linking error of 6097472, get_output_distribution

- contrib/epee/include/net/abstract_tcp_server2.inl
This would make monerod use 100% CPU when running with torsocks
without Tor running
> abstract_tcp_server2: fix busy calling of idle IO service

- external/easylogging++/easylogging++.cc
- external/easylogging++/easylogging++.h
It's not actually needed for this use, and saves a STL header
> easylogging++: remove std::deque usage

- src/crypto/slow-hash.c
- These functions are declared twice in slow-hash.c. Remove one of the copies.
- The declarations have the wrong return type, should be void, not int.
Function definitions here: https://github.com/monero-project/monero/blob/1e74586ee99e4bd89626d2eb4d23883cd91f0f81/src/crypto/aesb.c#L151-L180
Test plan: make release-test
> Small function declaration cleanup in slow-hash.c

- src/wallet/wallet2.cpp
As discovered in [#4674](https://github.com/monero-project/monero/issues/4674#issuecomment-433190600), if the wallet .keys file needs to be updated -- for example, if the password is changed -- it is rewritten in an unsafe manner: the existing file is truncated and then rewritten, so if the process were to crash in between these two steps, the keys would be lost.
This patch fixes that by using the same mechanism already used to update the history file: write the data to a new file, and rename it into place.
> wallet2: rewrite keys file in a safer manner

- tests/unit_tests/keccak.cpp
```c++
C:/msys32/home/buildbot/slave/monero-static-win32/build/tests/unit_tests/keccak.cpp: In member function 'virtual void keccak_0_and_0_Test::TestBody()':
C:/msys32/home/buildbot/slave/monero-static-win32/build/tests/unit_tests/keccak.cpp:40:24: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
for (size_t i = 0; i < sz; ++i) \
~~^~~~~~~~~~~~
data[i] = i * 17; \
~~~~~~~~~~~~~~~~~~~ 
uint8_t md0[32], md1[32]; \
~~~~~~~~~~~~~~~~~~~~~~~~~~~
keccak((const uint8_t*)data.data(), data.size(), md0, 32); \
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
KECCAK_CTX ctx; \
~~~~~~~~~~~~~~~~~     
keccak_init(&ctx); \
~~~~~~~~~~~~~~~~~~~~  
size_t offset = 0; \
~~~~~~~~~~~~~~~~~~~~  
for (size_t i = 0; i < sizeof(chunks) / sizeof(chunks[0]); ++i) \ …
```
> tests: fix MSYS2 gcc 7.3.0 warning -Wtype-limits

- contrib/epee/include/misc_log_ex.h
```c++
In file included from C:/msys32/home/buildbot/slave/monero-static-win32/build/src/common/util.h:45:0,
from C:/msys32/home/buildbot/slave/monero-static-win32/build/src/crypto/crypto.h:42,
from C:/msys32/home/buildbot/slave/monero-static-win32/build/tests/unit_tests/http.cpp:63:
C:/msys32/home/buildbot/slave/monero-static-win32/build/contrib/epee/include/misc_log_ex.h:35:0: warning: "MONERO_DEFAULT_LOG_CATEGORY" redefined
#define MONERO_DEFAULT_LOG_CATEGORY "default"
In file included from C:/msys32/home/buildbot/slave/monero-static-win32/build/tests/unit_tests/http.cpp:30:0:
C:/msys32/home/buildbot/slave/monero-static-win32/build/contrib/epee/include/net/http_auth.h:40:0: note: this is the location of the previous definition
#define MONERO_DEFAULT_LOG_CATEGORY "net.http"
```
> tests: fix MSYS2 warning 'MONERO_DEFAULT_LOG_CATEGORY redefined'

- src/wallet/wallet2.cpp
Even if it is never relayed, it ensures a daemon supplying
fake outs on demand will never be asked for a set with the
real input being the only intersecting member (only a problem
with people who trust their privacy to some stranger's node,
but it seems to be a massively common thing, even in Monero)
> wallet2: save ring in the ringdb once a tx is created

- src/wallet/CMakeLists.txt
This fixes problem with building monero-gui, see [issue](https://github.com/monero-project/monero-gui/issues/1726). Symbols from device_trezor were missing in wallet_merged.
> Fix build of monero-gui by adding device_trezor to wallet_merged

- src/wallet/wallet2.cpp
@iDunk5400 reported in #monero-dev
> Current master on Ubuntu 16.04 (GCC 5.4.0)  https://paste.fedoraproject.org/paste/LbcCnZn31BNLwhHXQU0fqQ/raw
> build: fix Ubuntu 16.04 (GCC 5.4.0) compilation

- src/common/base58.cpp
Fixes build error, makes `uint_8be_to_64` code consistent with `uint_64_to_8be` implementation.
Build error logs: https://github.com/monero-project/monero/pull/4837#issuecomment-437998175
> common: fix base58 gcc -Werror=implicit-fallthrough

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
hi,
this is the on_restore_deterministic_wallet RPC call for restoring a wallet with a given seed. optionally specify restore_height, seed_offset.
takes all arguments of monero-wallet-cli when starting with --restore-deterministic-wallet:
* seed
* seed_offset
* password
* restore_height
* filename (wallet name)
build and tested successfully on Ubuntu 16.04.
also hopefully satisfies #4058
> wallet_rpc: add on_restore_deterministic_wallet RPC

- src/rpc/core_rpc_server.cpp
If you request the current block height you end up with an error message like `"Too big height: 1692829, current blockchain height = 1692829"`, can be confusing. Instead it should use the top block height (current block height - 1).
> rpc: use block_height - 1 for top block height in error messages

- README.md
Increased swap size on raspberry pi compiling guide, since it might crash if the raspberry has any service runing in the background
> README.md: increase swap size on Raspberry Pi

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
This pull request adds a new `export_transfers` command to the wallet cli that exports the transfers to a csv file.
Since `show_transfers` and `export_transfers` basically require the same data, I've added a new function `get_transfers` that returns a vector of `transfer_view` structs (new structure as well). That function does all the querying, calculations, sorting and can consume some of the common arguments.
Then, it's up to the caller function to display the data in the appropriate way (print or export as csv).
Notable difference between the csv file and the printed list of transfers:
- The csv file shows the "running balance" next the the transfer amount. This field is not affected by unconfirmed transfers (pending/failed/pool).
- To handle transfers with multiple outputs, the csv …
> Add new command "export_transfers" to save transfers to csv

- src/cryptonote_core/tx_pool.h
It was leftover from a change that was undone before commit,
but the comment change was let through
> tx_pool: fix comment about transaction_prefix

- src/cryptonote_core/tx_pool.cpp
This should make it possible to have two daemons running on the
same database again.
> tx_pool: allow take_tx to work without m_txs_by_fee_and_receive_time

- src/cryptonote_config.h
- src/p2p/net_node.cpp
- src/p2p/net_node.h
Bandwidth constrained monerod node owners may want to know the limit-rate-up and limit-rate-down default values so that they can be set if needed before running the node, but --help does not display those values (only the -1 default). The only way to find out those values is by looking at the source code (currently 2048 & 8192 kB/s), or by running the node and then getting the value. 
Made changes to expose those values when ./monerod --help is entered.
> Expose limit-rate defaults from command line help

- src/wallet/wallet_rpc_server.cpp
> wallet_rpc_server: include additional tx keys in sign_transfer response

- contrib/epee/src/mlocker.cpp
leak the mutex instead, it's a one off
> mlocker: fix dtor ordering problem

- src/simplewallet/simplewallet.cpp
try_connect_to_daemon with silent=false already prints failure message
> simplewallet: remove redundant messages on daemon connection failure

- src/wallet/wallet2.cpp
When a tx gets from unconfirmed to conirmed, the rings for that
transaction were being added twice
> wallet2: fix print_ring printing double entries for transactions

- src/simplewallet/simplewallet.cpp
Currently, the wallet skips asking for password when it's watch-only, which seems wrong since it still has some amount of secret information such as the view key.
> simplewallet: don't skip asking for password when watch-only

- src/wallet/wallet2.cpp
15:43 < hahsun> Im on stagenet and I suddenly get this exception: 2018-11-04 14:42:52.416 [RPC0] ERROR wallet.wallet2 src/wallet/wallet2.cpp:2070 !m_blockchain.is_in_bounds(current_index). THROW EXCEPTION: error::out_of_hashchain_bounds_error
16:01 <+moneromooo> OK, possibly because the blckchain is always seeded with the genesis block hash...
16:02 <+moneromooo> So that case should be allowed, assuming it doesn't break the code around it.
16:05 <+moneromooo> OK if stop_height == size || (size==1 && stop_heigt ==0)
16:05 <+moneromooo> Throw if not that.
16:06 < hahsun> k
> wallet2: fix out_of_hashchain_bounds_error in refresh

- src/ringct/rctOps.cpp
saves a conversion, and uses a double scalarmult instead of
two scalarmults
> rct: speedup commit a little

- contrib/gitian/README.md
- contrib/gitian/gitian-build.py
The version prefix 'v' should just be set constantly.
This should allow building commits as well, if a commit is passed in instead of a tag.
Reflect this change in the README as well.
> Fix version prefix in gitian build

- src/common/CMakeLists.txt
- src/common/combinator.cpp
- src/common/combinator.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
This PR fixes issue #4793
The problem was in insufficient LR pairs and supplementary transactions generated. Unlike standard N/N and N-1/N cases M/N sometimes requires more transaction generated to exclude all combinations of signers that may possibly to decline current transaction.
Hence, in 2/4 wallets with signers A, B, C and D with A be a transaction creator wallet needs to pick one more signer by excluding 2-of-3 possible signers combinations. So wallet have to create transactions with following signers to exclude: `BC`, `BD` and `CD`. 
I think it's worth to include this fix in point release as well.
PS. Huge thanks to @rbrunner7 for active collaboration and his help with testing it!
> Fix issue 4793 - M/N multisig transaction signature

- src/daemon/daemon.cpp
- src/daemon/rpc.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
This can go out of sync with m_core's nettype if you run in fakechain mode since entering fakechain mode is done through code not the command line and core_rpc_server only looks at the command line to figure out the nettype it launches in.
> Don't cache nettype in core_rpc_server use m_core

- src/cryptonote_basic/miner.cpp
- src/cryptonote_core/blockchain.cpp
- src/rpc/core_rpc_server.cpp
block already has a default ctor, and the extra object
churn due to its innards (vectors, etc) is pointless.
> Avoid unnecessary temp block and copy ctor

- src/blockchain_db/lmdb/db_lmdb.cpp
> lmdb: fix gcc 7.3.0 'implicit-fallthrough' warning

- contrib/epee/src/mlocker.cpp
This prevents exceptions from showing up in various awkward
places such as dtors, since the only exception that can be
thrown is a lock failure, and nothing handles a lock failure
anyway.
> mlocker: don't throw from lock/unlock

- contrib/epee/src/mlocker.cpp
> mlocker: fix access to global lock map after dtor on exit

- src/wallet/wallet2.cpp
Motivated by https://monero.stackexchange.com/questions/10483
Some exchanges appear to have customized the wallet software
in an inappropriate way, making the tx extra field partially
unreadable. PR #3716 changed the wallet behavior disallowing
such partially valid tx extra.
An example tx reported by the user is
e87c675a85f34ecac58a8846613d25062f1813e1023c552b705afad32b972c38
where the normal tx pubkey appears again with the aditional
tx pubkeys tag `04` which is inappropriate.
> wallet2: resume processing when tx extra is partially broken

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_protocol/cryptonote_protocol_defs.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- tests/core_proxy/core_proxy.h
- tests/unit_tests/ban.cpp
To help protect one's privacy from traffic volume analysis
for people using Tor or I2P. This will really fly once we
relay txes on a timer rather than on demand, though.
Off by default for now since it's wasteful and doesn't bring
anything until I2P's in.
> protocol: option to pad transaction relay to the next kB

- contrib/valgrind/monero.supp
- external/easylogging++/easylogging++.cc
- external/easylogging++/easylogging++.h
If someone has a better patch, feel free.
> easylogging++: faster access to logging

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/blockchain_utilities/CMakeLists.txt
- src/blockchain_utilities/blockchain_prune_known_spent_data.cpp
- tests/unit_tests/testdb.h
Only for pre rct for obvious reasons.
Note: DO NOT use a known spent list which includes outputs
which are not known spent. If the list includes any output
that's just strongly thought to be spent, but not provably
so, you risk finding yourself unable to sync past the point
where that output is spent.
I estimate only 200 MB saved on current mainnet though,
unless the new blackballing rule unearths a good amount of
large-amount-set extra spent outs.
> Outputs where all amounts are known spent can now be pruned

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
The pull request adds a command "pop_blocks <nblocks>" to monerod.
> add command pop_blocks monerod

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
Some of the inputs for block in a span will be from other earlier
blocks in that span. Keep track of those outputs so we don't have
to look them up again after those early blocks are added to the
blockchain.
> blockchain: avoid unnecessary DB lookups when syncing

- src/cryptonote_core/cryptonote_core.cpp
- src/daemon/daemon.cpp
This avoids the miner erroring out trying to submit blocks
to a core that's already shut down (and avoids pegging
the CPU while we're busy shutting down).
> daemon: stop miner before we bring the whole thing down

- src/cryptonote_basic/cryptonote_basic.h
Since it's all inline, I suspect the compiler will merge the
duplicate stores anyway.
> cryptonote: add a set_null for transaction_prefix

- src/ringct/rctTypes.h
Fixing a build warning on g++ 7.3.0
> Bulletproof: Initialize members in default construtor.

- src/common/util.cpp
- src/common/util.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/CMakeLists.txt
- src/wallet/message_store.cpp
- src/wallet/message_store.h
- src/wallet/message_transporter.cpp
- src/wallet/message_transporter.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
Unlike my earlier PR #4134 back in July with preview code this here is the completed initial version of the MMS (Multisig Messaging System) that I would like to submit for review and later inclusion into the Monero codebase, hopefully ready for going into service with the next hardfork in Spring.
The system was beta-tested extensively, and its functionality was improved and refined over several iterations already.
To make reviewing this considerable amount of new and changed code easier I have written the following text with high-level information about the implementation of the MMS: https://rbrunner7.github.io/mms_code
There you also find links to explanations what this MMS is about in the first place, and instructions how to get the MMS running for testing purposes.
There currently is …
> MMS (Multisig Messaging System): Initial version

- src/simplewallet/simplewallet.cpp
Help messages describe the commands usage. When users run the command
with wrong arguments, it usually helpfully offers the usage, too.
Unfortunately, these two usage messages were duplicated in the code and
started to get out of sync.
Fixing with constant strings.
> Simplewallet: Unify usage messages.

- .travis.yml
- Dockerfile
- cmake/CheckTrezor.cmake
- cmake/test-protobuf.cpp
- cmake/test-protobuf.proto
- contrib/depends/README.md
- contrib/depends/packages/libusb.mk
- contrib/depends/packages/native_protobuf.mk
- contrib/depends/packages/packages.mk
- contrib/depends/toolchain.cmake.in
- src/device_trezor/CMakeLists.txt
- src/wallet/CMakeLists.txt
Fixes `/contrib/depends` for protobuf so it works also in cross-compilation under docker. 
Two packages are needed, `native_protobuf` and `protobuf`. `native_protobuf` builds `protoc` under host so it can use it to generate trezor messages. Native `protoc` is also used during build of the target host `protobuf` dependency. 
Adds dependencies for GUI compilation. Changes to the `monero-wallet-gui.pro` file:
```qmake
TREZOR_LINKER = $$cat($$WALLET_ROOT/lib/trezor_link_flags.txt)
LIBS += $$TREZOR_LINKER -lboost_thread
```
> Build: protobuf fixes for docker, cross-compilation, monero-gui

- src/wallet/wallet2.cpp
They'll get duplicated otherwise
> wallet2: clear all payments on soft rescan_bc

- src/wallet/wallet2.cpp
I started figuring out anomaly big count of log messages during wallet sync:
```
2018-12-14 11:51:10.720	    7fc455397780	DEBUG	wallet.wallet2	src/wallet/wallet2.cpp:2200	Block is already in blockchain: 07df8c064d0eb589ef9b68ff380816a1d69d4b1a9a9e5cfb2d9c740c7bf0091d
2018-12-14 11:51:10.720	    7fc455397780	DEBUG	wallet.wallet2	src/wallet/wallet2.cpp:2200	Block is already in blockchain: 8e8577f8b4bade8a6c2201e8af8603774c9d3c3b6a0fcfda2c45409a5f3b2af4
2018-12-14 11:51:10.720	    7fc455397780	DEBUG	wallet.wallet2	src/wallet/wallet2.cpp:2200	Block is already in blockchain: 7a9e78b73a31b5d03ee30def977a95b4dc386e9e6cdc2e904477a2fcaec99236
2018-12-14 11:51:11.496	    7fc455397780	DEBUG	wallet.wallet2	src/wallet/wallet2.cpp:2200	Block is already in blockchain: …
```
> Sync short hash chain bug fixed

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/rpc/core_rpc_server.cpp
- tests/unit_tests/testdb.h
We know all the data we'll want for getblocks.bin is contiguous
> blockchain_db: speedup tx output gathering

- src/device_trezor/trezor/protocol.cpp
tx_prefix_hash is required in the key derivation for decryption of the tx keys
> device/trezor: store tx_prefix_hash in tx key aux

- src/wallet/wallet2.cpp
It looks like the intention was to hash it for `crypto::generate_ring_signature` but it just uses the key-image wholesale as the hash `(const crypto::hash &)td.m_key_image)` instead.
> Remove unused hash in export_key_images

- contrib/epee/include/string_tools.h
- contrib/epee/src/net_utils_base.cpp
- src/cryptonote_protocol/block_queue.cpp
- src/p2p/net_node.inl
- tests/functional_tests/transactions_flow_test.cpp
- tests/net_load_tests/net_load_tests.h
There is a `boost::uuids::to_string` method since Boost 1.45 and an `operator<<` has long since existed, making these to-strings unnecessary. Moving the other function drops one include from a commonly used header. This also moves things one step closer to removing `boost::lexical` from the header too (which brings in lots of headers itself).
> Remove boost::lexical_cast for uuid and move uuid parser to cpp

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
Also add the type back, as it was somehow weirdly split into
two different fields, one being a union...
> simplewallet: fix show_transfers colouring, and add red for failed

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
To use if you want all key images, not just the ones for
recently imported outputs
> wallet_rpc_server: add all field to export_key_images

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
While the lookups are faster, the zeroCommit calls have to be
done again when storing the new outputs in the db, which ends
up making the whole thing slower after all, and the ways this
can be cached aren't very nice code wise, so let's forget it
since the gains aren't very large anyway.
> cryptonote_core: revert extra_tx_map

- src/simplewallet/simplewallet.cpp
It seemed like a good idea at the time
> simplewallet: remove ability to transfer with detached short payment ids

- contrib/depends/packages/boost.mk
Clang gave a visibility error when compiling boost with visibility hidden.
> Remove visibility settings from boost.mk

- src/simplewallet/simplewallet.cpp
in case it returns 0, and other uses don't, plus it's a estimation anyway.
> simplewallet: don't subtract 1 to estimate blockchain height

- src/simplewallet/simplewallet.cpp
Make the new `exchange_multisig_keys` command in `simplewallet` show the newly established multisig address at the end, like `make_multisig` already does.
> simplewallet: Show new address after going multisig

- README.md
`pacman -Syuu` can either upgrade or degrade the packages (depending upon the package lists), and should not be normally used. Instead of that, one should use `pacman -Syu` which only upgrades the packages.
> Changed Windows build commands.

- contrib/epee/src/readline_buffer.cpp
Per https://github.com/monero-project/monero/issues/3799#issuecomment-453266091
> readline: don't dereference possible NULL pointer

- src/wallet/wallet2.cpp
Half of the patch was correct, but half was introducing another bug,
where a wallet asking for a fork that the daemon does not know about
yet would decide to use those rules.
> wallet2: fix incorrect patch for determining fork rules

- src/wallet/api/subaddress_account.cpp
Same behaviour as subaddress.cpp now.
> wallet api: don't truncate address in subaddress_account

- src/cryptonote_core/blockchain.cpp
If two create_block_template are called at nearly the same time,
and a block is added at nearly the same time, this could happen:
- the blockchain top block is B0
- thread 1 enters create_block_template, takes blockchain lock
- thread 1 creates a fresh block referencing prev block B0
- thread 1 releases blockchain lock
- thread 0 adds a new block
- thread 0 enters create_block_template
- thread 0 updates block template
- thread 1 takes txpool lock and continues creating block template
- thread 1 overwrites block template with previous data
> blockchain: fix block template creation race

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- tests/unit_tests/long_term_block_weight.cpp
It seems to be buggy on reorgs, and prevents the use of
a blockchain with two nodes.
We'll speed this up again if/when the need arises.
> blockchain: remove buggy long term block weight cache

- src/crypto/CMakeLists.txt
- src/crypto/CryptonightR_JIT.c
- src/crypto/CryptonightR_JIT.h
Related to #5206. This fixes compilation on i386 arch.
If the PR is accepted I'll make a PR to master
> [RELEASE] disable asm w/ x64 instructions set on i386

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/tx_pool.h
- src/serialization/binary_archive.h
In serialization/binary_archive.h, the ios_base::streampos member type was used, which is deprecated (and removed in C++17). (see [cppreference.com](https://en.cppreference.com/w/cpp/io/ios_base)) The usage is changed to ios_base::pos_type, which is not deprecated.
In cryptonote_core/tx_pool.h, the function call overload of a comparison object was not marked 'const', which it should be for usage with STL containers. (I don't know why this compiled fine otherwise.)
Also, in cryptonote_core/blockchain.cpp, an enum value was used as a boolean condition. Since the enum value was nonzero, the condition was always true; I think the original code was a typo, and this fixes it.
Compiler: GCC 8.2.1
> Fix for usage of deprecated type, and bugfix

- src/cryptonote_basic/cryptonote_boost_serialization.h
The change made for v2 broke v1, and we have no way to know which
version we're serializing here. However, since we don't actually
care about space savings in this case, we continue serialiazing
both mask and amount.
> ringct: fix v1 ecdhInfo serialization

- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_core/cryptonote_tx_utils.h
- src/device/device.hpp
- src/device/device_default.cpp
- src/device/device_default.hpp
- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
- src/device/log.cpp
+ New management of destination keys and their verification by user
+ next V10 protocol support
+ some debug fixes
> Nano-S fixes for v0.14

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/net/connection_basic.hpp
- contrib/epee/include/net/http_client.h
- contrib/epee/include/net/http_server_impl_base.h
- contrib/epee/include/net/net_helper.h
- contrib/epee/include/net/net_ssl.h
- contrib/epee/include/net/net_utils_base.h
- contrib/epee/src/CMakeLists.txt
- contrib/epee/src/connection_basic.cpp
- contrib/epee/src/net_ssl.cpp
- src/common/download.cpp
- src/cryptonote_protocol/cryptonote_protocol_defs.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/daemon/rpc_command_executor.cpp
- src/device_trezor/trezor/transport.hpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
P2P and RPC connections now have optional tranparent SSL.
An optional private key and certificate file can be passed,
using the --{p2p,rpc,daemon}-ssl-private-key and
--{p2p,rpc,daemon}-ssl-certificate options. Those have as
argument a path to a PEM format private private key and
certificate, respectively.
If not given, a temporary self signed certificate will be used.
SSL can be enabled or disabled using --{p2p,rpc}-ssl, which
accepts autodetect (default), disabled or enabled.
Access can be restricted to particular certificates using the
--{p2p,rpc}-ssl-allowed-certificates, which takes a list of
paths to PEM encoded certificates. This can allow a wallet to
connect to only the daemon they think they're connected to,
by forcing SSL and listing the paths to the known good
certificates.
To …
> epee: add SSL support

- README.md
tested on current FreeBSD 11.2-p4 , used master and release-v0.13 branchs of monero (w\o any patches)
`gmake` - success
`gmake release-static` - fail (-fPIC error, i think i need build dependencies from ports static instead install from pkg)
`gmake debug` - fail (wallet2.cpp.o - file not recognized: file format no recognized)
`gmake release-test` - success (100% passed)
> README.md - add few FreeBSD instructions, fix v13.0 release tag

- src/blockchain_utilities/blockchain_prune.cpp
This uses system time since it doesn't see the p2p network,
so is not 100% accurate
> blockchain_prune: don't prune before v10

- external/db_drivers/liblmdb/mdb.c
Bump up number of keys for which we use fine-grained splitpoint search
Fixes an MDB_PAGE_FULL error reported in monero-blockchain-prune.
> ITS#8969 tweak mdb_page_split

- contrib/epee/include/math_helper.h
Fixed missing return value in once_a_time class on windows
> Fixed missing return value in once_a_time class on windows

- README.md
I just finished to configure Pootle to host the translations for the CLI: https://translate.getmonero.org/projects/CLI/.
From now on all translation-related work should be uploaded on Pootle and Pull Requests editing translation files should be labelled as invalid and closed (@moneromooo-monero @fluffypony ).
I already added on Pootle all languages available for the GUI. After a language will be completed for at least 70/80% i will open a PR to add that language to the list (using @monero-pootle).
> readme: add new workflow for translations (Pootle)

- src/wallet/wallet2.cpp
When trying to construct a transaction in a view-only wallet, wallet_keys_unlocker will decrypt the null spend key into account key's m_spend_secret_key that then gets passed to construct_tx_with_tx_key(). This then tries to generate a transaction using the decrypted null secret key and crashes in debug and fails in release mode.
> Fix crash in view wallets decrypting the null spendkey

- contrib/depends/packages/openssl.mk
OpenSSL 1.0.1k has a [fairly long list of active vulnerabilities](https://www.cvedetails.com/vulnerability-list/vendor_id-217/product_id-383/version_id-180645/Openssl-Openssl-1.0.1k.html).  
This PR updates the openssl depends package to 1.0.2q, which has all of the above patched. Configuration options that halted the build were removed.
> Update openssl to 1.0.2q (depends)

- src/net/CMakeLists.txt
I've got the following error on `make debug` on OSX 10.14.3:
```
Undefined symbols for architecture x86_64:
"common_category()", referenced from:
make_error_code(common_error) in parse.cpp.o
make_error_code(common_error) in tor_address.cpp.o
"boost::system::detail::system_category_ncx()", referenced from:
boost::system::system_category() in parse.cpp.o
boost::system::system_category() in socks.cpp.o
boost::system::system_category() in libepee.a(net_utils_base.cpp.o)
"boost::system::detail::generic_category_ncx()", referenced from:
boost::system::generic_category() in parse.cpp.o
boost::system::generic_category() in socks.cpp.o
boost::system::generic_category() in tor_address.cpp.o
boost::system::generic_category() in libepee.a(string_tools.cpp.o)
boost::system::generic_category() in …
```
> Debug compilation fix: net lib missing common deps

- contrib/epee/include/net/http_protocol_handler.inl
When specifying additional header fields in an epee http response object (via `epee::net_utils::http_response_info::m_additional_fields`), the serialised headers don't include a space after the colon. This commit fixes this.
(For reference: the [HTTP/1.1 spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) specifies "The field value MAY be preceded by any amount of LWS, though a single SP is preferred.")
> epee: Add space after ':' in additional http response headers

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/abstract_tcp_server2.inl
The [Boost ASIO documentation](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/io_service.html) indicates that `io_service::restart` (formerly `io_service::reset`) must be called if a call to `io_service::run` returns. And the reset call is not thread-safe - meaning all `io_service::run` calls would have to be exited. Failing to do this results in the various `io_service` run variations not working properly (they don't execute any "work"). This _may_ be the reason why `monerod` occasionally stops processing data, although the conditions would have to be "just" right.
The fix is to use `io_service::work` so that `io_service::run` never returns until `io_service::stop` is called. Thrown exceptions do not require a call to `io_service::reset`.
> Use io_service::work in epee tcp server

- src/blockchain_db/lmdb/db_lmdb.cpp
If mdb_block_info changes again, the v2 to v3 conversion would
convert to an incorrect format.
> db_lmdb: make mdb_block_info format conversion more future proof

- src/device/CMakeLists.txt
- src/device/device.hpp
- src/device/device_default.cpp
- src/device/device_default.hpp
- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
- src/ringct/rctSigs.cpp
Always send TX public key when generating output destination keys: it may be an additional TX public key in case of subaddress; before we always use R.
Fix the commitment mask generation: It must be delegated to device as it implies the amount key.
Send MONERO_VERSION string in reset command to allow version compatibility check.
Some enhancement of debug log.
I try various transaction from/to main/sub address, but additional test with both v9 and v11 hardfork are welcome. 
This patch required application v1.2.0. tagged here https://github.com/LedgerHQ/ledger-app-monero/tree/1.2.0.
> Fix computation of change address + Fix v11 fork

- contrib/epee/src/net_ssl.cpp
- pkey gets deleted by the pkey_deleter but the caller tries to serialize it which causes errors as the memory is freed
Complements #5257 as the deleter messes up the pkey.
> epee: certificate generation fix, pkey deleted

- src/wallet/wallet2.cpp
It's better to just ignore them, the user does not really need
to know they're here. If the mask is wrong, they'll fail to be
used, and sweeping will fail as it tries to use it.
Reported by Josh Davis.
This was supposed to wait till a release, but it goes in now since the usual jerk made it public.
> wallet2: don't store 0 amount outputs, they'll fail to be spent

- Makefile
- cmake/CheckTrezor.cmake
- src/device_trezor/CMakeLists.txt
- src/device_trezor/device_trezor.cpp
- src/device_trezor/device_trezor_base.cpp
- src/device_trezor/device_trezor_base.hpp
- src/device_trezor/trezor/debug_link.cpp
- src/device_trezor/trezor/debug_link.hpp
- src/device_trezor/trezor/messages_map.cpp
- src/device_trezor/trezor/messages_map.hpp
- src/device_trezor/trezor/tools/build_protob.py
- src/device_trezor/trezor/transport.cpp
- src/device_trezor/trezor/transport.hpp
- src/net/CMakeLists.txt
- src/wallet/wallet2.h
- tests/CMakeLists.txt
- tests/core_tests/chaingen.cpp
- tests/core_tests/chaingen.h
- tests/core_tests/wallet_tools.cpp
- tests/core_tests/wallet_tools.h
- tests/trezor/CMakeLists.txt
- tests/trezor/trezor_tests.cpp
- tests/trezor/trezor_tests.h
This PR adds integration tests with the Trezor emulator. 
- Tests Key image sync and transaction signing.  
- Several transaction signing scenarios with varying #utxo, types of utxo (received to sub-address, received with additional tx keys), # of outputs, types of outputs (normal, to sub-address, to multiple addresses), payment id.
- Tests generate valid blockchain (init step) and then spends mined funds with the Trezor (test step). 
- *Init step*: In order to save CPU time, the common blockchain is generated before all tests are run. Before each test, the blockchain is rewound to the original state. Core verifies only new blocks on the blockchain added by the test being run. 
- *Test step*: There are several testing scenarios added for testing transaction signature on Trezor. Scenarios …
> device/trezor: integration tests

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
Add two new methods `generate_from_keys` and `generate_from_view_key`. These methods are useful if the key generation is outside of the wallet, e.g. in an other library.
Example of `generate_from_keys`:
```
curl -X POST http://localhost:18083/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"generate_from_keys","params":{"restore_height": 0, "filename": "test", "address": "48tgL9CicAra88CfK5giqYRxbXTLEBvva1XCpc7GwNTGLxX4uGXE8neK9oejJ8dJUKGStW2Mu3PfrMhr3u6gymP47xfV9YE", "spendkey": "183818b6222c89dec1216810aa56c3c1262271b04af1cadd030c93a4bcf75908", "viewkey": "183818b6222c89dec1216810aa56c3c1262271b04af1cadd030c93a4bcf75908"}}' -H 'Content-Type: application/json'
{
"id": "0",
"jsonrpc": "2.0",
"result": {
"address": "48tgL9CicAra88CfK5giqYRxbXTLEBvva1XCpc7GwNTGLxX4uGXE8neK9oejJ8dJUKGStW2Mu3P …
```
> wallet-rpc: Add generate_from_keys and generate_from_view_key

- src/device_trezor/device_trezor.cpp
Fixes upcoming update which adds encrypted dummy payment ID to the transactions.
Trezor client logic fix.
> device/trezor: dummy payment ID fix

- src/common/dns_utils.cpp
This code is used for more than just these
> dns_utils: remove MoneroPulse/checkpoints mention in TXT record code

- src/cryptonote_basic/connection_context.h
- src/cryptonote_protocol/cryptonote_protocol_defs.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/daemon/command_line_args.h
- src/daemon/daemon.cpp
- src/daemon/daemon.h
- src/daemon/executor.cpp
- src/daemon/executor.h
- src/daemon/main.cpp
- src/daemon/rpc_command_executor.cpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/net_peerlist.h
- src/p2p/net_peerlist_boost_serialization.h
- src/p2p/p2p_protocol_defs.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
- src/rpc/message_data_structs.h
- src/serialization/json_object.cpp
Command line switch `--public-node`
1. Requires restricted RPC mode
2. Advertise node's restricted RPC port to other peers over P2P network
3. Print a warning at startup if restricted RPC server is listening on local or loopback address
4. Store remote peer's RPC port in peer list only if the peer's destination address is reachable
The following commands will include remote peers' RPC ports (if any):
1. `print_pl` daemon command
2. `get_peer_list`, `get_connections`, `sync_info` RPC calls
```diff
monerod --public-node
- ERROR, restricted RPC mode is required
monerod --public-node --restricted-rpc
+ OK, default RPC port will be advertised over P2P network
monerod --public-node --rpc-restricted-bind-port 1234
+ OK, RPC port 1234 will be advertised over P2P network
monerod --public-node …
```
> daemon: add --public-node mode, RPC port propagation over P2P

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- Experimental feature. Prototype implementation (just an idea).
- Enables to perform rescan_spent / key image import with an untrusted daemon. Spent check status involves RPC calls which require trusted daemon status as it leaks information (asks for particular key images being spent). The new call `rescan_bc_keep_ki` performs soft reset while preserving key images thus the following sequence of commands will correctly perform spent checking without need for trusted daemon: 
- refresh
- key image sync / import
- rescan_bc_keep_ki 
- Useful to detect spent outputs (e.g., after restore) with untrusted daemon on watch_only / multisig / cold / hw-backed wallets after expensive key image sync. Downside: need to download the blockchain since restore height.
- Usage: `rescan_bc keep_ki …
> wallet: rescan bc with preserving key images

- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/p2p/net_node.cpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
Allows to run a daemon that will connect to other peers, but won't download the blockchain.
Could be used in Monero GUI to find public RPC nodes by exploring P2P peers advertising such a service.
If `--bootstrap-daemon-address auto` gets implemented, the local daemon will automatically discover public nodes and provide transparent RPC proxy to the wallets.
Both CLI and GUI wallets will use automatically discovered public nodes with zero to no additional overhead on the wallet side.
Also `--bootstrap-daemon-address auto --no-sync` will be useful to users who don't want to store the blockchain locally.
As well it seems to be useful in conjunction with forthcoming `share-rpc` feature.
> daemon: add '--no-sync' arg to optionally disable blockchain sync

- src/cryptonote_config.h
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
When all our outgoing peer slots are filled, we cycle one peer at
a time looking for syncing peers until we have at least two such
peers. This brings two advantages:
- Peers without incoming connections will find more syncing peers
that before, thereby strengthening network decentralization
- Peers will have more resistance to isolation attacks, as they
are more likely to find a "good" peer than they were before
> cryptonote_protocol_handler: search for syncing peers in "cruise mode"

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
changeset to add multisig transactions to rpc describe_transfer endpoint 
request would look like:
```
{
"jsonrpc": "2.0",
"id": "0",
"method": "describe_transfer",
"params": {
"multisig_txset": "4d6f6e65726f206d756c746..."
}
}
```
> add multisig tx sets to describe_transfer rpc endpoint

- CONTRIBUTING.md
The [spec](https://tools.ietf.org/html/rfc2119) states that these keywords are aliased to each other (in order to alleviate issues arising from the misinterpretation of using "shall"). Consistency helps readers (especially new/unfamiliar ones). 👀 References:
- https://www.faa.gov/about/initiatives/plain_language/articles/mandatory/ 
- https://ell.stackexchange.com/a/171990/2487
> SHALL -> MUST

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- return the right output data when offset is not zero
- do not consider import failed if result height is zero
(it can be 0 if unknown)
- select the right tx pubkey when using subaddresses (it's faster,
and we might select the wrong one if we got an output using one
of the additional tx keys)
- account for skipped outputs for spent/unspent balance info
"spent" is arguably wrong, since it will count spent change
multiple times as it goes through receive/spend cycles.
> wallet2: key image import fixes

- Dockerfile
Execute monerod as non root user to add extra bit of security.
Be carefull : breaks existing deployement as VOLUME path changes (/root/.bitmonero to /home/monero/.bitmonero)
> Start monerod as non root user in docker

- src/wallet/api/wallet.cpp
`make_multisig_tx_set` misuse in wallet api led to inability to properly sign multisig transactions. It took about 1 week to debug it :)
> Wallet API: multisig_tx_set passing bug fixed

- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_core/cryptonote_core.cpp
It was in the wrong byte order
> cryptonote: fix calculating coinbase tx hash

- contrib/epee/include/console_handler.h
This avoids the annoying case where the shell prints its prompt
after the last line from Monero output, causing line editing to
sometimes go wonky, for lack of a better term
> console_handler: print newline on EOF

- ANONYMITY_NETWORKS.md
- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/net/http_client.h
- contrib/epee/include/net/net_helper.h
- contrib/epee/include/net/net_utils_base.h
- contrib/epee/src/CMakeLists.txt
- contrib/epee/src/net_helper.cpp
- src/net/CMakeLists.txt
- src/net/socks.cpp
- src/net/socks.h
- src/net/socks_connect.cpp
- src/net/socks_connect.h
- src/wallet/CMakeLists.txt
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- tests/fuzz/cold-outputs.cpp
- tests/fuzz/cold-transaction.cpp
- tests/fuzz/signature.cpp
- tests/unit_tests/multisig.cpp
- tests/unit_tests/net.cpp
Allows wallets to connect to daemon over tor/i2pd/kovri. If proxy usage is enabled, the daemon address must be onion/i2p based or use `--daemon-cert-file`. The idea is to prevent root CA shadiness over these networks in addition to the authenticated/unencrypted problems. A root CA can be combined with an onion/i2p address (the former can definitely be signed by a few CAs) by using `--daemon-address https://xyz.onion`. Additionally, `--daemon-address https://...` and `--daemon-cert-file` will work with ipv4 or ICANN hostnames.
Will have to coordinate with @moneromooo-monero for the SSL changes. The first commit (for p2p tor/socks) will be rebased away once its merged.
> Add Socks Proxy (for Tor/i2pd/Kovri) Support to Wallets

- src/cryptonote_basic/miner.cpp
If a thread asks to stop the miner, m_stop will be set, and
that thread will wait to join. If the main thread is exiting
at that time, it will ask the miner to stop, but the miner
will claim it's not mining and early out since m_stop is
set. This will cause the database and other things to get
shutdown. If the miner happens to find a block at that time,
it will try to call core, and crash.
Instead, lock and check whether any threads are currently
in m_threads, since they'll only be cleared once the threads
are joined. Moreover, since we lock, the second thread will
have to wait for the first one to have finished. Calling
join twice on a thread seems fine as per pthread_join(3).
> miner: fix possible exit crash due to race in stop

- src/wallet/wallet2.cpp
It was not recovering then, but creating a new random address
> wallet2: fix generation from json when restore height is not set

- contrib/epee/include/storages/portable_storage_base.h
Manually initialize the array_entry_t iterator to ensure it points
to the correct m_array, thereby preventing a potential use-after-free
situation.
Signed-off-by: Guido Vranken <guidovranken@gmail.com>
> Implement array_entry_t copy constructor

- src/cryptonote_core/cryptonote_core.cpp
The original intent of one false positive a week on average
was not met, since what we really want is not the probability
of having N blocks in T seconds, but either N blocks of fewer
in T seconds, or N blocks or more in T seconds.
Some of this could be cached since it calculates the same fairly
complex floating point values, but it seems pretty fast already.
> core: improve block rate monitor trigger probabilities

- src/p2p/net_node.inl
PR #4770 introduced visible defaults for the `--limit-rate-up` and `--limit-rate-down` daemon startup parameters. This broke processing of the bidirectional parameter `--limit-rate` i.e. that parameter got ignored:
That processing only tries to set what is not yet set by processing the more specific "up" and "down" parameters. It failed because the defaults made it look as if "up" and "down" were **always** set.
> Fix daemon startup parameter '--limit-rate' processing after parameter defaults

- contrib/epee/include/net/network_throttle-detail.hpp
- contrib/epee/include/net/network_throttle.hpp
- contrib/epee/src/network_throttle-detail.cpp
- src/common/util.cpp
- src/common/util.h
- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
The Monero daemon lacks so far an interactive command to show info about total network traffic since startup. (The `print_cn` command only print details per connection, and only about currently existing ones, not about terminated ones.)
This PR implements a new command `print_net_stats` to finally provide such a feature.
Sample output:
Received 7354450 bytes (7.01 MB) in 4682 packets, average 1.39 kB/s = 0.02% of the limit of 8.00 MB/s
Sent 49976456 bytes (47.66 MB) in 4705 packets, average 9.47 kB/s = 0.46% of the limit of 2.00 MB/s
The interactive command is based on new RPC commands that could be used e.g. to automatically monitor daemons and make sure that traffic does not go "through the roof".
> New interactive daemon command 'print_net_stats': Global traffic stats

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
it's been a while, only use ring_size now
> wallet_rpc_server: remove mixin from transfer RPCs

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
These commands let one freeze outputs by key image, so they
do not appear in balance, nor are considered when creating
a transaction, etc
This is helpful when receiving an output from a suspected spy,
who might try to track your other outputs by seeing with what
other outputs it gets spent.
The frozen command may be used without parameters to list all
currently frozen outputs.
> wallet: add freeze/thaw/frozen commands

- src/p2p/net_node.inl
This will cause DNS requests, which will block and timeout
if there is really no network connectivity
> p2p: don't lookup seed nodes when offline

- src/crypto/CMakeLists.txt
Like #5336 but for `master`. This change is needed to successfully link the executables on FreeBSD/amd64.
> Fix build on *BSD

- src/wallet/CMakeLists.txt
```
18:57 <vtnerd> selsta : the tor-wallet-proxy code is missing in the link stage in the `BUILD_GUI_DEPS` section. I've never seen a technique quite like that before, but it looks like its not grabbing targets to link against
19:49 <vtnerd> I "net" needs to be added to the "libs_to_merge" at the bottom of src/wallet/CMakeLists.txt
19:49 <vtnerd> *I think
```
> libwallet_merged: add missing net target

- src/wallet/wallet2.cpp
It makes more sense than (uint64_t)-1, which is going to look
like very much confirmed when not checking in_pool
> wallet2: set confirmations to 0 for pool txes in proofs

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
There's half a dozen calls, and it's easy to miss some when
adding a new field.
> wallet2: factor the watchonly/multisig/etc fields on creation

- src/rpc/core_rpc_server.cpp
To fill `pruned_as_hex`/`prunable_as_hex` or not and to fill `as_hex`/`as_json` or not should not be chosen exclusively.
> rpc.gettransactions: fix as_json field being left empty when prune=true

- tests/trezor/trezor_tests.cpp
Minor trezor test fix as `use_bulletproofs` was removed from transaction construction data.
> tests: trezor_test fix

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/net/connection_basic.hpp
- contrib/epee/include/net/http_client.h
- contrib/epee/include/net/http_server_impl_base.h
- contrib/epee/include/net/net_helper.h
- contrib/epee/include/net/net_ssl.h
- contrib/epee/src/connection_basic.cpp
- contrib/epee/src/net_ssl.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
The commit list explains the changes and why. I regret changing the names of `ssl_support_t` enum (which were unnecessarily redundant given the behavior of C++11 `enum class`), but it led to lots of lines changes.
Inspecting each commit manually might be preferable.
> SSL Behavior Changes

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/blockchain_db/testdb.h
- src/cryptonote_basic/cryptonote_basic.h
- src/cryptonote_basic/cryptonote_basic_impl.cpp
- src/cryptonote_basic/cryptonote_basic_impl.h
- src/cryptonote_config.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
Use the actual block weight limit, assuming that weight is always
greater or equal to size
> cryptonote: rework block size sanity check

- src/device_trezor/device_trezor.cpp
Increase monitor timeout to 5 minutes. 20 seconds was pretty annoying for slow sync
> device/trezor: increase live-refresh timeout

- src/common/util.cpp
- src/common/util.h
It was confusing unless you read code and the rename(2) man page.
> util: name replace_file arguments better

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
It's now needed for CNv4, and was not retained when cached
> blockchain: fix returned height in create_block_template

- src/blockchain_utilities/blockchain_prune.cpp
- src/cryptonote_core/blockchain.cpp
- src/daemon/rpc_command_executor.cpp
This check is now not needed anymore, and would prevent people
from using --prune-blockchain when starting a new sync
> Allow pruning before v10

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
I saw one when landing on www.tribler.org, and it seemed
like a good idea to have something similar, alongside some
more general "what is monero" text.
> simplewallet: add a welcome/disclaimer message command

- src/device/device.hpp
- src/device_trezor/device_trezor_base.cpp
- src/device_trezor/device_trezor_base.hpp
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet2_api.h
- src/wallet/api/wallet_manager.cpp
- src/wallet/api/wallet_manager.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
API changes to enable passphrase entry on host via API (e.g., for GUI) - callback triggers request for passphrase if required. If callback is set before opening / creating wallet from a device it can set the passphrase to the device.
I had to add another callback method to set wallet obj after it is created as callbacks usually need to hold it.
@moneromooo-monero what do you think about this approach?
> wallet: early listener set

- src/device_trezor/trezor/transport.cpp
- src/device_trezor/trezor/transport.hpp
- tests/core_tests/wallet_tools.cpp
- tests/trezor/daemon.cpp
- tests/trezor/trezor_tests.cpp
- tests/trezor/trezor_tests.h
- Tested blockchain hardforks modifiable via environment variable, default: test only HF 11
- Hardfork switching fixes (e.g., rewind 10 blocks to apply v10 rules after switch)
- Enable to change emulator and bridge ports via environment variables.
> Trezor: test fixes and improvements

- src/cryptonote_basic/difficulty.cpp
- src/cryptonote_basic/difficulty.h
- src/rpc/core_rpc_server.cpp
- tests/functional_tests/blockchain.py
This should be friendlier for clients which don't have bignum support
> rpc: make wide_difficulty hexadecimal

- src/common/combinator.h
GCC 4.8.4 compilation fails as `runtime_error` is defined in `stdexcept` which was not included.
> build fix: combinator.h stdexcept include added

- cmake/FindBacktrace.cmake
- external/easylogging++/CMakeLists.txt
Easylogging is currently broken on platforms that do support the non-posix backtrace methods, but require linking to a specific library. This PR explicitly links to the right library.
The FindBacktrace.cmake module is included in cmake 3.0+, but since we also support cmake 2.8.7, I have copied this file - with a small modification - in the cmake folder.
> easylogging++: link to backtrace

- external/db_drivers/liblmdb/mdb.c
That should hopefully shut coverity up
> lmdb: catch non-LMDB negative errors before strerror

- src/blockchain_db/blockchain_db.cpp
- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/blockchain_db/testdb.h
- src/cryptonote_basic/hardfork.cpp
- src/cryptonote_core/blockchain.cpp
- tests/core_tests/chaingen.h
- tests/unit_tests/blockchain_db.cpp
The db txn in add_block ending caused the entire overarching
batch txn to stop.
Also add a new guard class so a db txn can be stopped in the
face of exceptions.
> blockchain_db: fix db txn ending too early

- tests/core_tests/bulletproofs.h
- tests/core_tests/chaingen.h
- tests/core_tests/multisig.h
- tests/core_tests/rct.h
- tests/trezor/trezor_tests.cpp
GCC is unhappy about unitialized const `long_term_block_weight_window`
Fixes build error.
```cpp
struct test_options {
const std::pair<uint8_t, uint64_t> *hard_forks;
const size_t long_term_block_weight_window;
};
```
> tests: fix test_options initialization error

- src/rpc/core_rpc_server.cpp
I think this is the correct treatment since the miner tx doesn't contain the extra nonce field at all when reserve size == 0.
> rpc.getblocktemplate: set reserved_offset to zero when reserve_size==0

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- utils/python-rpc/framework/wallet.py
Loading the same wallet as the currently loaded one would autosave
the current state after loading it, leading to some kind of rollback
effect. We now save before loading to avoid this. If loading fails,
it means the current wallet will be saved (or maybe not, depending
on where the failure occurs: most of the sanity checks occur before
saving). There is a new autosave_current flag to open/restore calls
so the (enabled by default) autosave can be skipped.
> wallet_rpc_server: fix inconsistent wallet caches on reload

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/abstract_tcp_server2.inl
When closing connections due to exiting, the IO service is
already gone, so the data exchange needed for a gracious SSL
shutdown cannot happen. We just close the socket in that case.
> abstract_tcp_server2: fix timeout on exit

- src/daemon/main.cpp
rather than from data dir where it normally is.
It makes things like --log-file ./foo.log behave as you'd expect.
> daemon: if a log file has a /, interpret it from the cwd

- src/cryptonote_basic/hardfork.cpp
This is now obsolete, and this removes the warning on startup
on a new db that confuses some people
> hardfork: remove "no hf version db" recreation check

- src/cryptonote_basic/miner.cpp
Not super familiar with this code, but m_threads_active only has an instance of a decrement in the codebase and not any increment so it overflows and locks up the daemon and wallet.
See line 596 in miner.cpp for the decrement.
> Increment m_threads_active when mining thread starts

- README.md
- contrib/brew/Brewfile
This pull requests adds  support for a feature of homebrew that allows to maintain the dependencies of a project within the codebase, in form of a `Brewfile`.
This pull request:
- Adds the Brewfile itself
- Adapts the brew formulae command in the project README
With this file in place, all that needs to be done to install all dependencies is execute `brew bundle`.
There are more benefits for developers and/or testers. For example, this Brewfile can be used as a whitelist to remove all Homebrew formulae _not listed_ in this `Brewfile` by running `brew bundle cleanup`.
> Add Brewfile to allow for easier management of dependencies on macOS

- src/blockchain_db/berkeleydb/db_bdb.cpp
- src/blockchain_db/berkeleydb/db_bdb.h
- src/blockchain_db/testdb.h
- tests/unit_tests/hardfork.cpp
and delete obsolete BlockchainBDB::get_tx_output_indices along the way
> testdb: add override keyword where missing

- tests/core_tests/bulletproofs.h
- tests/core_tests/chaingen.cpp
- tests/core_tests/chaingen.h
Only needed because they want to overload check tx verification to handle vectors of tx verifications, so just give that function an explicit name instead to allow C++ to compile it.
> Remove unneeded SFINAE on check_tx/block verification in core_tests

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- tests/unit_tests/output_selection.cpp
Based on python code by sarang:
https://github.com/SarangNoether/skunkworks/blob/outputs/outputs/simulate.py
> wallet2: "output lineup" fake out selection

- translations/monero.ts
- translations/monero_fr.ts
- translations/monero_it.ts
- translations/monero_ja.ts
- translations/monero_sv.ts
Translations from https://translate.getmonero.org/projects/CLI/
Strings were submitted and reviewed on Pootle, before opening this PR i synced the files with the last merges. The result is: 41 new strings and 3 obsolete entries (removed). Ideally, all language files should be refreshed/resynced before tagging, if more commits get pushed.
I only submitted the translations for languages we already have, will add new languages as soon as one of them has enough translated strings.
> Add translations for it, fr, ja, sv from Pootle and refresh template file

- src/device_trezor/device_trezor_base.cpp
Fix of the button request callback logic. Without this PR the GUI "Proceed to the device" does not work, which is rather confusing for users.
> device/trezor: button request callback fix

- tests/unit_tests/net.cpp
@iDunk5400 finally got my windows build system working again.
This should fix the failing socks test cases in windows and no longer infinite loop when this particular case fails.
> Fix socks tests in windows and handle errors better

- src/wallet/wallet2.cpp
Use scope leave handler to properly signal key image computation finished to the device.
> wallet: fix key image computation signaling to the device

- contrib/epee/include/net/levin_protocol_handler_async.h
It can allocate a lot when getting a lot of connections
(in particular, the stress test on windows apparently pushes
that memory to actual use, rather than just allocated)
> levin_protocol_handler_async: tune down preallocation a fair bit

- src/wallet/wallet2.cpp
leading to the sanity check triggering
> wallet2: fix wrong change being recorded in sweep_all

- src/wallet/wallet2.cpp
In the case where previously a second unneeded output would be
added to a transaction. This should help *some* of the cases
where outputs are slowly being consolidated, leading to the
whole balance being locked when sending monero.
> wallet2: default to trying to keep 5 outputs of 2+ monero

- tests/unit_tests/output_distribution.cpp
updating the block size limit needs recent block sizes,
so we feed it dummy ones
> unit_tests: fix crash in debug in output_distribution test

- contrib/depends/Makefile
- contrib/depends/packages/gtest.mk
- contrib/depends/packages/native_cctools.mk
- contrib/depends/packages/native_cmake-unused.mk
- contrib/depends/packages/packages.mk
- contrib/depends/toolchain.cmake.in
- tests/CMakeLists.txt
I've used this patch to cross-build debug versions and tests of the monero binaries, which was quite helpful.
What do you think @TheCharlatan ? 
Regarding tests - I had to add `contrib/depends/packages/gtest.mk` as embedded GTest is built as an external project which I found difficult to set toolchain file for. Thus I've rather created a cross-combiled library which is later picked up by the tests cmake file.
Regarding `option()` calls in the toolchain file - I had to add them as the first cmake run ignores `set()` for options from toolchain file if the `option` was not set before. This leads to strange behavior as the first run ignores those toolchain-set options but the second run takes them into consideration.
To build the tests it is needed just:
```cpp
$DOCKER_EXEC bash -c …
```
> build: debug and test builds via contrib dockers

- src/p2p/net_node.inl
- src/p2p/net_peerlist.h
- src/p2p/p2p_protocol_defs.h
This can be used for fingerprinting and working out the
network topology
> p2p: do not send last_seen timestamp to peers

- src/rpc/core_rpc_server.cpp
- src/rpc/daemon_handler.cpp
- src/rpc/rpc_handler.cpp
- src/rpc/rpc_handler.h
- tests/functional_tests/functional_tests_rpc.py
- tests/functional_tests/get_output_distribution.py
- tests/unit_tests/output_distribution.cpp
It can now handle small reorgs without having to rescan the
whole blockchain.
Also add a test for it.
> rpc: improve get_output_distribution

- src/wallet/wallet2.cpp
If we have fewer outputs available on the chain than what we
require, but the output we're spending already has a ring,
it would loop picking outputs randomly, but never find enough.
Also tune logs for better debugging this kind of thing.
> wallet2: fix infinite loop picking outputs in corner case

- cmake/FindBacktrace.cmake
It fixes at least one case of building on ARM with Docker
> cmake: fix some case of "backtrace lib not found" breaking

- contrib/epee/include/net/net_ssl.h
- contrib/epee/src/net_ssl.cpp
When built with the depends system, openssl does not include any
cipher on the current whitelist, so add this one, which fixes the
problem, and does seem sensible.
> net_ssl: SSL config tweaks for compatibility and security

- contrib/epee/src/net_ssl.cpp
This fixes a number of leaks here, and exit works just fine without ASAN complaining.
If you previously had issues with this, please test, it might have been a bug elsewhere.
> net_ssl: free certs after setting them up

- src/common/password.cpp
This keeps its builtin command editing away
Thanks iDunk for testing on Windows
> password: do not use line input on windows

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
also add a note when receiving the tx, because the user
might not notice the "XXX blocks to unlock" in the balance.
> wallet: add unlock_time details to show_transfers

- src/cryptonote_core/blockchain.cpp
Make sure the tip hash still matches the cached block. Fixes #5553
> Fix for stale block template cache

- tests/unit_tests/output_selection.cpp
It's an inherently random test
> unit_tests: make the density test a bit less stringent

- tests/functional_tests/get_output_distribution.py
When the wallet auto refreshes after mining the last two blocks
but before popping them, it will then try to use outputs which
are not unlocked yet. This is really a wallet problem, which
will be fixed later.
> functional_tests: fix rare get_output_distribution failure

- src/cryptonote_core/cryptonote_core.cpp
Avoids a massive amount of spurious warnings if the last update before
the daemon exited was a while ago and the daemon was syncing
> core: update pruning if using --prune-blockchain on a pruned blockchain

- contrib/depends/packages/openssl.mk
- This addresses https://www.openssl.org/news/secadv/20190226.txt (CVE: 2019-1559) which impacted all versions of openssl-1.0.
Note that this does not address CVE-2019-1543 (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-1543), which impacts all versions of openssl 1.1 through 1.1.0j and 1.1.1b ... I do not believe monero uses any of this functionality from openssl, and 1543 does not affect 1.0.2r.
The above is patched in openssl, where it was marked as low severity.  Similar issues possibly present in monero (unrelated to openssl, directly), should be looked into w.r.t. the specific issue present in CVE-2019-1543.
> [depends] update openssl to 1.0.2r

- cmake/GenVersion.cmake
- contrib/depends/packages/packages.mk
- contrib/depends/toolchain.cmake.in
- contrib/gitian/gitian-linux.yml
- contrib/gitian/gitian-osx.yml
- contrib/gitian/gitian-win.yml
Don't use `-march=native`
Re-enable parallel make
Using `-march=native` made the binaries depend on the build system's CPU, and those binaries could crash on older machines. This was breaking the Mac binaries. It also meant that the binaries would differ between different build machines. This was causing the differences in the x86-64-linux builds. I've tested with both serial and parallel build, and results are now identical, so parallel make was never the issue.
> Fix reproducible builds

- src/p2p/net_peerlist.h
Older nodes don't pass that information around
> p2p: don't forget pruning seed or public RPC port when updating peers

- src/cryptonote_core/tx_sanity_check.cpp
we don't want to prevent bona fide txes, just obvious bad ones
> tx_sanity_check: relax the median check a lot

- src/common/dns_utils.cpp
It is down permanently. See: https://xiala.net/
"Ende November 2018 werden alle Dienste von xiala.net abgeschaltet."
> Remove Xiala.net from the list of dns resolvers

- src/blockchain_db/lmdb/db_lmdb.cpp
to avoid errors when the txn is too large
> db_lmdb: commit pruning txn at checkpoints

- src/cryptonote_core/blockchain.cpp
This happens often when a pre-pruning node asks a pruned node
for data it does not have
> blockchain: silence an error getting blocks for pruned nodes

- contrib/depends/Makefile
- contrib/depends/funcs.mk
- contrib/depends/packages/eudev.mk
- contrib/depends/packages/expat.mk
- contrib/depends/packages/hidapi.mk
- contrib/depends/packages/icu4c.mk
- contrib/depends/packages/ldns.mk
- contrib/depends/packages/libiconv.mk
- contrib/depends/packages/ncurses.mk
- contrib/depends/packages/packages.mk
- contrib/depends/packages/protobuf.mk
- contrib/depends/packages/readline.mk
- contrib/depends/packages/sodium-darwin.mk
- contrib/depends/packages/sodium.mk
- contrib/depends/packages/unwind.mk
- contrib/depends/packages/zeromq.mk
- contrib/depends/toolchain.cmake.in
Readline is now compiled with ncurses as a backend. I also attempted to build with termcap instead of a full ncurses installation, but since the releases so far have not supported readline on windows and 
the termap Makefile does not handle installation directories properly that are demanded by depends, 
Besides adding readline, this pull request also adds some debug targets to the depends Makefile. To check all the available targets now, you can run `cat Makefile | awk '!/SHELL/ && /^[A-z]/ {print $1}' | awk '{print substr($0, 1, length($0)-1)}' . 
To speedup the depends cached builds, remove some some clutter from the package files. This mainly includes removing all the shared libraries and .la linker files. It also gives stronger guarantees that monero only links the static libs …
> Fix readline compilation 

- contrib/depends/Makefile
- contrib/depends/funcs.mk
- contrib/depends/packages/eudev.mk
- contrib/depends/packages/expat.mk
- contrib/depends/packages/hidapi.mk
- contrib/depends/packages/icu4c.mk
- contrib/depends/packages/ldns.mk
- contrib/depends/packages/libiconv.mk
- contrib/depends/packages/ncurses.mk
- contrib/depends/packages/packages.mk
- contrib/depends/packages/protobuf.mk
- contrib/depends/packages/readline.mk
- contrib/depends/packages/sodium-darwin.mk
- contrib/depends/packages/sodium.mk
- contrib/depends/packages/unwind.mk
- contrib/depends/packages/zeromq.mk
- contrib/depends/toolchain.cmake.in
Readline is now compiled with ncurses as a backend. I also attempted to build with termcap instead of a full ncurses installation, but since the releases so far have not supported readline on windows and
the termap Makefile does not handle installation directories properly that are demanded by depends,
Besides adding readline, this pull request also adds some debug targets to the depends Makefile. To check all the available targets now, you can run `cat Makefile | awk '!/SHELL/ && /^[A-z]/ {print $1}' | awk '{print substr($0, 1, length($0)-1)}' .
To speedup the depends cached builds, remove some some clutter from the package files. This mainly includes removing all the shared libraries and .la linker files. It also gives stronger guarantees that monero only links the static libs without …
> Fix readline release

- contrib/depends/packages/hidapi.mk
The macos binaries in release v0.14.1.0 were compiled with the buggy
hidapi-0.8.0-rc1 version. This resulted in users not being able to use
their Ledger with the latest cli wallet. After the patch depends now
fetches the source from a separately published release.
> Depends: Use HIDAPI from master branch

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/net_utils_base.h
- contrib/epee/src/net_utils_base.cpp
- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/net/error.h
- src/net/parse.cpp
- src/net/parse.h
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/net_node_common.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
- tests/unit_tests/ban.cpp
- tests/unit_tests/net.cpp
Note that while the subnet is a type of network address, it does not get serialized, to avoid issues with a peer sending those in a peerlist. I'm not sure whether this is best that way, or with a filter-on-receive in the caller. This seems safer though.
> allow blocking whole subnets

- CMakeLists.txt
I noticed that when building, if a submodule is found out to date, the user is asked to update that single submodule. If there are more outdated submodules, the user's build will stop every time until all submodules are updated. With this change, the suggestion is to run `git submodule update --init --force` without specifing a submodule, so that all of them will be updated in one go. I don't know if this change is wanted/needed, @moneromooo-monero it's up to you. 
I also added a newline at the end of `or run cmake with -DMANUAL_SUBMODULES=1")`, to make the string more visible.
> CMakeLists.txt: suggest to update all submodules if one of them is outdated

- src/wallet/wallet2.cpp
30 blocks should be more than enough to drain the txpool of
transactions made with the old fee scheme
> wallet2: don't wait a day before using new version fees

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/blockchain_db/testdb.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
Alternative blocks are cleared on startup unless --keep-alt-blocks
is passed on the command line
> blockchain: keep alternative blocks in LMDB

- tests/unit_tests/mnemonics.cpp
- tests/unit_tests/output_selection.cpp
- tests/unit_tests/rolling_median.cpp
We don't need secure randomness here, but it should shut coverity up
> use crypto::rand instead of libc rand in a few tests

- contrib/epee/include/net/abstract_tcp_server2.inl
The lock is meant for the network throttle object only,
and this should help coverity get unconfused
> abstract_tcp_server2: move some things out of a lock

- translations/generate_translations_header.c
Close opened file before call to exit(). This avoids potential resource leak.
To find this problem I have used Clang Static Analyzer with alpha.unix.Stream checker.
> Close file before exit to avoid potential resource leak

- src/blockchain_utilities/blockchain_export.cpp
We don't need any of the pruned data for this
> blockchain_export: allow exporting blocks.dat format from pruned

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_protocol/cryptonote_protocol_defs.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
TXs are filled in the block_complete_entry-ies. No TX's ever seem to be requested via the removed array.
> Remove unused txs member in NOTIFY_RESPONSE_GET_OBJECT

- src/device/device.hpp
- src/device/device_cold.hpp
- src/device_trezor/device_trezor.cpp
- src/device_trezor/device_trezor.hpp
- src/device_trezor/trezor/protocol.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- Trezor: support for device address display (subaddress, integrated address)
- Wallet::API support added
- Simplewallet:
- `address device [<index>]`
- `address new <label>`  // shows the address also on the device
- `integrated_address [device] <payment_id|address>`  // new optional "device" arg to display also on the device
Relates to:
- https://github.com/monero-project/monero-gui/issues/2184
- https://github.com/trezor/trezor-firmware/pull/201
- https://www.reddit.com/r/Monero/comments/c1mgzm/how_to_verify_subaddress_on_trezorledger_device/
> device: show address on device display

- .github/FUNDING.yml
Github has a new cool feature, the "Sponsor" button. When activated it will show a button on the left of the "watchers" button, which will show a link to the 'Contributing' page on getmonero.org.
Right now the link would be `https://web.getmonero.org/get-started/contributing/`, but i can change it to something else if necessary (maybe `https://ccs.getmonero.org/donate/`?).
It's basically just a button showing a link to a 'Donation' page, i though it's a nice feature.
If i understood correclty, the functionality should be activated on the GitHub UI as well (see link below). Ping @fluffypony.
More info: https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository
A repository where the button is active: https://github.com/WeblateOrg/weblate
> Add 'sponsor' button on GitHub

- src/simplewallet/simplewallet.cpp
Exceptions would otherwise terminate the process silently
> simplewallet: print errors on exceptions creating wallets

- contrib/gitian/README.md
- contrib/gitian/gitian-build.py
This commits adds the `--no-apt` flag to the gitian-build.py script. This allows gitian builds to be run without root access and non-debian based operating systems.
> Add option to run gitian-build.py on non-debian os

- src/wallet/api/wallet.cpp
get_attribute expects 2 values instead of 1
> Fixed error preventing build of monero-gui

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/net/http_server_impl_base.h
- contrib/epee/include/net/local_ip.h
- contrib/epee/include/net/net_parse_helpers.h
- contrib/epee/include/net/net_utils_base.h
- contrib/epee/src/net_helper.cpp
- contrib/epee/src/net_utils_base.cpp
- src/daemon/rpc_command_executor.cpp
- src/net/parse.cpp
- src/net/parse.h
- src/p2p/net_node.cpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/net_peerlist_boost_serialization.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/rpc/rpc_args.cpp
- src/rpc/rpc_args.h
- src/wallet/wallet_rpc_server.cpp
Adds IPv6 support for daemon p2p, daemon RPC, and wallet RPC.
Currently there is no option to bind different ports for
IPv4 and IPv6 for RPC, but that can be changed if necessary.
References this issue https://github.com/monero-project/monero/issues/147
> IPv6 support

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
Requires https://github.com/monero-project/monero/pull/5606
> rpc: implement get_public_nodes command

- src/rpc/core_rpc_server.cpp
It would try to get their prunable hash, but v1 txes don't have one
> rpc: fix get_transactions getting v1 txes from the txpool

- src/cryptonote_core/cryptonote_core.cpp
In that case, we'll still keep the "Monero is now disconnected
from the network" near the end of the log
> core: do not complain about low block rate if disconnected

- contrib/epee/include/net/http_protocol_handler.inl
- contrib/epee/include/net/http_server_handlers_map2.h
- src/cryptonote_config.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
Make bans control RPC sessions too. And auto-ban some bad requests.
Drops HTTP connections whenever response code is 500.
> Bans for RPC connections

- tests/unit_tests/output_selection.cpp
This is an inherently probabilistic check, which occasionally fails
for a matching distribution
> unit_tests: add more leeway to the "same distribution" check

- src/simplewallet/simplewallet.cpp
The wallet was ignoring --restore-height and --restore-date params and
prompting for them again.
> Fix --restore-date usage

- src/wallet/api/wallet.cpp
- getTxKey method throws an exception, e.g., when user declines txKey export
- if exception is not caught it crashes GUI
> wallet_api: catch getTxKey exception

- tests/functional_tests/functional_tests_rpc.py
Without this functional_tests_rpc failed on Arch Linux with Python 3.7.3:
```
"functional_tests_rpc" start time: Jun 19 21:52 EDT
Output:
----------------------------------------------------------
File "/.../tests/functional_tests/functional_tests_rpc.py", line 68
except Exception, e:
^
SyntaxError: invalid syntax
<end of output>
Test time =   0.17 sec
----------------------------------------------------------
Test Failed.
```
> tests: functional: fix python syntax

- CMakeLists.txt
find_package(PythonInterp) needs to be called before the tests.
> cmake: fix tests generator

- src/p2p/net_peerlist.h
"Exploring the Monero Peer-to-Peer Network". https://eprint.iacr.org/2019/411
> p2p: add a reference to Cao, Tong et al. for the last_seen changes

- src/rpc/CMakeLists.txt
headers are defined at .h files instead of .cpp ones
> rpc headers fix @ CMakeLists.txt

- contrib/gitian/README.md
This PR fixes a number of small inconsistencies in the gitian build documentation, reduces redundancy and adds more info where needed.
* Add info on installing docker and creating the `docker` group.
* Fixes usage of git tags to have a real tag example and make sure that the full tag (eg `v0.14.1.0`) is used consistently rather than the various mixed-use before.
* Simplify signing instructions and explain how to verify checksums.
* Many small fixes to ensure consistent file naming in `.assert` and `.sig` files.
* Remove `export` of bash shell variables only used in current shell.
@TheCharlatan -- Please review when you have time  :-)
> gitian build README improvements

- contrib/depends/packages/icu4c.mk
Before this commit the icu4c repo was fetched from TheCharlatan's repository. This step was made, because up until recently the source code was hosted on sourceforge and their downloads proved very
unreliable. The origin is now the official icu4c repository. 
Also remove some commented lines left over from development.
> Depends: Update icu4c to latest support version

- contrib/gitian/gitian-linux.yml
- contrib/gitian/gitian-osx.yml
- contrib/gitian/gitian-win.yml
The tar archives generated by gitian are currently unversioned. This adds either a tag name when building from a tag, or a short commit id when building from a commit hash.
> Gitian: Add version string to output tar archives

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
The m_check_txin_table was only used for transactions for transactions with version 1, and if CACHE_VIN_RESULTS was defined, and then only as a cache. Because of this, it's likely used by nobody. We were keeping a nested map up-to-date for it though, which I removed.
> cryptonote: Remove unnecessary m_check_txin_table

- src/rpc/zmq_server.cpp
The actually addresses (rather negates the need for), #5697 too.
> zmq: fix for MacPorts latest zmq/cppzmq

- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/p2p/net_peerlist.h
- src/wallet/wallet2.cpp
- tests/unit_tests/ringct.cpp
- tests/unit_tests/rolling_median.cpp
According to [the docs][1], `std::random_shuffle` is deprecated in C++14 and removed in C++17. Since `std::shuffle` is available since C++11 as a replacement and monero already requires C++11, I think it is a good idea to use `std::shuffle` instead.
The choice of random number generator was inspired by the other usages of `std::shuffle` in the codebase; since the original `std::random_shuffle` made no guarantees whatsoever about the quality of its randomness, this does not introduce problems there.
[1]: https://en.cppreference.com/w/cpp/algorithm/random_shuffle
> Replace std::random_shuffle with std::shuffle

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
Circumvents the need to create a new blockhashing blob when you already know the data you want to set in the extra_nonce (so use this instead of reserve_size).
>  rpc: get_block_template add optional extra_nonce

- CMakeLists.txt
- README.md
Based on a patch from @mrme0w (Closes #5569). Fixes #5770
I didn't incorporate the readline changes, as OpenBSD ships readline in base.
> fix building on OpenBSD, simplify Readme section

- src/rpc/rpc_handler.cpp
In static member function ‘static boost::optional<cryptonote::rpc::output_distribution_data> cryptonote::rpc::RpcHandler::get_output_distribution(const std::function<bool(long unsigned int, long unsigned int, long unsigned int, long unsigned int&, std::vector<long unsigned int>&, long unsigned int&)>&, uint64_t, uint64_t, uint64_t, const std::function<crypto::hash(long unsigned int)>&, bool, uint64_t)’:
cc1plus: warning: ‘void* __builtin_memset(void*, int, long unsigned int)’: specified size 18446744073709551536 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
> rpc: work around a GCC 7.4.0 (at least) bug

- .travis.yml
- README.md
- contrib/depends/README.md
- contrib/depends/packages/ldns.mk
- contrib/depends/packages/openssl.mk
- contrib/depends/packages/packages.mk
- contrib/depends/toolchain.cmake.in
It is now possible to cross compile to riscv64 with `make depends target=riscv64-linux-gnu` in the top level Makefile.
> Add depends riscv 64 bit support

- src/crypto/CryptonightR_JIT.c
The value was positive rather than zero, but the caller only
checks for negative errors
> CryptonightR_JIT: fix return value on error

- src/simplewallet/simplewallet.cpp
send_message_config isn't used anywhere else in the code, and it is clear from the help command that it should be named send_signer_config.
> Fix incorrectly named binding for MMS send_signer_config command

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
This can already be obtained with `set`, but it's easier to point people to a dedicated command.
Usage scenario: User forgets to write down their restore height and would like to obtain it to make restoring the wallet at a later point in time faster.
> simplewallet: add restore_height command

- translations/ready
- utils/translations/build-translations.sh
Some translations are committed before they're ready to be used
> translations: add a ready file to control which translations to build

- .gitignore
Hi, this is my first patch.
I'm [one of the few] using NetBeans, and this PR adds the `nbproject` directory created by NetBeans to `.gitignore`.
Hope to make more contributions soon!
> Add nbproject directory to .gitignore

- src/wallet/message_store.cpp
- src/wallet/message_transporter.cpp
- src/wallet/message_transporter.h
Using the Bitmessage mechanism of *chans* instead of normal addresses as the basis for the auto-config mechanism of the MMS has advantages:
They are faster because no initial key exchange is needed - everybody who knows the chan name knows already the key (or better said, can derive the key from the chan name).
Especially in connection with the PyBitmessage app that the MMS uses chans have another advantage over normal addresses: It's possible to delete them manually if anything goes wrong and the MMS has no chance to delete them automatically.
Just for completeness' sake it should be noted that one should not bring this change into service exactly in the middle of an already-running auto-config process.
> MMS: Use chans instead of normal addresses for auto-config

- src/device/device_io_hid.cpp
`hid_error()` could return a null, which causes the program to crash with std::logic_error(), since a string cannot take a null in its constructor.
I saw this error on reddit, and I'm facing the same problem. So I fixed it.
> hid_error() could return a null, which causes the program to crash with

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
The check added here (in #5732/#5733) is supposed to disconnect behind
peers when the current node is syncing, but actually disconnects behind
peers always.
We are syncing when `target > our_height`, but the check here triggers
when `target > remote_height`, which is basically always true when the
preceeding `m_core.have_block(hshd.top_id)` check is true.
> Fix check for disconnecting peers when syncing

- src/blockchain_db/lmdb/db_lmdb.cpp
We've added a lot of new indices recently, and 20 isn't enough for them plus
new DBs opened during format migrations.
> Increase max_dbs from 20 to 32

- contrib/epee/include/net/local_ip.h
- src/net/parse.cpp
We support older boost than 1.66.
> make_address_v6 not introduced until boost 1.66

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
New CLI wallet variable: export-format with options "raw" (the default),
or "hex". "Raw" behaves as before, "hex" forces the wallet to convert
data to ASCII.
On import, we try to decode ASCII first, and if that fails, fall back to
raw in a sort of primitive auto detect.
Implements https://github.com/monero-project/monero/issues/2859
> Wallet: Option to export data to ASCII

- src/crypto/crypto.cpp
- src/crypto/crypto.h
- src/crypto/random.c
- src/crypto/random.h
- src/wallet/wallet2.cpp
It lets the user add custom entropy to the PRNG.
It does this by hashing the new data and xoring the resulting
hash with the PRNG state.
> wallet: add --extra-entropy command line flag

- Dockerfile
Updated:
- cmake 3.14.0 to 3.14.6
- boost 1.69 to 1.70
- cppzmq 4.3.0 to 4.4.1
- sodium 1.0.17 to 1.0.18
- udev 3.2.7 to 3.2.8
- protobuf 3.7.0 to 3.7.1
- zmq from 4.3.1 to 4.3.2 [(CVE-2019-13132:](https://github.com/zeromq/libzmq/releases) a remote, unauthenticated client connecting to a
libzmq application, running with a socket listening with CURVE
encryption/authentication enabled, may cause a stack overflow and
overwrite the stack with arbitrary data, due to a buffer overflow in
the library)
> Docker updated dependencies cmake boost sodium cppzmq udev protobuf zmq

- utils/build_scripts/android32.Dockerfile
- utils/build_scripts/android64.Dockerfile
Fixes issue with libtinfo5 being required by iconv1.15 but not installed
by default in latest Debian stable.
Tested with a fresh build of the Android image.
Fixes https://github.com/monero-project/monero/issues/5768
> Fix Android build in Docker

- src/ringct/bulletproofs.cc
- src/ringct/rctOps.cpp
- src/ringct/rctOps.h
- src/ringct/rctSigs.cpp
- tests/performance_tests/main.cpp
- tests/performance_tests/rct_mlsag.h
- tests/unit_tests/ringct.cpp
- Removes redundant point conversions in MLSAG verification
- Replaces public key hash-to-point zero checks with round hash-to-scalar zero checks
- Updates tests
- Improves error messages
> ringct: MLSAG speedup and zero-hash check

- contrib/gitian/gitian-build.py
Two non-critical issues being fixed here for MacOS.
1. Missing `=`.  Surprisingly this was not breaking the MacOS build ([gbuild](https://github.com/devrandom/gitian-builder/blob/master/bin/gbuild) expects `name=value` pairs!)  The reason this still builds is that the remote `url` was being interpreted as `nil` by ruby and then _defaulting_ to the url specified at [gitian-osx.yml#L27](https://github.com/monero-project/monero/blob/master/contrib/gitian/gitian-osx.yml#L27) 
2. A warning message _"Cannot build for MacOS, SDK does not exist. Will build for other OSes"_ was being shown incorrectly during the "setup" phase.  Explanation: During setup, `gitian-builder` will be cloned from https://github.com/devrandom/gitian-builder ... only after that can the MacOS SDK be added the the `inputs` …
> Gitian build script fixes for MacOS (osx)

- src/rpc/CMakeLists.txt
- src/rpc/bootstrap_daemon.cpp
- src/rpc/bootstrap_daemon.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
Implemented `--bootstrap-daemon-address auto` mode.
Allows to sync and use the wallet while the daemon is syncing with the network.
* **While the daemon is syncing**
it will automatically select random public node (node that is running with `--public-node` mode enabled) to serve incoming requests (i.e. will use it as a remote node). If currently selected public node fails, the daemon will switch to another randomly chosen public node.
* **Once the daemon is fully synced**
it will use the local blockchain to serve incoming requests, i.e. operating in normal mode.
> daemon: automatic public nodes discovering and bootstrap daemon switching

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
`handle_notify_new_block` and `handle_notify_new_fluffy_block` might trigger chain synchronization under some circumstances
https://github.com/monero-project/monero/blob/1bb4ae3b5e9c6e9599fbefb2fd311d7c850ff06c/src/cryptonote_protocol/cryptonote_protocol_handler.inl#L770
> cryptonote_protocol: fix '--no-sync', ignore new blocks and txes

- contrib/epee/include/syncobj.h
Note the misspelling of the macro name.
This code has been present, unchanged, ever since the original move to github in 2014 with commit 296ae46ed. Perhaps it is time to remove it now. :)
> Remove unused code under WINDWOS_PLATFORM guard

- src/cryptonote_core/blockchain.cpp
Apply the overflow logic used for computing already_generated_coins in
the main chain to alternative chains.
> blockchain: Fix alt chain generated coins overflow

- src/rpc/core_rpc_server.cpp
> rpc: fix unitialized 'core_rpc_server::m_was_bootstrap_ever_used'

- src/p2p/net_node.inl
It was here while debugging, and I forgot to move it away
> p2p: move log away from global

- README.md
The [Monero snap package](https://snapcraft.io/monero) is very obsolete (0.11) and not maintained since November 2017. I removed the reference in the readme and replaced it with Debian.
> readme: remove snap monero package and add debian

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/functional_tests/transactions_flow_test.cpp
- utils/python-rpc/framework/wallet.py
One considers the blockchain, while the other considers the
blockchain and some recent actions, such as a recently created
transaction which spend some outputs, but isn't yet mined.
Typically, the "balance" command wants the latter, to reflect
the recent action, but things like proving ownership wants
the former.
This fixes a crash in get_reserve_proof, where a preliminary
check and the main code used two concepts of "balance".
> wallet: fix mismatch between two concepts of "balance"

- tests/unit_tests/output_distribution.cpp
-   Initialize the `hash` in the `get_block_hash()` function of the
`output_distribution` unit test explicitly, to silence `valgrind`
warnings.
Before this change, running the `output_distribution` unit test
through `valgrind` results in warnings about uninitialized values.
To reproduce, build (in `Debug` mode) and run the unit tests
through `valgrind`:
```bash
valgrind \
--log-file=valgrind.output_distribution.log \
--leak-check=full \
--track-origins=yes \
./build/tests/unit_tests/unit_tests \
--gtest_filter=output_distribution.*
```
(Checked with Clang 8.0.0, GCC 8.3.0 and Valgrind 3.13.0.)
> Fix uninitialized values for output_distribution

- external/db_drivers/liblmdb/mdb_dump.c
- external/db_drivers/liblmdb/mdb_load.c
mdb_load wasn't properly inserting escaped backslashes into the data.
mdb_dump wasn't escaping backslashes when generating printable output.
> ITS#9068 mdb_dump/load fix backslash escaping

- contrib/depends/packages/packages.mk
Following 13c0b8c, the unwind package is being attempted to be built on
Windows and Mac when it should only be built on Linux.
> Fix Travis build on Windows + Mac

- src/rpc/core_rpc_server.cpp
Best case is an address mined previously and it'll get returned,
worst case it was never initialized in the first place
> rpc: don't include an address in mining_status when not mining

- contrib/epee/include/misc_log_ex.h
- contrib/epee/src/mlog.cpp
- external/easylogging++/easylogging++.cc
- external/easylogging++/easylogging++.h
- src/common/perf_timer.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- tests/unit_tests/logging.cpp
As a side effect, colouring on Windows should now work
regardless of version
> Properly format multiline logs

- src/blockchain_utilities/blockchain_import.cpp
- src/crypto/hash.h
- src/cryptonote_basic/miner.cpp
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/rpc/core_rpc_server.cpp
- src/wallet/message_store.cpp
- src/wallet/wallet2.cpp
- tests/core_tests/tx_validation.cpp
- tests/functional_tests/transactions_flow_test.cpp
- tests/unit_tests/test_protocol_pack.cpp
This is the same as the #5698, but I've rebased it, replaced `boost::value_initialized` with the list initializer in a couple of places in the tests and removed unused boost headers.
> Changed the use of boost:value_initialized for C++ list initializer

- src/cryptonote_config.h
- src/cryptonote_core/blockchain.cpp
- tests/core_tests/chaingen_main.cpp
- tests/core_tests/rct.cpp
- tests/core_tests/rct.h
Some custom wallet code apparently ignores this, which causes users
of that code to be fingerprinted
> blockchain: enforce 10 block age for spending outputs

- CMakeLists.txt
With this change, building the `iwyu` target will provide information
on unused headers, which can be removed to reduce compilation times. It also warns about missing headers - which can sometimes work when a particular STL-version has it already included from another dependency.
> Add the iwyu target to get information on unused headers

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
It's not great and seems vulnerable to peers lying to cause disconnections of other peers, so we'll come up with a better way later.
> Revert disconnection of peers "less synced" when we're syncing

- contrib/epee/include/misc_log_ex.h
- contrib/epee/src/mlog.cpp
use mfatal/merror/mwarning/minfo/mdebug/mtrace
> epee: misc_log_ex.h can now be used in C code

- contrib/gitian/gitian-build.py
Use shorter, prefix-unique directory names
gitian-builder  -> builder
gitian-sigs     -> sigs
monero-binaries -> out
Just use builder/inputs/monero, no need for 2nd repo clone
> Streamline build setup

- src/wallet/api/wallet.cpp
Fixes monero-project/monero-gui#2382
> wallet2_api: fix load unsigned tx from file error propagation

- src/cryptonote_core/tx_pool.cpp
There was a subtle bug in the histogram calculation in tx_memory_pool::get_transaction_stats that could, under uncommon conditions, result in an out-of-bounds write. For more information, see the extended description of the commit, which fixes this bug.
This bug was found while experimenting with speeding up adding transactions to the mempool using parallelisation.
> Fix bug in mempool get_transaction_stats histogram calculation

- src/cryptonote_core/blockchain.cpp
This would create an invalid block, though would require an attacker
to have mined a long blockchain with drifting times (assuming the
miner's clock is roughly correct)
Fixed by crCr62U0
> blockchain: ensure the block timestamp can't go below recent median

- contrib/epee/include/net/abstract_tcp_server2.inl
Resetting the timer after shutdown was initiated would keep
a reference to the object inside ASIO, which would keep the
connection alive until the timer timed out
> abstract_tcp_server2: fix lingering connections

- src/wallet/CMakeLists.txt
Required due to RandomX integration
> build: link wallet_merged against blockchain_db and hardforks obj

- src/cryptonote_protocol/levin_notify.cpp
- src/cryptonote_protocol/levin_notify.h
- src/p2p/net_node.inl
- tests/unit_tests/levin.cpp
Noticed this bug while working on mempool/dandelion++ stuff. If white noise is disabled for i2p/tor, it shouldn't use the flooding behavior used on public networks - the txes should only be sent over outgoing i2p/tor connections. Otherwise, a link to the i2p/tor exit node address can be made. Includes new tests to verify this behavior.
> Fixed i2p/tor tx flooding bug (white noise disabled)

- external/easylogging++/ea_config.h
- easylogging assumes certain non-standard headers and functions
- these function only exist in glibc
- compiling under linux without glibc thus broke compilation
> easylogging: Disable crash log on non-glibc libraries

- src/p2p/net_node.inl
Unbound uses a 64 kb large character array on the stack, which
leads to a stack overflow for some libc implementations. musl
only gives 80 kb in total. This PR changes the stack size for
these threads to 1mb, which solves the segmentation fault.
> Request a thread stack size that is large enough for unbound

- src/crypto/rx-slow-hash.c
Was using the wrong cache slot, and returning invalid PoW hashes to RPC clients
> Fix randomx cache selection for RPCs

- src/wallet/wallet_rpc_server.cpp
Fix #5887 
RPC `on_transfer_split` now returns false with same error as `on_transfer`, in case no tx is successfully sent.
> RPC on_transfer_split error consistent with on_transfer if no tx sent

- src/cryptonote_core/blockchain.cpp
Use the lesser of the short and long terms medians, rather then
the long term median alone
From ArticMine:
I found a bug in the new fee calculation formula with using only the long term median
It actually needs to be the lesser of the long term median and the old (modified short term median)
short term median with the last 10 blocks calculated as empty
Yes the issue occurs if there is a large long term median and, the short term median then falls and tries to then rise again
The fees are could be not high enough
for example LTM and STM rise to say 2000000 bytes
STM falls back to 300000 bytes
Fees are now based on 2000000 bytes until LTM also falls
So the STM is could prevented from rising back up
STM short term median LTM long term median
> blockchain: tweak fee as a function of median values

- src/p2p/net_node.cpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/rpc/rpc_args.cpp
- src/rpc/rpc_args.h
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/node_server.cpp
Currently the daemon ignores p2p or rpc port bind failure by default.
Requires https://github.com/monero-project/monero/pull/5947
> p2p+rpc: don't skip p2p or rpc port bind failure by default

- contrib/epee/include/net/levin_protocol_handler_async.h
If adding a response handler after the protocol is released,
they could never be cancelled again, and would end up keeping
a ref that never goes away
> levin: armour against some "should not happen" case

- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
This seems like a simple mistake. I don't know why this hasn't caused any issues before.
> tx_pool: make spent return-by-reference as intended

- src/cryptonote_basic/miner.cpp
Checking battery status uses x86-only headers and functions. Remove this functionality to get it to build on other architectures.
> Fix build on FreeBSD/!x86

- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
miner_tx_hash is serialized in fill_block_header_response already, so remove the 2nd call in on_get_block.
> Print cumulative difficulty and don't serialize miner tx hash twice in print_block

- contrib/epee/include/int-util.h
- contrib/epee/src/CMakeLists.txt
- contrib/epee/src/int-util.cpp
- src/cryptonote_basic/cryptonote_basic_impl.cpp
- src/cryptonote_core/blockchain.cpp
- tests/unit_tests/mul_div.cpp
add a 128/64 division routine so we can use a > 32 bit median block
size in calculations
> Support median block size > 4 GB

- README.md
We use another Localization platform now: Weblate (translate.getmonero.org)
> Change 'Pootle' to 'Weblate' in Readme

- src/cryptonote_core/blockchain.cpp
as a safety to reject if it somehow does not get initialised
> blockchain: initialize pow to ff..ff

- contrib/epee/include/net/abstract_tcp_server2.inl
> abstract_tcp_server2: move "Trying to connect" from error to debug

- contrib/epee/include/net/net_ssl.h
- contrib/epee/src/net_ssl.cpp
TCP server has its own worker threads executing io_service's tasks thus `run_one()` can block.
> epee: fix SSL server handshake, run_one() can block, use poll_one()

- src/blockchain_db/lmdb/db_lmdb.cpp
as opposed to an absent record
> db_lmdb: an empty prunable data record means the tx is not pruned

- src/blockchain_utilities/blockchain_utilities.h
This limit must be increased, otherwise the stagenet blockchain cannot be imported. Fixes #5957
> utils: Increase max block size for import/export

- contrib/epee/include/net/abstract_tcp_server2.inl
> epee: use SO_REUSEADDR on non-Windows targets

- src/hardforks/hardforks.cpp
* Mainnet: 1978433 (~30th November), according to preliminary consensus from the 2019-09-22 dev meeting.
* Stagenet: 454721 (~16th November), 2 weeks before the mainnet as has been the case for the v8 and v10 forks.
* Testnet: already forked
All fork heights correspond to the beginning of a RandomX epoch (`height % 2048 == 65`).
> v12 fork heights

- contrib/depends/packages/cppzmq.mk
- contrib/depends/packages/zeromq.mk
- 4.1.7 is a required security release
- `$(package)_patches` should still apply
- I have not looked into why exactly we are building against the 4.1 series instead of the 4.3 series though I assume 4.1 is somehow a repro build requisite (4.3 is the standard on the distributions I've seen - and it seems to build correctly)
- I have not tested these diffs (the build should still work though). Testers welcome.
> depends: bump cppzmq/zeromq4-1 to latest versions

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
- utils/python-rpc/framework/daemon.py
This allows flushing internal caches (for now, the bad tx cache,
which will allow debugging a stuck monerod after it has failed to
verify a transaction in a block, since it would otherwise not try
again, making subsequent log changes pointless)
> rpc: add a flush_cache RPC

- cmake/GitVersion.cmake
When building of a `git clone monero`, but not in a sub dir under `monero`, cmake fails to find stuff.
Adding `WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}` to `execute_process()` fixes that.
> CMake build out of source

- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/rpc/core_rpc_server.cpp
Currently if a user restarts already synced daemon with `--bootstrap-daemon-address auto --no-sync` options, the daemon will immediately disable bootstrapping cause local blockchain is synced.
But it shouldn't do that if `--no-sync` is enabled.
Reported by @selsta
> daemon: always use bootstrap daemon (if set) in '--no-sync' mode

- contrib/gitian/gitian-build.py
Create out dir in workdir, not in builder dir to make copying of archives succeed.
> [v0.15] gitian: fix out dir location

- contrib/gitian/gitian-build.py
Create out dir in workdir, not in builder dir to make copying of archives succeed.
> gitian: fix out dir location

- contrib/epee/include/net/abstract_tcp_server2.inl
This fixes rapid reconnections failing as the peer hasn't yet
worked out the other side is gone, and will reject "duplicate"
connections until a timeout.
> epee: close connection when the peer has done so

- src/wallet/node_rpc_proxy.cpp
Fixes https://github.com/monero-project/monero/issues/6131
> wallet: set non-empty error string on connection failure

- src/daemonizer/posix_fork.cpp
Don't leave stdout/stderr dangling on a fork.
> Fix #6147 DB corruption from child process overwrite

- src/daemonizer/posix_fork.cpp
Don't leave stdout/stderr dangling on a fork.
> [v0.15] Fix #6147 DB corruption from child process overwrite

- contrib/gitian/README.md
* Removed the version-specific checksum to simplify maintenance.
* Added android to signing example per #6077.
* Removing the `TODO` which is obsolete.
> Gitian Readme: adding android signing & remove version-specific checksum.

- ANONYMITY_NETWORKS.md
Some items below such as the `torrc` config will break in mysterious ways if items are not on seperate lines.  The command line params of course could be inline, but it seems the _intention_ was to show two separate options for readers to choose from.
**Update:** added some typo fixes.
@vtnerd @jtgrassie
> ANONYMITY_NETWORKS.md : fix unintentional wrapping

- tests/functional_tests/mining.py
this prevents messing up any subsequent test too
> functional_tests: ensure mining stops on error in mining test

- contrib/depends/packages/sodium.mk
- contrib/depends/patches/sodium/fix-whitespace.patch
Version 1.0.16 is no longer provided on the same path of the libsodium release website.
> depends: update libsodium to 1.0.18

- tests/core_tests/chaingen.cpp
- tests/core_tests/chaingen.h
- tests/core_tests/wallet_tools.cpp
Currently, the `chaingen.cpp` does not support generating testing block chain with the HF12, which uses RandomX. The problem is that the miner function requires blockchain object to get certain block hashes.
I've created a simple workaround which extracts the block and hardforks from the `events` list. If caller needs to build HF12 blocks, he should set events and network type for the blockchain object. 
It is initial implementation of a working fix, it is not optimal as the blockchain object is constructed with each new block (if HF>=12), but this is robust as there is no need to maintain blockchain db consistency with the tests, it is just created from events when needed.
What do you think?
> tests: fix HF12 chaingen

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- utils/python-rpc/framework/wallet.py
Add a method for creating batches of subaddresses, instead of creating them one at a time with `create_address`.
> Add count parameter to create_address method in wallet RPC

- src/blockchain_db/blockchain_db.cpp
- src/blockchain_db/blockchain_db.h
- src/cryptonote_config.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/cryptonote_protocol/enums.h
- src/cryptonote_protocol/levin_notify.cpp
- src/cryptonote_protocol/levin_notify.h
- src/p2p/net_node.cpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/net_node_common.h
- tests/core_tests/chaingen.h
- tests/unit_tests/levin.cpp
This changes the Tx notification algorithm from a basic "flooding" to Dandelion++ Fluff (aka diffusion). This is close the design that Bitcoin Core is using for diffusion (but does not have "full" Dandelion++). This makes it more difficult to learn connection graphs, because each tx is propagated slightly differently due to randomized delays. It also gives an opportunity to send your txes with other txes being spread at the same time.
I decided to PR this immediately because of [this comment](https://github.com/monero-project/monero/pull/5965/files/cfe35e7903c179bcc93be15ed1427b1d7b89588b#diff-d65754889afbda19c7e62e5f3212bd5cR1298) by @moneromooo-monero in the split mempool PR. The issue was that "private" txes being re-relayed would be sent at the same time as "public" txs being …
> Change to Tx diffusion (Dandelion++ fluff) instead of flooding

- contrib/gitian/gitian-build.py
All sigs are currently placed in the linux sigs directory, use a directory for each platform as before instead.
> Gitian: Fix sigs generation

- .github/workflows/build.yml
~~Windows will be added once I get it working.~~ Done.
Any opinions against this? It should be easy to maintain compared to the buildbots as anyone can edit and fix them. We used Github Actions for the GUI repository and it worked well.
If we move to Gitlab I can setup a different CI provider.
Also the buildbot slave links should get removed once this gets merged as they are unmaintained anyway.
> workflows: add build and test workflow

- tests/core_tests/chaingen.cpp
- e.g., fixes gen_block_big_major_version test, error: generation failed: what=events not set, cannot compute valid RandomX PoW
- ask for events only if difficulty > 1 (when it really matters)
- throwing an exception changed to logging, so it is easy to spot a problem if tests start to fail. Throwing an exception could be too harsh for some tests, it may be a desired situation.
> fix tests bug added in #6110

- src/lmdb/table.h
> 23:04 <+hyc> would be nice sto shut these warnings up http://paste.debian.net/1113538/
> n file included from /home/ubuntu/build/monero/src/lmdb/table.cpp:27:
/home/ubuntu/build/monero/src/lmdb/table.h:18:22: warning: 'const' qualifier on function type 'MDB_cmp_func' (aka 'int (const MDB_val *, const MDB_val *)') has no effect [-Wignored-qualifiers]
MDB_cmp_func const* const key_cmp;
^~~~~
/home/ubuntu/build/monero/src/lmdb/table.h:19:22: warning: 'const' qualifier on function type 'MDB_cmp_func' (aka 'int (const MDB_val *, const MDB_val *)') has no effect [-Wignored-qualifiers]
MDB_cmp_func const* const value_cmp;
^~~~~
A free function cannot be const, so a pointer to a const one is meaningless. The compiler ignores this qualifier, but warns about it.
> lmdb: Remove meaningless const qualifier on function type

- src/cryptonote_core/cryptonote_core.cpp
This is handy when doing tests that generate a lot of transactions, since that
takes time it's preferable to re-use the database for future runs. The option defaults to false for the sake of backwards compatibility.
> Add a --keep-fakechain option to keep fakechain databases

- src/blockchain_utilities/blockchain_stats.cpp
It reports the actual size as pruned, however
> blockchain_stats: make it work on pruned blockchains

- src/daemon/command_parser_executor.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
It's a very common usage (for my anyway) and avoids the need to
get the current height, paste, subtract one, etc
> daemon: allow printing N blocks from the end of the chain

- contrib/epee/include/net/net_helper.h
- contrib/epee/src/http_auth.cpp
This is a bug waiting to happen
> epee: reorder a couple init list fields to match declaration

- src/cryptonote_basic/miner.cpp
This avoids lengthy init times when testing
> miner: use verification mode for low diff one block nonce searches

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
Adding a new `amounts` field ot the output of `get_transfers` RPC
method. This field specifies individual payments made to a single
subaddress in a single transaction, e.g., made by this command:
transfer <addr1> <amount1> <addr1> <amount2>
Resolves https://github.com/monero-project/monero/issues/6163
> Wallet: Distingush amounts for a single subaddress

- .github/workflows/build.yml
libwallet compilation is disabled by default so I guess this can be useful.
> workflows: add libwallet compile check

- .github/workflows/build.yml
```
cc1plus.exe: out of memory allocating 600896 bytes
```
Looks like 7GB RAM is not enough for -j3 on Windows. While monero compiles fine most of the time, it appears that it ran out of RAM twice.
https://github.com/monero-project/monero/runs/429237309
https://github.com/monero-project/monero/runs/429239677
> workflows: windows j3 -> j2

- tests/unit_tests/bulletproofs.cpp
It was intended to check a case which is actually valid (0 gamma),
but was actually duplicating the bad amount test.
Reported by WhatDo_ on IRC.
> unit_tests: remove invalid bulletproofs unit test

- contrib/epee/src/net_ssl.cpp
boost::asio::ssl::context is created using specifically TLSv1.2, which
block the ability to use superior version of TLS.
Filtering is also made specially later in the code to remove unsafe
version for TLS such SSLv2, SSLv3 etc..
This change is removing double filtering to allow TLSv1.2 and above to
be used.
> ssl: allow multiple version of TLS

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/rpc_args.cpp
- src/rpc/rpc_args.h
RPC clients ban feature counts how many errors every host has made and after it gets more than certain threshold the host is banned for 24 hours.  
Often public monero nodes are not exposed directly to internet but resides behind web server or a proxy. In this valid case the only remote host the node sees is proxy server's one. If one of external clients makes some RPC calls that end up with ban the RPC becomes unavailable for all the clients.
This is what happened with our public node lately.
If `--disable-rpc-ban` option is set the feature is disabled.
> Command line option to disable ban RPC clients

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
Dividing `dt` here by 1e6 converts it to seconds, but that is clearly wrong since `REQUEST_NEXT_SCHEDULED_SPAN_THRESHOLD_STANDBY` is measured in microseconds.  As a result, this if statement was effectively never entered.
> Fix time comparison math

- contrib/epee/include/serialization/keyvalue_serialization_overloads.h
- contrib/epee/include/storages/parserse_base_utils.h
- contrib/epee/include/storages/portable_storage.h
- contrib/epee/include/storages/portable_storage_base.h
- contrib/epee/include/storages/portable_storage_from_bin.h
- contrib/epee/include/storages/portable_storage_from_json.h
- tests/unit_tests/net.cpp
- Removed copy of field names in binary deserialization
- Removed copy of array values in binary deserialization
- Removed copy of string values in json deserialization
- Removed unhelpful allocation in json string value parsing
- Removed copy of blob data on binary and json serialization
The changes to the binary deserialization and serialization **do** affect the p2p code, which includes the stuff in the key-value serialization code. The changes are fairly straightforward.
I also did some benchmarking:
`GET_BLOCKS_FAST` with 1000 blocks fetched and `pruned == true` (identical to wallet behavior).
Serialization within 1 ms. Deserialization ~4.9% speedup on ryzen 3900x and ~5.6% on i7-7Y75 (mobile). The raw numbers were 3 ms and 6 ms improvement respectively.
`BLOCK_HEADERS_RANGE` with …
> Improved performance for epee serialization:

- src/wallet/wallet2.cpp
If the hashes received would move the current blockchain past the
stop point, the short history would not be updated, since we do
not expect another loop, but the daemon might return earlier hashes,
causing the end index to not be enough to reach the threshold and
this require another loop, which will download the same hashes and
cause an infinite loop.
> wallet2: fix hang in wallet refresh

- src/rpc/core_rpc_server.cpp
Since we now get pruned data in the first place, the "unpruned" data
size will in fact be the pruned data size, leading to confusion
> rpc: drop the obsolete and wrong "unpruned size" log

- contrib/depends/funcs.mk
Ref: https://github.com/zcash/zcash/pull/2700
> depends: empty spaces in PATH variable cause build failure

- src/rpc/core_rpc_server.cpp
It was removed to save duplicated generation time, but it can
be copied from another instance instead
> rpc: fill miner_tx_hash again

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
If more than one thread wants to make sure of the spend secret key,
then we decrypt on the first caller and reencrypt on the last caller,
otherwise we could use an invalid secret key.
> wallet2: guard against race with multiple decrypt_keys users

- contrib/epee/src/hex.cpp
- tests/unit_tests/epee_utils.cpp
Identical to PR #6359 except on 0.15 branch. There shouldn't be any issues with current usage, so this is mainly a protection against potential modifications to this branch.
> Fixed string_ref usage bug in epee::from_hex::vector

- src/p2p/net_node.inl
During the handshake for an incoming connection, the peer id is checked against the local node's peer id only for the specific zone of the incoming peer, in order to avoid linking public addresses to tor addresses:
https://github.com/monero-project/monero/blob/5d7ae2d2791c0244a221872a7ac62627abb81896/src/p2p/net_node.inl#L2343
However, on handshakes for outgoing connections, all zones are checked:
https://github.com/monero-project/monero/blob/5d7ae2d2791c0244a221872a7ac62627abb81896/src/p2p/net_node.inl#L1064
If an attacker wanted to link a specific tor node to a public node, they could potentially connect to as many public nodes as possible, get themselves added to the peer whitelist, maybe stuff some more attacker-owned addresses into the greylist, then disconnect, and for any future …
> p2p: plug tor to clearnet association vector

- contrib/gitian/README.md
- contrib/gitian/gitian-build.py
The ip link currently listed in the README no longer works on the newest version of lxc shipped with ubuntu 18.04, this commit corrects this.
> Gitian: Change lxc ip link

- contrib/epee/include/hex.h
- src/rpc/daemon_handler.cpp
- src/rpc/daemon_handler.h
- src/rpc/daemon_messages.cpp
- src/rpc/daemon_messages.h
- src/rpc/message.cpp
- src/rpc/message.h
- src/serialization/CMakeLists.txt
- src/serialization/json_object.cpp
- src/serialization/json_object.h
- tests/unit_tests/epee_utils.cpp
- tests/unit_tests/json_serialization.cpp
- Finding handling function in ZMQ JSON-RPC now uses binary search
- Temporary `std::vector`s in JSON output now use `epee::span` to
prevent allocations.
- Binary -> hex in JSON output no longer allocates temporary buffer
- C++ structs -> JSON skips intermediate DOM creation, and instead
write directly to an output stream.
I ran a "hell test" for performance numbers - `GetBlocksFast` with unpruned txes during the biggest blocks (borromean!). The improvement is likely lower for smaller JSON messages, but is still representive of a decent speed improvement:
Fanless i7-7Y75 laptop -> ~33.7%, ryzen 3900x desktop -> ~34.1%
Unfortunately, there is lots of churn due to the function argument changes. And the JSON output can still use improvement (there will hopefully be more changes to the ZMQ …
> Various improvements to the ZMQ JSON-RPC handling:

- src/serialization/json_object.h
Quick and dirty workaround. Could be fixed in other ways at cost of additional changes.
> workaround for GetObject windows.h macro and rapidjson conflict

- README.md
10 block lock time is for incoming outputs and not only incoming transactions (an outgoing transaction may have an incoming change output that is also locked for 10 blocks)
> README: lock time is for incoming outputs, not transactions

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
The added condition "hshd.current_height >= target" guards against reporting "synchronized" too early in the special situation that the very first peer sending us data is synced to a lower height than ourselves.
In this situation, `target` gets set to our own current height at line 344 because core's `target_blockchain_height` is not yet set. `core.have_block` comes out as true because we already have that lower block, and the result is reporting "You are now synchronized with the network" too early.
> Daemon: Guard against reporting "synchronized" too early

- src/cryptonote_core/blockchain.cpp
M100 = max{300kb, min{100block_median, m_long_term_effective_median_block_weight}}
not
M100 = max{300kb, m_long_term_effective_median_block_weight}
Follow up from PR #5941 which altered how fees for new transactions are calculated, but not how nodes verify transaction fees. Low risk fix.
> Fix check_fee() and get_dynamic_base_fee_estimate() discrepancies

- src/net/i2p_address.cpp
- src/net/tor_address.cpp
- tests/unit_tests/net.cpp
The less(lhs, rhs) functions for both i2p and tor addresses do not work as expected. The logic should only be testing the ports if the hosts are equal (if currently falls back to ports if lhs.host >= rhs.host).
A concrete example:
let addrA = aaaaaaaaaaaaaaaa.onion:443
and addrZ =zzzzzzzzzzzzzzzz.onion:80
less(addrA, addrZ) returns true (since strcmp(addrA.host, addrZ.host) < 0)
less(addrZ, addrA) returns true (since strcmp(addrZ.host, addrA.host) > 0 and addrZ.port < addrA.port)
> net: fix incorrect less operator for top/i2p addresses

- contrib/gitian/gitian-build.py
The previous version was not working correctly as [subprocess.call](https://docs.python.org/2/library/subprocess.html#subprocess.call) returns the exit status (aka `returncode`) of the command executed.  The exit status will be `0` if the command succeeds, which is interpreted as `False`, then negated by the preceding `not`.
Exit status will be something other than `0` if it fails (eg `1`, `128`, etc) so we just catch them all.
The script should fail if `--docker` is specified, but the command is not available.
Finally, `shell=False` is the default, so no need to specify.
New version will correctly test if `docker` command is available and fail with a nice message if not.
**Note:** Let me know if you'd prefer this be switched to use the `which` command.  I was trying not to modify …
> gitian-build.py: Fixing check for docker command.

- src/wallet/wallet2.cpp
Because the user might do this for reasons unknown.
Values beyond l-1 will be reduced, so are accepted.
Reported by who-biz.
> wallet2: reject zero keys in json input

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- src/cryptonote_protocol/cryptonote_protocol_defs.h
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- tests/core_proxy/core_proxy.h
- tests/unit_tests/node_server.cpp
A newly synced Alice sends a (typically quite small) list of
txids in the local tpxool to a random peer Bob, who then uses
the existing tx relay system to send Alice any tx in his txpool
which is not in the list Alice sent
> protocol: request txpool contents when synced

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
This allows RPC coming from the loopback interface to not have
to pay for service. This makes it possible to run an externally
accessible RPC server for payment while also having a local RPC
server that can be run unrestricted and payment free.
> rpc: add --rpc-payment-allow-free-loopback

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
The warning about spending more than one output with similar creation
time was skipped if print-ring-members was not set, and it defaults to
false, which means most people probably aren't getting this warning if
they spend correlated outputs.
Reported by SeventhAlpaca.
> simplewallet: warn about correlations if print-ring-members is not set

- src/wallet/wallet2.cpp
The backward compatibility code was always setting it to 1
in modern wallets since store_tx_keys was not present and thus
assumed to be 1 by default.
Reported by SeventhAlpaca
> wallet2: fix store-tx-info loading

- contrib/epee/include/storages/portable_storage_base.h
The implicit copy assignment operator was deprecated because the class
has an explicit copy constructor. According to the standard:
> The generation of the implicitly-defined copy assignment operator is
> deprecated (since C++11) if T has a user-declared destructor or
> user-declared copy constructor.
> 
Recent versions of gcc (9.1+) and clang (10.0) warn about this.
> epee: Explicitly define copy assignment operator

- contrib/epee/include/net/levin_protocol_handler_async.h
- src/p2p/net_node.inl
When a handshake fails, the handshake method was closing the
connection, and the caller was also doing so on error, triggering
the noisy (but harmless) exception.
> p2p: fix frequent weak_ptr exception on connection

- src/cryptonote_basic/account.cpp
- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_config.h
- src/device/device_default.cpp
- src/multisig/multisig.cpp
- src/ringct/bulletproofs.cc
- src/rpc/rpc_payment.cpp
- src/wallet/ringdb.cpp
- src/wallet/wallet2.cpp
Moves some hash function domain separators to a common configuration location, to reduce the likelihood of future collision.
> Hash domain separation

- contrib/epee/demo/iface/transport_defs.h
- contrib/epee/include/net/http_protocol_handler.h
- contrib/epee/include/net/munin_connection_handler.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/daemon/main.cpp
- src/ringct/bulletproofs.cc
- src/simplewallet/simplewallet.cpp
- tests/unit_tests/mul_div.cpp
- tests/unit_tests/test_tx_utils.cpp
Cleaning up a little around code base, and I found empty statements on our fork. It is human error, and they are safely removed.
> Clean removal of empty statements

- src/rpc/rpc_payment_signature.cpp
Or is there a reason to allow old timestamps?
> rpc: Add check for too old timestamps in payment signatures.

- tests/unit_tests/hmac_keccak.cpp
- tests/unit_tests/keccak.cpp
Closes https://github.com/monero-project/monero/issues/6345, resolves #6412
> unit_tests: fix missing test names

- contrib/epee/include/hex.h
- contrib/epee/include/storages/parserse_base_utils.h
- contrib/epee/include/string_tools.h
- contrib/epee/src/hex.cpp
- src/rpc/rpc_args.cpp
- src/serialization/json_object.cpp
- src/serialization/json_object.h
- src/wallet/wallet2.cpp
- tests/unit_tests/epee_utils.cpp
The initial reason for the change was hex->bin conversion in the ZMQ JSON-RPC server required a temporary `std::string` for each attempt. The individual commits should explain the other changes.
@hyc and @moneromooo-monero should have copyrights, allowing the move into the monero copyrighted file. This move isn't strictly necessary to improve performance, but does it make easier on the compiler (less code in the header AND declared in a header with less overhead). The latter is useful because the ZMQ JSON code can (eventually) just include `hex.h` instead of the more expensive `string_tools.h`.
> Improve hex->bin Conversion

- README.md
From the FreeBSD architecture handbook (https://www.freebsd.org/doc/en/books/arch-handbook/jail-restrictions.html) as it relates to `allow.sysvipc`, "By default, this sysctl is set to 0. If it were set to 1, it would defeat the whole purpose of having a jail; privileged users from the jail would be able to affect processes outside the jailed environment."  This is undesirable behavior.
Per `man jail`, regarding `allow.sysvipc`, "A process within the jail has access to System V primitives.  This is deprecated in favor of the per-module parameters."
Since FreeBSD 11, the new way to deal with this (the per-module parameters) is with: `sysvshm`, for shared memory, `sysvsem`, for semaphores, and `sysvmsg`, for message queues.  These can be set selectively to either `disable`; `inherit`, for …
> README: Provides safer semaphore privilege to FreeBSD jail; notes port/pkg availability

- src/rpc/CMakeLists.txt
- src/rpc/bootstrap_daemon.cpp
- src/rpc/bootstrap_daemon.h
- src/rpc/bootstrap_node_selector.cpp
- src/rpc/bootstrap_node_selector.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/bootstrap_node_selector.cpp
Improved public node selection algo used in `Simple mode`/`---bootstrap-daemon-address auto`.
1. In-memory public nodes cache storing up to N (N=1000 by default) entries
2. If the cache doesn't have at least one good public node (having fails count == 0):
1. Get public nodes from P2P
2. Add new white public nodes to cache with initial fails count = 0
3. Add new gray public nodes to cache with initial fails count = 1
4. Truncate the cache to N public nodes, keep the nodes having lower fails count
3. Select most stable public node (sorted by fails count), if there are multiple - choose a random one
4. Send an RPC request:
1. On fail - increase the node's fails count by 2 and go to step 2
2. On success - decrease the node's fails count by 2 and go to step 4
> daemon: auto public nodes - cache and prioritize most stable nodes

- src/rpc/message.cpp
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/zmq_rpc.cpp
The ZMQ JSON-RPC fails to ensure that the `method` field is a string.
> Fixed bug in ZMQ JSON-RPC method field

- README.md
- contrib/epee/src/net_ssl.cpp
The reason for this is that we use `boost::asio::ssl::context::tls`,
which was introduced in version 1.64, the current master will not
compile with an older boost version.
Additionally, the check in CMake for boost version smaller than 1.62 was
removed, since this no longer applies (the configure would have failed
because the required minimum version was not found).
The instructions for building boost from source on debian Jessie have
been slightly changed, with the old instructions we would have tried to
remove all installed boost packages - which are also used by other
packages installed on the system. Instead we now only remove the header
files.
The downloaded version for boost has also been bumped to 1.72. If we are
building boost from source, there is no reason not to use the most …
> Fix compatibility with boost < 1.64

- src/cryptonote_protocol/levin_notify.cpp
- tests/unit_tests/levin.cpp
Transactions are temporarily queued per connection for diffusion, which can leak receive/processing order of two different connections.
> Fix receive order leakage with tx fluffing

- src/blockchain_db/lmdb/db_lmdb.cpp
If a db resize happened, the txpool meta cursor might be stale,
and was not being renewed when necessary.
It would cause this SEGSEGV:
in mdb_cursor_set ()
in mdb_cursor_get ()
in cryptonote::BlockchainLMDB::get_txpool_tx_blob(crypto::hash const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cryptonote::relay_category) const ()
in cryptonote::tx_memory_pool::get_transaction(crypto::hash const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cryptonote::relay_category) const ()
in cryptonote::t_cryptonote_protocol_handler<cryptonote::core>::handle_notify_new_fluffy_block(int, epee::misc_utils::struct_init<cryptonote::NOTIFY_NEW_FLUFFY_BLOCK::request_t>&, cryptonote::cryptonote_connection_context&) ()
> db_lmdb: fix race crash using a stale cursor

- contrib/depends/packages/sodium.mk
- contrib/depends/patches/sodium/disable-glibc-getrandom-getentropy.patch
Resolves https://github.com/monero-project/monero/issues/6396
> depends: libsodium disable getrandom()/getentropy() (glibc < 2.25)

- src/simplewallet/simplewallet.cpp
Also avoid rewriting the wallet if the setting is already was we need
> simplewallet: fix smart mining not starting after first setup

- contrib/depends/packages/qt.mk
5.7.1 was removed from official qt.io archive, this is one of the few mirrors remaining that keep a copy.
I think it would be better if @TheCharlatan updated to a newer version soon than merging this PR
> depends: update qt 5.7.1 download link

- src/cryptonote_core/tx_pool.cpp
- tests/core_tests/chaingen_main.cpp
- tests/core_tests/tx_pool.cpp
- tests/core_tests/tx_pool.h
This makes the check closer [to the original](https://github.com/monero-project/monero/blob/c96b7ee61910ab64e0e0cbd978addfe2ea3e4b27/src/cryptonote_core/tx_pool.cpp#L416). The inline comment should explain enough. This was due to a reddit post, asking about DoS and Dandelion (mentioned in a Bitcoin thread). I also think the check is far more clear now, my original approach was a bit confusing.
The summary is that this allows a txid to go from stem->fluff but does not allow a key-image with two different txid in the stem phase. This can only occur if someone were trying to spam.
> Correct key image check in tx_pool

- src/blockchain_db/blockchain_db.cpp
- src/blockchain_db/blockchain_db.h
- src/crypto/duration.h
- src/cryptonote_basic/verification_context.h
- src/cryptonote_config.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_protocol/cryptonote_protocol_defs.h
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/cryptonote_protocol/cryptonote_protocol_handler_common.h
- src/cryptonote_protocol/levin_notify.cpp
- src/cryptonote_protocol/levin_notify.h
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/net_node_common.h
- src/rpc/core_rpc_server.cpp
- src/rpc/daemon_handler.cpp
- src/rpc/daemon_handler.h
- tests/core_tests/chaingen.h
- tests/core_tests/chaingen_main.cpp
- tests/core_tests/tx_pool.cpp
- tests/core_tests/tx_pool.h
- tests/unit_tests/levin.cpp
- New flag in NOTIFY_NEW_TRANSACTION to indicate stem mode
- Stem loops detected in tx_pool.cpp
- Embargo timeout for a blackhole attack during stem phase
> Adding Dandelion++ support to public networks:

- src/common/util.cpp
- src/common/util.h
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
About every 2 minutes the normal simple sync progress message in the daemon
Synced 2002098/2002459 (99%, 361 left)
gets an estimate for remaining sync time added:
Synced 2002118/2002459 (99%, 341 left, 43% of total synced, estimated 2 minutes left)
And after sync finishes a little statistic is output:
Synced 203 blocks in 1 minutes (1.765 blocks per second)
> Daemon: Print estimates for time until fully synced

- contrib/epee/include/net/abstract_http_client.h
- contrib/epee/include/net/http_client.h
- contrib/epee/include/storages/http_abstract_invoke.h
- contrib/epee/include/syncobj.h
- contrib/epee/src/CMakeLists.txt
- contrib/epee/src/abstract_http_client.cpp
- src/wallet/message_store.cpp
- src/wallet/message_store.h
- src/wallet/message_transporter.cpp
- src/wallet/message_transporter.h
- src/wallet/node_rpc_proxy.cpp
- src/wallet/node_rpc_proxy.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_payments.cpp
- tests/fuzz/http-client.cpp
- Add contrib/epee/include/net/abstract_http_client.h which
http_client.h extends.
- Replace `simple_http_client` with `abstract_http_client` in wallet2,
message_store, message_transporter, and node_rpc_proxy.
- Skip code incompatible with webassembly using `#if defined
__EMSCRIPTEN__` directives.
- Add ability to import and export wallet file buffers in wallet2
instead of using file system.
Code and collaboration credits: moneromooo, endogenic, mymonero
Feedback is requested on removing the call to `miner::find_nonce_for_given_block` in cryptonote_tx_utils.cpp and changing the default http method from `GET` to `POST` in wallet2.h and http_abstract_invoke.h (otherwise the browser issues `GET` requests which fail).
> Allow wallet2.h to run in WebAssembly.

- contrib/depends/packages/openssl.mk
Its obsolete since long. My proposal would be to store all depends on getmonero.org server and create a fallback address like https://getmonero.org/depends-sources
Also update the link for getting openssl 1.0.2r, its been moved
> depends: update openssl package link

- src/wallet/api/wallet2_api.h
- src/wallet/api/wallet_manager.cpp
GUI version and build tag may differ from libwallet ones (i.e. monero core version used to build GUI).
The commit provides a way to check updates based on GUI version and build tag.
> wallet_api: checkUpdate - optional version and buildtag params

- tests/functional_tests/make_test_signature.cc
- tests/functional_tests/rpc_payment.py
This fixes a test failure now that timestamps are more constrained
> functional_tests: ensure signed timestamps are fresh

- src/p2p/net_node.inl
This is a new PR to replace the closed [https://github.com/monero-project/monero/pull/6417](https://github.com/monero-project/monero/pull/6417)
In summary:
I am running a mainnet node in the cloud and I would like to volunteer it as a seed node.
Of note:
1. It has a fixed IP address
2. I will be promptly updating it as required (currently running v0.15.0.5)
3. I intend to keep running it for the long term
4. Having followed the discussion at the last monero-dev meeting (29/03/20), I have added my node's IP address to the list in this PR.
The provider is `Hetzner` and it is located in `Helsinki, Finland`.
I think that @binaryFate will be able to vouch for me in terms of trust.
If you need further details, let me know.
> p2p: add seed node.

- src/cryptonote_core/tx_pool.cpp
makes silly g++ 5.4.0 happy by removing the confusion for `const auto relay_method` var so as it compiles on xenial
> txpool.cpp: rename var to fix for old g++ version (xenial default)

- contrib/epee/include/byte_slice.h
- contrib/epee/src/byte_slice.cpp
- src/net/zmq.cpp
- src/net/zmq.h
- src/rpc/daemon_handler.cpp
- src/rpc/daemon_handler.h
- src/rpc/message.cpp
- src/rpc/message.h
- src/rpc/rpc_handler.h
- src/rpc/zmq_server.cpp
- tests/unit_tests/net.cpp
Sending JSON response on the ZMQ RPC server has two allocations + copies - one into a std::string and a second internally within ZMQ. This removes that second copy (but ZMQ still allocates internally!), which is an obvious performance gain.
Its possible to remove the allocation+copy into `bye_slice` by getting `rapidjson` to write directly into a `byte_slice` compatible buffer. I am "saving" that for a future commit because its a bit more code.
I ran with this with clang ASAN mode, no memory leaks detected in the unit tests or in the ZMQ JSON-RPC server usage.
> Use byte_slice for sending zmq messages - removes data copy within zmq

- src/p2p/net_node.h
- src/p2p/net_node.inl
Speed up the daemon startup, ~15-20sec gain.
1. On-demand seed nodes initialization (DNS seed nodes lookup with fallback to hardcoded list). Shouldn't do this on each daemon startup, but only when we have no white peers and want to connect to a seed node.
Run the task in background, i.e. in p2p connection thread on first `connect_to_seed()` call.
2. `m_seed_nodes` access should be thread-safe
3. `m_fallback_seed_nodes_added` flag should be atomic
> p2p: startup speedup, init seed nodes on first 'connect_to_seed()'

- contrib/epee/include/net/http_base.h
- contrib/epee/include/net/http_client.h
- src/device/device.hpp
- src/device_trezor/device_trezor.cpp
- src/device_trezor/device_trezor.hpp
- src/device_trezor/device_trezor_base.cpp
- src/device_trezor/device_trezor_base.hpp
- src/device_trezor/trezor/debug_link.cpp
- src/device_trezor/trezor/debug_link.hpp
- src/device_trezor/trezor/protocol.cpp
- src/device_trezor/trezor/protocol.hpp
- src/device_trezor/trezor/transport.cpp
- src/device_trezor/trezor/transport.hpp
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet2_api.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- tests/trezor/daemon.cpp
- tests/trezor/daemon.h
- tests/trezor/trezor_tests.cpp
- tests/trezor/trezor_tests.h
- choice where to enter the passphrase is now made on the host (Trezor changed this in new firmwares)
- use wipeable string in the Trezor communication stack
- wipe passphrase memory after use
- protocol optimizations, prepare for new firmware version which scales better with subaddresses
- subaddresses are not pre-computed but each UTXO carries also subaddr index so all key are computed on the fly, constant memory w.r.t. number of subaddresses
- same for key image refresh
- sending only required info to the Trezor for each step, saves Trezor CPU & RAM, faster protocol
- optimizations detailed in https://github.com/trezor/trezor-firmware/pull/786
- minor fixes and improvements
- tests: fix and update Trezor tests, HF12, disable long payment ID test
- wallet API update for passphrases, GUI …
> trezor: adapt to new passphrase mechanism

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
Expects an account number, then the usual sweep_all options
Useful to move monero that was accidentally sent to a subaddress
with a very large account index.
> simplewallet: add sweep_account command

- tests/unit_tests/levin.cpp
fixes gcc warning
```
/home/runner/work/monero/monero/tests/unit_tests/levin.cpp: In member function ‘virtual void levin_notify_stem_without_padding_Test::TestBody()’:
/home/runner/work/monero/monero/tests/unit_tests/levin.cpp:585:16: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wdangling-else]
if (sent && is_stem)
^
/home/runner/work/monero/monero/tests/unit_tests/levin.cpp: In member function ‘virtual void levin_notify_local_without_padding_Test::TestBody()’:
/home/runner/work/monero/monero/tests/unit_tests/levin.cpp:655:16: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wdangling-else]
if (sent && is_stem)
^
```
> unit_tests: fix gcc warning

- src/ringct/bulletproofs.cc
- src/ringct/rctOps.cpp
- src/ringct/rctOps.h
- tests/performance_tests/crypto_ops.h
- tests/performance_tests/main.cpp
- tests/unit_tests/ringct.cpp
Speeds up Bulletproof verification by eliminating unnecessary point compression and decompression when performing multiply-by-8 operations on group elements to ensure proper subgroup membership.
Updates performance and unit tests.
Example speedups on test machine:
- single 1-output proof: 5.2% speedup
- single 2-output proof: 2.9% speedup
- 4-batch of 2-output proofs: 10.6% speedup
- 64-batch of 2-output proofs: 25.7% speedup
> Bulletproofs: verification speedup

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
Takes too long to fetch DNS checkpoints on startup. 
It will check DNS checkpoints a few moments later in background (from p2p connection thread on a new block/tx).
Will still do the check on startup If a user enforced DNS checkpoints (`--enforce-dns-checkpointing`).
> cryptonote_core: skip dns checkpoints on startup if not enforced

- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_core/cryptonote_core.cpp
An automatic tx variable is initialized properly on the first
run through the loop, but not the second. Moving the variable
inside the loop ensures the ctor is called again to init it.
> cryptonote: fix reuse of non default tx data when relaying

- tests/functional_tests/functional_tests_rpc.py
- tests/functional_tests/transfer.py
- tests/functional_tests/txpool.py
Testing behavior of Dandelion++ via the restricted port is not possible currently - the stem/fluff mode changes the behavior of the node and is selected randomly.
> Revert functional test changes in babf25d2e and 571546067

- src/cryptonote_core/tx_pool.cpp
The core tests don't need updating because `insert_key_images` already filter this out (there are actually two different tests when adding a transaction).
> Used legacy category to match insert_key_images behavior

- src/wallet/message_store.cpp
> message_store: don't print an error when there is no mms file

- src/cryptonote_core/cryptonote_core.cpp
It doesn't really work anymore since we don't have a fork soon
> cryptonote_core: take out the time based upgrade warning

- src/device_trezor/device_trezor.cpp
We know that Trezor Firmware 2.3.1 will support the new protocol client version (v3).
Same as https://github.com/monero-project/monero/pull/6519
> trezor: add new firmware version support

- contrib/epee/include/md5_l.inl
> epee: use memwipe rather than memset for md5 secrets

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
This can now happen if:
- we have a pruned db
- we have not connected to the monero network for a while
- we connect to a node
- that node asks us for history
- we only have a pruned version of the most recent common block
In that case, it's better to not reply but keep the connection alive,
so we can sync off it.
> protocol: don't drop a connection if we can't get a compatible chain

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
Because there's a neverending supply of cunts claiming a wrong
version just to say "look at me" I guess
> protocol: move the "peer claims higher version" warning to debug

- contrib/epee/src/byte_slice.cpp
- tests/unit_tests/epee_utils.cpp
The Bug:
1. Construct `byte_slice.portion_` with `epee::span(buffer)` which copies a pointer to the SSO buffer to `byte_slice.portion_`
2. It constructs `byte_slice.storage_` with `std::move(buffer)` (normally this swap pointers, but SSO means a memcpy and clear on the original SSO buffer)
3. `slice.data()` returns a pointer from `slice.portion_` that points to the original SSO cleared buffer, `slice.storage_` has the actual string.
Mirror of: https://github.com/monero-project/monero/pull/6559
> [release-v0.16] ByteSlice: Fix persisting ptr to std::moved SSO buffer

- contrib/epee/include/console_handler.h
- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/net/http_server_impl_base.h
- contrib/epee/include/storages/levin_abstract_invoke2.h
- src/blockchain_utilities/blocksdat_file.h
- src/blockchain_utilities/bootstrap_file.h
- src/checkpoints/checkpoints.cpp
- src/device_trezor/trezor/transport.cpp
- src/p2p/net_node.inl
- src/rpc/rpc_args.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- tests/core_tests/chaingen.h
This fixes the build with Boost 1.58 and fixes all warnings with Boost 1.73+ (by including `boost/bind/bind.hpp`). Only `src/simple/simplewallet.cpp` still uses the global `_1` variables.
The [differences between `std::bind` and `boost::bind`](https://stackoverflow.com/questions/10555566/difference-between-c11-stdbind-and-boostbind).
> Fix boost <1.60 compilation and fix boost 1.73+ warnings

- contrib/epee/src/mlog.cpp
- src/rpc/core_rpc_server.cpp
It's not something the user needs to know, and will display
attacker controlled data
> rpc: don't display invalid json errors on default log level

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
The cache is discarded when a block is popped, but then gets
rebuilt when the difficulty for next block is requested.
While this is all properly locked, it does not take into account
the delay caused by a database transaction being only committed
(and thus its effects made visible to other threads) later on,
which means another thread could request difficulty between
the pop and the commit, which would end up using stale database
view to build the cache, but that cache would not be invalidated
again when the transaction gets committed, which would cause the
cache to not match the new database data.
To fix this, we now keep track of when the cache is invalidated
so we can invalidate it again upon database transaction commit
to ensure it gets calculated again with fresh data next time it
is …
> blockchain: fix timestamp/difficulty cache getting out of sync

- contrib/epee/include/storages/parserse_base_utils.h
Reported by minerscan
Also independently found by OSS-Fuzz just recently
> epee: fix array underflow in unicode parsing

- src/common/updates.cpp
To notarize the macOS GUI we have to distribute it as .dmg
> [branch] updates: mac gui .tar.bz2 -> .dmg

- external/easylogging++/easylogging++.cc
- src/common/CMakeLists.txt
- src/common/utf8.h
- src/mnemonics/language_base.h
Some of it might be coming from untrusted sources
> easylogging++: sanitize log payload

- contrib/epee/src/byte_slice.cpp
- tests/unit_tests/epee_utils.cpp
The Bug:
1. Construct `byte_slice.portion_` with `epee::span(buffer)` which copies a pointer to the SSO buffer to `byte_slice.portion_`
2. It constructs `byte_slice.storage_` with `std::move(buffer)` (normally this swap pointers, but SSO means a memcpy and clear on the original SSO buffer)
3. `slice.data()` returns a pointer from `slice.portion_` that points to the original SSO cleared buffer, `slice.storage_` has the actual string
> ByteSlice: Fix persisting ptr to std::moved SSO buffer

- src/device/device_ledger.cpp
Using version `0.16.0.0` of the `monero-wallet-cli`, an error appears when trying to `transfer` funds to more than one address on the Ledger Nano S/X:
```
Error: unexpected error: Wrong Device Status: 0x6701 (UNKNOWN), EXPECTED 0x9000 (SW_OK), MASK 0xffff
```
This is the due to an incorrect assignment of `buffer_send[4]` (`unsigned char` representing `LC`) [line 1482](https://github.com/monero-project/monero/blob/release-v0.16/src/device/device_ledger.cpp#L1482) to more than `255` which results to an incorrect lenght command.
```
1     1    1    1    1     1     var
+-------------------------------------------+
| CLA | INS | P1 | P2 | LC | Opt | Add data |
+-------------------------------------------+
^
len(Opt + Add data)
```
It's fixed by setting `len` to be at most `254` (`262-5-3`) …
> Ledger: Fix incorrect lenght of command INS_PREFIX_HASH

- tests/performance_tests/equality.h
- tests/performance_tests/performance_tests.h
Too many iterations cause std::bad_alloc for the timings vector,
and the micro prefix displays as some other character, so use u.
Reported by iDunk
> performance_tests: some windows fixes

- utils/systemd/monerod.service
The default monero.conf file depends on the existence of the folders `/var/log/monero/` and `/var/lib/monero/`.
This change makes sure systemd will create them, together with the proper permissions, if they don't exist.
`StateDirectory` can be considered an extra safety in case the user `monero` happens to have been created with specifying `/var/lib/monero/` as a home folder but without actually creating it.
> systemd: Make sure required folders exist

- README.md
I'm not sure if libzmq was the name of the package in previous releases, but for 12.1 libzmq doesn't exist.  It should be libzmq4.
https://www.freshports.org/search.php?query=libzmq&search=go&num=10&stype=name&method=match&deleted=excludedeleted&start=1&casesensitivity=caseinsensitive
> libzmq should be libzmq4.

- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
It'll make it clearer when a DB init failure is due to being
on a filesystem which does not support mmap
> db_lmdb: test for mmap support at init time

- src/crypto/keccak.c
Some tools report the alignment check as UB, which seems a bit
dubious, but since the performance difference between the two
versions is minimal, I'll go with the safe version
> keccak: remove aligned check

- CMakeLists.txt
Either it breaks building `monero` submodule (CMake `add_subdirectory`)
> cmake: insert CMAKE_CURRENT_SOURCE_DIR in CMAKE_MODULE_PATH

- ZMQ.md
- src/common/notify.cpp
- src/common/notify.h
- src/cryptonote_basic/events.h
- src/cryptonote_basic/fwd.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/daemon/command_line_args.h
- src/daemon/daemon.cpp
- src/daemon/main.cpp
- src/net/zmq.cpp
- src/net/zmq.h
- src/rpc/CMakeLists.txt
- src/rpc/fwd.h
- src/rpc/zmq_pub.cpp
- src/rpc/zmq_pub.h
- src/rpc/zmq_server.cpp
- src/rpc/zmq_server.h
- src/serialization/json_object.h
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/json_serialization.cpp
- tests/unit_tests/json_serialization.h
- tests/unit_tests/zmq_rpc.cpp
Supports txpool and mainchain events. Will be updated after PR 6357 is merged. Markdown file has description on how clients should use it, and code has decent comments on implementation quirks.
> Adding ZMQ/Pub support for txpool_add and chain_main events

- src/blockchain_db/blockchain_db.cpp
- src/blockchain_db/blockchain_db.h
- src/cryptonote_config.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/cryptonote_protocol/enums.h
- src/cryptonote_protocol/levin_notify.cpp
- tests/unit_tests/levin.cpp
The last bullet point on the CCS for transaction privacy is a randomized delay before a node takes an incoming transaction from i2p/tor and sends it over ipv4/6. My thought was an attempt to conceal the bandwidth/timing analysis of i2p/tor. If the the i2p/tor hidden service only has one incoming connection, this delay possibly/probably does nothing. But if the hidden service has 2+ incoming connections sending white noise, the transaction could've been received over any of the white noise connections.
This creates another mempool state.
@SarangNoether might be interested.
> Add randomized delay when forwarding txes from i2p/tor -> ipv4/6

- .gitmodules
- CMakeLists.txt
- contrib/depends/toolchain.cmake.in
- src/crypto/CMakeLists.txt
- src/crypto/wallet/CMakeLists.txt
- src/crypto/wallet/crypto.h
- src/crypto/wallet/empty.h.in
- src/device/device_default.cpp
- tests/CMakeLists.txt
- tests/benchmark.cpp
- tests/benchmark.h.in
Sorry for the do not merge tag again. But this requires [a PR in another repo](http://github.com/monero-project/supercop/pull/3).
This is a working example of the amd64 ASM from supercop to speedup wallet scanning. The speedup is less now, presumably due to slow downs in other areas of the wallet. Scanning from block 1 to 2031549 (mainnet) drops from 5.8 minutes to 4.14 minutes (~28.6%) on my test machine. The benchmark utility (see below) shows a crypto speedup of ~146% with two output transactions.
The test machine is a ryzen 3900x / 32 GiB PC3200 RAM / 970pro nvme / x570 desktop. The daemon and wallet were on the same box. The first run for each crypto implementation was tossed in an effort to "normalize" the file cache. The disk is encrypted, so LMDB hitting disk has an additional …
> Support for supercop ASM in wallet, and benchmark for supercop

- src/rpc/daemon_handler.cpp
- src/rpc/daemon_handler.h
- src/rpc/message.cpp
- src/rpc/message.h
- src/rpc/rpc_handler.h
- src/rpc/zmq_server.cpp
- src/serialization/CMakeLists.txt
- src/serialization/json_object.cpp
- src/serialization/json_object.h
- tests/unit_tests/zmq_rpc.cpp
Reading a chunk of transactions (via ZMQ `GetBlocksFast`) in larger blocks takes 0.5 seconds (yes seconds!), which makes for a bad time when re-scanning older viewkeys with light wallet server.
Fixing pruned txes with `GetBlocksFast` has a ~73% speedup on a ryzen 3 testbox. This is specifically for large borromean blocks, but has good speedups overall considering the newer transaction volume. The other two patches have a combined ~31% speedup for pruned blocks, and ~36% speed for unpruned blocks.
Overall reading `GetBlocksFast` went from ~0.55 seconds to ~0.11 seconds (~82% faster), which is still somewhat poor (but better). I have other optimizations to push (a schema breaking change in particular), but even the DOMless I-know-where-hex-data-is mode still tops out at 75 milliseconds; …
> Improve ZMQ GetBlocksFast (Pruned Txes)

- src/rpc/daemon_rpc_version.h
- src/rpc/message.cpp
- src/serialization/json_object.cpp
- src/serialization/json_object.h
- tests/unit_tests/json_serialization.cpp
This changes the `txextra` field from an array of integers to a hex string.  This results in a ~12% speedup on pruned txes and a ~2% speed up non-pruned txes. The mythical (but real) DOMless mode has a ~17% speedup with this change (the mode primarily accelerates hex processing).
Since this is a breaking change, I changed the major version number of the server. I decided to simultaneously drop two fields which are superfluous - the same values are always written. If the status is not `OK`, then the JSON-RPC error field is used instead.
> Change ZMQ-JSON txextra to hex and remove unnecessary base fields

- contrib/epee/include/console_handler.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/daemon/command_server.cpp
- src/daemon/command_server.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
This keeps the basic feature of PR #6127 of `help` without any arguments in the CLI wallet showing a short list of important commands instead of all commands (about 120 lines of output), but reverts its introduction of a new `help_advanced` command: The full list of CLI wallet commands is available now through `help all`.
In addition, a new `apropos` command in both CLI wallet and daemon searches all command usage strings and descriptions for a single keyword, or a number of keywords with "and" logic. Example:
apropos transfer
In the CLI wallet this lists all variants of transfer commands. Or
apropos multisig
lists anything that has something to do with multisig.
See also issue #6494 for some background info about the revert.
> Wallet, daemon: From 'help_advanced' back to 'help', and new 'apropos' command

- README.md
In the readme the wrong libusb dependency on Debian/Ubuntu and Fedora is mentioned and outputs this error while building:
```
-- Found HIDAPI: /usr/lib/x86_64-linux-gnu/libhidapi-libusb.a  
CMake Warning at cmake/FindHIDAPI.cmake:53 (message):
libusb-1.0 library not found, binaries may fail to link.
Call Stack (most recent call first):
CMakeLists.txt:446 (find_package)
```
> Mention correct libusb dependency

- src/wallet/wallet2.cpp
I somehow deleted the last submission of this PR.
> fix warning by removing std::move() on temporary http_client object

- src/common/updates.cpp
To notarize the macOS GUI we have to distribute it as .dmg
> updates: mac gui .tar.bz2 -> .dmg

- CMakeLists.txt
- contrib/depends/toolchain.cmake.in
It is now possible to specify a custom openssl dir by using `-DOPENSSL_ROOT_DIR` on macOS.
Tested with gitian, works as expected now. The old `OpenSSL_DIR` was probably a typo.
> cmake: allow custom openssl path on macOS

- src/daemon/rpc_command_executor.cpp
Pruned coinbase txes are the same as unpruned ones, so the
prunable data is empty
> daemon: don't print "(pruned)" for coinbase txes

- README.md
- external/easylogging++/ea_config.h
Fixes the easylogging problem in [#6592](https://github.com/monero-project/monero/issues/6592) (the RandomX problem there is fixed by [PR6698](https://github.com/monero-project/monero/pull/6698).
> For NetBSD, add instructions to README.md and define to ea_config.h

- contrib/epee/include/misc_language.h
- contrib/epee/include/rolling_median.h
- tests/unit_tests/rolling_median.cpp
Originally when the rolling median has an even number of elements stored, it returns the average of the middle two elements like this:
`return (a+b)/2`
However, if `(a + b)` is greater than the size of the type of `a` and `b`, the result might wrap around (e.g. if it's an integral type, etc.).
While it is unlikely wraparound will ever occur based on how Monero uses the rolling median, it's better to have safe code in case this template gets reused elsewhere. The new equation is
`(a+b)/2 = (a/2) + (b/2) + ((a - 2*(a/2)) + (b - 2*(b/2)))/2`
This is intended to play nice with integral division, however floating point types may have more rounding errors due to the additional operations.
> rolling_median_t: fix wraparound case

- contrib/epee/include/net/local_ip.h
These functions are unused, and don't have any tests. Does no harm to remove them IMHO, and reduces code to maintain.
Also it considered unique local addresses (`fc00::/7`) as link local addresses which is not true, ULA addresses are still global, but they aren't routed on the public internet and intended only for private networks.
> epee: Remove unused functions in local_ip.h

- src/rpc/core_rpc_server.cpp
It's more obvious there's no txid, and it saves space
> rpc: return empty txid get_outs rather than 00..00 when not requested

- src/cryptonote_basic/miner.h
This prevents setting target to, eg, 65 being ignored
and remove an unused constant
> miner: increase min/max intervals to full extents

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
insert doesn't actually insert if another element with the
same key is already in the map
> wallet2: fix setting tx keys when another is already set

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
There are a few Borromean proofs txes in the v8 era, and these
aren't supported by get_pruned_transaction_weight
> cryptonote_protocol: don't synced pruned blocks before v9

- src/wallet/wallet2.cpp
The sort predicate is a boolean ordered-before value, but these are returning the memcmp value directly, and thus returns true whenever the pubkeys aren't equal.  This means:
- it isn't actually sorting.
- it can (and does) segfault for some inputs.
> Fix broken multisig pubkey sorting

- README.md
Removed AUR package, since doesn't seem to exist anymore and added Debian package (the CCS-funded one).
We will link to this list from the website: https://github.com/monero-project/monero-site/pull/1135
> README: update list of third party monero packages

- contrib/epee/include/byte_stream.h
- tests/unit_tests/epee_utils.cpp
This is used by the [light wallet server](https://github.com/monero-project/monero/pull/4139) that has been successfully separated from this repo. This is only a single line of code to maintain (+tests), and is likely useful to something internal eventually.
> Add clear method to byte_stream

- src/ringct/rctSigs.cpp
- src/ringct/rctTypes.h
also fix a an assert message refering t MLSAG
> ringct: fix CLSAG serialization after boost/epee changes

- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
- Update protocol version to allow MLSAG and CLSAG in Ledger Monero application
- Update minimal version required for Ledger Monero application
- Fix method to send scalar `z` in `clsag_sign()` which can't be encrypted in the Monero client because it hasn't been generated on the HW.
> Fix protocol with Ledger's HW when using CLSAG

- src/device_trezor/trezor/protocol.cpp
- src/wallet/wallet2.cpp
- tests/trezor/daemon.cpp
- tests/trezor/trezor_tests.cpp
- Enables CLSAG transaction support for Trezor
- Fixes Trezor tests, testing HF \in {12, 13}
- Requires https://github.com/trezor/trezor-firmware/pull/1246
- Testing: https://github.com/ph4r05/monero/releases/tag/v16.0.0.0-tests-u18.04-01
- @SarangNoether for notif
> Trezor: Enable CLSAG support for Trezor client

- src/hardforks/hardforks.cpp
This PR decreases the `stagenet` hardfork heights for `v13` and `v14`, so the `stagenet` hardfork will take place before the `mainnet` hardfork, hopefully.
Right now, according to https://community.xmr.to/xmr-countdown/ and https://community.xmr.to/xmr-countdown/stagenet/ the `mainnet` hardfork comes first.
I chose (assuming 2 minutes per block):
* `v13`: 675405. (ca. 2020-09-28 at 11:52).
* `v14`: 676125. (ca. 2020-09-28 at 08:32).
This is open for discussion.
> Let stagenet hardfork happen before mainnet.

- src/cryptonote_config.h
Not sure if these are used by projects including the header to code outside of our source tree. I'd gladly close again, if that is  provably the case.
EDIT:
CRYPTONOTE_GETBLOCKTEMPLATE_MAX_BLOCK_SIZE removed here: https://github.com/monero-project/monero/commit/1607cb7e0c5cc5e1400766f595e723531a97cb7b
CRYPTONOTE_POOLDATA_FILENAME removed here: https://github.com/monero-project/monero/commit/b52abd1370cc21484d64f45504adbab47240debf
> Remove unused macros from cryptonote_config.h

- tests/functional_tests/mining.py
It only happens sometimes, not consistently to reproduce. I don’t know if setting it to 90 fixes it.
- https://github.com/monero-project/monero/pull/6835/checks?check_run_id=1146997271
- https://github.com/monero-project/monero/pull/6758/checks?check_run_id=1082850323
> functional_tests: rewrite mining code, clearer timeout info

- CMakeLists.txt
Crash stacktrace: https://github.com/monero-project/monero-gui/issues/3093#issuecomment-695834834
> build: ARM - disable stack trace due to segfault in libunwind

- contrib/gitian/gitian-linux.yml
This is a new indirect dependency due to the use of poisson_distribution,
introduced in PR#6354 commit 67ade8005
> Fix lgamma/signgam dependency [RELEASE 0.17]

- utils/systemd/monerod.service
Per the systemd.service(5) man page, "It is generally recommended to use Type=simple for long-running services whenever possible."
It's better than Type=forking because the service (monerod) will be a direct child of systemd, which can then directly monitor it with the wait() family of syscalls.
AFAIK, the only reason to fork is to disassociate the controlling terminal and login session from the process. This isn't needed under systemd which already handles all of that.
Without the --detach option, monerod will send log messages to stdout/err, in addition to its own log file. By default, these duplicate messages would end up in the journal (and/or syslog). The two `Standard*=null` directives fix that.
> systemd: Don't use Type=forking

- src/wallet/api/address_book.cpp
- src/wallet/api/address_book.h
- src/wallet/api/wallet2_api.h
Apparently in the Monero GUI, in order to edit the description of an address book entry the GUI removes and adds a new entry altogether. This patch adds the possibility to edit an existing item.
https://github.com/monero-project/monero-gui/blob/238b1b777f508c907bcfb4b5186445a12feeffe2/pages/AddressBook.qml#L377-L400
> Allow AddressBook description edits via wallet/api

- contrib/gitian/gitian-freebsd.yml
- contrib/gitian/gitian-linux.yml
Fix empty RPATH token issue. Only affects Linux and FreeBSD.
> Force CMAKE_SKIP_RPATH=ON [release-v0.17]

- src/rpc/core_rpc_server.cpp
Bugfix for next_seed_height in getblocktemplate rpc
> [release-v0.17] core_rpc_server: getblocktemplate - fix next_seed_height

- cmake/CheckTrezor.cmake
GUI uses monero as a submodule thus `${CMAKE_SOURCE_DIR}` resolves to the wrong folder.
> cmake: CheckTrezor - use ${CMAKE_CURRENT_LIST_DIR} to locate tests

- cmake/Version.cmake
GUI uses monero as a submodule thus ${CMAKE_SOURCE_DIR} resolves to the wrong folder.
> cmake: Version - use CMAKE_CURRENT_LIST_DIR

- src/cryptonote_core/blockchain.cpp
Miners with MLSAG txes which they'd already verified included
a couple in that block, but the consensus rules had changed
in the meantime, so that block is technically invalid and any
node which did not already have those two txes in their txpool
could not sync. Grandfather them in, since it has no effect in
practice.
> blockchain: fix sync at v14 boundary

- contrib/gitian/gitian-linux.yml
This is a new indirect dependency due to the use of poisson_distribution,
introduced in PR#6354 commit 67ade8005. It causes a dependency on
glibc 2.23, while we previously only required 2.17.
> Fix lgamma/signgam dependency

- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/i_core_events.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/cryptonote_protocol/levin_notify.cpp
- src/cryptonote_protocol/levin_notify.h
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/net_node_common.h
- tests/unit_tests/levin.cpp
Monero node ignores incoming txes while syncing. Thus should avoid sending a tx to desynced peer in Dandelion++ stem phase..
Resolves https://github.com/monero-project/monero-gui/issues/3140, https://github.com/monero-project/monero/issues/6885
> Dandelion++: skip desynced peers in stem phase

- .github/workflows/build.yml
Github Actions Mac image gets updated every week -> unnecessary.
> workflows: don't brew update

- contrib/gitian/gitian-freebsd.yml
- contrib/gitian/gitian-linux.yml
Fix empty RPATH token issue. Only affects Linux and FreeBSD.
> Force CMAKE_SKIP_RPATH=ON

- src/p2p/net_node.inl
IPv6 addresses include a range that can map IPv4 addresses,
which allowed those mapped addresses to bypass filtering.
This filter should be replaced by AS filtering at some point.
> p2p: use /16 filtering on IPv4-within-IPv6 addresses
