- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
New output ephemeral code
Add compatibility check
> Nano s 0.14 fixes 1

- LICENSE
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/blockchain_utilities/blockchain_import.cpp
- src/blockchain_utilities/bootstrap_file.cpp
- src/blockchain_utilities/bootstrap_file.h
- src/blockchain_utilities/bootstrap_serialization.h
- src/cryptonote_basic/cryptonote_boost_serialization.h
- src/cryptonote_basic/difficulty.cpp
- src/cryptonote_basic/difficulty.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_protocol/cryptonote_protocol_defs.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/rpc/daemon_handler.cpp
- src/rpc/message_data_structs.h
- src/serialization/difficulty_type.h
- tests/difficulty/CMakeLists.txt
- tests/difficulty/difficulty.cpp
- tests/difficulty/gen_wide_data.py
- tests/difficulty/wide_difficulty.py
- tests/performance_tests/CMakeLists.txt
- tests/performance_tests/check_hash.h
- tests/performance_tests/main.cpp
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/difficulty.cpp
- tests/unit_tests/serialization.cpp
Since cumulative difficulty is creeping up, and we're likely going
to change to a faster PoW in the near future, let's do this now.
Based on Boolberry work by:
jahrsg <jahr@jahr.me>
cr.zoidberg <crypto.zoidberg@gmail.com>
> Make difficulty 128 bit instead of 64 bit

- tests/README.md
> tests: fix path in instructions

- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_server.cpp
at least when using restore_deterministic_wallet
> wallet: fix memory only wallets

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
It can enable/disable auto refresh, and set auto refresh period
> wallet_rpc_server: new auto_refresh RPC

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
> wallet: flush output cache upon reorg

- src/simplewallet/simplewallet.cpp
We want people to really realize it's bad for *their* privacy.
> simplewallet: make the long payment ids warnigns more warney

- src/rpc/core_rpc_server.cpp
Somehow only one of the calls got into that PR
> rpc: quantize db size up to 5 GB in restricted mode

- Dockerfile
Added environment variables for
```
ENV CFLAGS='-fPIC'
ENV CXXFLAGS='-fPIC'
```
Upgraded versions of statically built dependencies.
I encourage to double-check the git/file hashes.
> Upgraded static dependency versions and hashes in Dockerfile.

- src/daemon/daemon.cpp
> daemon: init public_port in all ctors

- tests/unit_tests/hmac_keccak.cpp
@moneromooo-monero as you suggested on IRC
> test: hmac_keccak - fix number of chunks counting

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
and return both in get_languages
> wallet_rpc_server: allow english/local language names in create_wallet

- contrib/epee/src/net_ssl.cpp
- Don't check for nullptr when freeing OpenSSL types (docs clearly states it's a noop in this case)
- Use RSA_generate_key_ex instead
> epee: replace call to deprecated RSA_generate_key

- README.md
Add OSX one liner install and also edit Ubuntu line to "Install all dependencies at once on Debian/Ubuntu:"
> Add OSX one liner & edit Ubuntu install line name

- contrib/epee/include/net/http_client.h
- contrib/epee/include/net/net_helper.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
displays total sent and received bytes
> simplewallet: new net_stats command

- src/cryptonote_basic/miner.cpp
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
The setup-background-mining option can be used to turn this off
> wallet: new option to start background mining

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
allows for a cheap mechanism to check "am I up to date with the blockchain"
> Add hash of top block to /getheight RPC

- src/device/device_io_hid.cpp
- src/device/device_io_hid.hpp
- src/device/device_ledger.cpp
Add support of next device generation from Ledger
> Add NanoX support

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/ringdb.cpp
- src/wallet/ringdb.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Useful when debugging, though not much for users
> simplewallet: new unset_ring command

- src/simplewallet/simplewallet.cpp
fix init warning on whatever compiler version
> fix init warning on whatever compiler version

- contrib/gitian/gitian-linux.yml
- contrib/gitian/gitian-win.yml
@TheCharlatan forgot to take these flags out after doing debugging work, taking them back out again
> do not build in parallel as it is non-deterministic

- src/blockchain_utilities/blockchain_import.cpp
> blockchain_import: error out if preparing to handle blocks fails

- cmake/FindLibUSB.cmake
Static compilation fixes for libusb
> build: libusb static compilation fix

- README.md
- added link to guide for Pootle
- link directly to CLI project on Pootle
- improved wording
> readme: add some more instructions for translators

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
if we don't want to export new outputs only
> wallet_rpc_server: add a all flag to export_outputs

- src/cryptonote_core/CMakeLists.txt
- src/cryptonote_core/tx_sanity_check.cpp
- src/cryptonote_core/tx_sanity_check.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/wallet/wallet2.cpp
- utils/python-rpc/framework/daemon.py
This will weed out some transactions with silly rings
> rpc: new sanity check on relayed transactions

- external/easylogging++/easylogging++.cc
- external/easylogging++/easylogging++.h
It's a bit of a hack, but doing it right would need a lot
of changes to the easylogging++ source.
> easylogging++: minimal stdout logging format

- contrib/epee/include/net/http_client.h
- src/wallet/node_rpc_proxy.cpp
- src/wallet/node_rpc_proxy.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
It will avoid connecting to a daemon (so useful for cold signing
using a RPC wallet), and not perform DNS queries.
> wallet: new --offline option

- tests/unit_tests/ban.cpp
The is_host_blocked method is not on master yet
> unit_tests: undo is_blocked implementation factoring

- src/daemonizer/windows_daemonizer.inl
The RPC functional tests need it
Thanks to iDunk for debugging/testing
> daemonizer: add --non-interactive for windows

- src/device_trezor/device_trezor_base.cpp
- src/device_trezor/trezor/transport.cpp
- src/device_trezor/trezor/transport.hpp
- Trezor type detection refactored, T1 disabled (was enabled before which was a bug)
- Sort connected devices by env TREZOR_PATH. 
- Compatible with Trezor ecosystem using TREZOR_PATH env var
- Enables to pick particular Trezor to use in GUI as we don't have the multi-device selection yet
- Dump all detected devices to log for better debugging / troubleshooting
> device/trezor: device sorting and filtering improved

- contrib/epee/include/net/net_ssl.h
- contrib/epee/src/net_ssl.cpp
- src/rpc/core_rpc_server.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_server.cpp
SHA1 is too close to bruteforceable
> change SSL certificate fingerprint whitelisting from SHA1 to SHA-256

- src/lmdb/error.cpp
state_not_recoverable is not defined there
> error: fix compile error on windows with depends

- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_server.cpp
> wallet: fix certificate fingerprint length check

- README.i18n.md
- README.md
- contrib/depends/README.md
- contrib/depends/packages.md
- contrib/gitian/README.md
- src/blockchain_utilities/README.md
- tests/README.md
- tests/gtest/README.md
* After seeing that README.md was huge, I decided to add a Table of Contents, including major headers and links to them.
* After some issues with comments inside code blocks being detected as headings when generating ToCs, I noticed that formatting choices for code blocks weren't consistent across fencing and indents, so I updated these to use fencing, as this allows for syntax highlighting...
* ...which let me add syntax highlighting to code blocks where appropriate.
> Updates for README.md and other Markdown files

- contrib/epee/include/net/net_fwd.h
- src/common/rpc_client.h
- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/daemon.cpp
- src/daemon/main.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/core_rpc_server.cpp
- src/rpc/rpc_args.cpp
- src/rpc/rpc_args.h
- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_server.cpp
See individual commit comments.
> Fix SSL configuration

- tests/functional_tests/bans.py
- tests/functional_tests/blockchain.py
- tests/functional_tests/cold_signing.py
- tests/functional_tests/daemon_info.py
- tests/functional_tests/functional_tests_rpc.py
- tests/functional_tests/get_output_distribution.py
- tests/functional_tests/integrated_address.py
- tests/functional_tests/mining.py
- tests/functional_tests/multisig.py
- tests/functional_tests/proofs.py
- tests/functional_tests/sign_message.py
- tests/functional_tests/speed.py
- tests/functional_tests/transfer.py
- tests/functional_tests/txpool.py
- tests/functional_tests/wallet_address.py
Also add missing bans test to the default tests
> functional_tests: fix python3 compatibility

- contrib/epee/include/net/net_fwd.h
- src/common/rpc_client.h
- src/daemon/command_parser_executor.cpp
- src/daemon/command_parser_executor.h
- src/daemon/command_server.cpp
- src/daemon/daemon.cpp
- src/daemon/main.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/core_rpc_server.cpp
- src/rpc/rpc_args.cpp
- src/rpc/rpc_args.h
- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_server.cpp
As requested by @moneromooo-monero in [PR 5561](https://github.com/monero-project/monero/pull/5561).
These were straight cherry-picked, watch build bots.
> Fix SSL Configuration 0.14

- translations/monero.ts
- translations/monero_fr.ts
- translations/monero_it.ts
- translations/monero_ja.ts
- translations/monero_sv.ts
This PR resync and refresh all language files for the next release.
Can be reproduced running the script `update-translations.sh` in `utils/translations`
> [0.14] Refresh and uppdate translations for new release

- src/cryptonote_basic/miner.cpp
- src/cryptonote_basic/miner.h
- src/rpc/core_rpc_server.cpp
- src/rpc/daemon_handler.cpp
> miner: fix double free of thread attributes

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
https://git.xmr.pm/xmrdsc/monero/commit/dad4612fc14277a10012ae78c8df9bc5fa03d506
> expose set/get walletcache attribute functionality in wallet api

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
I have removed an unused private member.
> Unused private member m_miner_address

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Don't keep asking for it on an intact connection
Wallet is too chatty over the wire
> Remember RPC version on initial connect

- src/p2p/net_node.cpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
We might have external access without having to do this
> p2p: delay IGP probing on startup

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
PS: Didn't touch RPC minor version this time since there are multiple concurrent RPC-related PRs raising it.
> rpc: implement set_bootstrap_daemon method

- src/crypto/slow-hash.c
Delete slow-hash.c more include string.h
> Delete slow-hash.c more include string.h

- src/wallet/wallet2.cpp
- Ignore null keys stored as tx keys as those are invalid. TX key cache can be full of zero keys which blocked tx key recovery using Trezor
Required for https://github.com/monero-project/monero-gui/issues/2183
> device: tx_key caching fix

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
I created a new function and didn’t change `createTransaction` for compatibility reasons.
> wallet_api: add multi destination tx support

- src/simplewallet/simplewallet.cpp
This is likely to be done via a script
> simplewallet: don't ask about mining when running a command line

- README.md
- Referencing https://hackerone.com/reports/592094
- Referencing https://hackerone.com/reports/417515
> README: add beginnings of "Known Issues"

- src/cryptonote_core/cryptonote_tx_utils.h
- src/simplewallet/simplewallet.cpp
- src/wallet/api/transaction_history.cpp
- src/wallet/wallet_rpc_server.cpp
Resolves https://github.com/monero-project/monero-gui/issues/906
> wallet: provide original address for outgoing transfers

- contrib/gitian/gitian-build.py
- contrib/gitian/gitian-linux.yml
- contrib/gitian/gitian-osx.yml
This fixes #5730 (now open on gitlab as [monero-site#964](https://repo.getmonero.org/monero-project/monero-site/issues/964) and as https://github.com/monero-project/meta/issues/372)
@dEBRUYNE-1  - Let me know if you have more insight into this fix as I didn't see it in the codebase.
> Gitian build (mac, linux): gzip => bzip2

- contrib/epee/include/net/levin_protocol_handler_async.h
> epee: fix connections not being properly closed in some instances

- src/device/device_ledger.cpp
Fixes https://github.com/monero-project/monero-gui/issues/2354
> device: fix ledger requesting secret keys export twice

- src/p2p/net_node.h
- src/p2p/net_node.inl
Also remove the delta time fixup, since we now ignore those
as they're attacker controlled
> p2p: sanitize peer lists

- src/blockchain_utilities/blockchain_blackball.cpp
- src/wallet/ringdb.cpp
(Ported from https://github.com/aeonix/aeon/pull/132)
Result:
```
2019-08-22 01:19:12.321 W Starting...
2019-08-22 01:19:12.321 I Creating spent output cache in /Users/stoffu/.shared-ringdb/spent-outputs-cache
2019-08-22 01:19:12.330 W Scanning for spent outputs...
2019-08-22 01:19:14.562 I Opening monero blockchain at /Users/stoffu/.bitmonero/lmdb/
2019-08-22 01:19:14.791 W 0-9999: 49.5605% ( 42793 / 86345 )
2019-08-22 01:19:15.065 W 10000-19999: 62.9995% ( 55490 / 88080 )
2019-08-22 01:19:15.408 W 20000-29999: 73.9453% ( 65801 / 88986 )
2019-08-22 01:19:15.772 W 30000-39999: 80.9059% ( 70253 / 86833 )
2019-08-22 01:19:16.2482W 40000-49999: 74.5016% ( 100572 / 134993 )
2019-08-22 01:19:18.4127W 50000-59999: 66.8429% ( 575737 / 861329 )
2019-08-22 01:19:20.1615W 60000-69999: 75.7723% ( …
```
> blockchain_blackball: add --historical-stat which prints historical stats of spent ratio

- README.md
updating the TOC
(rebased as the author left it as is)
> updating Readme.md TOC

- contrib/lsan/lsan.supp
with the Cryptonight per-thread buffer
> contrib: add a suppressions file for leak sanitizer

- CMakeLists.txt
- external/easylogging++/CMakeLists.txt
- external/easylogging++/easylogging++.cc
> easylogging++: split strings manually

- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/src/connection_basic.cpp
- src/rpc/bootstrap_daemon.cpp
- src/rpc/bootstrap_daemon.h
- src/wallet/wallet2.cpp
- tests/performance_tests/rct_mlsag.h
Please see the comments in git-log, thank you.
> Crypto security fix + Coverity fixes

- tests/unit_tests/multiexp.cpp
- tests/unit_tests/ringdb.cpp
Fixes assertion failure (curstate == 1) in random.c in debug mode
> unit tests: replace global var with lambda returning static local var

- src/cryptonote_basic/verification_context.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/net_node_common.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
PoW is expensive to verify, so be strict
> ban peers sending bad pow outright

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
https://github.com/aeonix/aeon/pull/131
> wallet2: add ignore-outputs-{above/below} option

- src/crypto/rx-slow-hash.c
* Faster cache initialization with SSSE3/AVX2
* Automatic detection of CPU capabilities in RandomX
* Fixed a possible out-of-bounds access in superscalar program generator
* Use MONERO_RANDOMX_UMASK to manually disable RandomX flags in monerod
> RandomX: update to v1.1.4

- src/simplewallet/simplewallet.cpp
It may be more intuitive for some people
> simplewallet: add --restore-from-seed alias

- src/p2p/net_node.inl
added for mainnet, testnet, and stagenet. 
server is owner by snipa, both snipa and I have access to it. No idea where its hosted. 
xmrchain.net is a block explorer thats been around a while.
> node.inl, add xmrchain.net IP to hardcoded peers

- src/cryptonote_core/cryptonote_core.cpp
> cryptonote: fill in tx weight when syncing from pruned blocks

- src/daemon/rpc_command_executor.cpp
It got switched to hexadecimal when we went to 128 bit values
> daemon: print difficulty in decimal, as it used to be

- cmake/GitVersion.cmake
- cmake/Version.cmake
This fixes #6012 and seems to work correctly in all cases. The file is regenerated if and only if the version tag changes (or the input file does). In particular:
1) Nothing is regenerated or rebuilt if nothing changes in the source tree
2) After `git commit --allow-empty -m 'whatever'`, the version file is regenerated and built, and the executables quickly relinked, with no unexpected other targets being built. The new executables report the correct new version hash.
3) Modifying the input file `src/version.cpp.in` or deleting the output file `build/.../version.cpp` causes the file to be regenerated with no unexpected errors.
Additionally, since 33e91e1a1e94c2957f59def9fe49f75956a9f699, I don't think the two cases not using GenVersion.cmake could have worked -- they don't set …
> cmake: Fix generation of version.cpp

- src/cryptonote_core/tx_pool.cpp
> tx_pool: fix divide by 0 in log

- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
To be merged after #5958. Commits from #5958 will disappear once it gets merged.
> device: bounds checking in Ledger send_secret/receive_secret

- src/rpc/core_rpc_server.cpp
See https://github.com/monero-project/monero/issues/5994#issuecomment-545522611
> rpc: Include tag in get_info version string

- src/cryptonote_basic/miner.cpp
- src/cryptonote_basic/miner.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/rpc/core_rpc_server.cpp
- tests/core_tests/chaingen.cpp
It causes link errors at least on mac
> cryptonote: untangle dependency from miner to blockchain

- README.md
> README update upgrade table with details

- README.md
with details for nov 30th network upgrade
> README update upgrade table

- src/daemon/command_parser_executor.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/CMakeLists.txt
- src/rpc/rpc_version_str.cpp
- src/rpc/rpc_version_str.h
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/rpc_version_str.cpp
Fixes #5994. To be useful, #6017 and #6015 are also needed.
> daemon: Use rpc for "version" command

- src/simplewallet/simplewallet.cpp
> simplewallet: remove remaining payment id dead code

- src/ringct/bulletproofs.cc
Slightly more efficient computation of scalars used by Bulletproofs prover
> Minor prover simplification (Bulletproofs)

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
protects against having your keys mangled
> wallet2: make keys unlocker reentrant

- README.md
https://github.com/monero-project/meta/issues/420
> README: remove unmaintained build status

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/blockchain_db/testdb.h
- src/cryptonote_core/blockchain.cpp
About twice as fast, very roughly
> blockchain: speedup fetching pruned contiguous tx blobs

- src/daemon/command_parser_executor.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
prints size, weight and (if mined) height
> daemon: add +meta print_tx parameter

- src/common/download.cpp
Happens on at least one windows box
> download: catch exceptions checking for size

- contrib/epee/src/net_ssl.cpp
Because it always does things wonkily doens't it
> net_ssl: load default certificates in CA mode on Windows

- README.md
see also https://github.com/void-linux/void-packages/blob/master/srcpkgs/monero/template
> README: add Void Linux package dependencies

- README.md
replaces #6126 because I can't squash things with the github web GUI
> update readme to encourage joining #monero-dev

- .github/workflows/build.yml
Packages appear to be preinstalled now.
> workflows: fix macOS build

- .travis.yml
- README.md
Also update the cross compiling readme for android and freebsd.
> Add travis freebsd

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/daemon/command_parser_executor.cpp
- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
Flushes m_invalid_blocks in Blockchain.
> rpc: add bad-blocks to flush_cache RPC

- src/crypto/rx-slow-hash.c
Don't try to allocate the dataset repeatedly if it has already failed.
> Silence miner debugmsg spam

- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_basic/cryptonote_format_utils.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- tests/functional_tests/blockchain.py
The tail emission will bring the total above 64 bits
> print_coinbase_tx_sum now supports 128 bits sums

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
Message was "peer claims higher version that we think"
Requested change "peer claims higher version than we think"
> Corrected message typo

- src/simplewallet/simplewallet.cpp
This ensures we get asked for the password if needed
> simplewallet: set manual refresh mode in rescan_bc

- src/p2p/net_node.inl
> p2p: drop the peerlist dump to TRACE

- src/rpc/message.cpp
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/zmq_rpc.cpp
Same as Pr #6361 except to the 0.15 branch.
> Fixed bug in ZMQ JSON-RPC method field

- src/blockchain_db/locked_txn.h
- src/cryptonote_core/tx_pool.cpp
for example, in the RPC server
> core: move the LockedTXN class out of txpool so it may be reused

- src/p2p/net_node.inl
The code would ignore the first one to be added
> p2p: fix off by one adding fallback peers

- src/daemon/rpc_command_executor.cpp
> daemon: if no banned IPs print something

- src/serialization/json_object.cpp
[See Issue](https://github.com/monero-project/monero/issues/6392)
> Fixing static_asserts in ZMQ JSON

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/blockchain_db/testdb.h
- src/cryptonote_core/blockchain.cpp
Useful for wallet refresh or node sync
> blockchain_db: faster fetching of consecutive txes

- src/p2p/net_node.inl
Node from syksy, administered by mooo
> p2p: add another seed node

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- src/rpc/core_rpc_server.cpp
- tests/functional_tests/functional_tests_rpc.py
- tests/functional_tests/transfer.py
- tests/functional_tests/txpool.py
- utils/python-rpc/framework/daemon.py
Follow up to PR 6313. First commit is from that PR, with the others fixing the functional tests. In a separate PR since some code changes to the daemon itself were made.
This also relates to PR 6403, except the more restricted key-image check is moved up in the sequence so that RPC commands get proper error reporting.
> Fix Dandelion++ Functional Tests

- Dockerfile
> docker - openssl update

- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_basic/cryptonote_format_utils.h
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/device/device.hpp
- src/device/device_default.cpp
- src/device/device_default.hpp
- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
Same PR as  #6424  but on master code
> Add timelock verification on device

- src/simplewallet/simplewallet.cpp
Resolves #6438
@erciccione translations need amending regarding this string as well
> simplewallet: fix strings (show_transfers & export_transfers)

- src/simplewallet/simplewallet.cpp
something not that important i found while browsing the file's code
> simplewallet : missing function block separator

- CMakeLists.txt
- cmake/FindCcache.cmake
If ccache is found in the PATH, it is automatically picked up and used by CMake.
> FindCcache automatically

- src/crypto/crypto.cpp
- src/multisig/multisig.cpp
- src/ringct/rctSigs.cpp
- src/ringct/rctTypes.h
- src/wallet/wallet2.cpp
> use memwipe on secret k/alpha values

- src/p2p/net_node.inl
So that we don’t have to rebase constantly. If you want to add your seed node comment.
> Seed nodes

- src/rpc/daemon_handler.cpp
@ndorf see why I didn't know about this endpoint, I accidentally deleted it. Crap. Bringing it back.
> Fixes for ZMQ JSON-RPC endpoint names for raw tx

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
We don't have a function to calculate their weight from a pruned
version (yet).
> cryptonote_protocol: do not request pruned borromean sig txes

- src/wallet/wallet2.cpp
Closes https://github.com/monero-project/monero/issues/6504
> wallet2: fix keys file deserialization exception handling

- external/easylogging++/easylogging++.cc
- src/common/CMakeLists.txt
- src/common/utf8.h
- src/mnemonics/language_base.h
Some of it might be coming from untrusted sources
> easylogging++: sanitize log payload

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
Not ready for this release yet, breaks existing behaviour (`help command`). We can improve it in `master` branch and include it in the next major release.
> [release-v0.16] revert noob-friendly help menu

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
It's time based and we don't have forks every 6 months anymore
> cryptonote_core: remove "We are most likely forked" message

- contrib/epee/src/byte_slice.cpp
- tests/unit_tests/epee_utils.cpp
I thought this pull request was created yesterday but I don't see it now ...
> Fixed bugs for take_slice and byte_stream->byte_slice

- README.md
- src/simplewallet/simplewallet.h
- tests/functional_tests/address_book.py
- tests/functional_tests/speed.py
- tests/functional_tests/validate_address.py
donate.getmonero.org address changed making functional tests fail.
Ref: https://github.com/monero-project/monero-site/pull/1010
> repo: update donation fund address

- src/rpc/rpc_payment.cpp
Got broken after making one of those micro optimizations requested on review..
> rpc: fix loading rpc payment data from file

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
This fixes the functional tests, since txes would not be mined
after being sent to the daemon (they'd be waiting for the
dandelion timeout first)
> tx_pool: mine stem txes in fake chain mode

- src/simplewallet/simplewallet.cpp
Release-based PR, same as #6677 
@selsta
> Add trezor support to sweep_single

- src/wallet/wallet2.cpp
change check of m_key_image_partial from td to td2
> fix typo in pick_preferred_rct_inputs

- external/CMakeLists.txt
- external/qrcodegen/CMakeLists.txt
- external/qrcodegen/QrCode.cpp
- external/qrcodegen/QrCode.hpp
- src/simplewallet/CMakeLists.txt
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
> simplewallet: add show_qr_code command

- CMakeLists.txt
- cmake/FindCcache.cmake
Wrapped the FindCcache with an opt out option as requested.
Also tidied up the FindCcache itself with some comments.
> Made ccache optional (opt out) and tidied up the FindCcache.cmake

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/network_throttle.hpp
- src/daemon/daemon.cpp
- src/wallet/message_transporter.h
- tests/core_proxy/core_proxy.cpp
- tests/unit_tests/mnemonics.cpp
there are quite a few as well that are implicitly included via another header while included directly as well but in some other pr
> remove double includes

- src/simplewallet/simplewallet.cpp
> simplewallet: add missing calls to on_command

- contrib/epee/src/net_ssl.cpp
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/device/device_ledger.cpp
> fix a few typos in error messages

- src/blockchain_utilities/blockchain_stats.cpp
> Don't forget size of prunable txn part [RELEASE]

- src/p2p/net_node.inl
ping @fluffypony, you added most of them years ago, do you still have access to these machines?
I would say we should keep this PR open for a while and if they are still offline then we can merge this.
> net_node: remove dead seed nodes

- .github/workflows/build.yml
Decreases msys2 setup time from ~11 minutes to ~3 minutes.
> workflows: update msys2 setup action v0 -> v1

- src/blockchain_utilities/blockchain_stats.cpp
> Don't forget size of prunable txn part

- tests/functional_tests/functional_tests_rpc.py
- tests/functional_tests/p2p.py
Tests tx/block propagation and reorgs
> functional_tests: add p2p functional tests

- .travis.yml
To avoid out of memory issues.
> travis: j3 -> j2 on i686-w64-mingw32

- src/cryptonote_core/blockchain.h
- src/wallet/wallet2.h
> Fix build with Boost 1.74

- src/rpc/daemon_handler.cpp
Yup, fixing a botched attempt at getting ZMQ pruned transactions to work.
> Fix ZMQ pruned bulletproof transactions

- .github/FUNDING.yml
```
14:37 <@fluffypony> just don't link to web.getmonero as that's a cache-skip
```
> repo: update "sponsor" link

- src/ringct/rctTypes.h
- src/wallet/wallet2.cpp
- index out of bounds when importing outputs
- accessing invalid CLSAG data
> fix a couple bugs found by OSS-fuzz

- README.md
> README: recommend v0.17.1.0

- src/cryptonote_core/blockchain.cpp
Miners with MLSAG txes which they'd already verified included
a couple in that block, but the consensus rules had changed
in the meantime, so that block is technically invalid and any
node which did not already have those two txes in their txpool
could not sync. Grandfather them in, since it has no effect in
practice.
> blockchain: fix sync at v14 boundary

- src/blockchain_utilities/blockchain_export.cpp
- src/blockchain_utilities/blockchain_import.cpp
- src/blockchain_utilities/bootstrap_file.cpp
- src/blockchain_utilities/bootstrap_file.h
And make import honor the starting block# recorded in a bootstrap file
> Allow setting start block on export [release-v0.17]

- tests/functional_tests/mining.py
Occasionally fails on Github Actions CI
> functional_tests: increase mining timeout

- src/p2p/net_node.inl
even if some run more than one node
> p2p: give all hosts the same chance of being picked for connecting

- src/rpc/core_rpc_server.cpp
Same as PR #6949 but on 0.17 branch.
> Fix CLI and unrestricted RPC relay_tx with stempool [0.17]

- src/cryptonote_protocol/levin_notify.cpp
Same as PR #6954 but on 0.17 branch.
> Fix tx flush callback queueing [0.17]

- src/cryptonote_protocol/levin_notify.cpp
- tests/unit_tests/levin.cpp
Same as PR #6973 but on 0.17 branch.
> Switch to Dandelion++ fluff mode if no out connections for stem mode [0.17]

- src/p2p/net_node.inl
Requires branch equivalent of 6897, these are hosted by me
> [release-v0.17] net_node: add tor / i2p seed nodes

- src/p2p/net_node.h
- src/p2p/net_node.inl
> Add support for i2p and tor seed nodes [0.17]

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
Same as PR #7021 on 0.17 branch.
> Fix timeout checks for forwarded and Dandelion++ stem txes [0.17]

- src/p2p/net_node.h
- src/p2p/net_node.inl
This should allow for i2p and tor seed nodes internally within the codebase.
> Add support for i2p and tor seed nodes

- src/common/powerof.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
This also removes potential thread safety bug in that function.
> Make Blockchain::get_fee_quantization_mask() compile time

- src/cryptonote_core/blockchain.cpp
> blockchain: remove some dead code

- src/rpc/core_rpc_server.cpp
Attempting to relay a tx in the stempool will now immediately fluff.
> Fix CLI and unrestricted RPC relay_tx with stempool

- contrib/epee/src/readline_buffer.cpp
Fixes https://github.com/monero-project/monero/issues/3799
> epee: readline_buffer - fix thread safety, fix sync() after stop()

- src/wallet/api/transaction_history.cpp
Resolves https://github.com/monero-project/monero-gui/issues/2008
> wallet_api: TransactionHistory - fill unconfirmed out payments dests

- src/daemon/main.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/rpc_args.cpp
- src/rpc/rpc_args.h
> Add rpc-restricted-bind-ip option

- src/daemon/main.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/rpc_args.cpp
- src/rpc/rpc_args.h
> Add rpc-restricted-bind-ip option [release]

- src/p2p/net_node.inl
Requires #6897, these are hosted by me
> net_node: add tor / i2p seed nodes

- src/wallet/wallet2.cpp
Release branch equivalent of #7058
> [release-v0.17] wallet2: set propagation timeout to current max timeout

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
Resolves https://github.com/monero-project/monero/issues/7029
> rpc: get_info - add 'synchronized' field

- src/cryptonote_config.h
- src/p2p/net_node.inl
There's always some people who just want to abuse things
> p2p: drop peers that spam peer lists

- .github/workflows/depends.yml
Replaces Travis, uploads 64bit Linux, Windows and Mac binary.
> workflows: add depends workflow, upload binaries

- .github/workflows/build.yml
I have done the same for the "depends" workflow and the GUI.
> workflows: shorten name

- .github/workflows/build.yml
~I’m still working on Windows.~
Done. PR is ready now.
> workflows: add ccache support

- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
true if and pretty much only if new blocks are being added
> rpc: add a busy_syncing field to get_info

- contrib/gitian/README.md
Add FreeBSD to "Signing assert files" section of gitian readme / guide
> Add command to sign freebsd assert file for gitian

- src/cryptonote_basic/connection_context.h
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
Some joker is spending time actually doing this
> protocol: drop nodes if they claim new data but only give stale data

- README.md
edited readme version table to include v0.17.1.7 as recommended version
> edited readme version table to include v0.17.1.7

- contrib/epee/include/storages/portable_storage_from_bin.h
especially when allocated size is >> serialized data size
> portable_storage: add some sanity checks on data size

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- tests/core_proxy/core_proxy.h
- tests/unit_tests/node_server.cpp
Reverts monero-project/monero#7154
> Revert "Reject existing claimed blocks in sync mode"

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- tests/core_proxy/core_proxy.h
- tests/unit_tests/node_server.cpp
> protocol: fix false positives dropping peers

- contrib/epee/include/storages/portable_storage_from_bin.h
> portable_storage: remove array element limit

- contrib/epee/include/storages/portable_storage_from_bin.h
also fix pedantic off by one in check
> portable_storage: check object limit where appropriate

- contrib/epee/include/storages/portable_storage.h
- contrib/epee/include/storages/portable_storage_from_bin.h
- contrib/epee/include/storages/portable_storage_to_bin.h
> [release-v0.17] portable_storage: forbid unnamed sections

- src/cryptonote_basic/CMakeLists.txt
- src/cryptonote_basic/connection_context.cpp
- src/cryptonote_basic/connection_context.h
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/p2p/net_node.h
- src/p2p/net_node.inl
- tests/unit_tests/levin.cpp
The dynamic map per connection for max_bytes was moved a static `switch`. I also added a test case.
> Command max_bytes moved from dynamic map to static switch

- src/cryptonote_basic/CMakeLists.txt
- src/cryptonote_basic/connection_context.cpp
- src/cryptonote_basic/connection_context.h
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/p2p/net_node.h
- src/p2p/net_node.inl
- tests/unit_tests/levin.cpp
> Command max_bytes moved from dynamic map to static switch [0.17]

- contrib/epee/src/readline_buffer.cpp
I often find myself executing the same command multiple times in a row, when using monero-wallet-cli. For example, I often call `refresh` until I can see that my balance is confirmed. When I then try to get to a previous command I entered, by pressing the "up" key, I found that I had to press it many times, before I surpassed the `refresh`s.
With this change, the history will not contain consecutive, identical entries anymore. This works both when the same command is re-entered manually and when it's entered by pressing "up" and "return". This is the same behaviour, that I know from [zsh](https://www.zsh.org/).
> readline_buffer: Avoid consecutive duplicates in the history

- LICENSE
I'm a little bit early with this PR. 😅
> Update repo copyright year to 2021

- src/cryptonote_protocol/levin_notify.cpp
this is not a levin packet, this is just its payload
> protocol: fix wrong command in logs

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
Necessary to resolve monero-project/monero-gui#3246
> wallet api: allow wallet to fetch all key images via api

- src/simplewallet/simplewallet.cpp
Added an optional filename parameter to the sign_transfer command to specify the file to read the transaction from for signing.
Resolves #7012
> simplewallet: Add input file parameter to sign_transfer

- src/wallet/api/transaction_history.cpp
Resolves monero-project/monero-gui#3124
> wallet_api: store fee for incoming txs in history

- .gitmodules
- external/CMakeLists.txt
No one maintains our fork, switch to upstream.
> miniupnp: set submodule to upstream, disable install

- src/simplewallet/simplewallet.cpp
> simplewallet: allow setting --restore-height 0

- README.md
Changed latest year from 2020 -> 2021. A minor change I know, but what an easy opportunity to get a change into something as cool as Monero!
> Updated copyright date in README.md

- docs/ANONYMITY_NETWORKS.md
Cherry-picked #7284 to master branch.
> docs: Remove outdated bits about anonymity network seed nodes

- src/simplewallet/simplewallet.cpp
> Simplewallet.cpp: Add export_outputs help

- contrib/epee/include/net/levin_protocol_handler_async.h
`m_deletion_initiated` in the levin code doesn't appear to be needed. The value is always checked after `start_outer_call()` which (semi-secretely) does a `weak_ptr`->`shared_ptr` in `connection::add_ref()`. The object is never destructed if a `shared_ptr` is held, so the atomic value is never going to be `true` in the checks.
> Remove unnecessary atomic operations in levin code

- tests/unit_tests/wipeable_string.cpp
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973196
> unit_tests: fix wipeable_string parse_hexstr test with latest gtest

- external/db_drivers/liblmdb/mdb.c
> ITS#9007 don't free loose writemap pages

- external/db_drivers/liblmdb/mdb.c
> ITS#9007 don't free loose writemap pages (release-0.17)

- src/device_trezor/device_trezor_base.cpp
- src/device_trezor/device_trezor_base.hpp
> device_trezor: wipe string fields, add check [release-v0.17]

- src/crypto/hash-ops.h
- src/crypto/tree-hash.c
- src/cryptonote_basic/CMakeLists.txt
- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_basic/cryptonote_format_utils.h
- src/cryptonote_basic/merge_mining.cpp
- src/cryptonote_basic/merge_mining.h
- src/cryptonote_config.h
- src/debug_utilities/cn_deserialize.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
- tests/unit_tests/crypto.cpp
- utils/python-rpc/framework/daemon.py
Note about possible conflict of interest: I made this patch for the benefit of another coin. However, I believe making it easier to merge mine is beneficial to monero due to the chance to get additional hash rate from (ideally) many merge mined chains.
> New add_aux_pow RPC to support merge mining

- utils/health/README.md
Just formatting some docs in utils/health
more to follow...
> Formatted markdown in readme.md

- src/device_trezor/trezor/protocol.cpp
release-v0.17 equivalent of https://github.com/monero-project/monero/pull/7418
@selsta
> trezor: simplify recognition of integrated addresses, fixes monero-gui, v0.17 branch

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
> wallet rpc: return output keys with incoming transfers

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/p2p/net_node.inl
This reverts commit 4e74385a1ae9eae4ae9e8d155dfd96978eb10e7a.
Replaced by #7308
> Revert "fix accessing an network address in a deleted context"

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_payments.cpp
Opening PR for early review. Will solve issue #7179
> wallet_rpc_payments: implement multithreading

- src/mnemonics/electrum-words.cpp
- src/mnemonics/electrum-words.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
Also sanity check language name
> wallet_rpc_server: set seed language in generate_from_keys

- README.md
Install all dependencies at once on openSUSE without typo
> dependencies in openSUSE

- external/easylogging++/easylogging++.cc
saves an object ctor/dtor per log
> easylogging++: in place log sanitization

- contrib/gitian/gitian-build.py
> gitian: remove osslsigncode

- contrib/gitian/gitian-build.py
> [release-v0.17] gitian: remove osslsigncode

- external/db_drivers/liblmdb/mdb.c
Broken in 9c6eb75c656363176a55c63c81803feb3cfa614d
> ITS#9496 fix mdb_env_open bug from #8704

- external/db_drivers/liblmdb/mdb.c
Broken in 9c6eb75c656363176a55c63c81803feb3cfa614d
> ITS#9496 fix mdb_env_open bug from #8704 (release-v0.17)

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Cherry-picked #7680. Related to #7673.
> wallet2: Fix rescan_bc keep_ki option

- Dockerfile
- contrib/depends/packages/boost.mk
- utils/build_scripts/android32.Dockerfile
- utils/build_scripts/android64.Dockerfile
> depends, docker: fix bintray links

- .github/workflows/build.yml
> workflows: upload source archive artifact

- src/wallet/api/address_book.cpp
- src/wallet/api/address_book.h
- src/wallet/api/transaction_history.cpp
- src/wallet/api/transaction_history.h
- src/wallet/api/transaction_info.cpp
- src/wallet/api/transaction_info.h
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
Includes not merged yet #7677
We have multiple open GUI PRs that depend on this and it is not clear when we will branch from master again so I backported them.
> [release-v0.17] backport wallet api changes from master

- contrib/epee/include/storages/portable_storage.h
> [release-v0.17] Fix boost 1.76.0 compatibility

- README.md
https://github.com/monero-project/meta/issues/575
> README: freenode -> libera

- src/wallet/api/wallet.cpp
> wallet_api: move adjust_mixin call within try block

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
This way there is no need to cache it on the GUI side, which can cause nasty bugs if the cache isn't updated.
> wallet_api: getPassword

- src/p2p/net_node.inl
I've got a decent sized machine running on OVH in Singapore. It's one of the remote nodes used for Feather Wallet. I set it up for all networks as well as tor inbound. Hoping I can contribute in this small way.
> add singapore.node.xmr.pm as seed node

- src/simplewallet/simplewallet.cpp
> simplewallet: don't truncate integ. address in export_transfers

- src/blocks/CMakeLists.txt
Co-authored-by: @perfect-daemon
Required for e.g. Xcode or ninja msys2
> cmake: fix non portable code

- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
Makes subaddress and wallet generation instantaneous.
> ledger: use software device if we have view key

- src/wallet/wallet2.cpp
> wallet: close device in wallet destructor, fixes #7784

- src/serialization/json_object.cpp
rct::RCTTypeNull doesn't have these fields (ecdhInfo, outPk, txnFee).
> Fixed json serialization of rct::RCTTypeNull

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
> wallet_api: expose offline mode status

- src/wallet/wallet2.cpp
https://github.com/monero-project/monero/pull/7798#issuecomment-887141766
> wallet2: Protect client from divide by 0 caused by integer truncation

- src/wallet/wallet2.cpp
Extra protection layer in the wallet
> wallet2: Ensure real output is unlocked in response from daemon

- utils/python-rpc/framework/wallet.py
> python-rpc: add missing python api for new freeze/thaw/frozen RPC

- contrib/epee/include/net/http_protocol_handler.inl
> support cors wildcard

- README.md
with edits from @UkoeHB from PR #7922 because I can't sqash because i use the github web gui like a plebe
> update readme research section contacts

- contrib/depends/packages/unwind.mk
- contrib/depends/patches/unwind/fix_obj_order.patch
> depends: update unwind, fix build with ubuntu 21.04

- Dockerfile
Resolves #7938
Should be easier to maintain in regards to dependencies. Untested.
> Dockerfile: use depends

- .github/workflows/build.yml
`openssl` is preinstalled but it appears incomplete.
> workflows: add missing dependency, fix mac build

- src/crypto/slow-hash.c
Same as #8031 for release-v0.17
> slow_hash: don't blow out Mac stack on ARM64 [v0.17]

- contrib/depends/packages/hidapi.mk
- contrib/depends/patches/hidapi/missing_win_include.patch
This might help with some edge cases where people have issues with Ledger not connecting.
> depends: bump hidapi to 0.11.0

- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_core/cryptonote_tx_utils.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
- utils/python-rpc/framework/daemon.py
Calculate PoW hash for a block candidate
Mainly adding this for use by p2pool. Will remove "WIP" tag when integration testing is done.
> Add calcpow RPC

- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_core/cryptonote_tx_utils.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
- utils/python-rpc/framework/daemon.py
Calculate PoW hash for a block candidate
Same as #8070
> Add calcpow RPC [release v0.17]

- contrib/gitian/DOCKRUN.md
- contrib/gitian/README.md
- contrib/gitian/dockrun.sh
> Add simple script for running gitian-build in docker [v0.17]

- src/rpc/core_rpc_server.cpp
> rpc: don't set error code as status string

- cmake/FindReadline.cmake
ARM equivalent of https://github.com/monero-project/monero/pull/3708
> cmake: find readline on macOS ARM

- tests/functional_tests/uri.py
> functional_tests: update uri test with external pid

- src/p2p/net_node.inl
update net_node.inl to remove old xmrchain.net server for seed node and add new IP for current xmrchain.net
> Update net_node.inl for xmrchain.net seed node IP

- src/p2p/net_node.inl
update net_node.inl to replace old xmrchain.net seed node with new xmrchain.net server IP so the old one can retire and spend its final days drinking things out of coconuts
> Update net_node.inl to to replace seed node

- README.md
Changed latest year from 2021 to 2022.
> Update Copyright year in README.md

- src/crypto/rx-slow-hash.c
If allocating large pages fails, we don't try again.
This has the obvious drawback of not being able to use large pages
if they fail once.
> crypto: fix constant randomx exceptions in large page allocator

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
> support authentication in monero-wallet-rpc set_daemon

- src/wallet/wallet2.cpp
- tests/functional_tests/transfer.py
Fixes #https://github.com/monero-project/monero/issues/8073
> Balance includes unconfirmed transfers to self

- contrib/epee/include/net/levin_base.h
- contrib/epee/include/net/levin_client.inl
- contrib/epee/include/net/levin_client_async.h
- contrib/epee/include/net/levin_helper.h
- contrib/epee/include/net/levin_protocol_handler.h
- contrib/epee/include/storages/portable_storage_from_bin.h
Fixes issues reported in #8120
> Undefined behaviour fixes

- src/crypto/crypto.h
- src/cryptonote_basic/account.cpp
- src/cryptonote_basic/account.h
- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_config.h
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/gen_multisig/gen_multisig.cpp
- src/multisig/CMakeLists.txt
- src/multisig/multisig.cpp
- src/multisig/multisig.h
- src/multisig/multisig_account.cpp
- src/multisig/multisig_account.h
- src/multisig/multisig_account_kex_impl.cpp
- src/multisig/multisig_kex_msg.cpp
- src/multisig/multisig_kex_msg.h
- src/multisig/multisig_kex_msg_serialization.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/core_tests/chaingen.h
- tests/core_tests/multisig.cpp
- tests/functional_tests/multisig.py
- tests/unit_tests/multisig.cpp
- utils/python-rpc/framework/wallet.py
> multisig key exchange update and refactor - release-v0.17

- src/simplewallet/simplewallet.cpp
> account info text alignment

- src/wallet/wallet2.cpp
> wallet2: use BP+ for cold signing

- src/hardforks/hardforks.cpp
As per [meeting](https://libera.monerologs.net/monero-dev/20220507#c92711-c92722)
> Set hf v15 testnet fork heights

- contrib/epee/src/net_ssl.cpp
- src/rpc/core_rpc_server.cpp
While copying my `data dir` to another drive, I missed copying the rpc_ssl.key file b/c of the file permissions. This change will give a much more clear, descriptive error in that scenario. Before the error message was something like `use_private_key_file: asio ssl error`. I put in a couple of layers of redundancy in case this scenario originates from somewhere that isn't `core_rpc_server`
> Give better error messages when missing SSL files

- src/p2p/net_node.inl
Tor/i2p nodes will sometimes send peer lists of size > the expected max to outgoing connections, which causes tor/i2p connections to drop. This PR ensures the peer list remains <= the max size.
I have a decent degree of confidence this is a significant cause of tor/i2p dropped connection issues in #6938 and #6631 (and sporadic failed tx submissions on tor nodes like in #8251), but it's not the only cause of these issues. Still in the process of investigating and patching what look like clearly apparent bugs, separate from this one.
In testing on my machine, I observed that my tor node will push peer lists larger than the max size on average every 1-3 minutes or so (sometimes the gaps are larger, sometimes smaller),  which is followed by the existing outgoing tor connection dropping. …
> p2p: Don't send peer list larger than max allowed

- README.md
Remade #8270 (includes edits from UkoeHB)
> README.md: Add v15/v16 network upgrade

- README.md
@agowa338 any wording suggestions?
> README: depends has only been tested on ubuntu 18.04 and 20.04

- .github/workflows/build.yml
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- tests/README.md
- tests/functional_tests/CMakeLists.txt
- tests/functional_tests/functional_tests_rpc.py
- tests/functional_tests/txpool.py
- utils/python-rpc/framework/zmq.py
> zmq: publish submitted txs via zmq [release-v0.18]

- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_basic/cryptonote_format_utils.h
- src/device/device.hpp
- src/device/device_default.hpp
- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
- src/device/log.cpp
- src/device/log.hpp
> ledger support for hf 15 (BP+, view tags) [release-v0.18]

- src/device_trezor/device_trezor.cpp
- src/device_trezor/trezor/protocol.cpp
- src/device_trezor/trezor/protocol.hpp
- tests/core_tests/chaingen.cpp
- tests/trezor/trezor_tests.cpp
- tests/trezor/trezor_tests.h
- BP+ support added for Trezor
- old Trezor firmware version support removed, code cleanup
Same as https://github.com/monero-project/monero/pull/8299 due to https://github.com/monero-project/monero/pull/8299#issuecomment-1204393941
> feat(trezor): add HF15 support, BP+, release-v0.18

- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
https://github.com/monero-project/monero/pull/8415
> txpool: continue pool pruning even if a tx can't be found [release-v0.18]

- contrib/gitian/DOCKRUN.md
Master version of this PR: https://github.com/monero-project/monero/pull/8442
> Bump Gitian build instructions to v0.18.1.0 [Release Branch]

- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/rpc/core_rpc_server.cpp
> rpc: skip bootstrap nodes that are lower than last checkpoint [release-v0.18]

- src/wallet/wallet2.cpp
> wallet2: Fix missing semi-colon in error message [master]

- src/multisig/multisig_account.cpp
- src/multisig/multisig_account.h
- src/multisig/multisig_account_kex_impl.cpp
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- tests/unit_tests/multisig.cpp
> multisig: fix seed restore (suggestions by @UkoeHB) [master]

- src/gen_multisig/gen_multisig.cpp
- src/multisig/multisig_account.cpp
- src/multisig/multisig_account.h
- src/multisig/multisig_account_kex_impl.cpp
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/unit_tests/multisig.cpp
- utils/python-rpc/framework/wallet.py
> multisig: force update option for key exchange [v0.18]

- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
> wallet2: fail to establish daemon cxn == "Disconnected" cxn status [master]

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- tests/core_proxy/core_proxy.h
- tests/unit_tests/node_server.cpp
See https://github.com/monero-project/monero/pull/8587
> Move update_checkpoints() to a later stage [release-v0.18]

- README.md
My attempt to modify the paragraph describing hard forks now because the 6 month thing and the october / april thing has been replaced with more of an ad-hoc sorta thing.
> update readme Scheduled upgrades section

- CMakeLists.txt
this pr dep on https://github.com/monero-project/miniupnp/pull/8 for fully successful building.
> fix build in netbsd

- .github/workflows/build.yml
- .github/workflows/depends.yml
> workflows: ubuntu 18.04 is deprecated

- .github/workflows/build.yml
- .github/workflows/depends.yml
> workflows: ubuntu 18.04 is deprecated [release-v0.18]

- src/blockchain_utilities/blockchain_prune.cpp
on my anecdotal SSD, goes from about 9 hours to 1h20.
> blockchain_prune: faster

- .github/workflows/gitian.yml
> workflows: build gitian on tag [release-v0.18]

- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
> wallet: fix create view-only wallet from existing wallet [release]

- src/p2p/net_node.inl
> p2p: fix back ping to discover healthy peers to connect to [release]

- .github/workflows/build.yml
> workflows: set a public DNS when doing tests [release-v0.18]

- README.md
updated readme with all relevant instances of v0.18.0.0 changed to v0.18.1.2
> update readme with v0.18.1.2 version number

- src/common/dns_utils.cpp
- src/common/threadpool.h
Closes #8695
Closes #8696
Fixes Windows CI
> common: add missing includes

- src/common/dns_utils.cpp
- src/common/threadpool.h
> common: add missing includes [release-v0.18]

- src/common/data_cache.h
- src/cryptonote_core/blockchain.cpp
- src/ringct/rctSigs.cpp
- src/ringct/rctSigs.h
> RingCT cache (huge block propagation speedup) [release-v0.18]

- src/rpc/core_rpc_server.cpp
There is potential for a double parsing of the tx base, which could be cached if it's found to be a performance issue later.
> rpc: do not misidentify coinbase txes as pruned

- src/blockchain_utilities/blockchain_stats.cpp
> blockchain-stats: print any remaining data at end of loop

- src/device/device_ledger.cpp
> device: Add ledger Stax device id to device detection [release-v0.18]

- src/p2p/net_node.inl
> p2p: avoid spam blocking ipv4 addresses in a blocked subnet [release-v0.18]

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Generally useful, at least  one person asked for this, and I've had this in TF for more than three years apparently.
> wallet2: add on_reorg callback

- src/simplewallet/simplewallet.cpp
from time to time, some people don't realize their wallets get created in their current working directory
> simplewallet: print fully qualified filename for new wallets

- contrib/epee/include/net/net_helper.h
- contrib/epee/src/net_ssl.cpp
- src/p2p/net_node.inl
Was a part of #8786 but got moved to its own PR
> epee: remove dead code in net_helper

- src/wallet/wallet2.cpp
- tests/unit_tests/output_selection.cpp
> wallet2: fix infinite loop in fake out selection unit test

- contrib/epee/include/file_io_utils.h
- contrib/epee/include/storages/parserse_base_utils.h
- src/common/combinator.h
- src/wallet/api/wallet2_api.h
> fix missing <cstdint> includes

- .github/workflows/build.yml
- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/node_rpc_proxy.cpp
- src/wallet/node_rpc_proxy.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
- src/wallet/wallet_rpc_server.cpp
- tests/README.md
- tests/functional_tests/CMakeLists.txt
- tests/functional_tests/transfer.py
> wallet2: fix rescanning tx via scan_tx [master]

- contrib/epee/include/net/levin_protocol_handler_async.h
The invoke function in the levin handler is currently unused. It is probably best to remove it because:
* using it and `async_invoke` at the same time is going to be problematic on the ordering of responses
* It blocks a thread waiting for a response, and requires another thread to process the response
#8569 removes related code that is also unused.
> Remove invoke function in levin handler

- src/common/container_helpers.h
- Adds templates to assist with handling containers.
> [seraphis] common: add container helpers

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server_commands_defs.h
> Show IPv6 addresses in connection list

- src/common/dns_utils.cpp
(belatedly) squashed commit per request
> Message about DNS_PUBLIC to help users with issue #8452

- src/cryptonote_basic/miner.cpp
Miner code didn't check for block major version. Closes #8821
> Fixed RandomX initialization when mining from scratch [release-v0.18]

- src/cryptonote_core/blockchain.cpp
> blockchain: ensure base fee cannot reach 0

- src/cryptonote_core/cryptonote_core.cpp
- utils/fish/monerod.fish
> daemon: remove --fluffy-blocks

- contrib/depends/packages/expat.mk
https://github.com/libexpat/libexpat/blob/fe8ff0345f889b322215739a3fa7b6ca8a8a6bbe/expat/Changes
> depends: update expat to 2.5.0

- contrib/epee/include/net/abstract_tcp_server2.inl
> properly terminate interrupted TCP connection. fixes #8685 [release-v0.18]

- contrib/epee/src/net_ssl.cpp
Same as #8899 but on release branch.
> Set SSL SNI even when server verification is disabled [0.18]

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- tests/functional_tests/mining.py
Closes https://github.com/monero-project/monero/issues/8874
> core_rpc_server: return ID of submitted block

- src/wallet/wallet2.cpp
> wallet2: when checking frozen multisig tx set, don't assume order [RELEASE]

- src/wallet/wallet2.cpp
> wallet2: fix `scan_tx` custom compare function incorrectly throwing on some envs [release]

- tests/functional_tests/multisig.py
The changes to the multisig tests in #8914 and #8904 affected each other, this PR cleans up the code and fixes that issue.
> functional_tests: fix multisig tests noutputs assertion

- tests/functional_tests/multisig.py
> functional_tests: fix multisig tests noutputs assertion [RELEASE]

- contrib/depends/packages/openssl.mk
https://www.openssl.org/news/cl30.txt
> depends: openssl: update to 3.0.11

- README.md
> README: remove obsolete forum

- contrib/epee/include/net/http_client.h
> http_client: reduce number of packets sent for small bodies [RELEASE]

- src/wallet/wallet2.cpp
> wallet2: ensure transfers and sweeps use same fee calc logic [release]

- contrib/depends/toolchain.cmake.in
https://github.com/tevador/RandomX/releases/tag/v1.2.1
> Update RandomX to 1.2.1

- contrib/depends/toolchain.cmake.in
https://github.com/tevador/RandomX/releases/tag/v1.2.1
> Update RandomX to 1.2.1 [release]

- contrib/gitian/gitian-linux.yml
> gitian: add riscv64 support [release-v0.18]

- src/ringct/rctTypes.h
> ringct: make `rctSigBase` serialization follow strict aliasing rule [RELEASE]

- src/crypto/jh.c
> JH hash compiler workarounds

- contrib/epee/src/mlog.cpp
- external/easylogging++/easylogging++.cc
> heed NO_COLOR environment variable [RELEASE]

- src/wallet/wallet2.cpp
Multisig keys per-transfer were being wiped, but not erased, which lead to a ginormous quadratic bloat the more transfers and exports you performed with the wallet. I talked to a person that was able to remove 335 MEGABYTES from their wallet cache b/c of this PR.
> wallet: fix multisig key storage leak

- src/wallet/wallet2.cpp
> wallet: fix multisig key storage leak [RELEASE]

- src/rpc/zmq_server.cpp
> Fix EAGAIN bug in ZMQ-RPC/ZMQ-PUB [0.18]

- .github/workflows/depends.yml
> workflows: upload macOS binary after name change

- contrib/epee/include/net/http_base.h
- src/common/dns_utils.cpp
* No need for entire new class (Fix #8732).
* Fix stdint.h header include in contrib/epee/include/net/http_base.h.
Fix #8732
> Cleanup scoped_ptr in src/common/dns_utils.cpp

- tests/unit_tests/aligned.cpp
Same as #9143 but on release branch.
> Add <cstdint> to aligned test

- src/ringct/rctTypes.h
Same as #9155 but on release branch.
> Zero initialize rctSigBase elements

- contrib/depends/packages/expat.mk
https://github.com/libexpat/libexpat/blob/R_2_6_0/expat/Changes
> depends: expat: update to 2.6.0

- contrib/depends/packages/openssl.mk
https://www.openssl.org/news/cl30.txt
> depends: openssl: update to 3.0.13

- docs/ANONYMITY_NETWORKS.md
> docs: omit i2p port number from ANONYMITY_NETWORKS

- src/cryptonote_basic/tx_extra.h
- src/serialization/container.h
- src/serialization/debug_archive.h
- src/serialization/difficulty_type.h
- src/serialization/pair.h
- src/serialization/serialization.h
- src/serialization/tuple.h
- src/serialization/variant.h
- tests/unit_tests/serialization.cpp
#9069
The main reason I want this PR on release is so I can add #9077 to release, which would make rebasing easier to wallet-based PRs since the container types differ between master and release.
> serialization: fix infinite loops and clean up dispatching [RELEASE]

- tests/unit_tests/epee_utils.cpp
> unit_tests: fix strtoul unit test [release-v0.18]

- src/cryptonote_core/tx_pool.cpp
> tx_memory_pool: make double spends a no-drop offense [RELEASE]

- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
> Fixed mempool pruning [release-v0.18]

- contrib/epee/include/net/http_client.h
This reverts commit 0ae5c91e504b8007dedc2b89c9b2b49c404ffec6.
Reason: regression caused Issue #9235. The request is not re-tried correctly on HTTP 401, so digest authentication didn't work.
> Revert "http_client: reduce number of packets sent for small bodies"

- src/ringct/rctTypes.h
> ringct: fix trunc_amount field name change [RELEASE]

- tests/block_weight/block_weight.cpp
- tests/block_weight/block_weight.py
the test was still performed with consensus rules from before
that change
> tests: update block_weight for 2021 scaling

- src/common/timings.cc
- src/common/timings.h
- tests/performance_tests/performance_tests.h
- Save data points in csv format.
- Support incremental saving.
In test `init()` methods:
```
if (params.core_params.td.get())
{
TimingsDatabase::instance null_instance;
null_instance.npoints = 0;
std::string report_csv;
std::string separator{','};
report_csv += std::to_string(param_a) + separator;
report_csv += std::to_string(param_b) + separator;
params.core_params.td->add(report_csv.c_str(), null_instance);
}
```
In `tests/performance_tests/main.cpp`:
```
TEST_PERFORMANCE0(filter, p, test_1);
TEST_PERFORMANCE0(filter, p, test_2);
if (p.core_params.td.get())
p.core_params.td->save(false);
```
Output recorded in file:
```
param_a,param_b,{comma-separated timings database stats}  //test_1 …
```
> [seraphis] common: update TimingsDatabase

- src/wallet/wallet2.cpp
> wallet2: ensure transfers and sweeps use same fee calc logic rnd2 [release]

- src/cryptonote_protocol/levin_notify.cpp
- src/cryptonote_protocol/levin_notify.h
- src/p2p/net_node.inl
- tests/unit_tests/levin.cpp
Same as #9267 except on master branch.
> Skip privacy networks (on tx sends) that don't have outgoing connections

- src/common/util.cpp
- src/common/util.h
- src/wallet/wallet_rpc_server.cpp
[9270](https://github.com/monero-project/monero/pull/9270)
> common: fix privatefile create [RELEASE]

- src/common/boost_serialization_helper.h
- src/common/util.cpp
- src/common/util.h
- src/p2p/net_peerlist.cpp
- src/wallet/wallet2.cpp
- tests/unit_tests/wallet_storage.cpp
https://github.com/monero-project/monero/pull/9305
> common: support boost filesystem copy_options. [RELEASE]

- contrib/epee/include/storages/portable_storage_val_converters.h
Closes https://github.com/monero-project/monero/issues/9304
> contrib: fix compilation error for boost 1.85

- src/p2p/net_node.inl
If someone wants their node added please add a comment under this PR. We especially need Tor / I2P addresses.
> net_node: update seed nodes

- src/p2p/net_node.inl
Also remove port for I2P seed nodes
#9316
> net_node: update seed nodes [release-v0.18]

- README.md
see https://github.com/monero-project/monero-site/pull/2298
globee past sponsor
> README.md: sponsors;remove forked networking/globee

- src/wallet/wallet2.cpp
> wallet: fetch pool txs in pruned form [RELEASE]

- src/serialization/json_object.cpp
- src/serialization/json_object.h
Same as #9370 but on release branch.
> Fix ZMQ Tx Pruning [release 0.18]

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
This helps with my attempt to make a frontend lib for LWS wallets.
> Make wallet2::estimate_fee static

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Same as #9425 but on 0.18 branch.
> Make wallet2::estimate_fee static [0.18]

- src/device/device_ledger.cpp
> device: add ledger flex support [release]

- src/cryptonote_basic/miner.cpp
- src/cryptonote_basic/miner.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
- tests/functional_tests/blockchain.py
> rpc: add cumul weight field to block template resp

- src/common/variant.h
- tests/unit_tests/variant.cpp
Upstreaming https://github.com/UkoeHB/monero/pull/28
edit: updated unit tests
> variant: split into variant and optional_variant

- src/cryptonote_core/blockchain.cpp
> Blockchain: fix temp fails causing alt blocks to be permanently invalid [RELEASE]

- docs/CONTRIBUTING.md
this is a redo of #9210 because I'm an idiot and can't squash
> docs: clarify proper PR title format

- src/lmdb/key_stream.h
- src/lmdb/table.h
- src/lmdb/util.h
- src/lmdb/value_stream.h
Same as #9511 except on release branch.
> Update/lmdb static asserts [0.18]

- contrib/epee/include/byte_stream.h
This is already in the `master` branch. I am PRing this to `release-v0.18` in case LWS has a 0.4 release against the 0.18 branch.
> Add byte_stream `value_type` and `data()` [0.18]

- utils/systemd/monerod.service
https://github.com/monero-project/monero/pull/9421
> monerod.service: use network-online.target [RELEASE]

- src/ringct/rctTypes.h
Part of upstreaming Seraphis/Carrot
> ringct: add operator!= for `key`

- src/device_trezor/device_trezor.cpp
- src/multisig/multisig_account.h
- src/multisig/multisig_account_kex_impl.cpp
- src/wallet/wallet2.cpp
I noticed the following typos while working on the Debian package for Feather Wallet.
> Fix typos.

- contrib/epee/include/string_tools.h
- contrib/epee/src/readline_buffer.cpp
- contrib/epee/src/string_tools.cpp
> epee: partially revert string tools to fix linking errors [RELEASE]

- src/wallet/wallet_rpc_server.cpp
https://github.com/monero-project/monero/pull/9581
> wallet: report exact reason for open_wallet failure [RELEASE]

- src/daemon/command_parser_executor.cpp
- src/p2p/net_node.inl
- tests/data/node/banlist_1.txt
- tests/unit_tests/node_server.cpp
> p2p: allow comments in banlist files [RELEASE]

- .github/workflows/build.yml
> ci: msys2: pin boost to 1.86.0 [RELEASE]

- .github/workflows/build.yml
- contrib/brew/Brewfile
> ci: brew: pin boost to 1.85 [RELEASE]

- src/wallet/wallet2.cpp
https://github.com/monero-project/monero/pull/9601
> wallet: shortchain history should include base block [RELEASE]

- src/cryptonote_core/blockchain.cpp
> Blockchain: get height of RingCT fork programmatically [RELEASE]

- src/common/password.cpp
> common/password: flush confirm prompt before user input

- src/common/password.cpp
> common/password: flush confirm prompt before user input [RELEASE]

- src/debug_utilities/object_sizes.cpp
- src/p2p/p2p_protocol_defs.h
> p2p: remove dead protocol defs

- external/CMakeLists.txt
> miniupnpc: fix build with gcc 14

- tests/unit_tests/dns_resolver.cpp
> tests: fix IPv4Success, DNSSECSuccess [RELEASE]

- src/rpc/core_rpc_server.cpp
See : https://github.com/monero-project/monero/pull/9660#issuecomment-2589444799
> release-v0.18: validate ip parameter in set_bans rpc call

- contrib/guix/manifest.scm
Unused. 
| package | old | new |
|---|---|---|
| p7zip | 16.02 | removed |
| package | old | new | 
|---|---|---|
| xmlto | 0.0.28 | removed |
| yasm | 1.3.0 | removed |
> guix: remove p7zip

- src/cryptonote_core/blockchain.cpp
> Revert "blockchain: detect and log bad difficulty calculations" [release-v0.18]

- src/daemon/main.cpp
> daemon: fix log message typo

- src/p2p/net_node.inl
> p2p/net_node.inl : update seed node [release v0.18]

- src/cryptonote_basic/connection_context.cpp
- src/cryptonote_basic/connection_context.h
- src/cryptonote_protocol/block_queue.cpp
- src/cryptonote_protocol/block_queue.h
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
Same as #9582 except on 0.18 release branch.
> Some cleanup in span/connection_context + few more checks [0.18]

- src/wallet/wallet2.h
> wallet: fix signed_tx_set RangeProofType serialization [RELEASE]

- tests/functional_tests/p2p.py
Reduce the likelihood of false positive failures in the p2p transaction propagation functional test by waiting up to a maximum timeout for a transaction to propagate, rather than using a fixed timeout, to reflect the random delay of Dandelion++ transaction propagation. This strategy also speeds test execution in cases where propagation occurs faster than the previously expected fixed delay.
> tests: Improve p2p tx propagation functional test [v0.18]

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
- utils/python-rpc/framework/wallet.py
Fixes https://github.com/monero-project/monero/issues/9785
> wallet: add wallet rpc call to get default fee priority

- src/blockchain_db/lmdb/db_lmdb.cpp
> BlockchainLMDB: fix data.mdb nuking on Windows [RELEASE]

- contrib/epee/include/net/abstract_tcp_server2.inl
I'm investigating a potential unit test for this. But I thought I would share for more immediate testing.
> Add incoming only test

- contrib/epee/include/net/abstract_tcp_server2.inl
Same as #9820 except on release branch.
> Add incoming only test [0.18]

- cmake/CheckTrezor.cmake
- src/device_trezor/trezor/messages_map.cpp
- src/device_trezor/trezor/messages_map.hpp
> trezor: fix protobuf 30 compatibility [0.18]

- Doxyfile
- src/device_trezor/device_trezor.cpp
- tests/libwallet_api_tests/scripts/README.md
- tests/trezor/daemon.h
- tests/unit_tests/levin.cpp
> chore: fix some typos in comments

- src/cryptonote_basic/cryptonote_basic_impl.h
> cryptonote_basic: remove unused struct [0.18]

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
> cryptonote_protocol: fix handling of pruned blocks during sync [RELEASE]

- src/wallet/wallet2.cpp
This addresses the issue described here: https://github.com/monero-project/monero/issues/9841
> wallet: Correct max / min block waiting periods for estimated_backlog in wallet2.cpp

- src/wallet/wallet2.cpp
https://github.com/monero-project/monero/pull/9842
> wallet: Correct max / min block waiting periods for estimated_backlog in wallet2.cpp [RELEASE]

- src/rpc/core_rpc_server.cpp
> chore: fix some typos

- contrib/guix/guix-build
https://libera.monerologs.net/monero-dev/20250406#c516903-c516936
> guix: unset HOST env variable

- .github/workflows/build.yml
> ci: run brew update

- cmake/CheckLinkerFlag.cmake
Same as #9886 but on release branch.
> Fix cmake usage in FetchContent and ExternalProject [0.18]

- contrib/epee/include/serialization/keyvalue_serialization_overloads.h
- src/common/perf_timer.h
> msys2 build: include int headers [RELEASE]

- contrib/epee/src/string_tools.cpp
confirmed by @tobtoht 
more info: https://github.com/monero-project/monero/pull/9149#issuecomment-2821087958
> epee: fix string_tools on Windows

- contrib/epee/include/net/abstract_tcp_server2.inl
Same as #9955 but on release branch.
> Add check for exception in tcp accept handler

- src/p2p/net_node.inl
Same as #9948 but on release branch.
> Add is_same_host check to p2p [0.18]

- src/simplewallet/simplewallet.cpp
https://github.com/monero-project/monero/pull/9977
> simplewallet: respect `do-not-relay` in `sweep_single` [0.18]

- src/rpc/daemon_handler.cpp
- src/rpc/daemon_messages.cpp
- src/rpc/daemon_messages.h
Same as #9957 but on release branch. This looks a little different because the release branch has logic for the older fee system.
> Add new dynamic fees to ZMQ [0.18]

- src/rpc/core_rpc_server.cpp
> rpc: return error correctly on bad key image string [RELEASE]

- docs/URI_SCHEME.md
This was taken from the [Wiki](https://github.com/monero-project/monero/wiki) without modifications.
The wiki is outdated and unmaintained. It can be disabled after this PR is merged.
> docs: add URI scheme

- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
> wallet: deprecate `wallet2::find_and_save_rings()` [RELEASE]

- README.md
Related to:
* https://github.com/monero-project/monero/issues/10028#issuecomment-3172056980
* https://github.com/monero-project/monero/pull/9988
* https://github.com/monero-project/monero/pull/9784
> add depends command for Apple Silicon macOS binaries

- src/simplewallet/simplewallet.cpp
> simplewallet: batch address creation limit to match rpc [0.18]

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
> Cleaner validation (faster and saner) [v0.18]

- docs/CONTRIBUTING.md
\+ 3 approvals from contributors.
> CoC: allow maintainers to merge their own prs if queued

- docs/CONTRIBUTING.md
Discussion: https://github.com/monero-project/monero/pull/9738#discussion_r1930201296
> CoC: remove constraints on 'release history'

- docs/CONTRIBUTING.md
Discussion: https://github.com/monero-project/monero/pull/9738#discussion_r1930251371
> CoC: remove constraint suggesting copyright can be 'owned collectively'

- docs/CONTRIBUTING.md
Discussion: https://github.com/monero-project/monero/pull/9738#discussion_r1929970951
> CoC: prohibit anyone from committing patches to the project directly

- docs/CONTRIBUTING.md
Discussion: https://github.com/monero-project/monero/pull/9738#discussion_r1929981342
> CoC: do not encourage using real names or 'well-known aliases'

- docs/CONTRIBUTING.md
Discussion: https://github.com/monero-project/monero/pull/9738#discussion_r1930188646
> CoC: 'log an issue' -> 'open an issue'
