monero-project/monero

- src/p2p/net_node.inl
Fix seed nodes for i2p and Tor on 0.17 branch. Verified the previous error was the result of the incorrect location. Also verified that these seed nodes are used when the proxy is enabled.
> Fix i2p/tor seed nodes [0.17]

- .github/workflows/build.yml
Fixes the warnings, also better maintained.
> workflows: bump msys2 action to v2

- src/cryptonote_config.h
- src/cryptonote_core/tx_pool.cpp
Same as PR #7025 on 0.17 branch.
> Change Dandelion++ fluff probability to 20%, and embargo timeout to 39s [0.17]

- CMakeLists.txt
Add two new options, MONERO_PARALLEL_COMPILE_JOBS and MONERO_PARALLEL_LINK_JOBS to try and prevent running out of memory when building everything.
Requires >= cmake 3.0.0, and the use of the Ninja generator.
If the values are unset, or if Ninja is not used, it behaves as before.
* https://cmake.org/cmake/help/latest/prop_gbl/JOB_POOLS.html
* https://reviews.llvm.org/D6304
```bash
cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DMONERO_PARALLEL_LINK_JOBS=1
cd build
ninja
```
> cmake: Use job pool feature to limit concurrent jobs

- src/daemon/command_parser_executor.cpp
- src/daemon/command_server.cpp
When given a wrong argument, some daemon commands failed with "unknown
command" error, instead of a meaningful error message. This patch
brings consistency into the error messages.
In several places, this patch removes relatively useful messages,
and replaces them with more generic ones. E.g.,
-    std::cout << "use: print_pl [white] [gray] [<limit>] [pruned] [publicrpc]" << std::endl;
+    std::cout << "Invalid syntax: Too many parameters. For more details, use the help command." << std::endl;
There are two reasons for this:
1. Consistency.
2. Removing duplicates.
The detailed information about the parameters is present in
the help messages already. Having it in two places increases
the risk that the messages would get out of date.
> Update error messages in daemon

- src/wallet/api/transaction_history.cpp
- src/wallet/api/transaction_info.cpp
- src/wallet/api/transaction_info.h
- src/wallet/api/wallet2_api.h
Adds `coinbase` and `description` to the `TransactionInfo` object. This modifies the object. However, Monero GUI should still work ok:
https://github.com/monero-project/monero-gui/blob/2fd3974194d555979e9b960d44d613ffdc67a7c9/src/libwalletqt/TransactionInfo.cpp#L141-L154
> Extend TransactionInfo with coinbase and description attributes in wallet/api

- src/rpc/CMakeLists.txt
rpc_daemon was not declared whatsoever.
These includes should point to rpc instead.
> rpc_private_headers declaration fix

- tests/unit_tests/block_reward.cpp
Tests running after being compiled with `make debug-test` failed with
```
[  FAILED  ] block_reward_and_current_block_weight.fails_on_huge_median_size
[  FAILED  ] block_reward_and_current_block_weight.fails_on_huge_block_weight
```
With the introduction of the patch in https://github.com/monero-project/monero/commit/be82c40703d267184ee07bf7be71002122c86656#diff-1a57d4e6013984c420da98d1adde0eafL113 the assertions checking the weight of the median and current block against a size limit were removed. Since the limit is now enforced by a long divisor and a uint64_t type, checking in a separate test makes little sense, so they are removed here.
> Unit Tests: Remove block reward upper bound size checks

- src/rpc/core_rpc_server.cpp
Bugfix for next_seed_height in getblocktemplate rpc
> core_rpc_server: getblocktemplate - fix next_seed_height

- src/cryptonote_core/cryptonote_core.h
FreeBSD clang version 8.0.1 complains a lot about these couple of lines, since they are #included all over the place.
With this change, a clean build succeeds with only one warning, something in gtest.h
> cryptonote_core: Fix missing override warnings

- CMakeLists.txt
- src/CMakeLists.txt
- src/blocks/CMakeLists.txt
- tests/CMakeLists.txt
- tests/block_weight/CMakeLists.txt
- tests/core_proxy/CMakeLists.txt
- tests/core_tests/CMakeLists.txt
- tests/crypto/CMakeLists.txt
- tests/daemon_tests/CMakeLists.txt
- tests/difficulty/CMakeLists.txt
- tests/functional_tests/CMakeLists.txt
- tests/fuzz/CMakeLists.txt
- tests/hash/CMakeLists.txt
- tests/libwallet_api_tests/CMakeLists.txt
- tests/net_load_tests/CMakeLists.txt
- tests/performance_tests/CMakeLists.txt
- tests/trezor/CMakeLists.txt
- tests/unit_tests/CMakeLists.txt
Fortunately Monero was quite prepared for the change, that I wanted to make, so it went smoothly. I have reused the functions:
- monero_add_executable
- monero_add_library_with_deps
to inject a new function: monero_add_target_no_relink,  and switched many (about 20) targets to use the above two functions.
Also added monero_add_minimal_executable, mostly for tests, since they don't need monero_add_executable and haven't even got its definition.
From now on, for shared library builds, by default the relinkage won't be needed for targets, whose dependent dynamic libraries have been relinked, without having their interface changed. This is perfect for TDD, where you write the unit test first, and only modify the production code, recompiling it quite often.
The behavior can be disabled by …
> Add RELINK_TARGETS and monero_add_target_no_relink 

- src/rpc/core_rpc_server.cpp
It will now try to both forward a tx to bootstrap daemon AND broadcast it through P2P.
Apparently sending through P2P is not that reliable at the moment due to "asshole peers".
> rpc: on_send_raw_tx (bootstrap) - send to bootstrap daemon and P2P

- src/cryptonote_protocol/levin_notify.cpp
- tests/unit_tests/levin.cpp
The paper doesn't state what to do this in situation. This is going to be useful with a couple of the checks for "bad" peers or syncing peers.
> Switch to Dandelion++ fluff mode if no out connections for stem mode

- contrib/epee/include/net/net_parse_helpers.h
fixes massive amounts of time spent on pathological inputs
Found by OSS-Fuzz
> epee: tighten the URL parsing regexp a little

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
Currently, the txpool DB is only checked every 2 minutes for relayable transactions. This causes longer than expected delays for Dandelion++ embargo timeouts, and forwarded transactions (from I2P/Tor). This changes the code so that the `cryptonore_core::core::on_idle()` function always checks the txpool (currently once a second). The txpool now has an atomic value for skipping all locking and DB reads until a specific amount of time has past.
This currently does **not** change the DB check time if a transaction transitions from stem to fluff (i.e. not blackholed), so there is some slight inefficiency on the locking and DB reads. Changing this would be a little more complex, and should be less important since a node is only doing a subset of total transactions via stem/i2p/tor.
> Fix timeout checks for forwarded and Dandelion++ stem txes

- src/blockchain_utilities/blockchain_export.cpp
- src/blockchain_utilities/blockchain_import.cpp
- src/blockchain_utilities/bootstrap_file.cpp
- src/blockchain_utilities/bootstrap_file.h
And make import honor the starting block# recorded in a bootstrap file.
The fields have always been present in the bootstrap file header, but ignored until now.
> Allow setting start block on export

- src/cryptonote_protocol/levin_notify.cpp
Found this via audit. If an exception is thrown in the flush txes callback (txes are now randomly delayed per-connection based on Dandelion++ recommendations), the state was _not_ reset possibly preventing another callback from being queued. This is related to catching all-exceptions and continuing. There was also a small possibility of multiple queued callbacks, thus the reference count (another thread queues the callback for dispatching while prepping another callback). Async is fun.
Unfortunately I do not believe this to be source of the reported issues, because the exceptions in the callback should be uncommon and the descriptions don't quite match.
> Fix tx flush callback queueing

- src/cryptonote_config.h
- src/cryptonote_core/tx_pool.cpp
A 20% fluff probability increases the precision of a spy connected to every node by 10% on average, compared to a network using 0% fluff probability. The current value (10% fluff) should increase precision by ~5% compared to baseline.
This decreases the expected stem length from 10 to 5. The embargo timeout was therefore lowered to 39s; the fifth node in a stem is expected to have a 90% chance of being the first to timeout, which is the same probability we currently have with an expected stem length of 10 nodes.
----
Not mentioned in commit message : transactions should be "blackholed" less frequently due to the shorter expected stem length. This is also the highest fluff probability recommended in the Dandelion++ paper.
> Change Dandelion++ fluff probability to 20%, and embargo timeout to 39s

- src/wallet/wallet2.cpp
Due to outdated nodes still running the old Dandelion++ parameter (and the bug fixed in #7021) it can take up to
```
(173 * 3 / 2 + 120 + 120) = 499.5 seconds
```
before a transaction ends up in the public mempool. I added half a second for network latency.
After the v15 hardfork every node will run the same Dandelion++ parameters so we can set it back to the current value.
> wallet2: set propagation timeout to current max timeout

- src/p2p/net_node.h
- src/p2p/net_node.inl
This is for [issue 7004](https://github.com/monero-project/monero/issues/7004). The changes the `peer_id` system to be used for IP p2p connections only, and not for I2P/Tor. The fallout:
* Misconfigurations with `--anonymous-inbound` can result in I2P/Tor self-connections.
* I2P/Tor could make an outbound connection when an inbound connection to the same node already exists.
The second bullet-point must be an accepted downside, because you cannot have privacy and tracking at the same time.
I decided against a per-connection `peer_id` because it still be used to identify users if an aggressive spy appeared. Take the `peer_id` received from a peer, and try to make some connections to `.i2p` and `.onion` addresses to see which one rejected the connection. This attack cannot be completely …
> Do not use peer_id tracking method over i2p/tor

- contrib/epee/include/byte_stream.h
- contrib/epee/src/byte_stream.cpp
- tests/unit_tests/epee_utils.cpp
This changes the allocation strategy of `byte_stream` to something closer to other libraries - the buffer capacity is doubled at minimum each time more space is needed. This lowers the number of calls needed to grow the buffer size while serializing data.
There is another patch incoming that allows for the buffer to be `realloc`ed smaller when serialization is completed.
> Change to more efficient allocation strategy in byte_stream

- contrib/epee/include/net/abstract_http_client.h
- contrib/epee/include/net/http_client.h
- contrib/epee/include/net/http_server_handlers_map2.h
- contrib/epee/include/net/levin_base.h
- contrib/epee/include/net/levin_protocol_handler_async.h
- contrib/epee/include/net/net_helper.h
- contrib/epee/include/storages/http_abstract_invoke.h
- contrib/epee/include/storages/levin_abstract_invoke2.h
- contrib/epee/include/storages/portable_storage.h
- contrib/epee/include/storages/portable_storage_template_helper.h
- contrib/epee/src/CMakeLists.txt
- contrib/epee/src/portable_storage.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/cryptonote_protocol/levin_notify.cpp
- src/wallet/wallet2.cpp
- tests/fuzz/http-client.cpp
- tests/fuzz/levin.cpp
- tests/net_load_tests/net_load_tests.h
- tests/unit_tests/epee_levin_protocol_handler_async.cpp
- tests/unit_tests/levin.cpp
- tests/unit_tests/net.cpp
- tests/unit_tests/test_protocol_pack.cpp
The primary motivation for this patch is to remove the internal copy in `std::stringstream::str()` and switch to a `realloc` call for buffer increases. The former is not possible until C++20, and the latter is not possible (yet) with the allocator design of `std::stringstream`. Construction of the object is also faster, and `write` calls have less overhead (no polymorphism or `sentry` objects). In some cases there's still a copy, but these can hopefully be cleaned up in future edits.
Taking glibc as an example - allocation requests over 128KiB are directly `mmap`ed via the kernel. Increasing this memory chunk with `realloc` can be done via `mremap` (on Linux and some BSDs), which either extends the virtual memory space or shuffles around the page table without copying the memory. This …
> Change epee binary output from std::stringstream to byte_stream

- src/cryptonote_protocol/block_queue.cpp
- src/cryptonote_protocol/block_queue.h
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/rpc/core_rpc_server.cpp
- tests/unit_tests/block_queue.cpp
It would otherwise be possible for a peer to send bad blocks,
then disconnect and reconnect again, escaping bans
> protocol: drop origin IP if a block fails to verify in sync mode

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
Old format is still alloewd there, this is a two fork update
> protocol: fix asking for pruned blocks for v10

- cmake/GitVersion.cmake
It would not say "release" if we're on a previous tag
> cmake: fix "release" version string on tagged releases

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
We can actually request a chain that's further away from what we
have as we buffer more and more
> protocol: revert incoming chain height check against local chain

- contrib/epee/include/byte_stream.h
- tests/unit_tests/epee_utils.cpp
I checked, and this does not affect any current code. Only the unused "pretty print" mode for rapidjson which indents JSON uses it currently. This fix is necessary for PR #7136 .
> Fix byte_stream::put_n

- contrib/epee/include/byte_stream.h
- tests/unit_tests/epee_utils.cpp
Same as #7151 but on release branch. This shouldn't affect any release code, but the change is simple and prevents mistakes from possible future modifications to release branch.
> Fix byte_stream::put_n [0.17]

- src/simplewallet/simplewallet.cpp
When I create a cold wallet, I want to generate a bunch of subaddresses in advance and store them within easy reach. This way I always have "fresh" subaddresses at hand, even when I don't have quick access to my secret keys.
It annoyed me, that I could only generate one subaddress at a time with `monero-wallet-cli`, so I thought a `address mnew <n>` command, which generates n addresses at once, would be useful. I chose the `mnew` name in the style of FTP's `put`/`mput` commands. I'm still very new to Monero, so please let me know if I reinvented a wheel here.
A downside to my implementation is, that the addresses cannot be labeled. I'm not sure if this is a big deal; I don't care about the labels, since I don't store the wallet anyway - I only store my mnemonic.
> Add "address mnew" command for monero-wallet-cli

- src/blockchain_db/lmdb/db_lmdb.cpp
These are functions that check whether a tx is in the db, so whether
it is there or not is really not interesting, and it seems to scare
people from time to time
> db_lmdb: move spammy "not found in db" message to TRACE

- contrib/epee/include/rolling_median.h
- src/p2p/net_node.inl
- src/ringct/bulletproofs.cc
- rolling_median: tried to free uninitialized pointer in a constructor
- net_node.inl: erase-remove idiom was used incorrectly. remove_if doesn't actually remove elements, see http://cpp.sh/6fcjv
- bulletproofs.cc: call to sizeof() instead of vector.size(), luckily it only impacts performance and not code logic there
> Fixed issues found by static analysis

- src/cryptonote_config.h
- src/p2p/net_node.cpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/net_node_common.h
If enabled, pulls IPs to block on blocklist.moneropulse.*, and
blocks then for 8 days (so IPs dropping from the list will
eventually get unblocked, and DNS failures don't result in
instant clearing of the blocklist).
Enable with --enable-dns-blocklist
> Optional DNS based blocklist

- .github/workflows/depends.yml
calling `apt update` before `apt install`, so that new locations of packages can be found. Note the semicolon instead of &&, preventing minor errors in `apt update` from breaking the installation.
> apt update before installing

- src/common/util.cpp
- src/common/util.h
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
do not include blocked hosts in peer lists or public node lists by default,
warn about no https on clearnet and about untrusted peers likely being spies
> restrict public node checks a little

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
this prevents losing time of "idle time" for a peer, which could
otherwise be reset by another timed sync command from the peer
> protocol: don't reset last request time on an idle timer

- contrib/epee/include/storages/portable_storage_from_bin.h
Duplicate keys are no longer silently ignored. The default output/serializer never generates duplicate keys. Unit tests passed locally (several tests use this code).
Eventually I'll add a test specific for this. Looking for responses, etc.
> Restrict duplicate keys in epee binary format [0.17]

- src/cryptonote_core/blockchain.cpp
it is accessed both when adding and when prevalidating a set
of new hashes from a peer
> blockchain: lock access to m_blocks_hash_of_hashes

- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/p2p/net_node.inl
Both drop_connection and add_host_fail can drop the connection,
which invalidates the context, and thus the address it contains.
Thanks to wfaressuissia[m] for lots of help and prodding when
debugging this
> fix accessing an network address in a deleted context

- contrib/epee/include/storages/portable_storage_from_bin.h
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/epee_serialization.cpp
Same as #7251 but on master + plus tests.
> Restrict duplicate keys in epee binary format

- contrib/epee/include/storages/portable_storage_from_bin.h
They require at least 24 bytes
> epee: also limit number of strings in portable_storage

- utils/health/valgrind-tests.sh
The new tool (utils/health/valgrind-tests.sh) is able to run Valgrind checks (cachegrind, callgrind and memcheck) on a list of executables (and their arguments) provided line-by-line via a text file, being the parameter of the script.
The *.out files can be analyzed with the kcachegrind tool.
I have minimized all of the repetitions. This was somewhat harder than expected, because the memcheck tool has a bit different interface than the other tools.
Below are the reports generated for the unit_tests executable:
[Valgrind reports for unit tests](https://github.com/monero-project/monero/files/5483682/valgrind-output.zip)
Summary:
- there were no memory leaks (!) (however, this doesn't mean, that an ever extending vector can't consume all the memory, before the daemon is closed)
- there's an …
> Run Valgrind checks for any binary in a list mj-xmr

- utils/health/README.md
- utils/health/clang-include-what-you-use-run.sh
Run with utils/health/clang-include-what-you-use-run.sh
include-what-you-use analyses the header file hierarchy and delivers hints on how to reduce their complexity.
Within this branch, I figured out how to ignore errors of the linting tools, and used this trick in the clang-tidy branch, which shares the same problem. It's the -k option for make.
This concludes the set of tools, that I find crucial to begin a targeted compilation time reduction. I'm now able to perform the changes in the code. Once all my tools (scripts) are merged, in parallel I will be creating the promised HTML summary report, with all the sub-reports accessible for every developer.
The report generation crashed at 59%, even with the -k option. I think, that the info it provided it already useful. …
> Clang IWYU header checker script

- src/rpc/core_rpc_server.cpp
since it only makes sense when syncing, and it confuses people
> rpc: report target height as 0 when synced

- src/daemon/rpc_command_executor.cpp
I could never remember what exactly all the columns in `sync_info` were, so I added a header row to the banner.
There it is, the most trivial PR you'll see all day.
Happy New Year!
> Header row for peer list in sync_info

- src/p2p/net_node.cpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
Helps daemons behind a proxy get more than one connection.
Defaults to 1 (no change)
> p2p: add --max-connections-per-ip daemon option

- Doxyfile
The changes are the following:
- create subdirs: As the Doxy docs say, putting everything into one directory might create performance problems, and with such an amount of data, it does create these problems on my machine. After the change, the user notices no drawbacks.
- scan whole repo: This allows for including the contrib directories, which add a reasonable amount of dependencies. I need it for my purposes for sure, while you might not, if you just want to distribute Monero's source documentation. However, notice, that by including the **src** dir only, you omit the **include** directory of Monero, which is equally important (or will be in the future)
- don't generate LaTeX: arguable, but if nobody needs it, and the HTML report is what we care about, then LaTeX generation is just a …
> Doxy - scan whole repo, create subdirs, don't generate LaTeX - mj-xmr

- contrib/epee/include/misc_language.h
- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/storages/portable_storage.h
- contrib/epee/include/storages/portable_storage_base.h
- contrib/epee/include/storages/portable_storage_from_json.h
- contrib/epee/include/storages/portable_storage_template_helper.h
- contrib/epee/include/storages/portable_storage_to_bin.h
- contrib/epee/include/storages/portable_storage_val_converters.h
- contrib/epee/src/CMakeLists.txt
- contrib/epee/src/misc_language.cpp
- contrib/epee/src/portable_storage.cpp
- src/wallet/node_rpc_proxy.cpp
- src/wallet/node_rpc_proxy.h
- tests/unit_tests/epee_serialization.cpp
I have touched here the header, that cumulatively was taking the longest time, as reported by ClangBuildAnalyser.
The change involves mainly moving inline functions into .cpp files, so that their dependencies can be hidden within.
portable_storage.h now
portable_storage.h now (outdated - see review):
portable_storage.h before:
Speed improvements:
| Prevous   |      Current      |
|----------|-------------|
|Compilation (798 times): |  Compilation (802 times): |
| Parsing (frontend):         1728.2 s |     Parsing (frontend):         1488.6 s   | 
| Codegen & opts (backend):   1739.0 s | Codegen & opts (backend):   1587.8  |
| 168138 ms: portable_storage.h (included 82 times, avg 2050 ms) | 136062 ms: portable_storage.h (included 83 times, avg 1639 ms) |
Reduction by 14 or by 19%, …
> Reduce compilation time of epee/portable_storage.h

- src/p2p/net_node.inl
> p2p: ignore empty IP from DNS block list

- src/mnemonics/language_base.h
Prevents those unnecessary 30+ log lines about 3-letter seed words for Spanish that are too short because prefix length for Spanish is 4 in general, e.g. when using `monero-wallet-rpc` and creating a new wallet: If a language sets the flag `ALLOW_SHORT_WORDS` this is not worth a warning.
> Only INFO log for short seed words with ALLOW_SHORT_WORDS active

- src/p2p/net_node.inl
- src/p2p/p2p_protocol_defs.h
removes a back and forth on connect, and the RPC can be removed
once all peers have updated
> p2p: make REQUEST_SUPPORT_FLAGS optional, pass flags in node data

- ANONYMITY_NETWORKS.md
According to IRC, seed nodes now exist for both Tor and I2P, but the doc still says otherwise.
> docs: Remove outdated bits about anonymity network seed nodes

- src/wallet/wallet_rpc_server.cpp
Resolves https://github.com/monero-project/monero/issues/7227
> wallet_rpc_server: don't abort on initial refresh failure

- CMakeLists.txt
Even tested GCC 10.2, Windows binaries still die on startup with PIE enabled.
> build: omit '-pie' linker flag in native non static WIN32 GCC builds 

- .github/workflows/build.yml
For MacOSX the right directory of ccache for storing and restoring is:
`/Users/runner/Library/Caches/ccache`
In the current setup, the directory ~/.ccache does Not default to the above directory.
> [CI] Fix MacOSX ccache by caching the right directory

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
> monero-wallet-cli: Added comman scan_tx

- src/wallet/wallet2.cpp
If more outputs are requested, they are split across
multiple transactions. This splitting is the same as is
done for transactions that are too large.
Fixes: #7322
> Stop adding more outputs than bulletproof allows

- Dockerfile
https://github.com/monero-project/monero/pull/7100#issuecomment-744709797
> Dockerfile: bump openssl version to 1.1.1i

- src/blockchain_db/blockchain_db.cpp
- src/blockchain_utilities/blockchain_ancestry.cpp
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_server.cpp
- tests/core_tests/tx_pool.cpp
- tests/unit_tests/net.cpp
Clang warns about a number of unexpected copies in for loops. This removes those copies, along with one other simple namespace cleanup.
> Basic cleanup

- tests/functional_tests/mining.py
The mining test fails quite often, due to RandomX taking more time to initialize, than the fixed timeout was set to. I increased it by 4 times for now.
The reason for this problem could be an abnormal stress on the CI machines from our and not only our project, while the RandomX is being initialized.
I have reproduced the problem by setting the timeout artificially to 1, and I got the same error message as we typically get.
In a possible future PR I will check, if I can obtain any feedback from the RX itself.
Active work time: ~0.5h
> Increase timeout for the mining test 4 times (to 240s)

- .github/workflows/build.yml
Tested using a repeated build, as well as an additional build, where one source file was intentionally changed to fail. The reaction was correct - all OSes, including Windows, failed.
Based on @selsta 's [input](https://github.com/monero-project/monero/compare/02eec3513e82aa9dd55b874c598bb27f1d8184c7..12a422c0935d19915c143114d682b3208f6edf8d).
Work time: ~ 1.7h
> [CI] Add ccache to Windows build

- CMakeLists.txt
The cmake executable name can vary across platforms.
> cmake: Use CMAKE_COMMAND.

- src/device_trezor/device_trezor_base.cpp
- src/device_trezor/device_trezor_base.hpp
ping @ph4r05
This would be a replacement for #7306 and #7330.
From IRC:
```
7330 or unmodified code isn't consistent with library api
1. it's expected be heap allocated memory
2. release_field_name returns string pointer that must be freed by caller in general
3. memwipe should be called before release_field_name in general
but it's better to replace that with set_allocated_field_name(new std::string(...)) and use mutable_field_name in order to wipe it after
```
> device_trezor: wipe string fields, add check

- contrib/epee/include/net/http_server_handlers_map2.h
It's better than 404 (Not found)
> epee: return HTTP error 400 (Bad request) on deserialization error

- contrib/epee/include/byte_slice.h
- contrib/epee/src/byte_slice.cpp
- tests/unit_tests/epee_utils.cpp
This allows for the optional shrinkage of the `byte_stream` buffer when converting to an immutable `byte_slice`. This uses `realloc` so in the bulk of calls this can be done without a copy. Larger buffers are likely to be "overcommited" by OSes anyway, so it frequently could be a NOP. Its still beneficial given that Monero supports 32-bit builds, where the address space reclamation can be beneficial.
> Allow byte_stream->byte_slice conversion to shrink unused buffer space

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/net_ssl.h
- contrib/epee/src/net_ssl.cpp
- src/rpc/core_rpc_server.cpp
`monerod` creates a new SSL certificate for RPC each run if the user does not provide a custom certificate. This stores the SSL key/cert in the data directory so that it can be re-used across runs. A user provided key always take precedence.
This will allow clients to perform some authentication - I am updating `wallet2` to store SSL fingerprints per host, and notify the user if the certificate changed since first use. A [working prototype for DANE/TLSA](https://github.com/vtnerd/monero/tree/improve/dane_tlsa) in the wallet also exists, which restricts the attack fingerprint of trust-on-first-use to the DNSSEC chain. This is imperfect, but an improvement over users using default settings with arbitrary RPC servers which has no authentication currently. Only DNSSEC is required, no paid …
> Store RPC SSL key/cert for consistent authentication between runs

- contrib/epee/include/serialization/keyvalue_serialization.h
This compiler warning occurs way too often and pollutes the view.
```
/tmp/monero/monero/src/rpc/instanciations.cpp:36:37:   required from here
/tmp/monero/monero/contrib/epee/include/serialization/keyvalue_serialization.h:76:22: warning: unused variable ‘this_ref’ [-Wunused-variable]
76 |     decltype(*this) &this_ref = *this;
|                      ^~~~~~~~
```
> Fix compiler warning for in keyvalue_serialization.h

- contrib/epee/src/CMakeLists.txt
This change allows the epee headers to be searched for easily via IDEs. Additionally, the IDEs will automatically save the changed headers, when compile command is issued.
> Epee: add headers to project files (via glob)

- README.md
use syntax highlighting on commands and command line arguments
> documentation: Make pruning section more consistent in README.md

- src/device_trezor/trezor/protocol.cpp
Now it is possible to simplify integrated addresses recognition using transaction destination info directly
Fixes https://github.com/monero-project/monero-gui/issues/3346 and wallet-api usages @dEBRUYNE-1
> trezor: simplify recognition of integrated addresses, fixes monero-gui

- src/rpc/core_rpc_server.cpp
When both of those options are set, OpenSSL call fails stopping the daemon from launching.
> Fix monerod --rpc-ssl disabled and --non-interactive combo

- src/common/dns_utils.cpp
- src/common/dns_utils.h
- src/net/CMakeLists.txt
- src/net/error.cpp
- src/net/resolve.cpp
- src/net/resolve.h
This adds a function to retrieve IPv4 or IPv6 records, along with TLSA records if the domain has DNSSEC enabled. These functions are unused in this patch. They will potentially be used by p2p encryption (#7078 ) to DNS seed nodes (wth TLS or noise encryption), or by `wallet2` SSL autodetect mode. If both features are rejected by the community, this PR will be closed or reverted.
This has been tested by SSL autodetect mode with the wallet. The associated OpenSSL code is not in this patch.
EDIT: From the OpenSSL description on DANE/TLSA, which helps explain:
> It is expected that the majority of clients employing DANE TLS will be doing "opportunistic DANE TLS" in the sense of RFC7672 and RFC7435. That is, they will use DANE authentication when DNSSEC-validated TLSA records are published for …
> Add TLSA support to DNSSEC fetching

- src/daemon/command_parser_executor.cpp
- src/daemon/command_server.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/bootstrap_daemon.cpp
- src/rpc/bootstrap_daemon.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
Daemon command
`set_bootstrap_daemon (auto | none | host[:port] [username] [password]) [proxy_ip:proxy_port]"`
CLI switch
`--bootstrap-daemon-proxy` - `<ip>:<port> socks proxy to use for bootstrap daemon connections`
RPC
`/set_bootstrap_daemon` - added `proxy` field
> bootstrap_daemon: proxy configuration support

- tests/functional_tests/CMakeLists.txt
It turned out, that the test part of CI was using Python2 all the time. Upgrading to Python3 brings compatibility, as well as runtime speed benefits.
> [CI] Use Python3 for funcional tests, instead of Python2

- src/crypto/rx-slow-hash.c
Flag in MONERO_RANDOMX_UMASK was being ignored, leaving no way to disable use of large pages.
> Honor LARGE_PAGES flag in randomx umask

- README.md
Inspired by @cabelo in https://github.com/monero-project/monero/pull/7476, I replaced the `libboost-all-dev` with only the required Boost libraries. This information will help in minimizing the dependency list for Monero's package maintainers.
I also moved the optional tools: `doxygen & graphviz` to the end of the list.
PS. I tested the list on a freshly installed VM.
> Doc: add only the required boost libraries instead of all of them

- external/db_drivers/liblmdb/mdb.c
mdb_load -a patch broke overwriting with MDB_CURRENT
> ITS#9500 fix regression from ITS#8662

- external/db_drivers/liblmdb/mdb.c
mdb_load -a patch broke overwriting with MDB_CURRENT
> ITS#9500 fix regression from ITS#8662 [release-v0.17]

- CMakeLists.txt
Under OpenBSD/amd64 6.8, with its boost package, the `-march=native` option causes a compile failure in any file that includes `boost/thread.hpp`. The same is true for `-march=<any other x86-64 platform>`.
Under OpenBSD/arm64 6.8, the `-march=native` flag isn't even supported. This fact is detected, and the flag is already not used by default, so this change has no effect there.
The compilation error can be reproduced as follows:
```
$ echo '#include <boost/thread.hpp>' | c++ -I/usr/local/include -x c++ - -march=westmere
In file included from <stdin>:1:
In file included from /usr/local/include/boost/thread.hpp:17:
In file included from /usr/local/include/boost/thread/once.hpp:26:
In file included from /usr/local/include/boost/thread/pthread/once_atomic.hpp:20:
In file included from …
```
> cmake: Don't default to -march=native on OpenBSD

- CMakeLists.txt
Fixes https://github.com/monero-project/monero/issues/7392
The use case for this change is ARM Mac (i.e. the "M1" SoC)
Both x86_64 Mac builds (real and `depends`) compile fine.
@selsta : Would you be so kind and run a short test on your Mac with this change?
> Mac: Enable on ARM, by not enforcing x86_64

- contrib/epee/include/misc_log_ex.h
- external/easylogging++/easylogging++.cc
- external/easylogging++/easylogging++.h
This small patch reduces `monerod` by ~3.1%, `monero-wallet-rpc` by ~2.8%, and `monero-wallet-cli` by ~2.4%. This numbers are from a static build with gcc 9.3.
This is a bit of micro-optimization, but this will help the CPU instruction cache slightly. Every call to log a message : (1) calls a function to get a global pointer, (2) constructs a `std::string`, (3) dereferences a pointer, (4) sets 3 register values for a function call. This moves steps (1), (2), and (3) to a single instance in another cpp file and reduces the number of register values needed to 2.
This also moves the "quick check" variable to static memory and delays `std::string` construction, which shortens the number of instructions executed to do the quick check. Since an overwhelming majority of calls "fails" this quick …
> Reduced executable size; reduced call sequence to "allowed" log function

- .github/workflows/build.yml
- tests/README.md
- tests/functional_tests/CMakeLists.txt
- tests/functional_tests/cpu_power_test.cpp
- tests/functional_tests/mining.py
- tests/functional_tests/util_resources.py
A more serious approach to determining the appropriate timeout for the mining test in `functional_tests_rpc`. The timeouts are calculated separately for RX init and for the mining of subsequent blocks themselves. Printing also available RAM, in case the RX init went wrong, which needs above 3 GB of RAM. Added comprehensive description.
As per the discussion with @iamamyth in https://github.com/monero-project/monero/pull/7371 , the adjustment is done by testing the time of generation of N next digits of Pi - once for a single core (mining use case) and once for as many cores as there are available (RX init). This test helps orientating in the currently available CPU processing power, even in the event of:
- other jobs taking up the virtual resources at the same time
- `ctest` being ran in …
> [CI] Adaptive mining timeout, depending on available CPU power

- src/cryptonote_core/cryptonote_tx_utils.h
- src/serialization/binary_archive.h
- src/serialization/container.h
- src/serialization/json_archive.h
- src/serialization/pair.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- tests/fuzz/cold-outputs.cpp
On Mac, size_t is a distinct type from uint64_t, and some
types (in wallet cache as well as cold/hot wallet transfer
data) use pairs/containers with size_t as fields. Mac would
save those as full size, while other platforms would save
them as varints. Might apply to other platforms where the
types are distinct.
There's a nasty hack for backward compatibility, which can
go after a couple forks.
> fix serialization being different on mac

- .github/workflows/build.yml
Result:
Typical run of the ubuntu-test lasts 2 hours. With ccache, the time is reduced down to 1:25 h, so by about 25%.
The reason why ccache was not enabled for test-ubuntu job, was that the compiled binaries for the (by default) native architecture, could be making use of registers (like AXV2) not available at a different host, where the test execution happens on the next run of the Action (as per recent IRC discussion with @selsta ).
The solution for this problem is using the generic build, achievable in Monero by setting the CMake variable ARCH to "default". In order not to interfere with the already existing Makefile target, designed for testing, the `release-test`, I have created an additional, new target, made specifically for CI, called `release-test-ci`, as suggested by @vtnerd …
> CI: ccache for ubuntu-test

- tests/unit_tests/levin.cpp
Just a small reduction of warning count. GCC was complaining about missing braces.
> Warnings: fix ut/levin.cpp missing braces

- tests/unit_tests/node_server.cpp
Fixes https://github.com/monero-project/monero/issues/7645
The test was crashing on Github with ~10% probability.
The fix and the comment block has been written by `wfaressuissia`. I only reported the problem and provided steps to reproduce, as well as confirmed each other's local experiments.
See the added comment block for an in-depth description.
> Tests: Fix test node_server.bind_same_p2p_port from randomly crashing

- tests/unit_tests/node_server.cpp
Fixes https://github.com/monero-project/monero/issues/7645
The test was crashing on Github with ~10% probability.
The fix and the comment block has been written by `wfaressuissia`. I only reported the problem and provided steps to reproduce, as well as confirmed each other's local experiments.
See the added comment block for an in-depth description.
> Tests: Fix test node_server.bind_same_p2p_port from randomly crashing v0.17

- contrib/epee/include/file_io_utils.h
- contrib/epee/include/storages/portable_storage_template_helper.h
- contrib/epee/src/CMakeLists.txt
- contrib/epee/src/file_io_utils.cpp
- src/blockchain_utilities/blockchain_ancestry.cpp
- src/blockchain_utilities/blockchain_blackball.cpp
- src/blockchain_utilities/blockchain_depth.cpp
- src/blockchain_utilities/blockchain_prune.cpp
- src/blockchain_utilities/blockchain_prune_known_spent_data.cpp
- src/blockchain_utilities/blockchain_stats.cpp
- src/blockchain_utilities/blockchain_usage.cpp
- src/checkpoints/checkpoints.cpp
- src/common/i18n.cpp
- src/cryptonote_basic/miner.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/daemon/command_parser_executor.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/rpc_payment.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/api/pending_transaction.cpp
- src/wallet/api/wallet.cpp
- src/wallet/message_store.cpp
The header consists of:
- parserse_base_utils.h: This will be reduced in an another PR. For now it would create too many conflicts 
- portable_storage.h: has to stay here
- file_io_utils.h: this is the one, where I could make meaningful changes for now, by encapsulating boost::filesystem and boost::system
Speed improvements:
| Prevous   |      Current      |
|----------|-------------|
|Compilation (798 times): |  Compilation (802 times): |
| Parsing (frontend):         1728.2 s |     Parsing (frontend):         1660.9 s   | 
| Codegen & opts (backend):   1739.0 s | Codegen & opts (backend):   1670.6  |
| 155623 ms: portable_storage_template_helper.h (included 79 times, avg 1969 ms) | 143785 ms: portable_storage_template_helper.h (included 79 times, avg 1820 ms) |
Reduction rate of 4% …
> Reduce compilation time of epee/portable_storage_template_helper.h

- contrib/epee/include/net/levin_base.h
- contrib/epee/include/net/levin_protocol_handler_async.h
- contrib/epee/include/storages/levin_abstract_invoke2.h
- contrib/epee/include/storages/portable_storage.h
- contrib/epee/include/storages/portable_storage_template_helper.h
- contrib/epee/src/levin_base.cpp
- contrib/epee/src/portable_storage.cpp
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/cryptonote_protocol/cryptonote_protocol_handler_common.h
- src/cryptonote_protocol/levin_notify.cpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/p2p/net_node_common.h
- tests/fuzz/levin.cpp
- tests/net_load_tests/net_load_tests.h
- tests/unit_tests/epee_boosted_tcp_server.cpp
- tests/unit_tests/epee_levin_protocol_handler_async.cpp
- tests/unit_tests/levin.cpp
This removes a copy of the payload in all outgoing p2p messages. The biggest impact is on requests for recent blocks - the entire p2p response will typically exceed the cpu cache which has an impact on the copy performance. Combined with other changes, modern GNU/glibc can go from DOM->bytes with zero copies (other than initial write), even if the buffer needs to be resized (kernel performs page table shuffling in worse case).
This also has an additional optimization for block notifications. The entire notification is generated once, and then ref-counted into the outgoing buffer queue for each connection.
If an encryption scheme is (eventually) used for p2p, another copy would be required (encrypted payload). However, the encryption will likely occur after the entire message is generated, …
> Remove payload copy in all outgoing p2p messages

- src/p2p/net_node.inl
Integer quantization biased the picks a lot (leading some indices
to never be selected)
> p2p: fix cubic selection in filtered peer list

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_error_codes.h
Some RPC return an error string in status, and the code must return
true on error (with a status string).
> rpc: fix some error return codes/status

- README.md
One needs the base Monero donation address to be able to restore the Monero Core Team donation wallet from address and viewkey. Address provided by selsta.
> Add base Monero address which is needed to view wallet

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
Required for monero-project/monero-gui#3378
It's helpful to be able to set offline mode like in the CLI
> expose set_offline to wallet api

- contrib/gitian/README.md
> Doc: Update Gitian (Reproducible Builds) with scripts and small fixes

- .github/workflows/build.yml
Simply arranged all the Linux builds' repetitions into variables.
> CI: Actions' build.yaml uses variables instead of repetitions

- CMakeLists.txt
- contrib/epee/src/CMakeLists.txt
I have extracted the already working solution of globbing the headers from `Epee` and put it into the macro `monero_find_all_headers`  in the main `CMakeLists.txt`. This will allow this feature to be reused even in unmaintained external repositories. I have also noticed, that there are numerous headers under the src, that are not being manually included by the according `CMakeLists.txt`. Integrating this macro will ease the maintenance burden of finding the missing headers and adding the new ones in the future. This automation also doesn't really do any harm, since headers (also those with an incorrect syntax) are only taken into account by the compiler, if they are being included by a C/CPP file.
> CMake: new macro - finding all headers (extract from epee)

- docs/COMPILING_DEBUGGING_TESTING.md
see `docs/COMPILING_DEBUGGING_TESTING.md`
New piece of documentation, which goes beyond `make && make install`, namely customizing the compilation commands and debugging in IDEs.
It will be extended once other branches are merged (listed at the bottom to show what's about to come).
> Doc: Compiling, debugging and testing efficiently

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Currently, the `rescan_bc keep_ki` command silently fails. The assertion in `hash_m_transfers()` is incorrectly inverted, and always fails on the first call, when literal `-1` is passed. This exception isn't handled properly, so no message is shown.
This function also incorrectly treated some integer members of `struct transfer_details` as pointers, causing memory errors.
With these fixed, this command seems to provide at least a good workaround for  #7673.
> [release-0.17] wallet2: Fix rescan_bc keep_ki option

- src/wallet/wallet2.cpp
The current value is, for whatever reason, off by roughly 40,000 blocks now. This plays a role when creating testnet wallets with the GUI wallet as that app asks for an estimate of current testnet blockchain height before connecting to any daemon and this way currently produces testnet wallets with restore height in the future, basically creating them broken.
> Wallet2: Update 'approximate_testnet_rolled_back_blocks'

- tests/functional_tests/functional_tests_rpc.py
- tests/functional_tests/mining.py
- tests/functional_tests/util_resources.py
4 changes:
- the path of the app doing cpu power measurements was adapted to enable local tests.
- measurements may be disabled with `MINING_NO_MEASUREMENT` env var. Then timeouts large enough are chosen. The use case are low end machines, where you know, that you're not modifying the mining code at a given time, but want to run other mining tests anyway.
- the mining logging may be disabled with `MINING_SILENT` env var.
- unified the build directory in `functional_tests_rpc.py` based on the existing pattern.
> Tests: mining cpu power app's path fix; Disabling measurements on demand

- contrib/epee/src/byte_slice.cpp
- src/serialization/json_object.h
- tests/unit_tests/json_serialization.cpp
```
/Users/selsta/dev/monero/contrib/epee/src/byte_slice.cpp:154:21: warning: loop variable 'source' of type 'const epee::span<const unsigned char>' creates a copy from type 'const epee::span<const unsigned char>' [-Wrange-loop-analysis]
for (const auto source : sources)
^
/Users/selsta/dev/monero/contrib/epee/src/byte_slice.cpp:154:10: note: use reference type 'const epee::span<const unsigned char> &' to prevent copying
for (const auto source : sources)
^~~~~~~~~~~~~~~~~~~
&
```
```
/Users/selsta/dev/monero/contrib/epee/src/byte_slice.cpp:163:23: warning: loop variable 'source' of type 'const epee::span<const unsigned char>' creates a copy from type 'const epee::span<const unsigned char>' [-Wrange-loop-analysis]
for (const auto source : sources)
^ …
```
> clang: fix -Wrange-loop-analysis warnings

- tests/unit_tests/epee_boosted_tcp_server.cpp
```
/Users/selsta/dev/monero/tests/unit_tests/epee_boosted_tcp_server.cpp:323:22: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
conn = std::move(shared_conn->conn.lock());
^
/Users/selsta/dev/monero/tests/unit_tests/epee_boosted_tcp_server.cpp:323:22: note: remove std::move call here
conn = std::move(shared_conn->conn.lock());
^~~~~~~~~~                        ~
1 warning generated.
```
> clang: fix -Wpessimizing-move warning

- src/wallet/CMakeLists.txt
Co-authored-by: @perfect-daemon 
This is relevant for wallets that use wallet_merged, they have to switch to wallet_api, e.g. like https://github.com/monero-project/monero-gui/pull/3448
> cmake: wallet_api doesn't need wallet_merged

- translations/CMakeLists.txt
Required for some IDEs (e.g. Xcode)
> translations: use full path in cmake

- CMakeLists.txt
```
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
```
> clang: fix -pie flag

- src/cryptonote_core/cryptonote_tx_utils.cpp
If an element of destinations is not supposed to be used, then the chosen loop type was wrong an was leading to a compilation warning.
> Warnings: unused var at cryptonote_tx_utils.cpp

- src/cryptonote_core/blockchain.cpp
Similarly as with https://github.com/monero-project/monero/pull/7705 , the loop was chosen so, that it ends up in an unused variable warning.
> Warnings: unused variable in core/blockchain.cpp

- cmake/FindLibUSB.cmake
If we add monero as a subdirectory in the GUI it will look for `test-libusb-version.c` inside the GUI repo, which we don't want.
> cmake: use CMAKE_CURRENT_LIST_DIR in FindLibUSB

- contrib/epee/src/CMakeLists.txt
Allows us to remove the openssl dependency from GUI.
> epee: include public openssl header in cmake

- tests/core_tests/chaingen.h
The variable is sometimes being used, so in order to suppress the warning, casting it to `void` was required.
> Warnings: unused var in core_tests:chaingen.h (perr_context)

- cmake/CheckLinkerFlag.cmake
Example on Mac with `-G Xcode` and #7692 
```
-- Looking for -Wl,--no-undefined linker flag - found
```
with patch applied:
```
-- Looking for -Wl,--no-undefined linker flag - not found
```
> cmake: fix check_linker_flag

- src/device_trezor/trezor/transport.cpp
```
/Users/selsta/dev/monero/src/device_trezor/trezor/transport.cpp:160:36: warning: 'ByteSize' is deprecated: Please use ByteSizeLong() instead [-Wdeprecated-declarations]
return static_cast<size_t>(req.ByteSize());
^
/usr/local/include/google/protobuf/message_lite.h:425:3: note: 'ByteSize' has been explicitly marked deprecated here
PROTOBUF_DEPRECATED_MSG("Please use ByteSizeLong() instead")
^
/usr/local/include/google/protobuf/port_def.inc:177:53: note: expanded from macro 'PROTOBUF_DEPRECATED_MSG'
#define PROTOBUF_DEPRECATED_MSG(msg) __attribute__((deprecated(msg)))
```
> trezor: deprecated ByteSize -> ByteSizeLong

- src/wallet/CMakeLists.txt
Reusing the recently merged `monero_find_all_headers` CMake function to include the missing (read: not added manually) header file `wallet_light_rpc.h`, as well as all the others, which were already there.
> CMake: glob missing headers for wallet2

- external/easylogging++/CMakeLists.txt
`EasyLogging` was missing the header file `ea_config.h` from its IDE project file. Now it's being globed automatically.
> CMake: glob missing headers for easylogging

- CMakeLists.txt
Verified on `core_tests` and `epee`, where adding these directives extended the list of "headers" found by the IDE.
For `core_tests` the change shall be committed in a later PR.
> CMake: add *.inl to monero_find_all_headers() glob, along *.h*

- CMakeLists.txt
- contrib/epee/src/CMakeLists.txt
- src/CMakeLists.txt
For a dynamic library build the change saves 9.5% of disk space and some linkage time, especially if the epee's implementation is to be changed. More savings may come, as more epee's implementation moves from headers to cpps. Similarly when you try to do Test Driven Development, you'll have to waste cumulatively a very long time on linkage.
In order to achieve this change, I had to move the `monero_add_library` from `src/CMakeLists.txt` to the root `CMakeLists.txt`
> Epee: dynamic linkage; move monero_add_library to root CMakeLists.txt

- CMakeLists.txt
Treating such warnings as errors, that when ignored are so severe, that they can segfault or even [UB](https://en.cppreference.com/w/cpp/language/ub) any application.
- `return-type`: aborts compilation when you forget to return a value from a function, when the caller expects it (or worse: there's a unnoticed branch of a complex function, which ends without returning the expected value)
- `switch`: aborts compilation when a new case isn't handled for a newly added enum entry. With this error in place, you can safely delete all `default:` cases made for runtime safety checks and enjoy static checks instead (so less need for time consuming  tests execution, as well as writing).
> Warnings: treat warnings as errors: 'switch' & 'return-type'

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/wallet/wallet2.cpp
if the wallet does it, it would get a wrong result (possibly even
negative) if its local chain is not synced up to the daemon's yet
> rpc: send confirmations in get_transactions result

- src/cryptonote_core/blockchain.cpp
The heavy rolling median reset only has to be performed after
all blocks are popped
> blockchain: speed up repeated pops (mostly in tests)

- contrib/epee/include/span.h
- src/blockchain_utilities/blockchain_blackball.cpp
- src/cryptonote_basic/cryptonote_basic.h
- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_basic/cryptonote_format_utils.h
- src/cryptonote_basic/tx_extra.h
- src/device_trezor/trezor/protocol.hpp
- src/ringct/rctTypes.h
- src/rpc/rpc_payment.cpp
- src/serialization/binary_archive.h
- src/serialization/binary_utils.h
- src/serialization/container.h
- src/serialization/crypto.h
- src/serialization/debug_archive.h
- src/serialization/difficulty_type.h
- src/serialization/json_archive.h
- src/serialization/pair.h
- src/serialization/serialization.h
- src/serialization/string.h
- src/serialization/variant.h
- src/wallet/message_store.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_server.cpp
- tests/core_tests/chaingen.h
- tests/fuzz/bulletproof.cpp
- tests/fuzz/cold-outputs.cpp
- tests/fuzz/cold-transaction.cpp
- tests/unit_tests/serialization.cpp
- tests/unit_tests/test_tx_utils.cpp
This improves block and transaction blob/binary to C/C++ structure performance by ~60% (in some cases, see below). The changes are pretty basic, but touches 27 files in some of the most critical areas of of code. The read performance is already fairly quick, so this might be overzealous. These functions will show up in profiles at times because of the frequency of their use (basically, everytime a block or transaction needs to be "read"). As an example, responding to a p2p download request improves by a tiny ~1.6% on a Ryzen 3 CPU. 
The bulk of the gains come from dropping a copy of the payload before reading. The remainder comes from eliminating virtual methods calls and some `std::istream` stuff. There is also a difficult to measure benefit with CPU cache usage reduction.
Unpacking 100 …
> Improve cryptonote (block and tx) binary read performance

- contrib/epee/include/storages/parserse_base_utils.h
- contrib/epee/src/CMakeLists.txt
- contrib/epee/src/parserse_base_utils.cpp
This micro change made it possible to reduce the visibility of the logging class and the `<algorithm>` header down to the implementation file.
The PR is intentionally small, not to abuse the reviewers' time. But as such, there will most probably be no noticeable gains from this PR alone.
I kept the trivial calls as inline, while all longer calls are moved to the corresponding .cpp file.
> Compil time: move epee storages/parserse_base_utils.h to .cpp

- CMakeLists.txt
- src/CMakeLists.txt
`-D STRIP_TARGETS=ON` is also possible for testing the debug build when you're low on ram-disk space.
Results:
| Case | Previous   |      New      | Change |
|----------|----------|-------------|-------------|
| Release-static | 381 MB |  353 MB | -7.35% |
| Release-shared | 225 MB | 213 MB | -5.33% | 
| Debug-shared | 6213 MB | 4582 MB | -26.25% | 
Whether to make stripping the default option for the `release` target, is a separate decision.
> CMake: strip targets (optional) with -D STRIP_TARGETS=ON

- external/easylogging++/easylogging++.cc
The m_typedConfigurations pointer is copied from one object to the next,
but deleted in the dtor, leading to potential double free. It is also
deleted first thing in the copy ctor, deleting uninitialized memory.
This does not seem to actually happen in practice (those functions do
not get called), but seems safer that way.
Coverity 1446562
> easylogging++: fix potential memory corruption

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
It only needs to parse the tx headers, not the full tx data
> core: speed up print_coinbase_tx_sum

- src/blockchain_db/blockchain_db.cpp
If an invalid input type were to get to this, the code could
remove key images that might be present already in the chain,
which could allow a double spend, even if this is impossible
with the current code.
Reported by KeyboardWarrior.
> blockchain_db: harden code against invalid input types

- src/blockchain_db/lmdb/db_lmdb.cpp
Turns out at least one arch (armel based) does not have unique_path
implemented and throws
> db_lmdb: catch exceptions testing for mmap support

- src/wallet/api/address_book.cpp
- src/wallet/api/address_book.h
- src/wallet/api/pending_transaction.cpp
- src/wallet/api/pending_transaction.h
- src/wallet/api/transaction_history.cpp
- src/wallet/api/transaction_history.h
- src/wallet/api/transaction_info.cpp
- src/wallet/api/transaction_info.h
- src/wallet/api/unsigned_transaction.cpp
- src/wallet/api/unsigned_transaction.h
- src/wallet/api/utils.cpp
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/api/wallet_manager.cpp
- src/wallet/api/wallet_manager.h
It has been 5 years since we renamed it. I couldn't find any wallet that use the "Bitmonero" namespace.
Also removed trailing empty lines.
> wallet/api: remove Bitmonero namespace alias

- src/device_trezor/trezor/transport.cpp
Turns out Ubuntu 18.04 ships with an old protobuf version.
> trezor: add #if for ByteSizeLong

- src/wallet/wallet2.cpp
RPC pay client ID is sent with each RPC request, set a new secret every time we switch nodes to mitigate trivial correlation.
> wallet: Reset RPC Pay ID on node switch

- src/device/device_ledger.cpp
This is needed to speed up synchronization by 6-7x, but requires another patch in wallet2.cpp that I will submit after I've checked that it doesn't break Trezor.
> ledger: don't lock for software device

- contrib/depends/Makefile
- contrib/depends/funcs.mk
- contrib/depends/packages/eudev.mk
- contrib/depends/packages/gtest.mk
- contrib/depends/packages/native_cctools.mk
~~Package archives are not uploaded yet to https://downloads.getmonero.org/depends-sources~~ done
I attempted to edit `fetch_file` so that `$(package)_file_name` is always used for the fallback download.
> depends: add getmonero package mirror

- .github/workflows/build.yml
A follow up of https://github.com/monero-project/monero/pull/7768 , where it was decided, that Ubuntu 18.04 shall be tested, but is a separate use case than Boost matrix use case. The Ubuntu 18.04 use case thus doesn't need the Boost matrix, and can be built with the default options.
Temp. info: This draft PR contains a commit to be reverted, taken from https://github.com/monero-project/monero/pull/7762 , which has to be merged first. Afterwards this PR will be published and rebased. The specific to-be-reverted commit helps to check if the both the fix and the verification method work.
> CI: ubuntu 18.04 backward compat. test

- tests/unit_tests/logging.cpp
Fixes https://github.com/monero-project/monero/issues/7756
Updates https://github.com/monero-project/monero/pull/7380 with the patch: https://github.com/monero-project/monero/pull/7380#issuecomment-788222115 since the PR got merged.
The patch contained 4 new UTests for EasyLogging++. 2 of them work correctly only after merging https://github.com/monero-project/monero/pull/7380 while the other 2 still await for the implementation to be improved.
[EDIT]
The 2 unresolved issues are now exported as a patch. See below https://github.com/monero-project/monero/pull/7771#issuecomment-874458351.
> EasyLogging++: Add UTests, that protect against regressions

- src/blockchain_utilities/blockchain-stats-readme.md
Fixes https://github.com/monero-project/monero/issues/7755
- small rewording 
- "piping" was mentioned but "redirecting" was really being meant
- better redirecting example from @trasherdk 
- piping example from @trasherdk
> Doc: Update blockchain stats with review comments

- src/blocks/CMakeLists.txt
Old cmake versions dislike having no space.
> blocks: fix cmake syntax

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
Rebase of #7349
This ensures each list of recipients is only the recipients
for one transaction. It also adds a new field "summary"
that describes the txset as a whole.
Fixes #7344
> Fix describe_transfer for multiple txes in a txset

- .github/workflows/build.yml
Lately I learned 2 important things:
- multiple runs of multiple jobs very quickly use up our quota for caches, so they get pruned too quick
- the general approach in Monero is rather to test for a typical/default case, while testing all the possible extremes would be too resource hungry, and I started to agree with this
This made me reduce the complexity of the GiutHub Actions, also by reusing the caches as often as possible. I will be testing the left out, resource hungry extremes locally and post them on a periodic report.
Here I'm reusing the cache for the Ubuntu-test from the Ubuntu-build. This will spare time and the disk space for the cache. In this case it might be valid to ask why we need the intermediate Ubuntu-build step then? For 2 reasons:
- if the tests fail, then at least …
> CI: Ubuntu-Test reuses Ubuntu-Build cache and building static libs

- src/wallet/wallet2.cpp
Let device implementation handle locking, if necessary. With ledger, if the viewkey was exported no locking is required because the software implementation is used. With Trezor, the software implementation is always used. This patch speeds up wallet refreshes by 6-7x.
Requires #7745.
> wallet2: Don't auto lock device on process parsed blocks

- src/wallet/wallet2.cpp
A proposal to address issues like #7783, https://github.com/trezor/trezor-firmware/issues/1686
Added @dEBRUYNE-1 's improvement.
> wallet: rephrase error message on invalid device address

- src/rpc/CMakeLists.txt
```
CMake Warning (dev) at CMakeLists.txt:566 (add_library):
Policy CMP0115 is not set: Source file extensions must be explicit.  Run
"cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
File:
/Users/selsta/dev/monero/src/rpc/instanciations.cpp
Call Stack (most recent call first):
CMakeLists.txt:554 (monero_add_library_with_deps)
src/rpc/CMakeLists.txt:101 (monero_add_library)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
> rpc: source file extensions must be explicit (cmake warning)

- contrib/epee/src/net_ssl.cpp
This is required to build on OpenBSD (which uses LibreSSL). It also allows building against versions of OpenSSL before 1.0.2.
> Make SSL key/cert storage backward-compatible

- CMakeLists.txt
First reported here: https://github.com/monero-project/monero/pull/6015#issuecomment-545726038
Steps to reproduce:
```
mkdir test && cd test
cmake ..
make randomx
cmake ..
make randomx
```
Second `make` call will unnecessarily build again. Same can be done with `epee` target.
- `randomx` target depends on the value of `${ARCH}`, which is being set after `add_subdirectory(external)`.
- `epee` target on `${HAVE_C11}` which is also set after `add_subdirectory(external)`.
Solution is to move the function calls.
Co-authored-by @perfect-daemon
> cmake: fix double build

- tests/unit_tests/epee_boosted_tcp_server.cpp
- tests/unit_tests/node_server.cpp
boosted_tcp_server: check condition before sleep too
cryptonote_protocol_handler: each instance of BlockchainLMDB requires separate thread due to private thread local fields
> unit_tests: fix broken tests

- .github/workflows/depends.yml
I separated `depends`' caches, which were treated as one, into 3 categories:
- most volatile: ccache
- much less volatile: depends packages, that are the base of the toolchains
- static: OSX SDK
In order to achieve this, each cache type uses a different key generation mechanism:
- ccache: the traditional git's commit hash
- depends: a hash of the package list, that build the binaries in the `built` directory
- OSX SDK: simply the version number
This strategy should help reducing the size cache by not mixing the volatile caches with the much more static ones, since there will be fewer writes of the static ones. The newly created volatile caches will not include the static data. This will also help us stay within our limits, ultimately preventing GitHub from deleting our caches due to their …
> Workflows: depends cache (static) separated from ccache (volatile)

- src/wallet/wallet2.cpp
When the wallet selects decoys using the gamma distribution, the expected distribution is supposed to be fit to the chain tip, but instead is being fit prior to the unlock time. The fix in this PR simply shifts the result of the gamma forward the expected duration of the unlock time. If the gamma spits out an output spent less than the unlock time, then it places that output in a random block within the first 50 spendable blocks (while still factoring in block density). I assumed that outputs younger than the unlock time that the gamma suggests should still be factored into the distribution because one would expect outputs selected by the gamma in this range to be spent soon after unlock. "Someone who spent an output after 1 block back when it was allowed likely would spend that output …
> wallet2: apply gamma distribution from chain tip when selecting decoys (#7807)

- contrib/depends/packages/freebsd_base.mk
A replacement of https://github.com/monero-project/monero/pull/7797, which (/whose ugliness) inspired @wfaressuissia to find a better solution.
The key was treat the original "_Exec format error_" for FreeBSD with prepending its compiler scripts with an explicit interpreter (in this case `/bin/sh`)
> CMake: ccache fix for FreeBSD

- src/wallet/wallet2.cpp
This PR is meant to replace #7798  for next release -- I recommend keeping 7798 on hold for now.
> wallet2: protect client from divide by 0 caused by integer truncation

- src/common/i18n.cpp
The error message was:
`/run/build/monero/src/common/i18n.cpp:74:8: error: ‘transform’ is not a member of ‘std’`
resulting from Boost 1.77 minimizing their headers. The above file assumed, that the `<algorithm>` header would be implicitly included by the Boost headers.
> v0.17: Fix Boost-1.77: Add missing algorithm header to i18n.cpp

- src/wallet/wallet2.cpp
This re-establishes the behaviour added by #348 whereby the wallet attempts to fund the tx fee by reducing the amount of a partial payment if one exists in the tx.
Fixes: #7337
> Attempt to carve the fee from a partial payment early

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/daemon/command_line_args.h
- src/daemon/core.h
- src/daemon/main.cpp
- src/daemon/p2p.h
- src/daemon/rpc.h
- src/p2p/net_node.cpp
- src/p2p/net_node.h
- src/p2p/net_node.inl
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
Patch originally provided by wfaressuissia[m] in #monero-dev, with minor changes.
Tails does not transparently torify traffic, as such torsocks must be used in absence of application-level configuration. This introduces various issues, such as long timeouts (See: https://github.com/monero-project/monero/issues/6708#issuecomment-658899258) and problems closing monerod because torsocks likes to eat sigints. This patch eliminates the need for torsocks by introducing a command line argument for setting the socks proxy. This will also allow the GUI to spawn monerod without using torsocks to fix simple and bootstrap mode on Tails.
> daemon: add command line arg to set socks proxy

- .github/workflows/build.yml
- .gitmodules
- CMakeLists.txt
- README.md
- contrib/depends/packages/expat.mk
- contrib/depends/packages/ldns.mk
- contrib/depends/packages/packages.mk
- contrib/depends/packages/unbound.mk
- contrib/depends/toolchain.cmake.in
- external/CMakeLists.txt
- src/common/CMakeLists.txt
Resolves #6619
unbound had a security audit and multiple issues were found and fixed in v1.9.3: https://ostif.org/our-audit-of-unbound-dns-by-x41-d-sec-full-results/
I don't know how relevant they are for monero, still our unbound submodule is unmaintained and outdated. Setting the it to upstream isn't trivial (it would require calling autoconf from cmake). Better solution is to just remove the submodule completely.
Deterministic builds are now using the latest stable unbound version.
> external: remove unbound submodule

- src/wallet/wallet2.cpp
- src/wallet/wallet_args.cpp
- src/wallet/wallet_args.h
- src/wallet/wallet_rpc_server.cpp
This PR fixes #7624 by simply checking for the simultaneous presence of both `--password-file` and `--wallet-dir` when starting `monero-wallet-rpc`.
> monero-wallet-rpc: Prevent --password-file from being used with --wallet-dir

- external/easylogging++/easylogging++.h
- tests/unit_tests/logging.cpp
There was a branch of `EasyLogging++` code, that lead to UB during incomplete configuration (see the added UTest). Now the branch will throw an exception, expecting to be handled at a higher level.
> EasyLogging++: new anti-UB test and propagating exception at misconfiguration

- .github/workflows/build.yml
A small cleanup of the cache names, using the `runner.os` variable, which evaluates to the appropriate OS. In case of Ubuntu it will be `Linux`
> CI: using runner.os for cache

- contrib/epee/include/stats.inl
- Fixes potential overflow in `get_median()` function.
Note that `get_mid()` was introduced to prevent overflow edge cases in `rolling_median_t`, and added to `median()` for similar reasons (#6718). This `get_median()` was overlooked at that time.
> epee: overflow bugfix in get_median()

- src/device/device.hpp
See https://github.com/monero-project/monero/pull/7875#issuecomment-902196927
Previous description:
The variable `mode` in `device` was being uninitialized when the non-empty constructor was being used. By delegating the constructor to the default constructor (C++11 feature), where the variable is initialized, I get the variable initialized and prevent code duplication.
> Device: remove unused and incorrect non-default constructor

- tests/core_tests/transaction_tests.cpp
```
/Users/selsta/dev/monero/tests/core_tests/transaction_tests.cpp:75:41: warning: unused typedef 'tx_output_entry' [-Wunused-local-typedef]
typedef tx_source_entry::output_entry tx_output_entry;
^
1 warning generated.
```
> core_tests: remove unused typedef, fix warning

- src/ringct/multiexp.cc
```
/Users/selsta/dev/monero/src/ringct/multiexp.cc:452:33: warning: unused variable 'mask' [-Wunused-variable]
static constexpr unsigned int mask = (1<<STRAUS_C)-1;
^
```
Silence it by moving the deceleration inside the `#elif 1` section.
> ringct: silence unused variable warning

- src/wallet/wallet_rpc_server.cpp
> wallet_rpc_server: fix help text remaining bold

- src/wallet/wallet2.cpp
```
/Users/selsta/dev/monero-gui/monero/src/wallet/wallet2.cpp:2821:33: warning: lambda capture 'i' is not used [-Wunused-lambda-capture]
tpool.submit(&waiter, [&, i, n_vouts, txidx](){ geniod(tx, n_vouts, txidx); }, true);
~~^
1 warning generated.
```
> wallet: fix unused lambda capture warning

- .gitmodules
- external/CMakeLists.txt
Should fix the issue with having to run `git submodule sync`.
> [release-v0.17] miniupnp: set submodule to upstream, disable install 

- tests/unit_tests/node_server.cpp
After fixing the random failure under Ubuntu of the test `bind_same_p2p_port` belonging to the suite `node_server`, the same test under Mac OSX ceased to work completely. @TimSycamore noted, that under OSX, the IP has to stay 127.0.0.1, and not 127.0.0.2.
There are some temporary commits in this PR to prove the point - that the UTs under OSX were failing without the IP fix. Also the unit tests for Mac are temporarily enabled, but maybe it wouldn't be a bad idea to run them regularly either, since they don't cost that much time (< 2 minutes)? Of course enabling them for good shall be done in a separate PR.
> Mac: fix unit test bind_same_p2p_port

- src/net/socks.h
- src/p2p/net_node.cpp
Found this while reviewing the codebase. If a timeout occurs in p2p socks code, the corresponding socket is left open and cleaned up at the mercy of the socks server. Socks servers are typically daemons run by the same user, so this is unlikely to be a widespread resource DoS issue, but still needs fixing. 
The `net::socks::client` class leaves timeout handling to the caller, with my original thinking that a particularly strategy shouldn't be "forced" upon the caller. Perhaps an `asio::steady_timer` would suffice as it would work "well enough" (although it would be a slight performance hit on the two current use cases).
> Quicker resource cleanup on p2p socks timeout

- docs/ZMQ.md
- src/cryptonote_basic/cryptonote_basic.h
- src/cryptonote_basic/events.h
- src/cryptonote_basic/fwd.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/cryptonote_tx_utils.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- src/daemon/daemon.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
- src/rpc/zmq_pub.cpp
- src/rpc/zmq_pub.h
- src/serialization/json_object.cpp
- src/serialization/json_object.h
- utils/python-rpc/framework/daemon.py
Adds the following:
- "get_miner_data" to RPC API
- "json-full-miner_data" to ZeroMQ subscriber contexts
Both provide the necessary data to create a custom block template. They are used by p2pool.
Data provided:
- major fork version
- current height
- previous block id
- RandomX seed hash
- network difficulty
- median block weight
- coins mined by the network so far
- mineable mempool transactions
> RPC and ZeroMQ APIs to support p2pool

- contrib/depends/packages/openssl.mk
It's been explicitly forcing `-j1` instead of allowing it to build in parallel. Looks like this has been broken since the initial commit. Explicitly specifying the *.pc targets is what breaks the parallel build. If they're omitted they'll get built anyway, in proper order.
> Fix parallel make of OpenSSL

- CMakeLists.txt
The option `SANITIZE` was not being advertised to the external user interfaces of CMake, like ccmake or cmake-qt.
Context: The option is needed for enabling the ASAN memory sanitizer.
> CMake: Add missing SANITIZE option

- .github/workflows/build.yml
- .github/workflows/depends.yml
There was a mixture of `ccache` settings set via env vars and command line. This PR unifies these settings and reuses them as a variable. Also made a tiny cleanup of the apt settings.
`hash_dir=false` helps in reusing the cache, when your project is named differently than the original one.
https://ccache.dev/manual/latest.html
If true (which is the default), ccache will include the current working directory (CWD) in the hash that is used to distinguish two compilations when generating debug info (compiler option -g with variations). Exception: The CWD will not be included in the hash if base_dir is set (and matches the CWD) and the compiler option -fdebug-prefix-map is used. See also the discussion under Compiling in different directories. …
> CI: ccache common settings variable and apt tidying

- CMakeLists.txt
- contrib/epee/src/CMakeLists.txt
- contrib/epee/tests/src/CMakeLists.txt
- external/easylogging++/CMakeLists.txt
Now that we have CMake 3.5 as minimum we can properly set the required C/C++ standard in a cross platform way.
Seen on Loki repo.
> cmake: set required C/C++ standard to 11

- src/simplewallet/simplewallet.cpp
Cherry-picked @selsta's #7764 
IMHO this should be in release; the `export_transfers` command is kinda broken without it.
> simplewallet: don't truncate integ. address in export_transfers

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
we reuse the wallet_keys_unlocker object, which does the right thing
in conjunction with other users of decrypt/encrypt (ie, refresh).
> wallet2: fix key encryption when changing ask-password from 0/1 to 2

- src/wallet/wallet2.cpp
```
/Users/selsta/dev/monero/src/wallet/wallet2.cpp:317:29: warning: unused variable 'e' [-Wunused-variable]
boost::system::error_code e;
^
/Users/selsta/dev/monero/src/wallet/wallet2.cpp:7076:29: warning: unused variable 'errcode' [-Wunused-variable]
boost::system::error_code errcode;
^
2 warnings generated.
```
> wallet2: remove 2 unused variables

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/tx_pool.cpp
- tests/unit_tests/long_term_block_weight.cpp
avoids mining txes after a fork that are invalid by this fork's
rules, but were valid by the previous fork rules at the time
they were verified and added to the txpool.
> tx_pool: full tx revalidation on fork boundaries

- src/cryptonote_core/tx_pool.cpp
```
/Users/administrator/monero/src/cryptonote_core/tx_pool.cpp:1584:39: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
m_blockchain.for_all_txpool_txes([this, &txes](const crypto::hash &txid, const txpool_tx_meta_t &meta, const cryptonote::blobdata_ref*) {
^~~~~
```
> cryptonote_core: fix unused lambda warning

- src/rpc/core_rpc_server.cpp
This will prevent people spending old pre-rct outputs using a
stranger's node, which may be a good thing
> rpc: fix DoS vector in get_output_distribution

- contrib/gitian/DOCKRUN.md
- contrib/gitian/README.md
- contrib/gitian/dockrun.sh
This shell script creates a docker image for running the gitian-build.py
script, to avoid version incompatibilities.
Only docker.io and apt-cacher-ng are required to be installed on the
host. The MacOSX SDK should also be present in this directory if Mac
builds are desired. A container named "gitrun" is used to launch
the builds, and all output will reside in this container as well.
Run as e.g.
`  OPT="-j 8" ./docker.sh v0.17.2.3`
> Add simple script for running gitian-build in docker

- src/device/device_ledger.cpp
The current code does work by accident, but it might break if someone uses `ASSERT_SW` in a different place, or if variables get renamed.
> device_ledger: fix incorrect macro

- contrib/depends/funcs.mk
- contrib/depends/packages/openssl.mk
depends didn't have target-specific overrides for _build_env
so ANDROID_NDK_HOME wasn't being set at build time.
This fix supersedes the manual edit of Configuration/15-android.conf.
Resolves #8095
> Fix Android OpenSSL build [release-v0.17]

- contrib/depends/funcs.mk
- contrib/depends/packages/openssl.mk
depends didn't have target-specific overrides for _build_env
so ANDROID_NDK_HOME wasn't being set at build time.
This fix supersedes the manual edit of Configuration/15-android.conf.
Resolves #8095  
(Same as #8096)
> Fix Android OpenSSL build [master]

- src/wallet/node_rpc_proxy.cpp
If Pay For RPC is not active the daemon RPC call `rpc_access_info` does not return a hashing blob, and trying to parse the hex string in `NodeRPCProxy::get_rpc_payment_info` as it's currently done results in an unnecessary error message that will appear repeatedly in a wallet log file is logging is active.
> Avoid unnecessary 'Invalid hashing blob' error message

- README.md
Since the non-root user 'monero' is specified in the Dockerfile, the
bind mount when running the container should be set to this user's home
directory be default, not the root user's home directory.
> Fix docker instructions to account for non-root user

- CMakeLists.txt
I set Clang as `CMAKE_CXX` compiler. Due to non-existent warnings flags of Clang, in the building phase, an annoying number of `unknown warning option` is printed.
This patch, badly, fixes this problem. Since it's one of my first patches on Monero repository and I have no knowledge of CMake, please let me know about any feedback.
> Fixed warnings for Clang (used as CMAKE_CXX compiler)

- Dockerfile
According to Dockerfile best practices
(https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint)
the best use for ENTRYPOINT is to set the image’s main command and then
use CMD as the default flags. This makes it easier to change the flags
passed to monerod when running the Docker image.
> Use CMD in Dockerfile

- src/crypto/crypto.h
- src/cryptonote_basic/account.cpp
- src/cryptonote_basic/account.h
- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_config.h
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/gen_multisig/gen_multisig.cpp
- src/multisig/CMakeLists.txt
- src/multisig/multisig.cpp
- src/multisig/multisig.h
- src/multisig/multisig_account.cpp
- src/multisig/multisig_account.h
- src/multisig/multisig_account_kex_impl.cpp
- src/multisig/multisig_kex_msg.cpp
- src/multisig/multisig_kex_msg.h
- src/multisig/multisig_kex_msg_serialization.h
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/core_tests/chaingen.h
- tests/core_tests/multisig.cpp
- tests/functional_tests/multisig.py
- tests/unit_tests/multisig.cpp
- utils/python-rpc/framework/wallet.py
- Refactors multisig key exchange (kex) and account generation.
- The key exchange interface has been generally simplified.
- No more `finalize_multisig()`.
- Most kex functionality has been sequestered in the `multisig` component library, so `wallet2` and friends only need a few relatively simple wrappers to get things done.
- Key exchange messages contain 'round' numbers, indicating which 'round' of message exchange those message correspond to. 'Rounds' are synchronous phases of key exchange where you collect message from other participants. Recording round numbers in messages allows kex participants to more easily track the kex process.
- The multisig kex algorithm has been updated.
- Use robust key aggregation (a.k.a. MuSig-style; see …
> multisig: key exchange update and refactor

- src/crypto/crypto-ops.c
- src/crypto/crypto-ops.h
- src/ringct/multiexp.cc
- tests/crypto/crypto-tests.h
- tests/crypto/crypto.cpp
- tests/crypto/main.cpp
The function `ge_p3_is_point_at_infinity()` is naively evaluating field elements that haven't been reduced by the field order.
Low, this function is not currently used for anything important (only performance testing of some `multiexp` functions). In general, whether a crypto element is reduced mod its group/field order or not, is only important in byte-aware contexts such as byte-wise comparisons (as in this case), or hash inputs (`ge_p3` point representations are never hashed in Monero).
Convert all field elements in the input `ge_p3` point to canonical representation (32-byte numbers reduced `mod q`) before evaluating them.
I added test cases with experimentally-found failures of the old function (these occurred in ~1 in 600k random `ge_p3` point representations of the identity …
> crypto: fix ge_p3_is_point_at_infinity()

- src/wallet/wallet2.cpp
- tests/functional_tests/transfer.py
Closes #8073
The wallet balance should correctly reflect unconfirmed transfers and change when used with #6986 and when strict mode is false.
> Balance includes unconfirmed transfers to self

- utils/systemd/monerod.service
monerod now supports `--proxy`, so torsocks shouldn't be recommended anymore.
> systemd: remove outdated torsocks example

- src/rpc/rpc_args.cpp
This PR removes the requirement for --rpc-login to be specified if --rpc-access-control-origins is.
This will allow public nodes to serve cross-origin requests. You can still use --rpc-login with
--rpc-access-control-origins, but it is no longer mandatory.
Original Issue: #8168
> Fixes: Don't require --rpc-login with --rpc-access-control-origins

- src/p2p/net_node.inl
I reached the storage limits of my vps, which is currently mostly dedicated to this node. This PR removes my seednode and replaces it with one hosted on [Haveno](https://github.com/haveno-dex)'s infrastructure.
> replace erciccione's seednode with one on haveno's infrastructure

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
See issue: https://github.com/monero-project/monero/issues/7126
This PR adds the wallet name and the network mode to the inactivity lock message.
> Add wallet name, network mode to inactivity lock.

- src/simplewallet/simplewallet.cpp
Closes #8171 
There are duplicate headers for 'amount' when performing export_transfers
all. Column five represents the total amount of the transaction while
column eleven represents the amount transferred per destination (e.g.
multi-destination transactions). The columns have been renamed to
'transaction amount' and 'destination amount` respectively.
> simplewallet: rename duplicate amount headers for clarity

- src/simplewallet/simplewallet.cpp
Closes #8176 
This commit adds an option to export transaction
keys when performing export_transfers all. By passing
option=with_keys a new column 'tx key' will be
populated with respective keys.
> simplewallet: add option for exporting tx keys

- src/cryptonote_core/cryptonote_core.h
- tests/core_tests/chaingen_main.cpp
-1.5% overall compilation time after changing just 2 files.
Before:
Please look to the right at the `cryptonote_core.h`. This entire tree is now disposed of.
After:
To be able to test the change in the most objective way, please execute:
```
mkdir -p build/time && cd build/time
git checkout master
cmake ../.. -DUSE_CCACHE=OFF -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=ON && make clean && time make > /dev/null
git checkout compil-time-cryptonote_core-portable_storage
cmake ../.. -DUSE_CCACHE=OFF -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=ON && make clean && time make > /dev/null
```
| Previous   |      Current      | Change |
|----------|-------------|-------------|
| real	104m23,886s |     real	102m50,045s  |  -1.5% |
> Compil. time: cryptonote_core minus portable_storage header

- src/cryptonote_core/blockchain.cpp
This comment suggests this check is unnecessary, when it is completely necessary as miner TXs can have multiple outputs *which is a statement directly, and incorrectly, contradicted by this comment*. While I don't ever see someone removing this code and getting their edits merged into Monero, someone inexperienced who thinks they're cleaning old code may break their own work, and then there's really just zero benefit to keeping this around.
> Remove footgun doc comment in miner TX validation

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
Closes #8214 
This commit adds a 'regexp' boolean field to the get_accounts
request. The flag is set to false by default and maintains backwards
compatibility. When set to true the user can search tags by regular
expression filters. An additional error message was added for failed
regular expression searches. Bump minor version to 25.
> wallet_rpc_server: support regex for tags in get_accounts

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/net/connection_basic.hpp
- contrib/epee/include/net/levin_protocol_handler_async.h
- contrib/epee/include/net/net_helper.h
- contrib/epee/include/net/network_throttle.hpp
- contrib/epee/include/reg_exp_definer.h
- src/cryptonote_basic/miner.cpp
- src/cryptonote_basic/miner.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
In this repo, `boost::interprocess` was being used soley to make `uint32_t` operations atomic. So I replaced each instance of
`boost::interprocess::ipcdetail::atomic(...)32` with `std::atomic` methods. I replaced member declarations as applicable. For example, when I needed to change a `volatile uint32_t` into a `std::atomic<uint32_t>`. Sometimes, a member was being used a boolean flag, so I replaced it with `std::atomic<bool>`.
You may notice that I didn't touch `levin_client_async.h`. That is because this file is entirely unused and will be deleted in PR #8211.
When I get more time, I will benchmark this to see if this changed the compile time in any manner.
> Eliminate dependence on boost::interprocess

- src/rpc/rpc_args.cpp
Same as PR #8187 for release v0.17
> [release-v0.17] Don't require --rpc-login with --rpc-access-control-origins

- contrib/epee/include/storages/parserse_base_utils.h
- contrib/epee/src/parserse_base_utils.cpp
- tests/unit_tests/epee_utils.cpp
* Remove `match_string()`, `match_number()`, and `match_word()`
* Remove `match_word_with_extrasymb()` and `match_word_til_equal_mark()`
* Adapt unit test for `match_number()` to `match_number2()`
* Adapt unit test for `match_string()` to `match_string2()`
Note: the unit tests were testing for the old version of the functions, and
the interfaces for these functions changed slightly, so I had to also edit
the tests.
As of writing, this PR has no merge conflicts with #8211
> Remove dead code from parserse_base_utils and fix unit tests

- tests/functional_tests/integrated_address.py
The integrated address functional test fails in the workflows due
to an assertion for missing payment id that is no longer needed.
Remove the assertion and update the assertion count.
Fixes 7dcfccb: ("wallet_rpc_server: fix make_integrated_address with no payment id")
> tests: integrated_address: remove missing payment id assertion

- src/blockchain_db/CMakeLists.txt
- src/checkpoints/CMakeLists.txt
- src/common/CMakeLists.txt
- src/crypto/CMakeLists.txt
- src/cryptonote_basic/CMakeLists.txt
- src/cryptonote_core/CMakeLists.txt
- src/daemon/CMakeLists.txt
- src/hardforks/CMakeLists.txt
- src/lmdb/CMakeLists.txt
- src/mnemonics/CMakeLists.txt
- src/multisig/CMakeLists.txt
- src/net/CMakeLists.txt
- src/ringct/CMakeLists.txt
- src/serialization/CMakeLists.txt
- src/simplewallet/CMakeLists.txt
Using the `monero_find_all_headers()` macro to add missing headers, where appropriate.
Whenever it wasn't a good idea, like in `wallet_api`, where the Author actually distinguishes between API and private headers, the macro wasn't used.
- `serialization` was actually missing all of its headers, except for one.
- `daemon` was referencing external headers (`cryptonote_protocol` and `p2p`), which are imported anyway through `target_link_libraries()`, so I took the liberty of removing these references
> CMake: Add missing headers via monero_find_all_headers macro

- src/device/device_ledger.cpp
The [Ledger nano S plus](https://shop.ledger.com/pages/ledger-nano-s-plus?r=00d147b67b6d) has a new Product ID, this PR adds it to the list of known IDs so the Nano S Plus can be used.
> Added support for Ledger Nano S Plus

- src/simplewallet/simplewallet.cpp
Before:
```
[wallet 49C5ha]: integrated_address 4JtkiNvoi3iSPHHvcfXPPyj66zHQ9h1X9hmLCjDZ6kbNUhtYwDhAMm79p9GZ1iPCUhDMEvKMkMJdgb7JURAkCZUuhuFpASeBvCxRJ5v9Je
Integrated address: 49C5ha7K6nCSPHHvcfXPPyj66zHQ9h1X9hmLCjDZ6kbNUhtYwDhAMm79p9GZ1iPCUhDMEvKMkMJdgb7JURAkCZUuUaa9DCp, payment ID: 87e4b8861f9c69d7
```
After:
```
[wallet 49C5ha]: integrated_address 4JtkiNvoi3iSPHHvcfXPPyj66zHQ9h1X9hmLCjDZ6kbNUhtYwDhAMm79p9GZ1iPCUhDMEvKMkMJdgb7JURAkCZUuhuFpASeBvCxRJ5v9Je
Standard address: 49C5ha7K6nCSPHHvcfXPPyj66zHQ9h1X9hmLCjDZ6kbNUhtYwDhAMm79p9GZ1iPCUhDMEvKMkMJdgb7JURAkCZUuUaa9DCp, payment ID: 87e4b8861f9c69d7
```
> simplewallet: fix integrated_address output string

- .github/workflows/build.yml
- Makefile
https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html
> Typical values include Debug, **Release**, RelWithDebInfo and MinSizeRel, but custom build types can also be defined.
> Depending on the situation, the value of this variable may be treated **case-sensitively** or case-insensitively.
> Makefile: fix spelling of CMAKE_BUILD_TYPE value

- README.md
very small changes to the readme
- empty spaces after sentences removed
- dependency install command blocks made copyable like the other ones below it
- backtick typo fix
sorry if reviewing this is a waste of brain power
> readme: small fixes

- src/cryptonote_config.h
- src/cryptonote_core/blockchain.cpp
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- tests/functional_tests/cold_signing.py
- tests/functional_tests/main.cpp
- tests/functional_tests/multisig.py
- tests/functional_tests/transfer.py
As per:
- https://github.com/monero-project/research-lab/issues/79
- https://github.com/monero-project/meta/issues/655
-----
This PR follows the "double fork" pattern to allow ring sizes of either 11 or 16 during a grace period, and then requires 16. This way users of updated wallets who submit tx's right before the fork height that make it into the pool will still have their tx's processed.
Also removed the obsolete command to allow users to set a default ring size in the client. Updated wallets will start to use ring size 16 at the fork height.
------
I'm currently syncing the chain from scratch with this code as a sanity check. Currently on block ~2.3mn, which is after the latest fork. Will update here when finished. Update: synced from scratch successfully.
> Bump ring size to 16 for v15

- src/multisig/multisig_account.cpp
- src/multisig/multisig_account.h
- src/multisig/multisig_account_kex_impl.cpp
- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_server.cpp
- tests/core_tests/multisig.cpp
- tests/functional_tests/multisig.py
- tests/unit_tests/multisig.cpp
**Problem**: When creating a group multisig account, each step of key exchange relies on messages from all other participants. If a malicious player only sends their final message to one honest player, but not others, then the other honest players will be stuck without completed accounts. If that one honest player receives funds to the address he created, then those funds will either be unspendable or only spendable with cooperation from malicious group members.
**Solution**: Add a round to multisig account creation to verify that all other participants have completed their accounts.
This PR also has some semantic and control-flow cleanup of the multisig kex implementation (I am not satisfied with the readability of my earlier work - cleanup will continue in PR #8203 and alongside the …
> multisig: add post-kex verification round

- src/crypto/keccak.c
All tests were conducted on the same PC (Ryzen 5 5600X running at fixed 4.65 GHz).
Before:
```
test_cn_fast_hash<32> (100000 calls) - OK: 1 us/call
test_cn_fast_hash<16384> (1000 calls) - OK: 164 us/call
```
After:
```
test_cn_fast_hash<32> (100000 calls) - OK: 0 us/call
test_cn_fast_hash<16384> (1000 calls) - OK: 31 us/call
```
More than 5 times speedup for cn_fast_hash.
Also noticed consistent 1-2% improvement in `test_construct_tx` results. @j-berman this should also speed up view tags #8061
> Optimized keccak implementation

- src/blockchain_db/blockchain_db.cpp
- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/ringct/rctSigs.cpp
- src/wallet/wallet2.cpp
- tests/core_tests/multisig.cpp
A change to the format commitment / 8 was included with BP+, which is a minor optimization which increased complexity, spread out where crypto code is handled, and created a disparate state between transactions and disk (as they were saved in their full form thanks to a processing step inside the DB code).
This PR reverts this planned change. The blockchain_db.cpp edits may look to be further edited than just this reversion, yet that was its code pre-BP+.
> Preserve commitment format inside transactions

- README.md
hi again, just a few more small changes:
- added arch/fedora deps code blocks
- `v0.17.1.0` > `v0.17.3.0`
- blockchain size + date update (wow its been 2 years!)
- misc. fixes
this also deletes the redundant 8-address for donations.  
was there a reason why both addresses were listed? (maybe for sorting donations?)
> readme: arch/fedora deps + small fixes

- src/ringct/bulletproofs_plus.cc
Just a minor thing - I noticed one field inversion per round can be saved in the BP+ prover while I was implementing it for Trezor
@SarangNoether @moneromooo-monero 
Not sure if this is already fixed in any of your branches or other PRs, I didn't find it among PRs. If it is a duplicate, feel free to close :)
> BP+ optimization save one inversion in prover, use sc_muladd

- Doxyfile
- contrib/epee/include/net/net_ssl.h
Thanks to @selsta for pointing out the Doxygen option!
No more of this:
Bonus: little doc fix for net_ssl.h
> Doxygen: Hide anonymous namespaces from documentation

- LICENSE
- Makefile
- src/multisig/multisig_account.cpp
- src/multisig/multisig_account.h
- src/multisig/multisig_account_kex_impl.cpp
- src/multisig/multisig_kex_msg.cpp
- src/multisig/multisig_kex_msg.h
- src/multisig/multisig_kex_msg_serialization.h
- src/ringct/bulletproofs_plus.cc
- src/ringct/bulletproofs_plus.h
- tests/core_tests/bulletproof_plus.cpp
- tests/core_tests/bulletproof_plus.h
- tests/performance_tests/bulletproof_plus.h
- tests/performance_tests/derive_view_tag.h
- tests/performance_tests/out_can_be_to_acc.h
- tests/unit_tests/bulletproofs_plus.cpp
- tests/unit_tests/scaling_2021.cpp
The newly merged files have overwritten the copyright to previous year apparently.
Also added the `Makefile` and `LICENSE` files, discovered by @AkritW in https://github.com/monero-project/monero/pull/8297 .
> Update copyright to 2022 for Hardfork files

- contrib/depends/packages/unbound.mk
Someone reported a crash / memory corruption bug on IRC that had unbound related error messages so I thought about updating `unbound` again.
Change logs:
- https://github.com/NLnetLabs/unbound/releases/tag/release-1.14.0
- https://github.com/NLnetLabs/unbound/releases/tag/release-1.15.0
I don't think there is anything relevant for monero but updating doesn't hurt.
> depends: update unbound to 1.15.0

- src/wallet/wallet2.cpp
```
/Users/selsta/dev/monero/src/wallet/wallet2.cpp:7871:12: warning: variable 'n_outs' set but not used [-Wunused-but-set-variable]
size_t n_outs = 0; for (const auto &e: ores.amount_outs) n_outs += e.outputs.size();
^
/Users/selsta/dev/monero/src/wallet/wallet2.cpp:9674:29: warning: variable 'accumulated_outputs' set but not used [-Wunused-but-set-variable]
uint64_t accumulated_fee, accumulated_outputs, accumulated_change;
^
/Users/selsta/dev/monero/src/wallet/wallet2.cpp:9878:12: warning: variable 'rct_outs_needed' set but not used [-Wunused-but-set-variable]
uint64_t rct_outs_needed = 2 * (fake_outs_count + 1);
```
I used `git blame` and I did not see any recent patches that caused these warnings.
> wallet2: fix a couple unused variable warnings

- contrib/epee/include/console_handler.h
`WaitForSingleObject` returns a `DWORD`, not an int, so assign `retval` as such and it should fix the error.
> Windows build: fix narrowing error on newer compilers

- src/cryptonote_core/tx_pool.cpp
It appears there is a logic error when calling `get_relay_delay()`. As a result, txs get stuck in the daemon if the daemon happens to fail the first submission, and don't re-relay as expected.
Examples of submission failures: #6938, #6929, #8251
The following sample numbers should hopefully help make it clear what the issue was, and how this PR implements a backoff delay as expected. Took me a bit to wrap my head around it -- it looks simple but it's deceptively tricky.
| `now - last_relayed_time` | `now - received_time` | `get_relay_delay` |
|--:|--:|--:|
|1   | 1   | 300  |
|301 | 301 | 600  |
|601 | 601 | 900  |
|901 | 901 | 1200 |
Notice how `now - last_relayed_time` is always <= `get_relay_delay`. This causes txs to get stuck [right …
> tx pool: fix backoff delay logic when re-relaying txs

- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/p2p/net_node.inl
- tests/unit_tests/node_server.cpp
`update_sync_search` runs in the idle loop, checking to see if we have outgoing connections >= the max allowed. If so, a sync'd connection gets dropped so that the daemon can try to connect to nodes that need to sync.
Currently it's [comparing the tally of **clearnet + tor + i2p** outgoing connections to the max of outgoing **clearnet** peers](https://github.com/monero-project/monero/blob/8349cfe4a63cfc63d50ce3818886b67a05e240a4/src/cryptonote_protocol/cryptonote_protocol_handler.inl#L1798); but, the tally of clearnet + tor + i2p outgoing peers is usually always going to be greater than the max allowed outgoing clearnet peers. Because of this, it's usually just going to drop a tor or i2p connection [right here](https://github.com/monero-project/monero/blob/8349cfe4a63cfc63d50ce3818886b67a0 …
> p2p: don't exclusively drop tor/i2p outgoing cxns in idle loop

- src/wallet/wallet2.cpp
When forced to deal with an untrusted node, a wallet will quantize
its current height to disguise the real height to the adversary, to
try and minimize the daemon's ability to distinguish returning
wallets.
Daemons will thus return more blocks than the wallet needs, starting
from earlier in the chain. These extra blocks will be disregarded
by the wallet, which had already scanned them.
However, for the purposes of reorg size detection, the wallet assumes
all blocks the daemon sends are different, which is only correct if
the wallet hasn't been coy, which is only the case for trusted
daemons (which you should use). This causes an issue when the size
of this "fake reorg" is above the sanity check threshold at which
the wallet refuses a reorg.
To fix this, the reorg size check is moved later …
> wallet2: fix spurious reorg detection with untrusted nodes

- contrib/gitian/README.md
- contrib/gitian/gitian-build.py
Prevents symptoms such as:
`Submodule 'external/miniupnp' is not up-to-date.`
during performing "Reproducible Builds".
A much less obtrusive alternative to https://github.com/monero-project/monero/pull/8292
Here I'm simply deleting the `monero` directory via the `--setup` switch and allow it to be cloned from scratch.
Thanks to @hyc for pointing out the easy way.
> Gitian: refresh the stale Monero dir via --setup switch

- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
Introduced in #7312
Tested on the GUI side and working as expected.
> wallet_api: add scanTransactions function

- external/boost/archive/portable_binary_archive.hpp
Unlike with some other warnings, clang does not have a `stringop-overflow` group so it doesn't recognize the `#pragma GCC ...` directive in #8338
> clang: warning fix for #8338

- src/rpc/core_rpc_server.cpp
Reverts PR #7937. Related to #8383.
Incorrect sequence that PR #7937 introduces:
1. db write to add block to chain begins
2. notification that block added to chain is pushed out to consumer
3. consumer makes request to RPC API expecting latest chain state in response
4. RPC server grabs db read txn guard [PR 7937]
5. db write from step 1 completes
6. consumer of RPC API receives consistent **but stale** view of the chain from before the most recent block was added thanks to the db read txn guard from step 4 [PR 7937]
This PR removes db read txn guards added in #7937 to the RPC server to avoid the above problem, accepting that the RPC API can still possibly return inconsistent data as the lesser of 2 evils (which is current behavior).
A stronger long term fix to ensure consistent chain …
> Revert "Make RPC server functions that read db thread safe"

- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
unconfirmed solely uses a - b, and received now accepts b so it can provide more detailed logs on what occurred (printing a - b, yet also a and b themselves).
The updated print statement ("a yet b") was discussed with mooo. This PR has not been reviewed by them however.
> Improve consistency between on_money_received and on_money_received_unconfirmed

- src/wallet/wallet2.cpp
Fixes the following issue when mempool contains more than 100 new transactions when connected to a restricted node: 
`Error calling gettransactions daemon RPC: r 1, status Too many transactions requested in restricted mode`
@selsta
> Chunk /gettransactions to avoid hitting restricted RPC limit

- src/wallet/wallet2.cpp
It's been a couple hardforks since this check was added, all daemons support `/get_output_distribution.bin`.
> wallet2: remove obsolete rpc version check

- src/wallet/wallet2.cpp
Related: #8407
There are no other places where DNS is used in wallet2, so the --no-dns flag can be removed.
> wallet2: don't use DNS to obtain segregation heights

- .github/workflows/depends.yml
Rename the "build-macos" job within "depends", as it is not building on macOS as the similarly named job within build.yml does. Also, both names overlap which is confusing when looking for step-by-step build instruction examples or when looking at the logfile.
> Rename build-macos CI Job

- src/wallet/wallet2.h
> wallet2: prevent crash when reading tx w/fewer outputs than expected

- src/wallet/wallet2.h
Would allow showing output pubkeys alongside destination addresses. Requested downstream [here](https://git.featherwallet.org/feather/feather/issues/379).
> wallet2: keep around transaction prefix for confirmed transfers

- src/cryptonote_config.h
- src/multisig/multisig_tx_builder_ringct.cpp
- src/multisig/multisig_tx_builder_ringct.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- tests/core_tests/multisig.cpp
To solve [this issue](https://github.com/monero-project/research-lab/issues/103) (@kayabanerve), obtain the ephemeral secrets for a multisig tx's outputs from a hash chain starting with a 32-byte entropy provided by the tx initiator plus the key images of the tx's inputs.
> multisig: mitigate fund-burning attack

- src/hardforks/hardforks.cpp
I set the stagenet fork to be around 1 week before mainnet, I'm not sure if this is enough.
> hardforks: set mainnet and stagenet v15/16 fork height

- CMakeLists.txt
- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/abstract_tcp_server2.inl
- contrib/epee/include/net/net_ssl.h
- contrib/epee/src/net_ssl.cpp
- tests/unit_tests/epee_boosted_tcp_server.cpp
Cherry-picked the commits from @perfect-daemon's #7760, resolved merge conflicts, and made most of the style changes requested in the PR. I made 0 logic changes to the PR. @perfect-daemon is the author of the PR and deserves full credit for the work.
#7760 is functionally a rewrite of the code handling server-side socket connections. It solves important issues that can be observed by running the tests provided in the PR, with the `monerod` code from before this PR.
Summarizing the issues the 3 tests demonstrate:
1. the SSL shutdown can hang,
2. the SSL handshake sequence can seg fault,
3. there is a circular dependency in the strand processing reads/writes that can lead to unnecessary dropped connections, worse performance, and other problems.
There are additional issues solved by the …
> connection: fix implementation (by @perfect-daemon)

- contrib/epee/include/net/enums.h
My mistake introduced in #8330.
Fixes:
```
In file included from /usr/include/c++/5/bits/hashtable.h:35:0,
from /usr/include/c++/5/unordered_map:47,
from /monero/monero/external/easylogging++/easylogging++.h:406,
from /monero/monero/contrib/epee/include/misc_log_ex.h:35,
from /monero/monero/contrib/epee/include/include_base_utils.h:32,
from /monero/monero/src/rpc/core_rpc_server.cpp:34:
/usr/include/c++/5/bits/hashtable_policy.h: In instantiation of 'struct std::__detail::__is_noexcept_hash<epee::net_utils::zone, std::hash<epee::net_utils::zone> >':
/usr/include/c++/5/type_traits:137:12:   required from 'struct std::__and_<std::__is_fast_hash<std::hash<epee::net_utils::zone> >, std::__detail::__is_noexcept_hash<epee::net_utils::zone, std::hash<epee::net_utils::zone> > >' …
```
> Template hash function to fix compiler error on version < gcc-6

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
> Fix use of rtxn without a mdb_txn_safe wrapper [release-v0.18]

- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
This is a copy of #8381 for release-v0.18 branch.
> Before the fix, it processed all transactions in the mempool which could be very slow when mempool grows to several MBs in size. I observed `get_block_template_backlog` taking up to 15 seconds of CPU time under high mempool load.
After the fix, only transactions that can potentially be mined in the next block will be processed (a bit more than the current block median weight).
> Fixed get_block_template_backlog performance [release-v0.18]

- src/device_trezor/device_trezor.cpp
- src/device_trezor/trezor/protocol.cpp
- src/device_trezor/trezor/protocol.hpp
- tests/core_tests/chaingen.cpp
- tests/trezor/trezor_tests.cpp
- tests/trezor/trezor_tests.h
- HP15 changes implemented to the Trezor client in Monero wallet
- BP+ support added for Trezor
- old Trezor firmware version support removed, code cleanup
Trezor firmware changes: https://github.com/trezor/trezor-firmware/pull/2232
> feat(trezor): add HF15 support, BP+

- src/crypto/hash-extra-jh.c
- src/crypto/hash-extra-skein.c
- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
- src/wallet/wallet2.cpp
This PR fixes 4 instances of `-Wunused...`
> GCC: unused warnings

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
Fix use of rtxn without a mdb_txn_safe wrapper
> Fix use of rtxn without a mdb_txn_safe wrapper

- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
Before the fix, it processed all transactions in the mempool which could be very slow when mempool grows to several MBs in size. I observed `get_block_template_backlog` taking up to 15 seconds of CPU time under high mempool load.
After the fix, only transactions that can potentially be mined in the next block will be processed (a bit more than the current block median weight).
> Fixed get_block_template_backlog performance

- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- Defensive change from `return` to `continue` to ensure pool pruning executes to completion.
- Ensure tx pool weight doesn't underflow.
- Will propose a fix in PR #8076 that prevents the root cause of the `"Failed to find tx_meta in txpool"` error. Noticed the cause of the error while reviewing that PR and that PR seems well positioned to solve it.
> txpool: continue pool pruning even if a tx can't be found

- .github/workflows/build.yml
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- tests/README.md
- tests/functional_tests/CMakeLists.txt
- tests/functional_tests/functional_tests_rpc.py
- tests/functional_tests/txpool.py
- utils/python-rpc/framework/zmq.py
When a daemon is in the "fluff" epoch and a user submits a tx to the daemon, the tx doesn't get published via zmq's `txpool_add`. Reported by @TrasherDK; see logs [1](https://libera.monerologs.net/monero-dev/20220707#c117558-c117568), [2](https://libera.monerologs.net/monero-dev/20220707#c117619-c117634), and [3](https://libera.monerologs.net/monero-dev/20220708#c117725-c117728).
Publish "just broadcasted" txs via zmq.
Of note, the test I added hangs waiting to receive txs that never come over zmq with the code from before this PR.
- upon tx submission, [`handle_incoming_tx` is called with `relay_method:local`](https://github.com/monero-project/monero/blob/8f48f464957c875af3183cd9d35769592e1aef48/src/rpc/core_rpc_server.cpp#L1258) with no knowledge of the daemon's fluff/stem epoch status …
> zmq: publish submitted txs via zmq

- src/crypto/keccak.c
If we were to call it with 100, it would cause rsiz to be 0,
leading to an infinite loop.
This is really a pedantic patch, but since there's already a
range test, might as well make it better.
> keccak: error out if passed mdlen 100

- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_basic/cryptonote_format_utils.h
- src/device/device.hpp
- src/device/device_default.hpp
- src/device/device_ledger.cpp
- src/device/device_ledger.hpp
- src/device/log.cpp
- src/device/log.hpp
Pairs with: https://github.com/LedgerHQ/app-monero/pull/110
I tested sending/receiving mainnet txs + tested sending/receiving testnet txs (post-fork), both exporting view key and not.
> ledger support for hf 15 (BP+, view tags) [master]

- contrib/epee/include/net/http_server_handlers_map2.h
- src/daemon/main.cpp
- src/daemon/rpc_command_executor.cpp
- src/rpc/core_rpc_server.h
Quick patch which fixes the issue where if you use some macros from `http_server_handlers_map2.h` you have to be in the `epee` namespace or it doesn't compile. Now can remove `using namespace epee;` from header file `core_rpc_server.h`, which caused a couple of name qualifying mistakes down the line.
> epee: http_server_handlers_map2 macros to use fully qualified names

- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/rpc/core_rpc_server.cpp
~~Also outdated nodes now get 50 fail points instead of 2.~~ Not necessary anymore with #8544.
> rpc: skip bootstrap nodes that are lower than last checkpoint

- tests/unit_tests/epee_boosted_tcp_server.cpp
While updating PR #7345 address sanitizer caught a memory leak due to a `std::shared_ptr` cycle.
> Fix shared_ptr cycle in test_epee_connection.test_lifetime

- src/wallet/wallet2.cpp
@woodser 's suggestion [here](https://github.com/monero-project/monero/pull/8510#issuecomment-1217315218)
> wallet2: Fix missing semi-colon in error message [release]

- src/multisig/multisig_account.cpp
- src/multisig/multisig_account.h
- src/multisig/multisig_account_kex_impl.cpp
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- tests/unit_tests/multisig.cpp
Solves the `invalid multisig seed` error when restoring a multisig wallet, reported by @tmoravec in #8537. Fixes suggested by @UkoeHB.
> multisig accounts no longer store a sum of multisig keyshares in the spend_secret_key slot. Instead it is the 'base multisig privkey', which is the private key used to sign key exchange messages post-update (and for the first step of key exchange both pre and post update). This explains why new multisig wallets are throwing an error (can be fixed by just deleting lines 4750-4754; there is no verification step like this for post-update spend secret keys).
> If restoring from 'multisig keys', presumably the wallet is fully set-up, so it's fine to set the rounds passed [in wallet2::generate()].
Tested restoring both a v0.17.2.0 and v0.18.1.0 multisig wallet …
> multisig: fix seed restore (suggestions by @UkoeHB) [release]

- src/gen_multisig/gen_multisig.cpp
- src/multisig/multisig_account.cpp
- src/multisig/multisig_account.h
- src/multisig/multisig_account_kex_impl.cpp
- src/simplewallet/simplewallet.cpp
- src/simplewallet/simplewallet.h
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/unit_tests/multisig.cpp
- utils/python-rpc/framework/wallet.py
In the default multisig key exchange (account setup) ceremony, every key exchange round requires a message from every signer. That requirement may not be strictly necessary in some real-world use-cases (where it may be safe to assume some or all signers are trustworthy during account setup), so this PR adds an option to 'force-update' key exchange.
- Adds a `force_update_use_with_caution` flag to the `multisig_account::kex_update()` method (it defaults to `false`). That interface change is propagated up the call stack to the `exchange_multisig_keys()` method in `wallet2` and the RPC.
- When force-updating an intermediate key exchange round, you need at least `num_signers - current_round_num` messages from _other_ signers (this is the bare minimum to actually make progress).
- When …
> multisig: force update option for key exchange [master]

- src/common/dns_utils.cpp
- src/common/threadpool.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/ringct/rctSigs.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_payments.cpp
- tests/core_tests/chaingen.h
monerod currently uses a single thread pool for everything, including DNS requests. If it runs on a low-end CPU (less than 8 threads), DNS requests can block incoming transactions handling entirely. This change fixes it by never mixing compute and I/O tasks. I/O thread pool has a fixed size of 8 threads because monerod never does more than 7 parallel DNS requests as far as I can see in the code. Also, 8 I/O threads will process all DNS requests in parallel on low-end CPUs whereas they were processed consecutively before.
> Second thread pool for I/O

- src/common/dns_utils.cpp
- src/common/threadpool.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/ringct/rctSigs.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_payments.cpp
- tests/core_tests/chaingen.h
This is a copy of #8576 for the release-v0.18 branch
> monerod currently uses a single thread pool for everything, including DNS requests. If it runs on a low-end CPU (less than 8 threads), DNS requests can block incoming transactions handling entirely. This change fixes it by never mixing compute and I/O tasks. I/O thread pool has a fixed size of 8 threads because monerod never does more than 7 parallel DNS requests as far as I can see in the code. Also, 8 I/O threads will process all DNS requests in parallel on low-end CPUs whereas they were processed consecutively before.
> Second thread pool for I/O [release-v0.18]

- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- tests/core_proxy/core_proxy.h
- tests/unit_tests/node_server.cpp
update_checkpoints() makes a few DNS requests and can take up to 20-30 seconds to complete (3-6 seconds on average). It is currently called from core::handle_incoming_block() which holds m_incoming_tx_lock, so it blocks all incoming transactions and blocks processing while update_checkpoints() is running. This PR moves it to until after a new block has been processed and relayed, to avoid full monerod locking.
> Move update_checkpoints() to a later stage

- contrib/epee/src/portable_storage.cpp
competing with #8535 
Shrinking a moved `byte_stream` in `byte_slice::byte_slice(epee::byte_stream&&, bool)` is very expensive (in glibc) so avoiding shrinking can speed up storing types to binary in RPC calls. This PR is 1 line instead of 100.
Credit: @vtnerd
> epee: dont shrink slice when storing to binary

- tests/unit_tests/memwipe.cpp
Fixes warnings:
```
warning: ‘*(uint32_t*)quux’ may be used uninitialized [-Wmaybe-uninitialized]
49 |     MDEBUG(std::hex << std::setw(8) << std::setfill('0') << *(uint32_t*)quux);
warning: ‘quux’ may be used uninitialized [-Wmaybe-uninitialized]
50 |     if (wipe) { ASSERT_TRUE(memcmp(quux, "bar", 3)); }
```
> unit_tests: suppress memwipe uninit warnings

- .github/workflows/gitian.yml
- only runs on tag
- each OS uses a separate runner
- hashes get printed on summary page
- the resulting build archives get uploaded as artifacts
> workflows: build gitian on tag

- .github/workflows/build.yml
- .github/workflows/depends.yml
`paths-ignore` has to be added to both push and pull_request, there is no fall through.
> workflows: skip ci when only changing documentation

- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
A user can create a view-only wallet from a normal wallet by calling `createWatchOnly()`. The GUI supports this feature. If the user calls this function from:
The result of `export_outputs()` will have a 0 offset and 0 `num_outputs`, which triggers this error in `import_outputs` (reported in #8614):
https://github.com/monero-project/monero/blob/fc907a957078cae2dc68348886a33363848dd089/src/wallet/wallet2.cpp#L13415-L13416
**Fix:** I updated the error logic of the throw.
Since all key images are known in a normal wallet, `export_outputs()` won't export any of the user's transfers into the fresh view-only wallet; the offset will advance past all of the user's transfers when exporting:
https://github.com/monero-project/monero/blob/fc907a957078cae2dc68348886a33363848dd089/src/wallet/wallet2.cpp …
> wallet: fix create view-only wallet from existing wallet [master]

- src/wallet/api/wallet.h
- tests/core_tests/wallet_tools.h
- tests/trezor/daemon.cpp
- tests/trezor/trezor_tests.cpp
- fix integrated address test, it was not testing integrated address suport
- fix trezor test build as dependent classes were changed
- add a friend test class for Monero::WalletImpl to support wallet api tests When using wallet_api in tests, synthetic chain is used. Without being able to set `allow_mismatched_daemon_version` in the underlying wallet, we are not able to use a synthetic chain with the tests
> fix(trezor-tests): fix trezor tests build, fix integrated addr test

- src/cryptonote_protocol/levin_notify.cpp
- tests/unit_tests/levin.cpp
An IRC user reported a Dandelion++ bug - the `monerod` Dandelion++ implementation does not match the paper exactly. When a user submits their transaction to their `monerod` for broadcasting, if their local daemon is in "fluff" mode their transaction must still be broadcast in "stem" mode. Our current implementation "fluffs" in this situation; now the implementation will "stem" in this situation.
The fallout from this is a potential targeted attack on a user - an attacker tries to fill up a users incoming table, thereby increasing the chances of knowing whether a particular transaction is received over "stem" (or not). If an attacker fills the incoming table, a fluffed transaction either originated at the victim node or 1+ outgoing links from the victim are in fluff mode. The attacker …
> Fix dandelion++ fluff/stem bug with local txes

- src/p2p/net_node.inl
When Node A receives an incoming connection from Node B, Node A will attempt to "back ping" Node B to see if Node B would be a healthy peer to connect to in the future. #8426 introduced a bug that causes Node A to fail to back ping Node B: Node A attempts to read Node B's response over an SSL stream, which errors out (looks like because Node A does not establish an SSL connection with Node B ... [see more on this here](https://github.com/monero-project/monero/issues/8520#issuecomment-1312308716)).
The back ping seems to be [a critical component of the p2p protocol for getting incoming connections](https://github.com/monero-project/monero/issues/8520#issuecomment-1310975634) (also see [this comment](https://github.com/monero-project/monero/blob/365fd45b031b0a5c8104195dfabb786e839cb114/src/p …
> p2p: fix back ping to discover healthy peers to connect to

- src/common/dns_utils.cpp
- src/common/dns_utils.h
- tests/unit_tests/dns_resolver.cpp
Unrelated, but similar code-wise to #8643. There is a check in `DNSResolver` which automatically fails to resolve hostnames which do not contain the `.` character. This PR removes that check.
> DNSResolver: fix not handling hostnames without dot characters

- .github/workflows/build.yml
To avoid any weird Github Actions related DNS issues.
> workflows: set a public DNS when doing tests

- src/crypto/crypto-ops.c
- src/crypto/crypto-ops.h
- src/crypto/crypto.h
- src/ringct/rctOps.cpp
- src/ringct/rctOps.h
- Make some `crypto-ops.c` static methods public. These will be used in PR #8662 for recomputing the main ed25519 generator.
- Allow sorting of key images.
- Add `to_bytes()` methods for converting `ec_point` and `ec_scalar` to unsigned char pointers. These methods are SUPER helpful when doing anything with the `sc_*` methods. Note that there is a variant of this in `device_default.cpp`.
- Rename `rct::ecdhHash()` to `rct::genAmountEncodingFactor()` and make it public.
> [seraphis] crypto: miscellaneous updates

- src/common/data_cache.h
- src/cryptonote_core/blockchain.cpp
- src/ringct/rctSigs.cpp
- src/ringct/rctSigs.h
The problem: block propagation takes up to 1.5 seconds even on a fast 6-core Ryzen with 64 GB RAM and an NVMe SSD because monerod must check all transactions before adding them to the new block. This affects mining pools (including P2Pool) and solo miners the most by increasing block orphan rate.
I discovered it when trying to optimize my P2Pool nodes. What I found is each transaction can be checked by monerod up to 3 times:
- when it's added to the mempool
- when it's added to the new block
- when it's sent via ZMQ to connected P2Pool nodes
Each check does exactly the same calculations, so it can be cached. The main offender here is `verRctNonSemanticsSimple` which doesn't have side effects, so if it gets the same input more than one time, it will return the same result each time. This …
> RingCT cache (huge block propagation speedup)

- contrib/epee/include/net/http_server_handlers_map2.h
this makes it easier to spot those mistakes by the caller
> epee: when loading a JSON RPC payload, ensure params is an object

- src/daemonizer/windows_service.cpp
current behaviour:
1. from a terminal with admin rights `monerod.exe --data-dir G:\\ --install-service`
2. monerod is added to services but not running
3. `monerod.exe --start-service` - runs, and works perfectly
4. restart system - monerod service is "stopped"/not running after boot.
with [SERVICE_AUTO_START:](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/inf-addservice-directive): 
4. restart system - monerod service is running as expected.
notes: (fixed by #8700 )
when service monerod is running, if you `monerod exit` the service gets uninstalled (?). so if e.g. the GUI implements this - clicking 'stop daemon' would uninstall the service, (run time flags will reveal that its in service mode)
> win-service: enable auto startup

- contrib/epee/src/readline_buffer.cpp
As of libreadline >= 8.1, bracketed paste sequences are enabled by default. This turns them off. This along with #8693, should mean that with environment variable `NO_COLOR` present, no escape sequences are generated in the output, just plain text.
> readline_buffer: disable bracketed paste escape sequences

- src/daemonizer/windows_service_runner.h
Issue mentioned by @plowsof in #8697
>when service monerod is running, if you monerod exit the service gets uninstalled (?). so if e.g. the GUI implements this - clicking 'stop daemon' would uninstall the service, (run time flags will reveal that its in service mode)
> daemonizer: don't uninstall windows service on exit

- src/crypto/rx-slow-hash.c
To reduce warning spam when large pages are unavailable.
> RandomX: print VM allocation warnings only once

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/simplewallet/simplewallet.cpp
- src/wallet/node_rpc_proxy.cpp
- src/wallet/node_rpc_proxy.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
This PR improves/optimizes wallet refresh, especially keeping a wallet synced continuously, by reducing the number of RPC calls to the daemon that `wallet2` needs to issue periodically from 3 down to 1. This thus implements the Monero issue https://github.com/monero-project/monero/issues/7571, duplicated as the Haveno issue https://github.com/haveno-dex/haveno/issues/110.
To achieve this the daemon RPC call `getblocks.bin` can now optionally give back info about the tx pool that the wallet uses for early detection of incoming payments and tracking whether transaction sending was successful. The extension to this call works in an incremental way: It does not simply return all the transactions that are currently in the pool, but a list of the transactions that entered the pool since the …
> wallet2, RPC: Optimize RPC calls for periodic refresh from 3 down to 1 call

- src/cryptonote_basic/verification_context.h
- src/cryptonote_config.h
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_core/tx_pool.cpp
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
Related to #6668
This patch limits the maximum size of tx_extra that's allowed in the transaction pool. Mined transactions bypass this check, which means this is a non-consensus change.
I set the limit to 1060 bytes. A typical transaction with 16 outputs needs up to 547 bytes for the transaction public keys, which still leaves 32 bytes of space for some custom data to send to each recipient.
Note that Bitcoin also has a [limit](https://github.com/bitcoin/bitcoin/blob/e325e0fccba4981d28053b79473ddaa44355e6e8/src/kernel/mempool_options.h#L47-L54) for arbitrary data payloads that defaults to a much lower value of just 83 bytes per transaction.
The purpose of this change is to make it harder to "upload" large amounts of unprunable data onto the blockchain. …
> Add a size limit for tx_extra in tx pool

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
The gamma picker and the caller code did not quite agree on the number of rct outputs available for use - by one block - which caused an infinite loop if the picker could never pick outputs from that block but already had picked all other outputs from previous blocks.
Also change the range to select from using code from UkoeHB.
> wallet2: fix infinite loop in fake out selection

- src/cryptonote_basic/verification_context.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
Alternative to #8806, and addresses issue in https://github.com/monero-project/monero/pull/8806#issuecomment-1485863660. So far it is untested.
> cryptonote core/protocol: don't drop peers for soft offenses

- src/crypto/c_threads.h
- src/crypto/rx-slow-hash.c
It's not allowed to use WaitForSingleObject with _beginthread, because the thread closes its own handle before exiting.
So the wait function will either wait on an invalid handle, or on a different handle used by something else.
Or, if it starts waiting before the thread exits, the behavior is undefined according to MS: "If this handle is closed while the wait is still pending, the function's behavior is undefined."
In my test sync I observed threads getting stuck infinitely on WaitForSingleObject, and then rx_set_main_seedhash spamming new threads when RandomX seed changes again. Eventually the system ran out of resources, and monerod aborted with "Couldn't start RandomX seed thread" message. See the attached screenshot of how it looked like before it crashed (note number of threads and …
> Fixed deadlock and crash when syncing with full dataset on Windows

- src/crypto/c_threads.h
- src/crypto/rx-slow-hash.c
> Fixed deadlock and crash when syncing with full dataset on Windows [release-v0.18]

- src/cryptonote_basic/verification_context.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
> cryptonote core/protocol: don't drop peers for soft offenses [release-v0.18] 

- src/ringct/multiexp.cc
- src/ringct/multiexp.h
- Refactors `pippenger_cached_data` to use a vector of `ge_cached` directly. This makes `pippenger_cached_data` reusable (I use it in a multiexp utility in the `seraphis_lib`).
- Exposes `ge_p3` versions of the multiexp functions for efficiency when desired.
- Replaces tabs with spaces in the multiexp notes, so they are legible in text editors that don't render tabs consistently (mine shows all the whitespace in the multiexp notes as single spaces).
> [seraphis] ringct: adjust multiexp

- README.md
https://voidlinux.org/news/2021/02/OpenSSL.html
> README: fix void ssl package

- src/wallet/wallet_rpc_server.cpp
it's too low a limit (at least one person mentioned having to call create_address in a loop due to it)
> wallet_rpc_server: allow creating more than 64 addresses at once

- CMakeLists.txt
As you can see in [this post](https://stackoverflow.com/questions/44719963/cmake-default-value-for-options-doesnt-work), CMake options are cached and the values are not updated with the `option` command if they already exist in the cache. The effect of this for debug builds is that when a debug build is run after a release build, the debug utilities are not built. This PR makes it so that the debug utilities are build always during and only during debug builds.
> build: fix BUILD_DEBUG_UTILITIES

- src/cryptonote_basic/cryptonote_basic_impl.h
It's spamming build logs with: 
```
monero/src/cryptonote_basic/cryptonote_basic_impl.h:43:29: warning: ‘template<class _Arg, class _Result> struct std::unary_function’ is deprecated [-Wdeprecated-declarations]
43 |   struct array_hasher: std::unary_function<t_array&, std::size_t>
|                             ^~~~~~~~~~~~~~
```
> cryptonote_basic: remove unused struct

- src/cryptonote_basic/cryptonote_basic.h
My IDE can't parse anything after this line.
> cryptonote::transaction_prefix: fix IDE parsing error

- src/wallet/wallet2.cpp
it was mistaking the number of forks in the fork table for the last fork
> wallet2: fix outdated wallet check

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Refines #8076 by reducing side effects of new pool state methods. This will make integrating `m_pool_info_query_time` into `NodeRPCProxy` easier.
> wallet2: make m_process_pool_txs local to refresh method

- .github/workflows/build.yml
- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/node_rpc_proxy.cpp
- src/wallet/node_rpc_proxy.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
- src/wallet/wallet_rpc_server.cpp
- tests/README.md
- tests/functional_tests/CMakeLists.txt
- tests/functional_tests/transfer.py
- Calling `scan_tx` on already processed received txs causes duplicates. (#8531)
- Scanning txs out of order can corrupt the wallet and render it unable to recover from a reorg correctly.
- Coinbase txs don't get scanned as miner txs via `scan_tx`.
- If a user provides a tx with height > the wallet's known scan height, `get_transfers` will return inaccurate num confirmation data for that tx until the wallet refreshes.
- If a wallet has already processed an **incoming** tx in the pool, the tx is then mined, and then the user calls `scan_tx` with that tx before the wallet refreshes, the tx will be in a state of both "unconfirmed" and "confirmed" until the wallet refreshes.
- `scan_tx` now requires a trusted daemon edit: if the user attempts to scan a tx that is not their most recent tx. I …
> wallet2: fix rescanning tx via scan_tx [release]

- .github/workflows/copyright.yml
creates a pull request on the 1st of January
> ci: update copyright

- contrib/epee/include/net/abstract_tcp_server2.inl
See issue https://github.com/monero-project/monero/issues/8685
Specifically the comment/patch by @j-berman https://github.com/monero-project/monero/issues/8685#issuecomment-1396659121
monerod would start using 160-180% CPU after a few days of uptime.
I was consistently running into this issue for multiple months.
With this patch monerod has been running for two weeks already, without high cpu usage.
Related/Same issue https://github.com/monero-project/monero/issues/8550
> epee net tcp server: properly terminate interrupted TCP connection. fixes #8685

- src/daemon/main.cpp
- src/daemonizer/daemonizer.h
- src/daemonizer/posix_daemonizer.inl
- src/daemonizer/windows_daemonizer.inl
- src/wallet/wallet_rpc_server.cpp
~~Considering that non-interactive and all system flags are allowed in config file of wallet-rpc, I believe the user request is founded.~~
EDIT: jtgrassie has justly pointed out that non-interactive is a dummy option for wallet-rpc, so this becomes a question of whether the user is indulged or not.
Only non-interactive is allowed, the system flags are still not allowed in config for monerod.
The anonymous namespace in Deamonizer.h makes things complicated as well as the fact that wallet_rpc uses the class too. I reworked daemonizer::init_options to accomodate both the new option for monerod and the status quo in wallet_rpc, without breaking encapsulation. Trivial changes either break wallet_rpc or allow all options for monerod. The latter is a one liner, but for the sake of accuracy it …
> Allow option 'non-interactive' in monerod config file

- README.md
Alpine Linux has a package for monero: https://pkgs.alpinelinux.org/package/edge/community/x86/monero    
You can also view the APKBUILD source here: https://git.alpinelinux.org/aports/tree/community/monero/APKBUILD
> Added Alpine Linux to list of packages in README

- src/cryptonote_basic/miner.cpp
Copy of #8831 for master branch.  Closes #8821
> Fixed RandomX initialization when mining from scratch

- src/cryptonote_core/cryptonote_core.cpp
Force sync every 100k blocks instead of every 1k blocks. Bumping this value is reported to make a big difference in sync performance, eg: https://github.com/monero-project/monero/issues/8189
> bump lmdb sync threshold for performance

- src/cryptonote_basic/cryptonote_format_utils.cpp
On systems where `ULONG_MAX` != `ULLONG_MAX` (e.g. most 32-bit systems), the `round_money_up` function will not correctly detect overflows.
> cryptonote_basic: fix amount overflow detection on 32-bit systems

- contrib/epee/include/byte_stream.h
Both of these are needed for the new serialization format, but might be useful for other purposes.
> Add byte_stream `value_type` and `data()`

- contrib/epee/include/hex.h
- contrib/epee/src/hex.cpp
- tests/unit_tests/epee_utils.cpp
Adds `to_hex::buffer` which is used by #8867 . This prevents allocations in some use cases.
> Add to_hex::buffer

- contrib/depends/packages/openssl.mk
Includes security fixes: https://www.openssl.org/news/openssl-1.1.1-notes.html
For the master branch, I have an open PR to upgrade to 3.0.9 (#8767) as the 1.1.1 series will be EOL soon (#8763).
> depends: update openssl to 1.1.1u [release-v0.18]

- src/wallet/wallet_rpc_server_commands_defs.h
Prereq of #8861 
Reorganizing the transfer response structs make it easier to makes changes to the responses in bulk and makes sure that there aren't weird discrepancies introduced between the endpoints for end users.
> wallet_rpc_server: dedup transfer RPC responses

- contrib/epee/include/net/net_ssl.h
- contrib/epee/src/net_ssl.cpp
- src/gen_ssl_cert/gen_ssl_cert.cpp
- src/rpc/core_rpc_server.cpp
This PR adds a new file to the data directory: `rpc_ssl.fingerprint`. This is a convenience file that stores the SHA-256 X509 digest of the PEM certificate at `rpc_ssl.crt`. This is ease-of-use improvement for those who want to manually add their node's fingerprint to the CLI wallet / other application (and hopefully GUI eventually, working on that currently). Now there aren't any commands to memorize; no searching for which types of fingerprints `net_ssl` uses. I hope this encourages more users to utilize secure connections over RPC.
There are 4 four part of this PR:
1. Move `get_fingerprint` function from `gen_multisig` to `net_ssl` (to be used below)
2. In `store_ssl_keys` (when storing the `.crt` and `.key` files for the first time), we now also store the `.fingerprint` file
3. Add …
> core_rpc_server: new file: rpc_ssl.fingerprint

- src/crypto/CMakeLists.txt
- src/crypto/generators.cpp
- src/crypto/generators.h
- tests/unit_tests/crypto.cpp
- Provide direct access to different representations of canonical fixed generators.
- Includes automatic validation of generator constants in debug mode.
**Future work**
- Add seraphis generators `X` and `U`.
> [seraphis] crypto: add generators file

- src/common/util.cpp
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/util.cpp
Alternative to #8849. 
I'm not convinced we need to support DNS lookup at all here. This PR considers a node "local" if the host is "localhost" or a IPv{4,6} address in the loopback range. The `is_privacy_preserving_network` check is no longer needed.
> common: do not use DNS to determine if address is local

- src/wallet/wallet_rpc_server_commands_defs.h
> wallet_rpc_server: dedup transfer RPC responses [RELEASE]

- src/common/perf_timer.cpp
All Monero binaries have 1 second startup delay because of this code. This is especially noticeable and affects UX in Monero GUI wallet with local node where it often starts another monerod instance to run commands and query node status.
> Speed up perf_timer init on x86

- src/common/perf_timer.cpp
All Monero binaries have 1 second startup delay because of this code. This is especially noticeable and affects UX in Monero GUI wallet with local node where it often starts another monerod instance to run commands and query node status.
> Speed up perf_timer init on x86 [release-v0.18]

- contrib/epee/src/net_ssl.cpp
This was found while running LWS, but I don't see a reason to _not_ fix this upstream.
Someone was trying a connection to a cloudflare site (webhooks) - which requires SSL SNI usage to work correctly - and combined it with a call to **not** verify the cloudflare server. It took me a while to track down the issue: we only set SNI when verifying the server certificate. There's no reason for this, it can be used with or without verifying the certificates.
> Set SSL SNI even when server verification is disabled

- src/serialization/json_object.cpp
- src/serialization/json_object.h
ZMQ serialization was not updated when CLSAGs were added to the monero transaction. This PR fixes that, so that txpool push messages can compute the full tx_hash correctly.
> Add CLSAG serialization to ZMQ code

- src/serialization/json_object.cpp
- src/serialization/json_object.h
Identical to #8903 but on release branch.
> Add CLSAG serialization to ZMQ code [0.18]

- src/common/dns_utils.cpp
Looks like the extra MWARNING was supposed to be guarded by the if statement.
> Fixup error message.

- contrib/epee/include/net/http_client.h
Right now, HTTP headers and the HTTP body are sent separately. This PR change sends the bodies and headers combined when appropriate. For small bodies, this can reduce the number of packets sent by 1. For a series of HTTP requests made with small bodies, the number of round trips can be reduced by up to 50%. 
You can test this by analyzing HTTP traffic with a packet sniffer like Wireshark.
> http_client: reduce number of packets sent for small bodies

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/simplewallet/simplewallet.cpp
- src/wallet/node_rpc_proxy.cpp
- src/wallet/node_rpc_proxy.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
This is the 0.18 release branch version of my PR #8076 already merged into master, with two commits, the main one from me and a second one with further improvements from @j-berman.
Conflicts that I had to resolve were minimal.
> wallet2, RPC: Optimize RPC calls for periodic refresh from 3 down to 1 call [release-v0.18]

- src/net/tor_address.cpp
- src/net/tor_address.h
- tests/unit_tests/net.cpp
v2 onion addresses were [removed](https://support.torproject.org/onionservices/v2-deprecation/) in October 2021.
Closes #7831
> net: tor_address: remove support for v2 onion addresses

- contrib/epee/include/serialization/wire.h
- contrib/epee/include/serialization/wire/adapted/list.h
- contrib/epee/include/serialization/wire/adapted/vector.h
- contrib/epee/include/serialization/wire/error.h
- contrib/epee/include/serialization/wire/field.h
- contrib/epee/include/serialization/wire/fwd.h
- contrib/epee/include/serialization/wire/traits.h
- contrib/epee/include/serialization/wire/wrapper/defaulted.h
- contrib/epee/include/serialization/wire/write.h
This PR contains the write serialization interface, and some glue code from #8867 . This does **not** replace any existing serialization; the goal is to start a discussion on the design of the write system.
The write system - for epee binary - is roughly 56% faster than the existing design. This is primarily due to the removal of the intermediate DOM building stage - everything is written directly from objects to the "sink". I will work on JSON output numbers later.
The code for epee binary writing and json writing is not included, that can be reviewed in a future PR.
> Write interface for new serialization system

- src/wallet/wallet2.cpp
Though highly unlikely today, it's theoretically possible to distinguish transfers from sweeps by the tx fee.
This PR ensures transfers and sweeps both use the result of `calculate_fee` as the tx fee (calculated using the tx's weight).
In a **sweep**: wallet2 first uses `estimate_fee` to get a baseline guess for the amount(s) to send, but will then use the result of `calculate_fee` as the tx fee.
In a **transfer**: wallet2 first uses `estimate_fee` as the tx fee. **If and only if** `calculate_fee` is larger than the result of `estimate_fee`, then it will use `calculate_fee`. Note that in practice today, the estimate is extremely likely to *under*-estimate the fee, therefore transfers are very likely to use `calculate_fee`, the same as sweeps today.
Modify transfers to use the fee from …
> wallet2: ensure transfers and sweeps use same fee calc logic

- contrib/epee/include/span.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/functional_tests/multisig.py
- utils/python-rpc/framework/wallet.py
If the field `enable_multisig_experimental` in the command `restore_deterministic_wallet` is set to `true`, `monero-wallet-rpc` will attempt to generate the wallet from a multisig seed instead of a normal seed, allowing the multisig wallet user to not have to resync initialization data. This multisig seed is the same data provided from `query_key_info`.
Edit: Also restoring from multisig seed now works when M <= N-2 and with any number of private multisig keys.
> wallet-rpc: restore from multisig seed (and fix generation)

- contrib/epee/include/span.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/functional_tests/multisig.py
- utils/python-rpc/framework/wallet.py
> wallet-rpc: restore from multisig seed (and fix generation) [RELEASE]

- src/wallet/wallet2.cpp
> wallet2: when checking frozen multisig tx set, don't assume order

- src/wallet/wallet2.cpp
Fixes #8951
On some envs, `scan_tx` throws when a synced wallet scans a tx older than the wallet's most recent tx and the wallet has lots of txs between those 2 txs.
Essentially it's possible for this to throw:
```cpp
std::vector<int> v;
for (int i = 0; i < 32; ++i) v.push_back(i);
std::sort(v.begin(), v.end(), [](const int l, const int r) {
if (l == r) throw std::runtime_error("Compared elem with itself");
return l < r;
});
```
I incorrectly assumed this was not possible ([reasoning](https://stackoverflow.com/questions/38966516/should-sorting-algorithm-pass-same-element-in-the-comparison-function) for why an `std::sort` implementation chooses to compare an element against itself).
Return false when comparing equal elems in the custom comparator; the comparator must meet the following …
> wallet2: fix `scan_tx` custom compare function incorrectly throwing on some envs

- docs/ANONYMITY_NETWORKS.md
Squashed version of #8898
Removed version 2 onion addresses as they're deprecated from TOR and updated I2P/Tor Stream Used Twice section to reference tweets relevant to section.
Fixed grammatical errors and changed the wording within the Wallet RPC section to better explain the differences between a I2P hidden service and a TOR hidden service.
> docs: update ANONYMITY_NETWORKS

- src/wallet/wallet2.cpp
The Monero GUI code was calling `Monero::wallet::setPassword()` on every open/close for some reason, and the old `store_to()` code called `store_keys()` with `watch_only=false`, even for watch-only wallets. This caused a bug where the watch-only keys file got saved with with the JSON field `watch_only` set to 0, and after saving a watch-only wallet once, a user could never open it back up against because `load()` errored out. This never got brought up before this because you would have to change the file location of the watch-only wallet to see this bug, and I guess that didn't happen often, but calling the new `store_to()` function with the new `force_rewrite` parameter set to `true` triggers key restoring and the bug appeared.
> wallet: store watch-only wallet correctly when `change_password()` is called

- src/wallet/wallet2.cpp
The Monero GUI code was calling `Monero::wallet::setPassword()` on every open/close for some reason, and the old `store_to()` code called `store_keys()` with `watch_only=false`, even for watch-only wallets. This caused a bug where the watch-only keys file got saved with with the JSON field `watch_only` set to 0, and after saving a watch-only wallet once, a user could never open it back up against because `load()` errored out. This never got brought up before this because you would have to change the file location of the watch-only wallet to see this bug, and I guess that didn't happen often, but calling the new `store_to()` function with the new `force_rewrite` parameter set to `true` triggers key restoring and the bug appeared.
> wallet: store watch-only wallet correctly when `change_password()` is called [RELEASE]

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
max_blocks is last on master branch
Reported by dynemeloun on IRC.
> wallet2: fix refresh function parameters [release-v0.18]

- src/cryptonote_core/blockchain.cpp
- tests/unit_tests/long_term_block_weight.cpp
The long term block weight cache was doing a wrong calculation when adding new blocks to the cache, which means nodes that have refreshed the cache could have different values stored in the cache than nodes that haven't.
> Fix ltw cache

- src/cryptonote_core/blockchain.cpp
- tests/unit_tests/long_term_block_weight.cpp
> Fix ltw cache [release-v0.18]

- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/blockchain_db/testdb.h
- src/cryptonote_basic/cryptonote_basic_impl.cpp
- src/cryptonote_basic/cryptonote_basic_impl.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server.h
- src/rpc/core_rpc_server_commands_defs.h
- tests/functional_tests/functional_tests_rpc.py
- tests/functional_tests/k_anonymity.py
- tests/unit_tests/lmdb.cpp
- utils/python-rpc/framework/daemon.py
Read more about k-anonymity [here](https://en.wikipedia.org/wiki/K-anonymity). We implement this feature in the monero daemon for transactions by providing a "Txid Template", which is simply a txid with all but `num_matching_bits` bits zeroed out, and the number `num_matching_bits`. We add an operation to `BlockchainLMDB` called `get_txids_loose` which takes a txid template and returns all txids in the database (chain and mempool) that satisfy that template. Thus, a client can ask about a specific transaction from a daemon without revealing the exact transaction they are inquiring about. The client can control the statistical chance that other TXIDs (besides the one in question) match the txid template sent to the daemon up to a power of 2. For example, if a client sets their …
> blockchain_db: add optional k-anonymity to txid fetching

- src/multisig/multisig_kex_msg.cpp
Resolves https://github.com/monero-project/monero/issues/8493. In the test for magic: `m_msg.substr(0, MULTISIG_KEX_V1_MAGIC.size())`, if the message was smaller than the magic, then a `substr` exception would be thrown.
> multisig: better errors for small malformed kex msgs

- contrib/epee/include/serialization/keyvalue_serialization.h
- src/rpc/core_rpc_server_commands_defs.h
- src/wallet/message_transporter.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/unit_tests/net.cpp
Prereq of https://github.com/monero-project/monero/pull/8867
> `KV_SERIALIZE`: remove extraneous semicolons in DSL

- external/easylogging++/ea_config.h
Relates to [this comment](https://github.com/monero-project/monero-gui/issues/3034#issuecomment-1149216693) in monero-project/monero-gui#3034. This commit allows monero-gui to compile successfully on FreeBSD.
Note: I tried putting `!defined __FreeBSD__` within the existing parentheses in the if statement, but it would never work. The way I have done it at least preserves the existing part. If there's a better way, it would be nice to know!
> ea_config: define ELPP_FEATURE_CRASH_LOG for freebsd

- src/wallet/wallet2.cpp
Fixes:
- create a new wallet
- set restore height to 0
- wallet fails to sync with `Error: refresh failed: refresh error: Unexpected hard fork version v1 at height 0. Make sure the node you are connected to is running the latest version. Blocks received: 0`
Synced a wallet restored from 0 with this change.
> wallet2: fix version check at hf version 1

- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/main.cpp
Setting the data directory this way is nice when the unit tests write to files while running (see new `store_to()` PR). Otherwise, files in the data directory will show up on git and you won't be able to have copies for different branches when running tests from root source directory. I also have wanted `--log-level` in the unit tests for a while now.
> unit_tests: set data dir relative to exe & add log-level arg

- src/cryptonote_basic/account_generators.h
This is a PR in my 'upstreaming seraphis_lib project', it is not used anywhere yet.
- Adds `account_generators.h` to `cryptonote_basic`.
Multisig account generation is the same for ringct and seraphis, so it's best to reuse all that code if possible. The only difference is the base generators used. Refactoring multisig accounts to depend on `account_generator_era` will allow seraphis to be easily supported.
- Refactor multisig accounts to use `account_generator_era`.
- Introduce seraphis generators.
> [seraphis] cryptonote_base: add account generators

- contrib/depends/packages/openssl.mk
- contrib/depends/packages/unbound.mk
>OpenSSL 1.1.1 series has reached its End of Life (EOL). As such it will no longer receive publicly available security fixes.
https://www.openssl.org/blog/blog/2023/09/11/eol-111/
This PR is based on #8767.
> depends: openssl: update to 3.0.11 [release]

- contrib/depends/packages/packages.mk
It is unused. easylogging++ [is used instead](https://github.com/monero-project/monero/blob/master/CMakeLists.txt#L537) when building with GCC, which is used for all Linux builds in depends.
We could use libunwind for FreeBSD, so I'm keeping the package definition in case someone wants to fix that build.
> depends: unwind: do not build for linux hosts

- contrib/gitian/gitian-linux.yml
Requires #9026
Test build to compare if hashes are reproducible
```
./gitian-build.py --setup --docker --url https://github.com/selsta/monero github-actions riscv-gitian
15:59 
./gitian-build.py --docker --detach-sign --no-commit --build -j 3 -o l --url https://github.com/selsta/monero github-actions riscv-gitian
15:59 
```
```
688fd44ffa1dd27b8a48e2abc1ead1e0bfb048f6acd9e7ac97b200e2d3697b48  monero-riscv64-linux-gnu-c56932183.tar.bz2
```
> gitian: add riscv64 support

- src/cryptonote_config.h
Header was using `uint64_t` without including `<cstdint>` which caused some issues downstream for windows builds
> cryptonote_config: include cstdint

- src/cryptonote_config.h
Header was using `uint64_t` without including `<cstdint>` which caused some issues downstream for windows builds
> cryptonote_config: include cstdint [RELEASE]

- src/ringct/rctTypes.h
Accessing an object of type `char` thru an lvalue of type `crypto::hash8` is undefined behavior. https://developers.redhat.com/blog/2020/06/03/the-joys-and-perils-of-aliasing-in-c-and-c-part-2
> ringct: make `rctSigBase` serialization follow strict aliasing rule

- src/crypto/jh.c
- Fixed uninitialized `state->x` warning
- Fixed broken code with `-O3` or `-Ofast`
The old code is known to break GCC 10.1 and GCC 11.4
Closes #9041
> JH hash compiler workarounds

- tests/core_tests/wallet_tools.cpp
Reported by @Gingeropolous
```
/home/user/monero/tests/core_tests/wallet_tools.cpp:42:86: error: call of overloaded ‘process_transactions(boost::assign_detail::generic_list<tools::wallet2*>, const std::vector<boost::variant<cryptonote::block, cryptonote::transaction, std::vector<cryptonote::transaction, std::allocator<cryptonote::transaction> >, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings, event_replay_settings> >&, const cryptonote::block&, block_tracker&, const boost::optional<crypto::hash>&)’ is ambiguous
process_transactions(boost::assign::list_of(wallet), events, blk_head, bt, blk_tail);
^
/home/user/monero/tests/core_tests/wallet_tools.cpp:40:6: note: candidate: static void …
```
> core_tests: fix gcc7 compilation

- tests/CMakeLists.txt
- tests/unit_tests/main.cpp
Fixes #8987
Instead of using raw `argv[0]`, first we resolve `argv[0]` then get parent's parent for test root dir. Also, the ctest suite was using the wrong tests/data folder: the one at the source root, not inside the build dir.
> unit tests: fix running from pwd and ctest selected location

- contrib/epee/src/readline_buffer.cpp
> readline_buffer: disable bracketed paste escape sequences [RELEASE]

- src/wallet/wallet2.cpp
Since we are required to check for uniqueness of decoy picks within any given ring, and since some decoy picks may fail due to unlock time or malformed EC points, the wallet2 decoy selection code was building up a larger than needed *unique* set of decoys for each ring according to a certain distribution *without replacement*. After filtering out the outputs that it couldn't use, it chooses from the remaining decoys uniformly random *without replacement*.
The problem with this is that the picks later in the picking process are not independent from the picks earlier in the picking process, and the later picks do not follow the intended decoy distribution as closely as the earlier picks. To understand this intuitively, imagine that you have 1023 marbles. You label 512 marbles with the …
> wallet: mitigate statistical dependence for decoy selection within rings

- src/wallet/wallet2.cpp
Fixes an issue where owned output key images are not always [included](https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L7324) in the signed transaction.
Tx pub keys for single destination transactions to a subaddress are calculated [differently](https://github.com/monero-project/monero/blob/master/src/cryptonote_core/cryptonote_tx_utils.cpp#L385).
> wallet: sign_tx: get tx pubkey from extra

- src/rpc/zmq_server.cpp
A user reported over IRC that connecting to the ZMQ-RPC server via web browser would crash the ZMQ-RPC permanently, until restart. After investigation, I found out that this only happens when the ZMQ-PUB server is also enabled.
When ZMQ-PUB is enabled, the ZMQ server switches to `zmq_poll` instead of using a blocking read with `zmq_read`. Invalid messages are not handled by the `zmq_poll`, and instead are left to `zmq_read` to filter out. So a "spurious" wakeup is done for `zmq_poll` only to be given an `EAGAIN` error by `zmq_read`.
This should finally clear out the longstanding issue from #8199 - now that I know whats happening, I think this is the only fix. #8592 is being closed too.
> Fix EAGAIN bug in ZMQ-RPC/ZMQ-PUB

- src/wallet/message_transporter.cpp
The MMS had some problems with the latest version of PyBitmessage that you can download [here](https://appimage.bitmessage.org/releases/20230116/) as an appimage when doing auto-config. Simply ignoring 2 errors more does the trick, as can be seen in the simple changes of this PR.
-------
Note that the development of PyBitmessage currently goes forward only very slowly, if at all, and that is still runs on Python 2, which is a problem because that's "end of life" and does not receive security updates anymore. The appimage mitigates that a bit, because you don't have to add that unsafe Python 2 permanently to your system, but still.
The MMS encrypts all messages before it hands them over to PyBitmessage, so it should be hard to break into the MMS by using a PyBitmessage exploit.
> MMS: Ignore 2 more API errors thrown by latest PyBitmessage

- contrib/epee/include/serialization/wire/write.h
I was going to "fix" this with C++17 `std::size`, but instead decided to continue using `boost::size` with a compile-time check.
Background:
Getting the size/count of a "range" of elements is tricky if the range iterator is _not_ random access. `std::size` fails on such ranges, and `boost::size` uses `std::distance` on such ranges. The problem with the boost approach is that input iterators are single-pass, and therefore the `std::distance` invalidates/exhausts the range before it is written!
This check simply verifies that the range is using `std::forward_iterator` tag or better when `boost::size` is called. Input iterators can still be used, but only with the `json_writer` class directly (i.e. not through base class, `epee_writer`, or `msgpack_writer`). Also (a theoretical) …
> Add compile-time check for input iterators in ::wire array writing

- src/cryptonote_basic/tx_extra.h
- src/serialization/container.h
- src/serialization/debug_archive.h
- src/serialization/difficulty_type.h
- src/serialization/pair.h
- src/serialization/serialization.h
- src/serialization/tuple.h
- src/serialization/variant.h
- tests/unit_tests/serialization.cpp
Resolves #8687
Before, when you tried to serialize a type which 1) was missing its `do_serialize` free function  and 2) was marked with `is_basic_type<T>`, we would end up calling `do_serialize<Archive, T>(Archive&,T&)`, which called `serializer<Archive, T>::serialize(Archive&, T&)`, which called `serializer<Archive, T>::serialize(Archive&, T&, boost::false_type, boost::false_type, boost::true_type)`, which called `do_serialize<Archive, T>(Archive&,T&)`, so on and so forth.
Now, instead of complicating dispatch by inserting a struct to make function expression calls name-dependent, we just use ADL and function overloading.
> serialization: fix infinite loops and clean up dispatching

- contrib/epee/src/http_auth.cpp
Clang now reports that `std::result_of` is deprecated in C++17. The replacement is `std::invoke_result`.
> Change std::result_of to auto

- CMakeLists.txt
`FindPythonInterp` no longer works by default with CMake 3.27 and produces the following warning:
> CMake Warning (dev) at CMakeLists.txt:40 (include):
>   Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
>   are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
>   the cmake_policy command to set the policy and suppress this warning.
https://cmake.org/cmake/help/latest/module/FindPythonInterp.html
`cmake_minimum_required` [resets](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#policy-settings) policy settings, so we need to move it to the top. `FindPythonInterp` is used elsewhere.
Alternatively, we could change it to `FindPython3`, but this would [require](https://cmake.org/cmake/help/latest/module/FindPython3.html) …
> cmake: silence FindPythonInterp warning

- src/cryptonote_basic/tx_extra.h
- src/rpc/rpc_payment.h
- src/serialization/container.h
- src/serialization/containers.h
- src/serialization/debug_archive.h
- src/serialization/difficulty_type.h
- src/serialization/pair.h
- src/serialization/serialization.h
- src/serialization/tuple.h
- src/serialization/variant.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- tests/unit_tests/serialization.cpp
Some downstream code (most notably PR https://github.com/UkoeHB/monero/pull/25) wants to use the src/serialization lib
for storing information persistently. When one builds classes/machines wishing to serialize containers, they must use
the `serializable_*` container classes. In this case, this makes the Seraphis library code unnecessarily tightly coupled
with the src/serialization code since one cannot swap out their type of storage format without major refactoring of class
field types. By serializing STL containers directly, we can abstract the serialization details away, making for much
cleaner design. Also small bonus side effect of this change is that STL containers with custom Comparators, Allocators,
and Hashers are serializable.
Depends upon …
> serialization: remove container wrappers and serialize directly

- src/rpc/daemon_messages.cpp
- tests/unit_tests/json_serialization.cpp
Found a major bug in ZMQ-RPC. None of the top-level messages check for `IsObject()` before attempting to read members, as-if it were in object. Every sub-object has this check already.
> Fix missing checks for IsObject in ZMQ jsonrpc reading

- src/rpc/daemon_messages.cpp
- tests/unit_tests/json_serialization.cpp
Same as #9079 but on release branch.
> Fix missing checks for IsObject in ZMQ jsonrpc reading [0.18]

- tests/unit_tests/node_server.cpp
The test node_server.bind_same_p2p_port fails by default on OpenBSD for at least the debug build. Using the same ifconfig command as described for MacOS results in the test passing.
Submitted on IRC
> OpenBSD: node server fix IP localhost by aliasing

- contrib/epee/include/storages/portable_storage_from_bin.h
Fixes compilation as we treat some warnings as errors as of https://github.com/monero-project/monero/pull/7481.
Closes #8622
> storages: add missing return

- .github/workflows/copyright.yml
author is now copyCat. 2nd commit allows the workflow to be manually run (separate so it can be reverted)
closes #9109
> workflows: copyright commit author

- CMakeLists.txt
Allows people to compile if their CMake is older than 3.27
@tobtoht
> CMake: only set policy CMP0148 to OLD if version >= 3.27

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/functional_tests/transfer.py
- tests/unit_tests/epee_utils.cpp
- utils/python-rpc/framework/wallet.py
To transfer ~5 XMR to an address such that your balance drops by exactly 5 XMR, provide a `subtractfeefrom` flag to the `transfer` command. For example:
transfer 76bDHojqFYiFCCYYtzTveJ8oFtmpNp3X1TgV2oKP7rHmZyFK1RvyE4r8vsJzf7SyNohMnbKT9wbcD3XUTgsZLX8LU5JBCfm 5 subtractfeefrom=all
If my walet balance was exactly 30 XMR before this transaction, it will be exactly 25 XMR afterwards and the destination address will receive slightly less than 5 XMR. You can manually select which destinations fund the transaction fee and which ones do not by providing the destination index. For example:
transfer 75sr8AAr... 3 74M7W4eg... 4 7AbWqDZ6... 5 subtractfeefrom=0,2
This will drop your balance by exactly 12 XMR including fees and will spread the fee cost equally over destinations with addresses …
> wallet: feature: transfer amount with fee included

- tests/unit_tests/epee_serialization.cpp
Good news: this property holds for current epee binary code in core repo. For real world example of issue brought on if this property is not upheld: https://github.com/monero-rs/monero-epee-bin-serde/issues/49
> epee binary: container can read from empty seq of any type

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/functional_tests/transfer.py
- tests/unit_tests/epee_utils.cpp
- utils/python-rpc/framework/wallet.py
> wallet: feature: transfer amount with fee included [RELEASE]

- src/wallet/wallet2.cpp
Calls the `on_reorg` callback inside `handle_reorg`, instead of inside `detach_blockchain`.
`detach_blockchain` can be called even where there isn't a reorg (see how `scan_tx` uses `detach_blockchain`). `handle_reorg` should be called every time there is a reorg.
> wallet2: fix `on_reorg` callback location

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
#8716 and #9006 applied to release
> wallet2: add on_reorg callback [release]

- contrib/depends/config.guess
- contrib/depends/config.sub
The files are exact copies from the original repository (git://git.savannah.gnu.org/config.git), in commit 28ea239c53a2d5d8800c472bc2452eaa16e37af2. The main reason for the update is because loongarch was mentioned in PR #9114 and new the latest config files handle loongarch, as well as WASM64, since the old files only cover WASM32. Tandem NSX and IA16, are also handled in the newest config files, which covers the changes TheCharlatan made in 2018.
> depends: update config scripts

- .github/workflows/build.yml
GitHub runners bundle a number of unnecessary packages, including a newer version of CMake. Runners prefer using bundled libraries and binaries over explicitly installed packages by default.
The CI build environment should match the expected environment (e.g. Ubuntu 20.04) as closely as possible, in order to mitigate unintended build system regressions.
See: https://github.com/monero-project/monero/pull/9126#issuecomment-1900128008
This PR needs #9126 to pass CI.
> actions: remove unnecessary packages

- src/wallet/wallet2.cpp
> wallet: mitigate statistical dependence for decoy selection within rings [RELEASE]

- contrib/epee/include/misc_language.h
a) Use `make_shared` which removes one extra allocation [1]. 
b) Port from `boost::shared_ptr` to `std::shared_ptr`.
c) use `= default` syntax instead of ` {} `. Which is cleaner.
1. https://stackoverflow.com/a/20895705
> Cleanup extra memory allocation, and port boost to std shared_ptr

- src/net/i2p_address.cpp
- src/net/i2p_address.h
- src/net/parse.cpp
- src/p2p/net_peerlist_boost_serialization.h
- tests/unit_tests/net.cpp
This should fix #8918 , but I am soliciting for tests before marking this as ready. Basically, I only know this passes the unit tests at this point.
The patch is pretty simple, I2P ports are now fixed at `0`, so opening the new pearliest manager should collapse the overloads on port once it goes into the internal map.
> Disable/fix ports with I2P

- src/net/i2p_address.cpp
- src/net/i2p_address.h
- src/net/parse.cpp
- src/p2p/net_peerlist_boost_serialization.h
- tests/unit_tests/net.cpp
Same as #9138 but on the release branch.
> Disable/fix ports with I2P [0.18]

- contrib/depends/funcs.mk
- contrib/depends/packages/unbound.mk
Security release: https://github.com/NLnetLabs/unbound/releases/tag/release-1.19.1
- Unbound 1.19.1 uses WSAPoll, which is only defined in winsock2.h if `_WIN32_WINNT >= 0x600` (Windows Vista).
- mingw in the gitian build environment defaults to `0x502` (Windows Server 2003, see: `/usr/share/mingw-w64/include/_mingw.h`), so set it explicitely
> depends: unbound: update to 1.19.1

- contrib/depends/funcs.mk
- contrib/depends/packages/expat.mk
- contrib/depends/packages/openssl.mk
- contrib/depends/packages/unbound.mk
Security fixes. #9163, #9164, #9165.
- Tested OpenAlias resolution and monerod DNS update check on Linux and Windows depends builds.
> depends: update expat, unbound, openssl [RELEASE]

- contrib/depends/packages/android_ndk.mk
- contrib/depends/patches/android_ndk/api_definition.patch
Splitting this out of #9162, since it also resolves an Android depends build issue here: https://github.com/seraphis-migration/monero/pull/16.
See related CI run: https://github.com/tobtoht/monero/commits/pr-16/
> depends: android_ndk: update to 18b

- docs/ANONYMITY_NETWORKS.md
Follow up for https://github.com/monero-project/monero/pull/9142
> docs: omit i2p port number from ANONYMITY_NETWORKS [release-v0.18]

- contrib/depends/packages/eudev.mk
- Repo was moved to https://github.com/eudev-project/eudev (old repo redirects)
- Changelog: https://github.com/eudev-project/eudev/releases
> depends: eudev: update to 3.2.14

- .github/workflows/build.yml
- .github/workflows/copyright.yml
- .github/workflows/depends.yml
- .github/workflows/gitian.yml
>Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20
See, e.g.: https://github.com/monero-project/monero/actions/runs/7950975630
> actions: update to v4 actions

- README.md
Void Linux decided to remove all cryptocurrency related packages including Monero from their official repositories. See https://github.com/void-linux/void-packages/pull/44422
Added instructions for NixOS: https://search.nixos.org/packages?channel=23.11&show=monero-cli&type=packages&query=monero
> Remove instructions for Void Linux, add NixOS

- tests/unit_tests/epee_utils.cpp
`errno` not guaranteed to be anything according to C standard, except on range error
> unit_tests: fix strtoul unit test

- src/cryptonote_core/tx_pool.cpp
Nodes who see different txs in a double spend attack will drop each other, splitting the network. Issue found by @boog900.
> tx_memory_pool: make double spends a no-drop offense

- src/cryptonote_core/tx_pool.cpp
`std::sort` is unstable, so it can return random sets of transactions when mempool has many transactions with the same fee/byte. It can result in p2pool mining empty blocks sometimes because it doesn't pick up "new" transactions immediately.
`std::stable_sort` should preserve the order of transactions that was returned by the DB request.
Example when P2Pool was mining an empty block despite full mempool:
```
NOTICE  2024-03-08 12:34:06.0670 P2Pool new miner data
---------------------------------------------------------------------------------------------------------------
host                    = 127.0.0.1:18081:ZMQ:18083
major_version           = 16
height                  = 3100556
prev_id                 = 93c317bb130f77459a0698d4a86c1bad815ca40a6c3fa513fecfd0d751635213
seed_hash …
```
> get_block_template_backlog: better sorting logic

- src/cryptonote_core/tx_pool.cpp
> get_block_template_backlog: better sorting logic [release-v0.18]

- src/simplewallet/simplewallet.cpp
- src/wallet/wallet2.cpp
Resolves #9221
The automatic fee level should switch between slow and normal depending on the current backlog.
https://monero.stackexchange.com/questions/11657/what-are-the-standard-fee-multiplier-levels#comment10765_11658
This behaviour broke at some point, likely during the 2021 fee code changes. This PR restores the previous behaviour.
> wallet2: adjust fee during backlog, fix set priority

- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- Fixed undefined behavior after a call to `remove_tx_from_transient_lists` (it used an invalid iterator)
- Fixed `txCompare` (it wasn't strictly weak ordered)
This PR fixes a crash/hang when mempool reaches `max-txpool-weight`
> Fixed mempool pruning

- contrib/epee/include/net/http_client.h
> Revert "http_client: reduce number of packets sent for small bodies" [RELEASE]

- src/ringct/rctTypes.h
Caused in commit 05231400cebfeedbbc0a5386f38a033bba6314b3, PR #9035. Caught by mrnaif on Matrix.
> ringct: fix trunc_amount field name change

- src/gen_multisig/gen_multisig.cpp
- src/multisig/multisig_account.h
- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet2_api.h
- src/wallet/message_store.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/unit_tests/multisig.cpp
This is a PR in my 'upstreaming seraphis_lib project'. Refactoring with this PR will make it easier to transition to seraphis in the future, since the seraphis multisig wallet will use `multisig::multisig_account_status`.
- Replaces `wallet2::multisig()` with `wallet2::get_multisig_status()`, which returns a `multisig::multisig_account_status` struct containing info about the wallet's transformation into a 'multisig wallet'.
- The function `wallet2::multisig()` is ambiguous (returns `true` if the wallet `is_multisig`), and badly defined (uses return by pointer reference to set variables related to the wallet's multisig status).
- It is also awkward to extend, requiring an updated function signature. I want to add `kex_rounds_remaining` to the status, which is much cleaner to do with an …
> [seraphis] wallet2: replace ambiguous 'multisig()' function with 'multisig_status' struct

- cmake/CheckTrezor.cmake
- cmake/FindLibUSB.cmake
- src/device_trezor/README.md
- tests/core_tests/wallet_tools.h
- tests/trezor/trezor_tests.cpp
- fixes support for C++ 17 && Protobuf v22+
- fixes libusb compile check for ubuntu
@selsta c++17 support came sooner than expected 😅 I've modified the code a bit to protobufv25 and c++17 works
> trezor: support c++17 and protobuf v25, libusb fix #smol

- contrib/epee/include/string_tools.h
- contrib/epee/src/readline_buffer.cpp
- contrib/epee/src/string_tools.cpp
1. Use `boost::filesystem` for already available operations.
2. Use `boost::string` for already available operations.
3. ~~Fix the inconsistent indentation.~~
> epee: cleanup string_tools

- src/ringct/rctTypes.h
- src/serialization/crypto.h
- src/serialization/serialization.h
- tests/unit_tests/serialization.cpp
There is currently no compiler protection when someone tries to do (for example) `BLOB_SERIALIZER(std::vector<int>)`. You just get runtime allocation errors. This has already eaten up dev time before, so this PR adds a static assertion that the type must be trivially copyable, as defined by the C++ standard. Types can override this if applicable if they use `BLOB_SERIALIZER_FORCED`.
> serialization: protect blob serialization from undefined behavior

- src/crypto/CMakeLists.txt
- src/crypto/blake2b.c
- src/crypto/blake2b.h
- tests/hash/main.cpp
- Adds Blake2b to `src/crypto`. The code is lifted almost verbatim from randomx.
- Updates the Blake2b test vectors to point to `src/crypto/blake2b.h`. Test with `ctest -R hash-blake2b` in the `tests/hash` folder in your build directory.
> [seraphis] crypto: add blake2b

- Makefile
- contrib/depends/packages/native_protobuf.mk
- contrib/depends/packages/protobuf.mk
- `install-libLTLIBRARIES` triggers builds for `libprotoc.a` and `libprotobuf-lite.a`, which we don't need.
- The make jobserver isn't available in `stage_cmds`, making this slower than necessary.
- This PR reduces build time to ~39s (for `native_protobuf` + `protobuf`) down from 1:50 on my machine.
- Forces Trezor support for depends builds to prevent a silent regression.
> depends: {native_,}protobuf: speedup build

- contrib/depends/packages/native_cctools.mk
- contrib/depends/patches/native_cctools/no-build-date.patch
The `native_cctools` depends package is not reproducible because it embeds the build date. This does not make its way into release binaries, but hinders automated reproducibility scanning.
> depends: native_cctools: don't embed build date

- contrib/depends/packages/native_libtapi.mk
- contrib/depends/patches/native_libtapi/no_embed_git_rev.patch
The `native_libtapi` depends package is not reproducible because it embeds the checked out git hash of whatever git repository it happens to have been extracted to, which is that of the monero repo in our case. If the `native_libtapi` package is cached, runs for different monero commits that otherwise do not invalidate the cache will use a `native_libtapi` package with a hash that does not match the hash of a clean build.
This does not make its way into release binaries, but hinders automated reproducibility scanning.
> depends: native_libtapi: don't embed git hash

- contrib/depends/packages/openssl.mk
- contrib/depends/packages/unbound.mk
The Unbound and OpenSSL depends packags are not reproducible when building android targets because the Android NDK's bundled archiver includes timestamps by default. The default options are not overridden properly for these packages.
The archiver lies about zeroing timestamps by default.
>  [D]          - use zero for timestamps and uids/gids (default)
This PR sets the `ARFLAGS` for these packages to the flags defined in the hosts file, [which includes `D` for android](https://github.com/monero-project/monero/blob/master/contrib/depends/hosts/android.mk#L13).
Note for OpenSSL: it only reads `ARFLAGS` (not `AR_FLAGS`) when passed as an argument.
> depends: fix ar zero timestamp for openssl & unbound on android targets

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- Removed `localhost:8080` default value to address string in wallet rpc
- If `set_daemon` rpc address string is empty, mwr will return an error and explicit message
> monero-wallet-rpc - Changed default cryptonote port

- tests/functional_tests/functional_tests_rpc.py
- tests/functional_tests/http_digest_auth.py
- utils/python-rpc/framework/daemon.py
- utils/python-rpc/framework/rpc.py
- utils/python-rpc/framework/wallet.py
Test:
1. Can't login to RPC server with --rpc-login enabled, but no auth provided
2. Can access RPC server with correct login
3. Can use internal HTTP client to access RPC server with correct login
With commit 0ae5c91e504b8007dedc2b89c9b2b49c404ffec6 not reverted, we fail test 3.
> functional_tests: test HTTP digest authentication

- contrib/epee/include/string_tools.h
- contrib/epee/src/readline_buffer.cpp
- contrib/epee/src/string_tools.cpp
[9149](https://github.com/monero-project/monero/pull/9149)
Cleanup string_tools.
1. Use boost::filesystem for already available operations.
2. Use boost::string for already available operations.
> epee: cleanup string_tools [RELEASE]

- src/wallet/wallet2.cpp
Looks like the logic from #8882 was accidentally removed in #8861 (regressing to the behavior noted in the #8882 description). This brings that logic back.
> wallet2: ensure transfers and sweeps use same fee calc logic rnd2

- src/cryptonote_protocol/levin_notify.cpp
- src/cryptonote_protocol/levin_notify.h
- src/p2p/net_node.inl
- tests/unit_tests/levin.cpp
This will check if the privacy network has outgoing connections before attempting to send over that network. The primary difference is that this will allow sending txes over Tor if I2P has no outgoing connections.
This differs from the PR yesterday in that it checks the outgoing checks directly instead of the count reported by the noise code.
> Skip privacy networks (on tx sends) that don't have outgoing connections [0.18]

- src/common/util.cpp
- src/common/util.h
- src/wallet/wallet_rpc_server.cpp
When creating a private file we need to delete the file if exists.
> common: fix privatefile create. 

- Makefile
> build: force Trezor for depends builds [release]

- src/common/util.cpp
- src/common/util.h
- src/p2p/net_peerlist.cpp
- src/wallet/wallet2.cpp
- tests/core_tests/chaingen_serialization.h
- tests/unit_tests/wallet_storage.cpp
Update [8751](https://github.com/monero-project/monero/pull/8751) to have support for both the older version and the newer version of boost.
> common: support boost filesystem copy_options.

- src/simplewallet/simplewallet.cpp
Update deprecated `boost::filesystem::complete` method.
https://github.com/monero-project/monero/issues/9304
> simplewallet: change boost::filesystem::complete to absolute.

- contrib/depends/Makefile
```
$ make -C contrib/depends --no-print-directory HOST="i686-w64-mingw32" print-all_packages
boost openssl zeromq expat unbound  sodium hidapi protobuf libusb  native_protobuf
```
A part of #8929.
> depends: add command to print variables

- src/multisig/multisig_account.h
- src/multisig/multisig_account_kex_impl.cpp
- src/wallet/api/wallet.cpp
- src/wallet/api/wallet.h
- src/wallet/api/wallet2_api.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/unit_tests/multisig.cpp
- utils/python-rpc/framework/wallet.py
This PR adds a small optimization to multisig account creation that is especially useful for 2-of-3 groups (disclaimer: there is a bounty for it [here](https://github.com/haveno-dex/haveno/issues/86)).
Multisig account creation is a series of rounds. Each round consists of sending messages to all the other group members. A member cannot complete a round until they have received a message for that round from each other member.
A standard 2-of-3 setup ceremony looks like this:
**Round 1**: Members A, B, C send initial messages to all other members.
**Round 2**: Members A, B, C use the previous round's messages to make their personal shares of the final key. They send a second message to all other members.
**Finalization**: Once a member has a full set of round 2 messages, they can finish …
> multisig: add key exchange round booster

- contrib/epee/include/string_tools.h
- contrib/epee/src/readline_buffer.cpp
- contrib/epee/src/string_tools.cpp
On Linux Mint 21.3, g++ Ubuntu 11.4.0-1ubuntu1~22.04, I get linking error for an undefined reference to `epee::string_tools::trim_right`. This PR reverts the changes to epee_readline.cpp in commit c56ee140, which turns a `boost::trim_right` callsite into an `epee::string_tools::trim_right` callsite.
> epee: partially revert c56ee140 to fix linking errors

- src/wallet/wallet2.cpp
This will greatly reduce communication overhead when syncing the mempool. Thanks to @Rucknium for inquiring into the details of the wallet sync protocol, which caused me to notice that pool txs are requested with proofs attached.
> wallet: fetch pool txs in pruned form

- src/cryptonote_protocol/levin_notify.cpp
- tests/unit_tests/levin.cpp
Fix duplicate transaction #9335
Thanks @Boog900  for suggesting how it can be done easier.  
There is another (draft) implementation which passes tests based on `std::set` [here](https://github.com/0xFFFC0000/monero/pull/20/files).
> cryptonote_protocol: prevent duplicate txs in fluff queue

- src/cryptonote_protocol/levin_notify.cpp
- tests/unit_tests/levin.cpp
Release for [9353]( https://github.com/monero-project/monero/pull/9353)
```
1. Fix duplicate transaction #9335
2. Add test for cases where there are duplicate transaction in fluff
```
> cryptonote_protocol: prevent duplicate txs in fluff queue [RELEASE] 

- src/serialization/json_object.cpp
- src/serialization/json_object.h
When requesting pruned txes over ZMQ, the txes aren't fully pruned. This is due to a quirk in the unpacking of txes - the pruned elements are still read into the local tx. Fixing this is a bit more involved. The ZMQ output code then has no context/flag for `prune` in the signature portion (because it assumes the signatures wouldn't have been unpacked in. a pruned tx).
This is a simple hack that passes the prune information from the base tx into the next function call. This allows for full pruning, which saves on bandwidth, output time, and read time.
I have verified locally (with LWS) that this output is still valid.
> Fix ZMQ Tx Pruning

- src/rpc/core_rpc_server_commands_defs.h
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Supports consistent RPC status handling between wallet2 and a new wallet lib
Used in the Seraphis lib async scanner: https://github.com/UkoeHB/monero/pull/23
> wallet2: move get_rpc_status func to RPC server definition file

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
Behavior before: when `req.start_height > chain tip`, response fails and the client is dropped and blocked
Behavior after: when `req.high_height_ok && req.start_height > chain tip`, the server returns a successful empty block response that includes the chain height
This is useful when firing parallel requests to scan the chain and the client doesn't initially know what the chain tip is. This avoids the client getting itself dropped when firing too high of a request.
The reason I implemented this new optional `high_height_ok` field rather than changing the default behavior to return a successful response when the request includes too high of a height is to maintain backwards compatibility with clients that perhaps currently rely on a failure response when requesting too high a height. …
> Daemon RPC: high_height_ok req boolean field /getblocks.bin

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/rpc/daemon_handler.cpp
- src/rpc/daemon_messages.h
Particularly useful in combination with https://github.com/monero-project/monero/pull/9382, so that the client can be certain it's on the correct chain even when the request to /getblocks.bin includes a `start_height > chain tip`
Used in the Seraphis lib async scanner: https://github.com/UkoeHB/monero/pull/23
> Daemon RPC: /getblocks.bin return chain's top_block_hash in resp

- contrib/epee/src/mlog.cpp
When using a relative path for the log filename,
since the iteration on files adds "./" to the beginning of the filename monero-wallet-rpc and monero-wallet-cli	cannot find already written log files and therefore rotate indefinitely  (causing unlimited storage usage).
Thanks to [@ofrnxmr](https://github.com/nahuhh) for reporting this bug to me.
> epee: fix mlog filename compare bug.

- contrib/epee/src/mlog.cpp
Release [9392](https://github.com/monero-project/monero/pull/9392)
> [RELEASE] epee: fix mlog filename compare bug.

- .github/workflows/depends.yml
This PR edits the depends GitHub Actions workflow to export the macOS Arm artifact alongside the pre-existing x86_64 macOS artifact.
This is an intermediary step for creating universal macOS binaries for monero.
> Add MacOS Arm artifact output

- src/rpc/daemon_handler.cpp
- src/rpc/message_data_structs.h
- src/serialization/json_object.cpp
- tests/unit_tests/json_serialization.cpp
* top_block_hash was never set in handler
* wide_difficulty was never sent in JSON
* wide_cumulative_difficulty was never sent in JSON
There will likely be a Release 0.18 version for this too.
> Fix ZMQ DaemonInfo

- src/rpc/daemon_handler.cpp
- src/rpc/message_data_structs.h
- src/serialization/json_object.cpp
- tests/unit_tests/json_serialization.cpp
* top_block_hash was never set in handler
* wide_difficulty was never sent in JSON
* wide_cumulative_difficulty was never sent in JSON
> Fix ZMQ DaemonInfo [0.18 release]

- utils/systemd/monerod.service
For certain configuration options like `add-priority-node`, the network needs to be online before the systemd service can start. See issue [here](https://github.com/monero-project/monero/issues/9419).
Update `monerod.service` to use `After=network-online.target`.
> monerod.service: use network-online.target

- src/rpc/core_rpc_server_commands_defs.h
Removes the unused [`COMMAND_RPC_FAST_EXIT`](https://github.com/search?q=repo%3Amonero-project%2Fmonero%20COMMAND_RPC_FAST_EXIT&type=code) type from the daemon RPC.
This type is leftover from the (now removed) `/fast_exit` endpoint from #252.
> rpc: remove `COMMAND_RPC_FAST_EXIT`

- src/common/va_args.h
- src/serialization/serialization.h
This PR is upstreaming changes in the Seraphis lib here: https://github.com/UkoeHB/monero/pull/39. The changes to the serialization header allow clean passing of extra arguments to field serialization in the DSL. This is used mainly to pass implied sizes of containers during deserialization to make the format more compact. For example, if my object has two containers A & B which must be the same size, I can serialize only the size of container A. Then, during deserialization, when I deserialize A, I can then use A's size to deserialize B.
Depends on #9286.
> serialization: support passing extra args to fields in DSL

- CMakeLists.txt
- contrib/epee/include/serialization/keyvalue_serialization.h
- contrib/epee/include/span.h
- contrib/epee/include/string_tools.h
- src/crypto/crypto.h
- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_protocol/block_queue.cpp
- src/device/device_default.cpp
- src/lmdb/util.h
- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_server.cpp
- tests/benchmark.cpp
- tests/core_tests/multisig.cpp
- tests/functional_tests/make_test_signature.cc
- tests/unit_tests/crypto.cpp
- tests/unit_tests/multisig.cpp
- tests/unit_tests/serialization.cpp
1. Use `std::is_standard_layout` and `std::is_trivially_copyable` instead of `std::is_pod` for KV byte-wise serialization, which fixes compile issue for Boost UUIDs
2. Use `std::has_unique_object_representations` instead of `alignof(T) == 1` for epee byte spans and epee hex functions
3. Removed reimplementation of `std::hash` for `boost::uuids::uuid`
4. Removed `<<` operator overload for `crypto::secret_key`
5. Removed instances in code where private view key was dumped to the log in plaintext
> build: fix build with Boost 1.85 and remove instances of viewkey logging

- CMakeLists.txt
- contrib/epee/include/serialization/keyvalue_serialization.h
- contrib/epee/include/span.h
- contrib/epee/include/string_tools.h
- src/crypto/crypto.h
- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_core/cryptonote_tx_utils.cpp
- src/cryptonote_protocol/block_queue.cpp
- src/device/device_default.cpp
- src/lmdb/util.h
- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet_rpc_server.cpp
- tests/benchmark.cpp
- tests/core_tests/multisig.cpp
- tests/functional_tests/make_test_signature.cc
- tests/unit_tests/crypto.cpp
- tests/unit_tests/multisig.cpp
- tests/unit_tests/serialization.cpp
1. Use `std::is_standard_layout` and `std::is_trivially_copyable` instead of `std::is_pod` for KV byte-wise serialization, which fixes compile issue for Boost UUIDs
2. Removed reimplementation of `std::hash` for `boost::uuids::uuid`
3. Removed `<<` operator overload for `crypto::secret_key`
4. Removed instances in code where private view key was dumped to the log in plaintext
Release version of https://github.com/monero-project/monero/pull/9450
> build: fix build with Boost 1.85 and remove instances of viewkey logging [RELEASE]

- .github/workflows/build.yml
- cmake/CheckTrezor.cmake
- MSYS2 [doesn't ship](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-abseil-cpp/PKGBUILD#L66) static abseil libraries. Windows users should use WSL2+depends if they want static binaries.
- Removes compatibility code for an ancient, unsupported version of CMake.
- Does not install [protobuf-c](https://github.com/protobuf-c/protobuf-c) in CI, as we don't need it.
- Removes fragile and unnecessary variable checks.
> ci: fix windows msys2 build

- CMakeLists.txt
- README.md
- This fixes Windows CI (again)
- Some distributions no longer ship the static compatibility libraries
- Bumped the minimum version, because nobody should be linking Monero against an ancient version of OpenSSL
> cmake: boost: fix header-only library search, bump minimum

- CMakeLists.txt
- README.md
> cmake: boost: fix header-only library search, bump minimum [RELEASE]

- contrib/epee/src/string_tools.cpp
- tests/unit_tests/epee_utils.cpp
Fixes a regression introduced in #9254. Previously it did not include the dot.
> epee: string_tools: remove dot from get_extension

- src/common/variant.h
- tests/unit_tests/variant.cpp
Two new features for `tools::variant`:
* Visit by lambda instead of static visitor (possible now because result type is deduced)
* Value-initialize the variant based on a type index
> variant: visit lambda and value-initialize by index

- src/common/va_args.h
This PR is upstreaming changes in the Seraphis lib here: https://github.com/UkoeHB/monero/pull/39. This header adds a macro `VA_ARGS_COMMAPREFIX` which, when passed `__VA_ARGS__`, expands to `, __VA_ARGS__` unless the length of `__VA_ARGS__` is 0, in which case it expands to nothing. This macro is useful for passing/declaring optional function arguments.
> common: add va_args.h

- src/lmdb/database.cpp
- src/lmdb/database.h
I added LMDB code to monero core a while ago. The only project (afaik) using it is LWS. I found this bug in the commit code - commit can fail with a resize request too.
If anyone thinks this code should be removed and put into LWS let me know shortly. I thought perhaps this could be used to replace existing LMDB code, but it looks unlikely at this point.
> Fix lmdb txn commit code

- src/common/variant.h
- src/serialization/variant.h
- tests/unit_tests/variant.cpp
`variant` changes from `seraphis_lib`
- https://github.com/UkoeHB/monero/pull/28
- https://github.com/UkoeHB/monero/pull/49
- https://github.com/UkoeHB/monero/pull/30
@jeffro256
> tools: update variant

- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
startup speed up 2-5x because this PR changing `O(n^2)` operation to `O(nlogn)`.
Almost all people involved in stressnet experiment who tested this patch, reported at least 2.5x speed up of startup time of monerod.
Thanks to @Boog900, @[spackle-xmr](https://github.com/spackle-xmr/), [Rucknium](https://github.com/Rucknium) and [ofrnxmr](https://github.com/nahuhh) for their help
> tx_pool: update internal data structure to boost::bimap.

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_errors.h
Supports consistent RPC error response handling between wallet2 and a new wallet lib
Credit to @jeffro256 for identifying the source of a syntax issue
Used in the Seraphis lib async scanner: https://github.com/UkoeHB/monero/pull/23
> wallet2: move wallet error on RPC resp handling to wallet_errors file

- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/rpc/daemon_messages.h
Enables making parallel requests for a small number of blocks. When scanning the chain using parallel requests, setting this request param to a small number (e.g. 10) can speed up progress feedback to the user significantly (compared to leaving the default to 1000 as is).
Used in the Seraphis lib async scanner: https://github.com/UkoeHB/monero/pull/23
> Daemon RPC: add max_block_count field to /getblocks.bin

- src/cryptonote_core/blockchain.cpp
Issue appeared in stressnet where nodes would never switch to the valid chain with longest proof of work, but instead log a message like so:
```
INFO    global  src/cryptonote_core/blockchain.cpp:2125 ###### REORGANIZE on height: 2534772 of 2534772 with cum_difficulty 1072308428953
INFO    global  src/cryptonote_core/blockchain.cpp:2125  alternative blockchain size: 2 with cum_difficulty 1072309197139
ERROR   txpool  src/cryptonote_core/tx_pool.cpp:596     Failed to find tx_meta in txpool
ERROR   verify  src/cryptonote_core/blockchain.cpp:4239 Block with id: <BLKID> has at least one unknown transaction with id: <TXID>
ERROR   blockchain      src/cryptonote_core/blockchain.cpp:1205 Failed to switch to alternative blockchain
ERROR   blockchain      src/cryptonote_core/blockchain.cpp:1217 …
```
> Blockchain: fix temp fails causing alt blocks to be permanently invalid

- cmake/FindReadline.cmake
When passing `PATHS` and `NO_DEFAULT_PATH` to `find_path` in CMake, `find_path` will not look into any other location. This will make building on non-canonical *ix based system hard. For example `GUIX` package solves this by passing argument: 
Search for `DReadline_ROOT_DIR=` in 
https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/finance.scm
> cmake: fix readline find_path call.

- README.md
these are not installed by default in containers
> readme: add missing ubuntu/debian build tools

- contrib/depends/Makefile
current behavior prevents debug/release config vars from working.
e.g. 
https://github.com/monero-project/monero/blob/master/contrib/depends/packages/boost.mk#L9-L10
because they are expanded like this:
https://github.com/monero-project/monero/blob/master/contrib/depends/funcs.mk#L126
> depends: release type should be lower case

- .github/workflows/depends.yml
Serves no purpose since https://github.com/monero-project/monero/pull/8312/commits/7ea1e214c5db6c48e405f8bb3ede8f5ec9b876db.
> ci: remove obsolete sdk cache

- src/common/stack_trace.cpp
The source code can't be compiled on FreeBSD without using `libunwind` which is available there.
> set USE_UNWIND for FreeBSD

- contrib/depends/toolchain.cmake.in
`option` doesn't belong in a toolchain file. These options exist, and are documented in, the (root) `CMakeLists.txt`. All variables here are overridden later on in the toolchain file.
> depends: remove option from toolchain file

- contrib/depends/toolchain.cmake.in
It was removed from depends in #9169.
> depends: remove unwind from toolchain

- src/wallet/wallet2.cpp
This is already fixed in the master branch.
> wallet2: fix error throw if unable to load cache [RELEASE]

- tests/trezor/trezor_tests.cpp
- tests/unit_tests/epee_utils.cpp
- tests/unit_tests/memwipe.cpp
Not including this header when using `std::setfill()` has caused compilation errors on some compilers
> tests: include <iomanip> where using std::setfill

- src/lmdb/key_stream.h
- src/lmdb/table.h
- src/lmdb/util.h
- src/lmdb/value_stream.h
This allows `boost::uuids::uuid` to be used in the lmdb glue code. LWS currently has this patched until this gets committed.
> Relax static_asserts in src/lmdb

- src/lmdb/database.h
This is primarily used by LWS. `std::result_of` has been deprecated in C++17, so this silences those warnings.
> Replace deprecated result_of with decltype

- contrib/depends/packages/freebsd_base.mk
11.3 no longer @ https://download.freebsd.org/ftp/releases/amd64/11.3-RELEASE/
moved to their old-releases archive mirror https://archive.freebsd.org/old-releases/amd64/
> packages: add freebsd base mirror

- tests/trezor/trezor_tests.cpp
`unlock_time` argument has been removed. With this PR `trezor_tests` will compile without any issue. 
https://github.com/monero-project/monero/pull/9151
> tests: remove unlock_time argument from trezor_tests

- README.md
- `python3` is required for all targets
- `wine1.6` and `bc` are not required
- `update-alternatives` needs an absolute path to alternative
> readme: fix win64 cross-compile requirements

- .github/workflows/depends.yml
- `python3` and `cmake` are required for all targets
- `gperf` is only required to build `eudev` for linux targets, but it doesn't hurt to install by default
- `python3-zmq` is not required, since we're not building tests here
- `imagemagick` and other image libraries are not (or no longer) required
> ci: cleanup depends package requirements

- README.md
This no longer accurate as of Ubuntu 20.04 and Debian 10, which are the earliest versions `master` builds on.
> readme: remove outdated gtest note

- README.md
- This PR replaces #9534
- Remove Windows 32-bit instructions: MSYS2 no longer packages `mingw-w64-i686-{libsodium,unbound,zeromq}`
> readme: update msys2 build instructions

- README.md
- Rasbian was renamed to Rapberry Pi OS, link updated
- Removed Raspbian Jessie section (EOL for over 4 years, GCC toolchain too old to build Monero)
> readme: update raspberry pi build instructions

- contrib/brew/Brewfile
```
Tapping homebrew/cask
Error: Tapping homebrew/cask is no longer typically necessary.
Add --force if you are sure you need it for contributing to Homebrew.
Tapping homebrew/cask has failed!
Tapping homebrew/cask-versions
Error: homebrew/cask-versions was deprecated. This tap is now empty and all its contents were either deleted or migrated.
Tapping homebrew/cask-versions has failed!
Tapping homebrew/core
Error: Tapping homebrew/core is no longer typically necessary.
Add --force if you are sure you need it for contributing to Homebrew.
Tapping homebrew/core has failed!
```
> brew: remove unneeded taps

- CMakeLists.txt
On Windows, CMake sets CMAKE{_HOST,}_SYSTEM_PROCESSOR to the value of the
PROCESSOR_ARCHITECTURE environment variable. On some systems it may be set to
AMD64. Lowercase it to ensure checks for "x86_64" or "amd64" work as expected.
For example: https://github.com/monero-project/monero/blob/master/src/crypto/CMakeLists.txt#L55
https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html
> cmake: lowercase ARCH_ID

- src/wallet/api/wallet2_api.h
Cleaner, adheres to POLA, and allows for better compiler optimization. Declaration should be backwards compatible. Requires C++17.
> wallet2_api: use `std::optional` instead of handmade `optional`

- src/serialization/binary_archive.h
Some compilers are stupid and give a warning on this line when `T = uint8_t`, even though it will never run
> serialization: silence warning about shifting `uint8_t` by 8

- contrib/epee/include/net/http_server_handlers_map2.h
- tests/unit_tests/epee_serialization.cpp
The problem is `monero-wallet-rpc` does not save the state of the wallet when closing the wallet.
As you can see in the image below, the value of `autosave_current` is `false`. When in fact it should be `true` \[1\]. ( The command I am running is default command ` curl http://localhost:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"close_wallet"}' -H 'Content-Type: application/json'` )
The reason for this bug is when the _only_ child of the key-value serialization object is optional ( as is the case with the `close_wallet` ), we don't call the function `_load` of the object. This line \[2\] returns `null` and therefore we don't call `_load` method, which initializes the object.  Whether the child section is null or not, we want to call `_load` method, to make sure the correct …
> contrib: force (de)serialization to create params section incase there is none.

- src/wallet/wallet_rpc_server.cpp
Report exact failure reason in error string when `open_wallet` fails.
> wallet: report exact reason for open_wallet failure.

- contrib/epee/src/byte_slice.cpp
There's _technically_ an overflow in `byte_slice.cpp` that I caught while simply scanning the code. This can occur if the total memory being copied exceeds `size_t`. This is unlikely to ever trigger, because the platform probably needs `sizeof(size_t) == 4 && sizeof(void*) == 8` (or similar) to occur. And somehow a `malloc` to copy all of this data needs to succeed too. Therefore, this is primarily just defensive programming to be strictly standards compliant.
> Fix memcpy in byte_slice constructor

- contrib/epee/src/byte_slice.cpp
Same as #9583 but on release 0.18 branch.
> Fix memcpy in byte_slice constructor [0.18]

- contrib/depends/funcs.mk
One build dependency tarball, [protobuf-cpp-3.6.1.tar.gz](https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz)) contains file owner uid/gid as 231664/89939. This file fails to extract during the build process with the following error on systems where either uid_t or gid_t is limited to 16 bits (e.g. older kernels, rootless containers etc) i.e. the maximum uid_t/gid_t is 65534:
```
tar: six.BUILD: Cannot change ownership to uid 231664, gid 89939: Invalid argument
```
Since the file ownership is immaterial for the build process, this PR adds the `--no-same-owner` flag to `tar` command. This fixes #8639
> Fixes tar extract cmd for systems with 16 bit uid_t

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server_commands_defs.h
Adds proxy support to the release-v0.18 branch using https://github.com/monero-project/monero/pull/9160 from @0xFFFC0000.
> wallet2: daemon-specific proxy for the wallet-rpc [release]

- src/simplewallet/simplewallet.cpp
> simplewallet: add header to show_transfers command

- contrib/epee/include/net/http_server_handlers_map2.h
- tests/unit_tests/epee_serialization.cpp
https://github.com/monero-project/monero/pull/9574
> contrib: force (de)serialization to create params section incase there is none [RELEASE]

- .github/workflows/build.yml
- Boost >= 1.87.0 breaks builds (#9596)
- MSYS2 ships Boost 1.87.0
- Temporary downgrade to get CI to pass until a proper fix is in place
> ci: msys2: pin boost to 1.86.0

- .github/workflows/build.yml
- contrib/brew/Brewfile
- Boost >= 1.87.0 breaks builds (#9596)
- Brew ships Boost 1.87.0 by default
- Temporary downgrade to get CI to pass until a proper fix is in place
- https://formulae.brew.sh/formula/boost
> ci: brew: pin boost to 1.85

- .github/workflows/build.yml
Don't cancel the 22.04 build if 20.04 fails, or vice versa.
> ci: don't fail-fast on matrix jobs

- src/common/variant.h
It is identical to the block above. Introduced by #9336 and #9176, which are essentially the same PR. Not sure why this wasn't a merge conflict.
This fixes CI.
https://github.com/monero-project/monero/actions/runs/12469150712/job/34801715003#step:8:513
> ci: common: remove duplicated definition

- tests/unit_tests/variant.cpp
I modified the unit tests in the master branch from the `seraphis_lib` branch between the time that the PR to split `variant` into `optional_variant` was merged into master, which is what caused this naming discrepancy and caused the unit tests to fail.
> unit_tests: fix variant tests after 'optional' name split

- .github/workflows/build.yml
- .github/workflows/depends.yml
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
not yet able to confirm windows builds . ( i think unrelated but im having issues with gitian for lin/win using master on my own fork)
> CI: -j4 with lin/win runners

- src/wallet/wallet2.cpp
Your wallet keeps track of part of the blockchain, starting from a specific point (called the "offset"). Sometimes, the wallet might only have one block stored (the "base block") or no blocks at all.
The bug is that when the wallet has just the "base block" (and no newer ones), this block wasn't being included in the list of blocks that the wallet sends to check its history with the blockchain. This makes the wallet’s history incomplete and can break synchronization.
Buggy Code:
1. Wallet starts at block 1000 (offset = 1000), with no newer blocks (sz == 0).
2. The code only adds the genesis block (block 0).
3. Result: The list looks like this:
`ids = [block_0]`
*Missing block 1000!*
1. Wallet starts at block 1000, with no newer blocks (sz == 0).
2. The fix correctly adds the base block …
> wallet: shortchain history should include base block

- contrib/depends/funcs.mk
Allows us to call `$($(package)_cmake)` to configure CMake projects in depends. 
Needed for:
- #9271
- #9478
> depends: add cmake config command

- src/cryptonote_core/blockchain.cpp
Get height of the RingCT fork to start the output distributuon programmatically, instead of using a hardcoded index.
If using a hardcoded index, when the hardfork tables are modified, this can cause segmentation faults or horrific privacy issues: https://codeberg.org/wownero/wownero/issues/488#issuecomment-2514880.
> Blockchain: get height of RingCT fork programmatically

- src/p2p/net_node.inl
As the title says. Hopefully get some testers to make sure nothing for broken (it is fairly basic).
> Fix --anonymous-inbound data leak

- src/p2p/net_node.inl
Same as #9632 but on release branch.
> Fix --anonymous-inbound data leak [0.18]

- src/rpc/core_rpc_server.cpp
The `set_bans` method does not validate if there is actually a host or ip passed as a parameter. If a faulty RPC call fails to provide one of those, it falls back to banning `0.0.0.0`:
IMO the better way to handle this would be to provide an error message upon a missing parameter, which I added here:
> validate ip parameter in set_bans rpc call

- contrib/epee/include/file_io_utils.h
- contrib/epee/src/file_io_utils.cpp
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/common/download.cpp
Replace all calls to epee::file_io::get_file_size with boost::filesystem::file_size in order to avoid lossy conversions from paths to strings, which tend to break filename resolution. This commit fixes a bug on Windows where the get_info RPC call reported a zero database size because BlockchainLMBD::get_database_size returned zero.
> Fix get_database_size on Windows

- external/CMakeLists.txt
This is a quick fix to get development builds working while we work out what to do with miniupnpc.
https://github.com/tobtoht/monero/actions/runs/12653434575/job/35258755783
Fixes #9678, #9359.
> miniupnpc: fix build with gcc 14 [RELEASE]

- .github/workflows/guix.yml
To check reproducibility without having to download the log bundle.
> ci: print guix hashes to summary

- .github/workflows/guix.yml
- contrib/guix/guix-build
According to @nahuhh these binaries haven't worked in years (see also: https://github.com/monero-project/monero/issues/8889#issuecomment-1583469451).
Android has mostly moved on to 64-bit: https://android.stackexchange.com/questions/253596
In [a 2020 blog post](https://newsroom.arm.com/blog/android-64bit-future-mobile) ARM stated that "nearly 90 percent of today’s Android devices deploy a 64-bit capable version of the OS."
> guix: drop 32-bit android target

- .github/workflows/depends.yml
Discussion: https://libera.monerologs.net/monero-research-lab/20240904#c422227-c422235
Context: https://github.com/monero-project/monero/pull/9436#pullrequestreview-2278670854
The last commercially available x86 processors were released [over 18 years ago](https://en.wikipedia.org/wiki/List_of_Intel_processors#Intel_Core). Windows 11 [requires 64-bit](https://www.microsoft.com/en-us/windows/windows-11-specifications).
Article from Nov 2021:
>The first 32-bit Windows version in the charts is Windows 7 with a share of 0.22 percent, followed by its Windows 10 sibling with 0.09 percent.
https://news.softpedia.com/news/new-data-shows-windows-32-bit-is-becoming-a-thing-of-the-past-534336.shtml
> build: drop support for 32-bit windows target

- src/wallet/wallet2.cpp
- tests/functional_tests/transfer.py
Fixes #9354
In #8566, I introduced a call to `refresh()` inside `scan_tx` so that when `scan_tx` executes to completion, wallet data would reflect the latest chain state (e.g. the number of confirmations on the tx/tx's locked status would be up to date). I also introduced a new variable `m_skip_to_height` to skip the wallet's refresh height to the tx's height if it hasn't synced to that height yet. The logic for `m_skip_to_height` mirrors the logic when a user includes a restore height when restoring the wallet.
When refresh "skips" to `m_skip_to_height` (or a user restores a wallet at a provided restore height), the wallet downloads every block hash from the chain even from before `m_skip_to_height` (or provided restore height),  which is (suspiciously) slow.
Thus, when restoring a …
> wallet2: remove refresh() from scan_tx

- src/blockchain_db/lmdb/db_lmdb.cpp
Fixes #9617
If the data-dir is compressed and the lmdb folder is (check for both, because if data-dir is compressed and lmdb doesnt exist yet, it is likely that the compression is configured to be applied recursively):
If just the db folder is compressed:
If not compressed at all:
Just logging an ERROR message, just like if Fat32 is used, not aborting, because for a small blockchain this not be a critical issue. 
Can we assume that "lmdb" stays the name of the db folder? Since it is hardcoded here. Otherwise, one would need to define it somewhere central. I assumed so, because `BlockchainLMDB::get_db_name()` also has it hardcoded.
> Check for windows NTFS compression on monerod startup (fixes #9617)

- src/blockchain_db/lmdb/db_lmdb.cpp
See https://github.com/monero-project/monero/pull/9664#issuecomment-2589442460
> release-v0.18: check for windows NTFS compression on database files

- contrib/epee/include/file_io_utils.h
- contrib/epee/src/file_io_utils.cpp
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/common/download.cpp
Cherry-pick 978f1d7d415d4532958c86f678ee7a246f7e5bc4 to release v0.18 branch (see PR https://github.com/monero-project/monero/pull/9663).
> Fix get_database_size on Windows [0.18]

- src/common/stack_trace.cpp
My **cmake(1)** command line is:
```sh
CPP="gcc -E" CC=gcc CFLAGS="-Wall -Os -g" CXX=g++ CXXFLAGS="-Wall -Os -g" cmake -D CMAKE_SKIP_RPATH=TRUE ..
```
Failure is similar to:
```
[ 90%] Linking CXX executable ../../bin/monero-gen-ssl-cert
/usr/local/bin/ld: ../common/libcommon.a(stack_trace.cpp.o): in function `tools::log_stack_trace(char const*) [clone .localalias]':
stack_trace.cpp:(.text+0x2f4): undefined reference to `_Ux86_64_getcontext'
/usr/local/bin/ld: stack_trace.cpp:(.text+0x315): undefined reference to `_ULx86_64_init_local'
/usr/local/bin/ld: stack_trace.cpp:(.text+0x32e): undefined reference to `_ULx86_64_step'
/usr/local/bin/ld: stack_trace.cpp:(.text+0x354): undefined reference to `_ULx86_64_get_reg'
/usr/local/bin/ld: stack_trace.cpp:(.text+0x37e): undefined reference to …
```
> Failed to build for FreeBSD using GCC

- contrib/depends/packages/freebsd_base.mk
- 11.3 is missing execinfo, which is needed for rust std library build (#9440)
- bump does not violate #9446
> depends: freebsd_base: update to 12.3

- contrib/depends/packages/packages.mk
Group by operating system. Sort operating systems by guix build order. Native packages get built before cross-compiled packages. Hardware packages are always built. Make package exclusions explicit.
> depends: cleanup packages.mk

- contrib/guix/libexec/build.sh
- contrib/guix/manifest.scm
| package | old | new |
|---|---|---|
| moreutils | 0.69 | removed |
| perl-io-tty | 1.14 | removed |
| perl-ipc-run | 20180523.0 | removed |
| perl-time-duration | 1.21 | removed |
| perl-timedate | 2.33 | removed |
| package | old | new | 
|---|---|---|
| docbook-xml | 4.4 | removed |
| docbook-xsl | 1.79.2-0.fe16c90 | removed |
| perl-archive-zip | 1.68 | removed |
| perl-canary-stability | 2013 | removed |
| perl-capture-tiny | 0.48 | removed |
| perl-common-sense | 3.75 | removed |
| perl-cpan-meta | 2.150010 | removed |
| perl-cpan-meta-requirements | 2.140 | removed |
| perl-cpan-meta-yaml | 0.018 | removed |
| perl-cpanel-json-xs | 4.30 | removed |
| perl-devel-symdump | 2.18 | removed |
| perl-extutils-config | 0.008 | removed |
| perl-extutils-helpers | 0.026 | removed |
| …
> guix: remove moreutils

- contrib/depends/packages/eudev.mk
- contrib/depends/packages/libusb.mk
- contrib/depends/packages/sodium.mk
- contrib/depends/packages/unbound.mk
> depends: don't run auto(re)conf anywhere

- src/cryptonote_core/blockchain.cpp
This reverts commit 5741b4d74de542f6f75dddad8125f4c4a5ad9143.
This change got introduced in #6544 with the goal to find a race condition in the difficulty code, it was found and fixed in #6650. Since then no issues have been found and 5 years have passed, it is time to revert it since it slows down the code.
Even after reverting this patch we still have a safeguard against race conditions with https://github.com/monero-project/monero/pull/6534.
> Revert "blockchain: detect and log bad difficulty calculations"

- src/crypto/generic-ops.h
This code could've caused issues if the pointer to the `public_key`, `key_image`, `hash`, etc wasn't aligned on an 8-byte boundary.
> crypto: make CRYPTO_DEFINE_HASH_FUNCTIONS adhere strict aliasing

- src/crypto/generic-ops.h
> crypto: make CRYPTO_DEFINE_HASH_FUNCTIONS adhere strict aliasing [RELEASE]

- src/common/pod-class.h
In src/common/pod-class.h, the POD_CLASS definition contained quite a lot of detritus, including a long-ago resolved FIXME. Delete all the noise.
> common: Remove resolved FIXME in pod-class.h

- src/crypto/crypto.h
Remove the following unused classes from the crypto namespace: public_keyV, secret_keyV, and public_keyM.
> crypto: remove unused POD classes

- .github/workflows/build.yml
We don't currently have a rolling release Linux distro in our CI. Arch Linux is a common development environment.
This would help us catch and fix issues like #9359 early.
> ci: add arch linux build

- tests/functional_tests/transfer.py
Needed to disable auto refresh *before* restoring the wallet, so [refresh doesn't run in the idle loop](https://github.com/monero-project/monero/blob/eaf9f98930fc72f1b468e980b220d53cadc85443/src/wallet/wallet_rpc_server.cpp#L198) upon restoring.
Fixes [this test failure](https://github.com/monero-project/monero/pull/9389#issuecomment-2608902212) highlighted by @tobtoht (apologies for missing it).
> functional tests: fix race in restore wallet refresh

- .github/workflows/build.yml
We pin Boost to 1.86.0 on the release branch for rolling release distributions because of a build issue with Boost 1.87. ICU (a dependency for Boost Locale) was updated to v76 in MSYS2 causing a [linking issue](https://github.com/monero-project/monero/actions/runs/12918551559/job/36027291926#step:6:13034). This PR temporarily downgrades ICU to fix the build.
We can remove this once we have backported #9628 to the release branch. This requires updating Boost (#9687), which needs careful testing and so should not be rushed out ahead of the upcoming tag.
> ci: msys2: downgrade icu to fix build [RELEASE]

- contrib/depends/packages/unbound.mk
- https://nvd.nist.gov/vuln/detail/CVE-2024-1931
- https://nvd.nist.gov/vuln/detail/CVE-2024-8508
- ☑ The tarball was signed with the same GPG key as the [previous update](https://github.com/NLnetLabs/unbound/releases/tag/release-1.19.1) (1.19.1)
- `EDFAA3F2CA4E6EB05681AF8E9F6F1C2D7E045F8D`
- ☑ The repository has not changed ownership since the previous update
- ☑ The git [tag](https://github.com/NLnetLabs/unbound/releases/tag/release-1.22.0) was GPG signed by the maintainer
- ☑ Blobs were removed from the source in `preprocess_cmds`
- ☑ The tarball [is used by](https://whatsrc.org/artifact/sha256:c5dd1bdef5d5685b2cedb749158dd152c52d44f65529a34ac15cd88d4b1b3d43) 5 or more distributions.
- ⚠ The source archive does **not** match the contents of the git repo. The following files remain …
> depends: unbound: update to 1.22.0

- .github/actions/set-make-job-count/action.yml
- .github/workflows/build.yml
- .github/workflows/depends.yml
Dynamically determine an appropriate number of make jobs for the GitHub runner container, based upon the number of available CPU cores and RAM, using the rule that each job requires a dedicated core and 2.25GiB of RAM.
> build: auto-set GitHub runner make job count

- .github/workflows/build.yml
- tests/create_test_disks.sh
- tests/unit_tests/is_hdd.cpp
Correct the unit tests for tools::is_hdd to avoid making assumptions about the configuration of a particular device based solely on the value of the __GLIBC__ preprocessor flag. Instead, rely on the test invoker to provide paths for devices of specific types via the process environment, thereby avoiding faulty assumptions and improving the specificity of test assertions. To ensure appropriate devices exist, add a script, tests/create_test_disks.sh, which configures loopback devices mirroring relevant configurations.
> tests: Fix tools::is_hdd unit tests

- .github/workflows/build.yml
The "--parallel" flag got dropped from the Arch Linux build due to unidentified, logical commit conflicts.
> ci: Parallelize Arch Linux build

- .github/workflows/build.yml
- .github/workflows/depends.yml
- .github/workflows/gitian.yml
> ci: update to v4 actions [RELEASE]

- src/wallet/wallet_errors.h
Simplifies calling logic where a branch ends but a return value is needed
> wallet: mark wallet error throwing functions as noreturn

- contrib/guix/README.md
Updates documentation in `contrib/guix/README.md`.
> guix: update documentation

- .github/workflows/build.yml
This is faster than setting up the libwallet-specific Ubuntu job, reduces cache usage, and gives us more confidence `wallet_api` builds across supported distros.
Annoyingly, we can't do `--target all --target wallet_api` here (yet) because this requires CMake 3.15 and Debian 10 is on 3.13.
> ci: build wallet_api for all linux cli jobs

- contrib/guix/libexec/prelude.bash
- contrib/guix/manifest.scm
- contrib/guix/patches/glibc-2.27-riscv64-fix-incorrect-jal-with-HIDDEN_JUMPTARGET.patch
- bumps binutils from 2.38 to 2.41, needed for #9440
Includes packages that are available in the guix container that we use to build Monero.
| package | old | new | rationale |
|---|---|---|---|
| **binutils** | 2.38 | 2.41 | |
| **binutils-cross** | 2.38 | 2.41 | |
| curl | 8.5.0 | 8.6.0 | |
| diffutils | 3.8 | 3.10 | |
| ed | 1.18 | 1.20.1 | |
| file | 5.44 | 5.45 | |
| gawk | 5.2.1 | 5.3.0 | |
| git-minimal | 2.45.2 | 2.46.0 | |
| **glibc**\* | 2.35 | 2.39 | |
| glibc-utf8-locales | 2.35 | removed | Use C.UTF-8 instead of ‘glibc-utf8-locales’ where possible<br>(949ee85019b242d29a1065cde27c491af57b657b) |
| gmp | 6.2.1 | 6.3.0 | |
| grep | 3.8 | 3.11 | |
| gzip | 1.12 | 1.13 | |
| libarchive | 3.6.1 | 3.7.7 | |
| libgc | 8.2.2 | 8.2.4 | |
| libpsl | n/a | 0.21.1 | curl: Update to …
> guix: bump time-machine to 9d09b0cf841fb657a1aec12e9bab68e00c2b493c

- CMakeLists.txt
It already defaults to `NEW` under `cmake_minimum_required(VERSION 3.5)`.
> cmake: remove obsolete policy setting

- .github/workflows/build.yml
GitHub will begin deprecation of the Ubuntu 20.04 runner in [Feb 2025](https://github.com/actions/runner-images/issues/11101). We support Ubuntu 20.04 until at least Apr 2026.
Proactively containerize both Ubuntu 20.04 and 22.04 to avoid future disruptions.
> ci: containerize ubuntu cli jobs

- src/p2p/net_node.inl
originally added in https://github.com/monero-project/monero/pull/9316#issuecomment-2092972195 
the box has changed ip, it is still my server, and will remain so, https://node3.monerodevs.org 
last 7 days activity of seed nodes @ https://github.com/plowsof/check-monero-seed-nodes (owner of tor zb... has been notified, likely a quick fix)
> p2p/net_node.inl : update seed node

- .github/actions/set-make-job-count/action.yml
- .github/workflows/build.yml
- tests/create_test_disks.sh
- tests/unit_tests/is_hdd.cpp
This PR consolidates changes made to `.github/workflows/build.yml` from `master` to `release-v0.18`.
The easiest way to review this PR would be to run:
```
git diff master tobtoht/ci_containerize_dev_rel -- .github/workflows/build.yml .github/actions/set-make-job-count/action.yml
```
I left out the Arch Linux build for now, because getting this to build on `release-v0.18` will require additional changes.
> ci: development build backports [0.18]

- tests/functional_tests/functional_tests_rpc.py
* Use a global startup timeout, and apply it to each socket's connect call, rather than repeating connection attempts with short timeouts.
* Avoid leaking sockets by closing them.
> tests: Improve functional_tests_rpc startup

- utils/python-rpc/framework/rpc.py
- utils/python-rpc/framework/test_rpc.py
Reduce bloat in the python RPC Response class by making better use of superclass methods and recursion. As part of this change, add tests for the Response class.
> utils: Simplify python RPC Response implementation

- src/ringct/rctOps.cpp
This vestigial include line breaks some downstream builds
> ringct: remove inclusion of cryptonote_format_utils.h in rctOps.cpp

- src/cryptonote_basic/connection_context.cpp
- src/cryptonote_basic/connection_context.h
- src/cryptonote_protocol/block_queue.cpp
- src/cryptonote_protocol/block_queue.h
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
> Some cleanup in span/connection_context + few more checks

- src/device_trezor/trezor/protocol.cpp
- src/ringct/rctSigs.cpp
- src/ringct/rctTypes.h
- src/wallet/wallet2.h
- tests/core_tests/bulletproof_plus.cpp
- tests/core_tests/bulletproof_plus.h
- tests/core_tests/bulletproofs.cpp
- tests/core_tests/bulletproofs.h
- tests/core_tests/chaingen_main.cpp
- tests/performance_tests/check_tx_signature.h
- tests/performance_tests/main.cpp
- tests/unit_tests/json_serialization.cpp
Remove unused Rangeproof types `RangeProofBulletproof `, and `RangeProofMultiOutputBulletproof`. In the prove code, if the `RangeProofBulletproof` enum was passed, then one bulletproof was created per output. If `RangeProofMultiOutputBulletproof` was passed, then K bulletproofs were produced, where K is the number of one bits in the count of the outputs, Neither of these are allowed by consensus: https://github.com/monero-project/monero/blob/2226d4f7e0bf316aa0d4241b9b498f928add4b8b/src/cryptonote_basic/cryptonote_format_utils.cpp#L150-L154 and https://github.com/monero-project/monero/blob/2226d4f7e0bf316aa0d4241b9b498f928add4b8b/src/cryptonote_basic/cryptonote_format_utils.cpp#L174-L178.
Also fixes an actual bug with the boost serialization of type `tools::wallet2::signed_tx_set`. If the …
> ringct: remove unused range proof types and fix serialization bug

- CMakeLists.txt
- contrib/depends/packages/boost.mk
`-DBOOST_ASIO_HAS_STD_STRING_VIEW=1` fixes:
```
/monero/contrib/depends/x86_64-unknown-freebsd/native/usr/include/c++/v1/experimental/string_view:18:3: 
warning: "<experimental/string_view> has been removed. Use <string_view> instead." [-W#warnings]
/monero/contrib/depends/x86_64-unknown-freebsd/include/boost/asio/detail/string_view.hpp:32:12: 
error: no member named 'experimental' in namespace 'std' using std::experimental::basic_string_view;
```
https://github.com/monero-project/monero/pull/9162#issuecomment-2574034170
Needs successful Gitian build and testing.
> depends: boost: update to 1.66.0 [RELEASE]

- .github/workflows/build.yml
- contrib/brew/Brewfile
- src/device_trezor/README.md
No longer needed since #8922.
Resolves two CI annotations:
- protobuf@21 has been deprecated because it is a versioned formula! It will be disabled on 2026-01-08.
- Already linked: /opt/homebrew/Cellar/boost/1.87.0
> brew: use latest protobuf

- contrib/depends/packages/darwin_sdk.mk
- contrib/depends/packages/freebsd_base.mk
Cleanup. $($(package)_staging_prefix_dir) maps to the same directory.
> depends: use staging_prefix_dir where possible

- contrib/guix/manifest.scm
A visualization of the build environment for Linux targets (after these changes):
Excludes `bash-minimal`, `glibc` and `gcc-lib` for clarity.
> guix: remove automake & autoconf

- tests/functional_tests/p2p.py
Reduce the likelihood of false positive failures in the p2p transaction propagation functional test by waiting up to a maximum timeout for a transaction to propagate, rather than using a fixed timeout, to reflect the random delay of Dandelion++ transaction propagation. This strategy also speeds test execution in cases where propagation occurs faster than the previously expected fixed delay.
> tests: Improve p2p tx propagation functional test

- .github/workflows/build.yml
Needs #9628 backport to pass CI.
> ci: add arch linux build [0.18]

- .github/workflows/depends.yml
- .github/workflows/guix.yml
- contrib/depends/packages/hidapi.mk
- contrib/depends/packages/native_cctools.mk
- contrib/depends/packages/ncurses.mk
- contrib/depends/packages/readline.mk
- contrib/depends/packages/sodium.mk
- contrib/depends/packages/zeromq.mk
- contrib/depends/toolchain.cmake.in
- contrib/guix/README.md
- contrib/guix/guix-build
Clang 10.0 [does not recognize](https://phabricator.services.mozilla.com/D87052) the `aarch64-apple-darwin` target. The release branch hacks around this by automatically [renaming the target](https://github.com/monero-project/monero/blob/release-v0.18/contrib/depends/hosts/darwin.mk#L3-L7).
This approach is less straightforward on master due to the [introduction of CMake](https://github.com/monero-project/monero/pull/9640) in depends. We would also need to inform CMake about the updated target to prevent it from passing `--target=aarch64-apple-darwin` to the compiler.
It's less messy to just rename the target to whatever clang expects.
> ci: containerize depends jobs

- contrib/epee/include/misc_log_ex.h
The default log size is roughly 5 GB, which is huge. Particularly for handheld devices. Setting the default size to 1GB is more reasonable IMHO.
> contrib: smaller and more reasonable log size.

- src/common/stack_trace.cpp
`D:/a/monero/monero/src/common/stack_trace.cpp:154:27: error: 'setw' is not a member of 'std'`
https://github.com/tobtoht/monero/actions/runs/13374416174/job/37350275299#step:6:859
> common: add missing iomanip include

- .github/workflows/build.yml
- Makefile
- README.md
- These Makefile targets predate `depends` and are not static and not cross-compiled.
- `make depends` should be used for cross-compiled static builds.
> make: remove static targets

- src/blockchain_utilities/blockchain_import.cpp
- src/cryptonote_basic/cryptonote_format_utils.cpp
- src/cryptonote_basic/cryptonote_format_utils.h
- src/cryptonote_basic/verification_context.h
- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/blockchain.h
- src/cryptonote_core/cryptonote_core.cpp
- src/cryptonote_core/cryptonote_core.h
- src/cryptonote_core/tx_pool.cpp
- src/cryptonote_core/tx_pool.h
- src/cryptonote_core/tx_verification_utils.cpp
- src/cryptonote_core/tx_verification_utils.h
- src/cryptonote_protocol/cryptonote_protocol_handler.h
- src/cryptonote_protocol/cryptonote_protocol_handler.inl
- src/cryptonote_protocol/cryptonote_protocol_handler_common.h
- src/daemon/command_parser_executor.cpp
- src/daemon/daemon.cpp
- src/daemon/rpc_command_executor.cpp
- src/daemon/rpc_command_executor.h
- src/rpc/core_rpc_server.cpp
- src/rpc/core_rpc_server_commands_defs.h
- src/rpc/daemon_handler.cpp
- tests/core_tests/chaingen.h
- tests/functional_tests/p2p.py
- tests/unit_tests/node_server.cpp
Pros:
* During sync, instead of performing 1 write, then 1 read, then one write for each tx in the chain, we just write once. This increases the lifespan of the disk and speeds up badly buffered / not buffered I/O. On a newer NVME and with a Ryzen 9 3900X, blockchain sync was around 3-4% faster. Differences will be more pronounced for systems bottle-necked by disk speed. 
* This PR is backwards compatible to receive `NOTIFY_NEW_BLOCK` commands, but the code paths between `handle_notify_new_block` and `handle_notify_new_fluffy_block` are merged for less code surface and review time.
Cons:
* Complicated review
Hopefully this will move `monerod` towards being slightly more workable for hard drives in the future.
I have created a function `cryptonote::ver_non_input_consensus()` in …
> blockchain sync: reduce disk writes from 2 to 1 per tx

- CMakeLists.txt
- contrib/depends/Makefile
- contrib/depends/packages/boost.mk
This should fix a reported crash during sync on Windows that was introduced in #9800.
Context starting here: https://libera.monerologs.net/monero-dev/20250217#c497165
Includes #9457 backport (needed).
> depends: boost: update to 1.69.0 [0.18]

- src/wallet/wallet2.cpp
The expression `std::max(1, CRYPTONOTE_DEFAULT_TX_SPENDABLE_AGE)` without the explicit `size_t` defaults to returning an `int`.
> wallet: fix different-signedness int comparison warnings

- src/cryptonote_core/blockchain.cpp
I can't see how this would trigger in the current codebase, so it's not a *current* safety issue, but I can very well see it becoming on in the future if downstream code doesn't handle the passing of pruned transactions correctly. I think the safe/good choice would be to remove this skip now that all transactions that pass into the mempool are supposed to be unpruned. And for all in-block txs, `check_tx_inputs()` isn't called for checkpointed blocks, and we sync pruned blocks only if syncing checkpointed blocks.
> Blockchain: remove skip for pruned txs in `check_tx_inputs()`

- src/blockchain_db/blockchain_db.cpp
- src/blockchain_db/blockchain_db.h
- src/blockchain_db/lmdb/db_lmdb.cpp
- src/blockchain_db/lmdb/db_lmdb.h
- src/blockchain_db/testdb.h
I found a place where `std::pair<transaction, blobdata>` was given to a function that took a `const std::pair<transaction, blobdata_ref>&` argument. As per C++ rules, this forces a hidden implicit copy of `transaction`, which is a rather expensive operation in the `add_block` routine. Additional, the `miner_tx` was being copied too (and also in a migration function, which is less important).
I haven't done any timing/performance analysis, but this should help block syncing by a tiny amount. If this passes checks, I'm going to propose this for 0.18, except using `blobdata_ref` instead of `span<...>`. I'm using `span<...>` in this patch because I hope to change things over from `blobdata` (aka `std::string`) to `epee::byte_slice`.
> Remove hidden transaction copy in add_block

- external/easylogging++/easylogging++.h
- tests/unit_tests/logging.cpp
The upstream version of el::base::TypedConfigurations::unsafeGetConfigByRef accesses uninitialized memory if a key doesn't exist. Commit b2c59af84de8d35c1eee38878053206a62756968 patched the library to throw in this case, avoiding the invalid access, but the more suitable pattern, both logically (configure with a default-initialized config shouldn't throw), and as evidenced by the behavior of unsafeGetConfigByVal, would be to return a const reference to a default-initialized value with static storage duration.
> logging: Fix easylogging++ init with blank config

- tests/unit_tests/epee_http_server.cpp
I noticed on two of my test boxes that the new HTTP tests seem to fail. I tracked this down to a cap on the body size, that seems to only be enforced by newer versions of Boost. Regardless, this PR seems to fix the tests on 1.85+.
If this PR passes all tests, I will PR the same fix to the release branch.
> Fix HTTP unit tests (broken with new Boost versions)

- CMakeLists.txt
This sets cmake required version to 3.5 (as per readme and other CMakeLists.txt) to fix build issues caused by compatibility with cmake 4.0.0. Other parts of the build system were using 3.5 already - but this one caused build to fail.
> build: set cmake_minimum_required(VERSION 3.5) consistently [release-v0.18]

- contrib/guix/guix-build
```
-u, --user=USER        instead of copying the name and home of the current
user into an isolated container, use the name USER
with home directory /home/USER
```
This can cause a silent failure to bind-mount directories into the container if user "user" is not present on the system.
Removing the option does not introduce non-determinism in build results.
Fixes #9885.
> guix: remove --user option

- contrib/guix/guix-clean
Accidental invocation of the `guix-clean` script should not delete files.
Shows which files and directories will be deleted and asks for confirmation unless `NO_CONFIRM` is set.
> guix: ask for confirmation before deleting files

- Dockerfile
Switch from lower case "as" to upper case "AS" to be consistent with the other keywords.
fixes #9894
> fix inconsistent casing in Dockerfile

- .github/workflows/guix.yml
- contrib/guix/README.md
- contrib/guix/guix-build
This PR drops support for x86 (32-bit) Linux release builds. Submitting this to test the waters.
The last commercially available x86 processors were released [over 18 years ago](https://en.wikipedia.org/wiki/List_of_Intel_processors#Intel_Core).
https://libera.monerologs.net/monero-dev/20250406#c516924
> guix: drop support for i686-linux-gnu

- .github/workflows/build.yml
- Run `brew update` to ensure CI runs with the latest homebrew packages. This takes ~10 seconds.
- Explicitly install `cmake` (so it is upgraded).
- Add `--quiet` to stop it from moaning about packages that are already installed.
> ci: run brew update [0.18]

- cmake/CheckLinkerFlag.cmake
The CMake configure stage fails if another projects uses the Monero project in `FetchContent` or `ExternalProject` due to an incorrect path. This fixes the path so that it is relative to the top-level `project(monero)` declaration, instead of the top-level CMake directory.
Slightly longer explanation: I am working on the [`lwsf`](https://github.com/vtnerd/lwsf) library which implements the `wallet2_api.h`, but targets a LWS-rpc server instead of `monerod`-rpc server. Ideally this project gets optionally built into the [`monero_c`](https://github.com/MrCyjaneK/monero_c) project for use in dart, typescript, and C#. Both projects need to use the libraries within the `monero` project, and instead of building twice, `FetchContent` allows the projects to coordinate configuring+building the …
> Fix cmake usage in FetchContent and ExternalProject

- src/cryptonote_basic/cryptonote_basic_impl.cpp
- src/cryptonote_basic/cryptonote_basic_impl.h
Useful for wallet business logic, which stores the *prefixes* in `m_transfers`, not the whole transaction.
Part of upstreaming Carrot
> cryptonote_basic: is_coinbase() take prefix

- CMakeLists.txt
Adds a line in the CMakeCache.txt of the build dir to edit `MANUAL_SUBMODULES`. Convenient for debugging a submodule's integration with Monero codebase when you don't want to pass the def on the command line each time.
> CMakeLists: add cache option for MANUAL_SUBMODULES

- external/easylogging++/easylogging++.h
Undefined behavior. Contructor explicitely deleted in libstdc++ for c++23: https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/basic_string.h#L756
```
/distsrc/monero/external/easylogging++/easylogging++.h:1096:106: error: use of deleted function 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::nullptr_t) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::nullptr_t = std::nullptr_t]'
1096 |   static void buildStrippedFilename(const char* filename, char buff[], const std::string &commonPrefix = NULL,
|                                                                                                          ^~~~
```
> easylogging: replace NULL with empty string literal

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Without this PR you should be able to reproduce the error with the following steps:
1. 2/2 multisig-wallets W1 and W2 both own some enotes with partial key images
2. use `export_multisig_info` for both wallets
3. use `import_multisig_info` for W1
4. turn off daemon (to reproduce the "no connection to daemon" error in next step, in the real world this happens by accident) 
5. attempt `import_multisig_info` for W2 (it fails as expected)
6. turn on daemon
7. use `import_multisig_info` for W2 (it looks like it worked, but it actually dropped enotes with partial key images from `m_transfers`, this becomes a problem e.g. if you try to sign a tx from this wallet)
8. use `transfer` from W1
9. use `sign_multisig` from W2, here we get `Error: Multisig error: This signature was made with stale data: …
> fix: multisig stale data after failed refresh

- contrib/epee/include/span.h
Changes the `operator[]` method so we can get mutable references to elements even if the span is `const`. The operator is now also `constexpr`. This behavior matches `std::span`.
C++ standard reference: https://en.cppreference.com/w/cpp/container/span/operator_at
> epee: span::operator[] allow mut ref from const span

- src/cryptonote_basic/cryptonote_basic.h
- src/cryptonote_core/blockchain.cpp
- src/rpc/rpc_payment.cpp
- src/wallet/wallet2.cpp
This one is a little aggressive - it adds move semantics to `transaction` and `block`. I deleted the move constructor+assignment to both objects and tried compiling everything but tests. This identified every move operation (that is currently secretly a copy), and I manually verified that the moves were valid. There was one `transaction` case that I could not verify, which I downgraded to a copy.
This PR also changes the default+copy constructors, and copy assignment. The reasoning was the `atomic` values - the changes have fewer memory barriers and branches, which should result in slightly faster code (particularly on arm).
The primary benefit is a `transaction` copy becomes a move in `add_block`. This should have a (small but) measurable improvement in block syncing, etc, as a …
> Improve move/copy/default constructor semantics for tx and block

- tests/functional_tests/p2p.py
Use a fixed, 240s deadline for the daemons to reach agreement and poll with a suitable frequency (.25s), rather than polling up to 100 times at roughly 10s intervals.
> tests: Speed up p2p reorg test

- src/serialization/json_object.h
A for each loop in ZMQ output accidentally copies every value in an array. This should have a minor speed improvement in ZMQ output.
> Fix copy in ZMQ input/output

- src/cryptonote_core/cryptonote_tx_utils.cpp
The catch-and-rethrow pattern here erases the stack trace on where exceptions in `construct_tx_with_tx_key` (a quite complicated function) are thrown, which makes debugging issues harder.
> construct_tx_and_get_tx_key: don't erase exception trace

- contrib/epee/include/net/levin_protocol_handler_async.h
- contrib/epee/include/syncobj.h
- src/cryptonote_protocol/cryptonote_protocol_handler-base.cpp
- src/wallet/api/wallet_manager.cpp
- tests/libwallet_api_tests/main.cpp
a. `critical_section` is functionally identical to a `boost::recursive_mutex`
b. `critical_region_t` is functionally identical to a `boost::unique_lock`
c. remove some vestigial definitions of `g_test_dbg_lock_sleep` as a variable
The "fake" copy constructors provided by the shims aren't used anyways.
> epee: syncobj: replace shims with Boost classes

- src/cryptonote_core/cryptonote_core.cpp
Detailed discussion [here](https://github.com/spackle-xmr/monero/pull/13/#issuecomment-2234543784).
> cryptonote_core: only verify txpool when the hardfork value has changed.

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
A while ago, this PR was merged https://github.com/monero-project/monero/pull/8941 (@moneromooo-monero)
The consequence of this was that the monero-wallet-rpc would hang on auto-refreshes. This is an example sequence of events that causes the hang:
- Restore wallet from a low height (e.g. 2,500,000)
- Refresh event begins (kicked off every second)
- More than REFRESH_INFICATIVE_BLOCK_CHUNK_SIZE is fetched, m_last_auto_refresh_time is not updated; furthermore,
- Over 1000ms have passed since the beginning of the refresh event.
- Next refresh cycle is immediately kicked off.
This continuous refresh event, without stop, blocks the wallet-rpc from responding to other events.
1. Create a wallet, either programatically (monero-wallet-rpc) or manually (monero-wallet-cli)
2. Get the address, …
> wallet: fix monero-wallet-rpc ignoring calls during sync

- contrib/epee/include/serialization/keyvalue_serialization_overloads.h
- src/common/perf_timer.h
For `uint*_t`, otherwise some downstream MSYS2 builds break.
> msys2 build: include int headers

- src/simplewallet/simplewallet.cpp
m_wallet_file contains the file full name, but the change_password function requires only the file name.
closes #9943
> simplewallet: cli using wrong filename for storing keys

- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
This commit fd08594caae37a592a6e9257e6ad577d9f8f9c32 introduced in this MR https://github.com/monero-project/monero/pull/9875 changed the refresh interval to 200ms during wallet sync, fixing other bugs in the process. 
Here I've done two things:
1. Recognize that m_auto_refresh_period can change, and protect it from multithreaded access via an atomic (it can change when a user sends a request to stop auto refresh, and its polled for in a separate thread that runs every 200ms during sync and 1000ms when we reach tip of chain).
2. Remove the if-condition that prevented us from executing tip-of chain logic that would transition us to the less-frequent polling once we arrive at the tip of the chain.
> wallet: Reset rpc-server refresh interval post-full sync

- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
- src/wallet/wallet_rpc_server.cpp
- src/wallet/wallet_rpc_server.h
- src/wallet/wallet_rpc_server_commands_defs.h
- tests/functional_tests/transfer.py
- tests/functional_tests/wallet.py
- tests/unit_tests/subaddress.cpp
- utils/python-rpc/framework/wallet.py
release version of #9953 / #8981
> wallet: immediate lookahead table expansion + set_subaddresss_lookahead RPC endpoint [0.18]

- .github/workflows/build.yml
Merge on or after June 30. (#9446)
We don't need this on `release-v0.18`, since we'll branch from master soon.
> ci: bump debian to 11

- contrib/guix/libexec/build.sh
- contrib/guix/manifest.scm
- Remove unused modules
- `moreutils` was removed in #9650
- `gperf` was removed in #9675 
- `libplist`, `util-linux`, `openssl` are unused
- Remove unused packages
- `file` and `patchelf` are unused.
- `zip` is only used for windows targets
- `xz` is only used for freebsd
- `unzip` is only used for android
- `libtool` and `python-minimal` are only used for darwin
- Update comments
> guix: cleanup manifest

- contrib/depends/packages/openssl.mk
- Update to 3.0.17
- https://github.com/openssl/openssl/blob/openssl-3.0.17/NEWS.md#openssl-30
- Remove directories containing blobs
> depends: openssl: update to 3.0.17

- src/crypto/hash.h
If `crypto::cn_slow_hash()` is called with `variant=1` and an input length of less thab 43 bytes, it triggers a program exit. This checks first and throws an exception instead.
Thank you to ADA Logics and the MAGIC Monero Fund for reporting this!
> crypto: check+throw for Cryptonight v1 invalid input

- src/daemon/command_line_args.h
This same description is listed in the other cli tools. I saw this argument in the daemon's help menu and didn't know how to set it, which is why I made this PR.
> daemon: Add log-level arg description

- .github/workflows/build.yml
#9968 
Debian 10 repo is no longer available. Not a transient issue. https://ftp.debian.org/debian/
> ci: bump debian to 11 [0.18]

- .github/workflows/gitian.yml
> ci: gitian: update runner to 22.04 [0.18]

- src/simplewallet/simplewallet.cpp
This is supposed to be a fix for #9698
There I had the misunderstanding that the `do-not-relay` option means we don't want to broadcast any tx to the daemon, but now I think we actually still want to allow submitting transactions (via CLI commands `submit_transfer` or in this case `submit_multisig`) even if `do-not-relay` is set true.
> set do_not_relay always false in submit_multisig_main

- README.md
#9987
Note: the Apple Silicon target was renamed to `arm64-apple-darwin` on `master`. (#9784)
> readme: fix macos depends requirements

- contrib/guix/manifest.scm
Tested `monerod` and `monero-wallet-cli` on FreeBSD 13.1.
> guix: build freebsd target with clang 18

- contrib/guix/INSTALL.md
- contrib/guix/libexec/prelude.bash
https://guix.gnu.org/blog/2025/migrating-to-codeberg/
The new repository should be more reliable. We can archive https://github.com/monero-project/guix as a result.
> guix: use canonical repository

- Dockerfile
- `bsdmainutils`: "This is a transitional package, it can be safely removed."
- `ccache`: Doesn't make sense to include here. We're not rebuilding anything.
- others: see comments on #9990
> Dockerfile: remove unused deps

- src/common/container_helpers.h
Since C++17, `std::vector::emplace_back()` returns a reference, so this helper isn't needed anymore.
> common: remove `tools::add_element`

- src/simplewallet/simplewallet.cpp
- src/wallet/api/wallet.cpp
- src/wallet/wallet2.cpp
- src/wallet/wallet2.h
Rings for outgoing transactions are stored within the scanning code since the last hardfork, so this code is largely unneccessary now.
> wallet: deprecate `wallet2::find_and_save_rings()`

- src/wallet/wallet_rpc_server.cpp
Allows calling /incoming_transfers for cold wallets especially.
This PR is part of upstreaming Carrot/FCMP++.
> wallet: RPC method /incoming_transfers without daemon connection

- src/simplewallet/simplewallet.cpp
Fixup of #9592, Payment IDs are 16 characters long not 15.
> simplewallet: fix payment id header in show_transfers command

- contrib/epee/include/net/abstract_tcp_server2.h
- contrib/epee/include/net/abstract_tcp_server2.inl
- src/p2p/net_node.h
- src/p2p/net_node.inl
Just as the title says. This gets more accurate reporting internally and externally.
> Skip ping connections in outgoing count

- src/wallet/fee_algorithm.h
- src/wallet/fee_priority.h
For small helper functions like these that live in a header, the modern C++ solution is to replace static with inline. This signals to the compiler that the function is defined in the header and avoids the "unused function" warning, as it creates a single definition for the entire program.
[Example](https://github.com/monero-project/monero/actions/runs/16183764676/job/45685482172?pr=9838#step:10:1760)
> wallet: fix warning in fee priority algorithm

- contrib/epee/src/abstract_http_client.cpp
When building on Ubuntu 22.04 with GCC 11.4.0 and Boost 1.89.0.beta1, the build failed with:
```
error: ‘floor’ was not declared in this scope
41 |       num_char = (int)floor((float)num_char / (float)radix);
|                       ^~~~~
```
https://github.com/monero-project/monero/blob/389e3ba1df4a6df4c8f9d116aa239d4c00f5bc78/contrib/epee/src/abstract_http_client.cpp#L41
Seen while beta testing upcoming Boost 1.89.0 (planned release tomorrow, Aug 13) at Homebrew - https://github.com/Homebrew/homebrew-core/pull/233031
No issues with Boost 1.88.0 so some Boost changes must have resulted in no longer indirectly including `math.h` or `cmath`.
> epee: include math header for upcoming Boost 1.89

- contrib/guix/guix-build
- contrib/guix/libexec/build.sh
Deprecated in favor of `guix shell`: https://guix.gnu.org/manual/devel/en/html_node/Invoking-guix-environment.html
> guix: switch to guix shell

- tests/functional_tests/cold_signing.py
Do not mark output import as done if exception is thrown for output being past last imported output.
The reason that the failure is uncommon with #10053 is because the cold wallet already has imported 80 outputs at this point in the test, and we only add ~3 outputs at a time, and import in 1-6 output chunks.
> functional_tests: fix piecemeal export in cold_signing, part 2

- contrib/epee/src/net_parse_helpers.cpp
Reported by hacksandhops and Ada Logic.
> epee: only parse valid port

- src/blockchain_db/lmdb/db_lmdb.cpp
Issue with alignment described in #10045. A full database migration shouldn't be required since alt blocks are flushed on startup.
> BlockchainLMDB: do not assume alignment for alt block entries

- .github/workflows/build.yml
Fixes CI.
See: https://github.com/monero-project/monero/actions/runs/17346427435/job/49247032842#step:5:75
> ci: macos: reinstall cmake

- contrib/epee/src/net_parse_helpers.cpp
Reported by hacksandhops and Ada Logic.
#10056
> epee: only parse valid port [release-v0.18]

- src/device_trezor/trezor/messages_map.cpp
when running make debug I noticed the following warning in terminal which goes away with these code changes:
Possibly original person used &text so as to not copy string objects, but that was happening anyways the way it was done and was improperly binding pointer to a temporary object.
/monero/src/device_trezor/trezor/messages_map.cpp: In static member function ‘static google::protobuf::Message* hw::trezor::MessageMapper::get_message(const std::string&)’: /monero/src/device_trezor/trezor/messages_map.cpp:83:23: warning: loop variable ‘text’ of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} binds to a temporary constructed from type ‘const char*’ [-Wrange-loop-construct] 83 | for(const string &text : PACKAGES){ | ^~~~ …
> Address warning when building caused by messages_map.cpp string handling

- src/p2p/net_node.inl
https://github.com/monero-project/monero/pull/10114
Testnet/stagenet are reachable but still syncing, should be ready before `v0.18.4.3`.
> net_node: add hinto seed nodes [v0.18]

- src/rpc/core_rpc_server.cpp
Notice how the RPC handler needs to return false for the macro handling the function to properly handle the error return:
https://github.com/monero-project/monero/blob/b591866fcfed400bc89631686655aa769ec5f2dd/contrib/epee/include/net/http_server_handlers_map2.h#L216-L223
> Daemon RPC: fix on_getblockhash error return on too high height

- src/cryptonote_basic/cryptonote_format_utils.cpp
> cryptonote_basic: rm redundant call to `get_transaction_hash()` in overload

- src/cryptonote_core/blockchain.cpp
- src/cryptonote_core/cryptonote_core.cpp
`check_tx_outputs` is called in one place, `ver_non_input_consensus_templated`:
```cpp
// Rule 5
if (!core::check_tx_semantic(tx, tvc, hf_version))
return false;
// Rule 6
if (!Blockchain::check_tx_outputs(tx, tvc, hf_version) || tvc.m_verifivation_failed)
return false;
```
Note in the snippet above that `core::check_tx_semantic` is called right before `check_tx_outputs`, and calls `check_outs_valid`:
```cpp
bool core::check_tx_semantic(const transaction& tx, tx_verification_context& tvc,
uint8_t hf_version)
{
...
if(!check_outs_valid(tx))
{
MERROR_VER("tx with invalid outputs, rejected for tx id= " << get_transaction_hash(tx));
tvc.m_verifivation_failed = true;
tvc.m_invalid_output = true;
return false;
}
```
`check_outs_valid` also makes sure output pubkeys are canonical:
```cpp
bool …
```
> Cleaner validation (faster and saner)

- src/cryptonote_basic/cryptonote_format_utils.cpp
> cryptonote_basic: rm redundant call to `get_transaction_hash()` in overload [RELEASE]

- src/wallet/wallet2.cpp
> wallet2: warn instead of throw when RingDB doesn't include spend [v0.18]

- docs/CONTRIBUTING.md
Should selsta be on here? Should I be on here?
It's not entirely clear if this is:
- a list of maintainers
- a special team of (non-)maintainers?
I'd like to get some input from others here.
> CoC: remove 'Monero Maintainer Team'

- docs/CONTRIBUTING.md
This section was forgotten to be removed. This project does not have "stable" releases.
https://github.com/monero-project/monero/pull/2174#discussion_r127844693
> CoC: remove 'creating stable releases' section
